From Equations Require Import Equations.
From PathDependent.LambdaPCC Require Import FinFun Syntax Context Typing Runtime.

Set Implicit Arguments.

Set Universe Polymorphism.
Unset Strict Implicit.
Unset Equations Derive Eliminator.

(** Finite proof-relevant runtime path equality. *)
Inductive PathRuntimeEq {n : nat} (sigma : Store n) :
    Path n -> Path n -> Type :=
| PREq_refl (p : Path n) : PathRuntimeEq sigma p p
| PREq_symm {p q : Path n} :
    PathRuntimeEq sigma p q -> PathRuntimeEq sigma q p
| PREq_trans {p q r : Path n} :
    PathRuntimeEq sigma p q -> PathRuntimeEq sigma q r ->
    PathRuntimeEq sigma p r
| PREq_coresolve {p q : Path n} {referent : Referent n} :
    PathResolve sigma p referent -> PathResolve sigma q referent ->
    PathRuntimeEq sigma p q
| PREq_fst {p q : Path n} :
    PathRuntimeEq sigma p q -> PathRuntimeEq sigma (PFst p) (PFst q)
| PREq_sel {p q : Path n} :
    PathRuntimeEq sigma p q -> forall a : Name,
      PathRuntimeEq sigma (PSel p a) (PSel q a).

Arguments PREq_refl {n sigma} p.
Arguments PREq_symm {n sigma p q} _.
Arguments PREq_trans {n sigma p q r} _ _.
Arguments PREq_coresolve {n sigma p q referent} _ _.
Arguments PREq_fst {n sigma p q} _.
Arguments PREq_sel {n sigma p q} _ a.

(** Runtime equality preserves the full generalized-resolution graph. *)
Lemma path_runtime_eq_resolve_iff {n : nat} {sigma : Store n}
    {p q : Path n} (evidence : PathRuntimeEq sigma p q)
    (referent : Referent n) :
    PathResolve sigma p referent <-> PathResolve sigma q referent.
Proof.
  revert referent.
  induction evidence; intro target.
  - tauto.
  - specialize (IHevidence target). tauto.
  - specialize (IHevidence1 target).
    specialize (IHevidence2 target). tauto.
  - split; intro resolution.
    + pose proof (path_resolve_deterministic p0 resolution) as equality.
      destruct equality. exact p1.
    + pose proof (path_resolve_deterministic p1 resolution) as equality.
      destruct equality. exact p0.
  - split; intro resolution.
    + dependent elimination resolution.
      eapply PR_fst.
      * exact (proj1 (IHevidence (RLoc x0)) p1).
      * exact s.
    + dependent elimination resolution.
      eapply PR_fst.
      * exact (proj2 (IHevidence (RLoc x0)) p1).
      * exact s.
  - split; intro resolution.
    + dependent elimination resolution.
      * eapply PR_sel.
        -- exact (proj1 (IHevidence (RLoc x1)) p3).
        -- exact s0.
      * eapply PR_sel_miss.
        -- exact (proj1 (IHevidence (RLoc x2)) p5).
        -- exact s1.
        -- eassumption.
        -- exact p6.
    + dependent elimination resolution.
      * eapply PR_sel.
        -- exact (proj2 (IHevidence (RLoc x1)) p3).
        -- exact s0.
      * eapply PR_sel_miss.
        -- exact (proj2 (IHevidence (RLoc x2)) p5).
        -- exact s1.
        -- eassumption.
        -- exact p6.
Qed.

(** Runtime equality survives allocation. *)
Definition path_runtime_eq_weaken {n : nat} {sigma : Store n}
    {p q : Path n} (evidence : PathRuntimeEq sigma p q)
    (v : Tm n) (is_value : Tm_IsValue v) :
    PathRuntimeEq (StoreVal sigma v is_value) (path_weaken p) (path_weaken q).
Proof.
  induction evidence.
  - exact (PREq_refl (path_weaken p)).
  - exact (PREq_symm IHevidence).
  - exact (PREq_trans IHevidence1 IHevidence2).
  - exact (PREq_coresolve
      (path_resolve_weaken p0 (v := v) is_value)
      (path_resolve_weaken p1 (v := v) is_value)).
  - unfold path_weaken in *. simp path_rename in *.
    exact (PREq_fst IHevidence).
  - unfold path_weaken in *. simp path_rename in *.
    exact (PREq_sel IHevidence a).
Defined.

(** Least path congruence below one binder.  Its type is declared before
    the mutually recursive conversion families that use it. *)
Inductive PathScopedLift {n : nat} (R : Path n -> Path n -> Type) :
    Path (S n) -> Path (S n) -> Type :=
| SL_bound : PathScopedLift R (PVar FZ) (PVar FZ)
| SL_old {p q : Path n} :
    R p q -> PathScopedLift R (path_weaken p) (path_weaken q)
| SL_symm {p q : Path (S n)} :
    PathScopedLift R p q -> PathScopedLift R q p
| SL_trans {p q r : Path (S n)} :
    PathScopedLift R p q -> PathScopedLift R q r -> PathScopedLift R p r
| SL_fst {p q : Path (S n)} :
    PathScopedLift R p q -> PathScopedLift R (PFst p) (PFst q)
| SL_sel {p q : Path (S n)} {a : Name} :
    PathScopedLift R p q -> PathScopedLift R (PSel p a) (PSel q a).

Arguments SL_bound {n R}.
Arguments SL_old {n R p q} _.
Arguments SL_symm {n R p q} _.
Arguments SL_trans {n R p q r} _ _.
Arguments SL_fst {n R p q} _.
Arguments SL_sel {n R p q a} _.

(** Proof-relevant conversion generated by replacing related paths. *)
Inductive CaptureRuntimeConv :
    forall {n : nat}, (Path n -> Path n -> Type) ->
      CaptureSet n -> CaptureSet n -> Type :=
| CRC_refl {n : nat} {R : Path n -> Path n -> Type}
    {C : CaptureSet n} : CaptureRuntimeConv R C C
| CRC_replace {n : nat} {R : Path n -> Path n -> Type}
    (context : CaptureSet (S n)) {p q : Path n} :
    R p q -> CaptureRuntimeConv R
      (capture_open context p) (capture_open context q)
| CRC_empty {n : nat} {R : Path n -> Path n -> Type} :
    CaptureRuntimeConv R CEmpty CEmpty
| CRC_union {n : nat} {R : Path n -> Path n -> Type}
    {C C' D D' : CaptureSet n} :
    CaptureRuntimeConv R C C' -> CaptureRuntimeConv R D D' ->
    CaptureRuntimeConv R (CUnion C D) (CUnion C' D')
| CRC_singleton {n : nat} {R : Path n -> Path n -> Type}
    {p q : Path n} : R p q ->
    CaptureRuntimeConv R (CSingleton p) (CSingleton q)
| CRC_select {n : nat} {R : Path n -> Path n -> Type}
    {p q : Path n} {a : Name} : R p q ->
    CaptureRuntimeConv R (CSelect p a) (CSelect q a)
with TyRuntimeConv :
    forall {n : nat}, (Path n -> Path n -> Type) -> Ty n -> Ty n -> Type :=
| TRC_refl {n : nat} {R : Path n -> Path n -> Type} {T : Ty n} :
    TyRuntimeConv R T T
| TRC_replace {n : nat} {R : Path n -> Path n -> Type}
    (context : Ty (S n)) {p q : Path n} :
    R p q -> TyRuntimeConv R (ty_open context p) (ty_open context q)
| TRC_capt {n : nat} {R : Path n -> Path n -> Type}
    {C D : CaptureSet n} {S0 T : Shape n} :
    CaptureRuntimeConv R C D -> ShapeRuntimeConv R S0 T ->
    TyRuntimeConv R (TyCapt C S0) (TyCapt D T)
with ShapeRuntimeConv :
    forall {n : nat}, (Path n -> Path n -> Type) ->
      Shape n -> Shape n -> Type :=
| SRC_refl {n : nat} {R : Path n -> Path n -> Type} {S0 : Shape n} :
    ShapeRuntimeConv R S0 S0
| SRC_replace {n : nat} {R : Path n -> Path n -> Type}
    (context : Shape (S n)) {p q : Path n} :
    R p q -> ShapeRuntimeConv R
      (shape_open context p) (shape_open context q)
| SRC_top {n : nat} {R : Path n -> Path n -> Type} :
    ShapeRuntimeConv R ShTop ShTop
| SRC_bot {n : nat} {R : Path n -> Path n -> Type} :
    ShapeRuntimeConv R ShBot ShBot
| SRC_fun {n : nat} {R : Path n -> Path n -> Type}
    {S0 S' : Ty n} {T T' : Ty (S n)} :
    TyRuntimeConv R S0 S' ->
    TyRuntimeConv (PathScopedLift R) T T' ->
    ShapeRuntimeConv R (ShFun S0 T) (ShFun S' T')
| SRC_pair {n : nat} {R : Path n -> Path n -> Type}
    {k : Kind} {S0 S' : Ty n} {a : Name}
    {d d' : Tau (S n) k} :
    TyRuntimeConv R S0 S' ->
    TauRuntimeConv (PathScopedLift R) d d' ->
    ShapeRuntimeConv R (ShPair S0 a d) (ShPair S' a d')
| SRC_single {n : nat} {R : Path n -> Path n -> Type}
    {p q : Path n} : R p q ->
    ShapeRuntimeConv R (ShSingle p) (ShSingle q)
| SRC_selection {n : nat} {R : Path n -> Path n -> Type}
    {p q : Path n} {a : Name} : R p q ->
    ShapeRuntimeConv R (ShTSel p a) (ShTSel q a)
with TauRuntimeConv :
    forall {n : nat}, (Path n -> Path n -> Type) ->
      forall {k : Kind}, Tau n k -> Tau n k -> Type :=
| TaRC_refl {n : nat} {R : Path n -> Path n -> Type}
    {k : Kind} {d : Tau n k} : TauRuntimeConv R d d
| TaRC_replace {n : nat} {R : Path n -> Path n -> Type}
    {k : Kind} (context : Tau (S n) k) {p q : Path n} :
    R p q -> TauRuntimeConv R (tau_open context p) (tau_open context q)
| TaRC_term {n : nat} {R : Path n -> Path n -> Type}
    {T U : Ty n} : TyRuntimeConv R T U ->
    TauRuntimeConv R (TauTerm T) (TauTerm U)
| TaRC_type {n : nat} {R : Path n -> Path n -> Type}
    {L L' U U' : Shape n} :
    ShapeRuntimeConv R L L' -> ShapeRuntimeConv R U U' ->
    TauRuntimeConv R (TauType L U) (TauType L' U')
| TaRC_capture {n : nat} {R : Path n -> Path n -> Type}
    {C C' D D' : CaptureSet n} :
    CaptureRuntimeConv R C C' -> CaptureRuntimeConv R D D' ->
    TauRuntimeConv R (TauCapture C D) (TauCapture C' D').

Arguments CRC_refl {n R C}.
Arguments CRC_replace {n R} context {p q} _.
Arguments CRC_empty {n R}.
Arguments CRC_union {n R C C' D D'} _ _.
Arguments CRC_singleton {n R p q} _.
Arguments CRC_select {n R p q a} _.
Arguments TRC_refl {n R T}.
Arguments TRC_replace {n R} context {p q} _.
Arguments TRC_capt {n R C D S0 T} _ _.
Arguments SRC_refl {n R S0}.
Arguments SRC_replace {n R} context {p q} _.
Arguments SRC_top {n R}.
Arguments SRC_bot {n R}.
Arguments SRC_fun {n R S0 S' T T'} _ _.
Arguments SRC_pair {n R k S0 S' a d d'} _ _.
Arguments SRC_single {n R p q} _.
Arguments SRC_selection {n R p q a} _.
Arguments TaRC_refl {n R k d}.
Arguments TaRC_replace {n R k} context {p q} _.
Arguments TaRC_term {n R T U} _.
Arguments TaRC_type {n R L L' U U'} _ _.
Arguments TaRC_capture {n R C C' D D'} _ _.

(** Project capture conversion from conversion of capturing types. *)
Equations ty_runtime_conv_capture_conversion {n : nat}
    {R : Path n -> Path n -> Type} {T U : Ty n}
    (conversion : TyRuntimeConv R T U) :
    CaptureRuntimeConv R (ty_capture_set T) (ty_capture_set U) :=
ty_runtime_conv_capture_conversion TRC_refl := CRC_refl;
ty_runtime_conv_capture_conversion
    (TRC_replace (TyCapt captures shape) evidence) :=
  CRC_replace captures evidence;
ty_runtime_conv_capture_conversion (TRC_capt captures shape) := captures.

(** Operations required of a proof-relevant path equality. *)
Record PathEqCongruence {n : nat} (R : Path n -> Path n -> Type) : Type := {
  eq_refl : forall p, R p p;
  eq_symm : forall p q, R p q -> R q p;
  eq_trans : forall p q r, R p q -> R q r -> R p r;
  eq_fst : forall p q, R p q -> R (PFst p) (PFst q);
  eq_sel : forall p q, R p q -> forall a, R (PSel p a) (PSel q a)
}.

Arguments eq_refl {n R} _ _.
Arguments eq_symm {n R} _ {p q} _.
Arguments eq_trans {n R} _ {p q r} _ _.
Arguments eq_fst {n R} _ {p q} _.
Arguments eq_sel {n R} _ {p q} _ _.

Definition path_runtime_eq_congruence {n : nat} (sigma : Store n) :
    PathEqCongruence (PathRuntimeEq sigma) :=
  {| eq_refl := fun p => PREq_refl p;
     eq_symm := fun _ _ e => PREq_symm e;
     eq_trans := fun _ _ _ e1 e2 => PREq_trans e1 e2;
     eq_fst := fun _ _ e => PREq_fst e;
     eq_sel := fun _ _ e a => PREq_sel e a |}.

Definition path_scoped_lift_refl_old {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    (x : Fin n) : PathScopedLift R (PVar (FS x)) (PVar (FS x)).
Proof.
  assert (equation : path_weaken (PVar x) = PVar (FS x)).
  { unfold path_weaken. simp path_rename. rewrite weaken_apply. reflexivity. }
  rewrite <- equation. exact (SL_old (eq_refl operations (PVar x))).
Defined.

Equations path_scoped_lift_refl {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    (p : Path (S n)) : PathScopedLift R p p :=
path_scoped_lift_refl operations (PVar FZ) := SL_bound;
path_scoped_lift_refl operations (PVar (FS x)) :=
  path_scoped_lift_refl_old operations x;
path_scoped_lift_refl operations (PFst p) :=
  SL_fst (path_scoped_lift_refl operations p);
path_scoped_lift_refl operations (PSel p a) :=
  SL_sel (path_scoped_lift_refl operations p).

Definition path_scoped_lift_congruence {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R) :
    PathEqCongruence (PathScopedLift R) :=
  {| eq_refl := path_scoped_lift_refl operations;
     eq_symm := fun _ _ e => SL_symm e;
     eq_trans := fun _ _ _ e1 e2 => SL_trans e1 e2;
     eq_fst := fun _ _ e => SL_fst e;
     eq_sel := fun _ _ e _ => SL_sel e |}.

(** Scoped runtime equality remains stable under ambient allocation. *)
Definition path_scoped_lift_weaken_runtime {n : nat} {sigma : Store n}
    {p q : Path (S n)}
    (evidence : PathScopedLift (PathRuntimeEq sigma) p q)
    (v : Tm n) (is_value : Tm_IsValue v) :
    PathScopedLift (PathRuntimeEq (StoreVal sigma v is_value))
      (path_rename p (ext (weaken n)))
      (path_rename q (ext (weaken n))).
Proof.
  induction evidence.
  - simp path_rename. exact SL_bound.
  - unfold path_weaken in *.
    rewrite !path_rename_rename, <- comp_weaken.
    pose proof (SL_old (path_runtime_eq_weaken r (v := v) is_value)) as old.
    unfold path_weaken in old. rewrite !path_rename_rename in old.
    exact old.
  - exact (SL_symm IHevidence).
  - exact (SL_trans IHevidence1 IHevidence2).
  - simp path_rename in *. exact (SL_fst IHevidence).
  - simp path_rename in *. exact (SL_sel IHevidence).
Defined.

(** Relation morphisms for simultaneous path substitution. *)
Definition PathSubstHom {n m : nat}
    (R : Path n -> Path n -> Type) (E : Path m -> Path m -> Type)
    (rho : PathSubst n m) : Type :=
  forall p q, R p q -> E (path_subst p rho) (path_subst q rho).

Definition path_scoped_lift_subst {n m : nat}
    {R : Path n -> Path n -> Type} {E : Path m -> Path m -> Type}
    {rho : PathSubst n m} {p q : Path (S n)}
    (map_old : PathSubstHom R E rho)
    (evidence : PathScopedLift R p q) :
    PathScopedLift E
      (path_subst p (path_subst_lift rho))
      (path_subst q (path_subst_lift rho)).
Proof.
  induction evidence.
  - simp path_subst. rewrite subst_lift_zero. exact SL_bound.
  - rewrite !path_weaken_subst_lift. exact (SL_old (map_old _ _ r)).
  - exact (SL_symm IHevidence).
  - exact (SL_trans IHevidence1 IHevidence2).
  - simp path_subst. exact (SL_fst IHevidence).
  - simp path_subst. exact (SL_sel IHevidence).
Defined.

Definition path_scoped_lift_open {n : nat}
    {R : Path n -> Path n -> Type} {p q : Path (S n)} {r s : Path n}
    (operations : PathEqCongruence R)
    (evidence : PathScopedLift R p q) (arguments : R r s) :
    R (path_open p r) (path_open q s).
Proof.
  revert r s arguments.
  induction evidence; intros r0 s0 arguments.
  - unfold path_open. simp path_subst.
    rewrite !subst_openAt_zero. exact arguments.
  - rewrite !path_weaken_open. exact r.
  - apply (eq_symm operations). apply IHevidence.
    apply (eq_symm operations). exact arguments.
  - eapply (eq_trans operations).
    + exact (IHevidence1 r0 s0 arguments).
    + exact (IHevidence2 s0 s0 (eq_refl operations s0)).
  - unfold path_open in *. simp path_subst in *.
    exact (eq_fst operations (IHevidence r0 s0 arguments)).
  - unfold path_open in *. simp path_subst in *.
    exact (eq_sel operations (IHevidence r0 s0 arguments) a).
Defined.

(** Conversion is natural under simultaneous substitution and a relation
    morphism. *)
Definition capture_runtime_conv_subst_replace {n m : nat}
    {R : Path n -> Path n -> Type} {E : Path m -> Path m -> Type}
    (context : CaptureSet (S n)) {p q : Path n} (evidence : R p q)
    (rho : PathSubst n m) (map_paths : PathSubstHom R E rho) :
    CaptureRuntimeConv E
      (capture_subst (capture_open context p) rho)
      (capture_subst (capture_open context q) rho).
Proof.
  rewrite !capture_open_subst.
  exact (CRC_replace (capture_subst context (path_subst_lift rho))
    (map_paths _ _ evidence)).
Defined.

Definition ty_runtime_conv_subst_replace {n m : nat}
    {R : Path n -> Path n -> Type} {E : Path m -> Path m -> Type}
    (context : Ty (S n)) {p q : Path n} (evidence : R p q)
    (rho : PathSubst n m) (map_paths : PathSubstHom R E rho) :
    TyRuntimeConv E
      (ty_subst (ty_open context p) rho)
      (ty_subst (ty_open context q) rho).
Proof.
  rewrite !ty_open_subst.
  exact (TRC_replace (ty_subst context (path_subst_lift rho))
    (map_paths _ _ evidence)).
Defined.

Definition shape_runtime_conv_subst_replace {n m : nat}
    {R : Path n -> Path n -> Type} {E : Path m -> Path m -> Type}
    (context : Shape (S n)) {p q : Path n} (evidence : R p q)
    (rho : PathSubst n m) (map_paths : PathSubstHom R E rho) :
    ShapeRuntimeConv E
      (shape_subst (shape_open context p) rho)
      (shape_subst (shape_open context q) rho).
Proof.
  rewrite !shape_open_subst.
  exact (SRC_replace (shape_subst context (path_subst_lift rho))
    (map_paths _ _ evidence)).
Defined.

Definition tau_runtime_conv_subst_replace {n m : nat}
    {R : Path n -> Path n -> Type} {E : Path m -> Path m -> Type}
    {k : Kind} (context : Tau (S n) k) {p q : Path n} (evidence : R p q)
    (rho : PathSubst n m) (map_paths : PathSubstHom R E rho) :
    TauRuntimeConv E
      (tau_subst (tau_open context p) rho)
      (tau_subst (tau_open context q) rho).
Proof.
  rewrite !tau_open_subst.
  exact (TaRC_replace (tau_subst context (path_subst_lift rho))
    (map_paths _ _ evidence)).
Defined.

Fixpoint capture_runtime_conv_subst {n : nat}
    {R : Path n -> Path n -> Type} {C D : CaptureSet n}
    (conversion : CaptureRuntimeConv R C D) {struct conversion} :
    forall {m : nat} {E : Path m -> Path m -> Type}
      (rho : PathSubst n m), PathSubstHom R E rho ->
      CaptureRuntimeConv E (capture_subst C rho) (capture_subst D rho)
with ty_runtime_conv_subst {n : nat}
    {R : Path n -> Path n -> Type} {T U : Ty n}
    (conversion : TyRuntimeConv R T U) {struct conversion} :
    forall {m : nat} {E : Path m -> Path m -> Type}
      (rho : PathSubst n m), PathSubstHom R E rho ->
      TyRuntimeConv E (ty_subst T rho) (ty_subst U rho)
with shape_runtime_conv_subst {n : nat}
    {R : Path n -> Path n -> Type} {S0 T : Shape n}
    (conversion : ShapeRuntimeConv R S0 T) {struct conversion} :
    forall {m : nat} {E : Path m -> Path m -> Type}
      (rho : PathSubst n m), PathSubstHom R E rho ->
      ShapeRuntimeConv E (shape_subst S0 rho) (shape_subst T rho)
with tau_runtime_conv_subst {n : nat}
    {R : Path n -> Path n -> Type} {k : Kind} {d e : Tau n k}
    (conversion : TauRuntimeConv R d e) {struct conversion} :
    forall {m : nat} {E : Path m -> Path m -> Type}
      (rho : PathSubst n m), PathSubstHom R E rho ->
      TauRuntimeConv E (tau_subst d rho) (tau_subst e rho).
Proof.
  - intros m E rho map_paths. destruct conversion.
    + exact CRC_refl.
    + exact (capture_runtime_conv_subst_replace context r
        (rho := rho) map_paths).
    + exact CRC_empty.
    + exact (CRC_union
        (@capture_runtime_conv_subst _ _ _ _ conversion1 _ _ rho map_paths)
        (@capture_runtime_conv_subst _ _ _ _ conversion2 _ _ rho map_paths)).
    + exact (CRC_singleton (map_paths _ _ r)).
    + exact (CRC_select (map_paths _ _ r)).
  - intros m E rho map_paths. destruct conversion.
    + exact TRC_refl.
    + exact (ty_runtime_conv_subst_replace context r
        (rho := rho) map_paths).
    + exact (TRC_capt
        (@capture_runtime_conv_subst _ _ _ _ c _ _ rho map_paths)
        (@shape_runtime_conv_subst _ _ _ _ s _ _ rho map_paths)).
  - intros m E rho map_paths. destruct conversion.
    + exact SRC_refl.
    + exact (shape_runtime_conv_subst_replace context r
        (rho := rho) map_paths).
    + exact SRC_top.
    + exact SRC_bot.
    + exact (SRC_fun
        (@ty_runtime_conv_subst _ _ _ _ t _ _ rho map_paths)
        (@ty_runtime_conv_subst _ _ _ _ t0 _ _
          (path_subst_lift rho)
          (fun p q evidence => path_scoped_lift_subst map_paths evidence))).
    + exact (SRC_pair
        (@ty_runtime_conv_subst _ _ _ _ t _ _ rho map_paths)
        (@tau_runtime_conv_subst _ _ _ _ _ t0 _ _
          (path_subst_lift rho)
          (fun p q evidence => path_scoped_lift_subst map_paths evidence))).
    + exact (SRC_single (map_paths _ _ r)).
    + exact (SRC_selection (map_paths _ _ r)).
  - intros m E rho map_paths. destruct conversion.
    + exact TaRC_refl.
    + exact (tau_runtime_conv_subst_replace context r
        (rho := rho) map_paths).
    + exact (TaRC_term
        (@ty_runtime_conv_subst _ _ _ _ t _ _ rho map_paths)).
    + exact (TaRC_type
        (@shape_runtime_conv_subst _ _ _ _ s _ _ rho map_paths)
        (@shape_runtime_conv_subst _ _ _ _ s0 _ _ rho map_paths)).
    + exact (TaRC_capture
        (@capture_runtime_conv_subst _ _ _ _ c _ _ rho map_paths)
        (@capture_runtime_conv_subst _ _ _ _ c0 _ _ rho map_paths)).
Defined.

(** Renaming is substitution by the path embedding of a finite map. *)
Definition capture_runtime_conv_rename {n m : nat}
    {R : Path n -> Path n -> Type} {E : Path m -> Path m -> Type}
    {C D : CaptureSet n} (f : FinFun n m)
    (map_paths : forall p q, R p q ->
      E (path_rename p f) (path_rename q f))
    (conversion : CaptureRuntimeConv R C D) :
    CaptureRuntimeConv E (capture_rename C f) (capture_rename D f).
Proof.
  rewrite <- !capture_subst_as_rename.
  apply (capture_runtime_conv_subst conversion
    (rho := finfun_as_subst f)).
  intros p q evidence. rewrite !path_subst_as_rename.
  exact (map_paths p q evidence).
Defined.

Definition ty_runtime_conv_rename {n m : nat}
    {R : Path n -> Path n -> Type} {E : Path m -> Path m -> Type}
    {T U : Ty n} (f : FinFun n m)
    (map_paths : forall p q, R p q ->
      E (path_rename p f) (path_rename q f))
    (conversion : TyRuntimeConv R T U) :
    TyRuntimeConv E (ty_rename T f) (ty_rename U f).
Proof.
  rewrite <- !ty_subst_as_rename.
  apply (ty_runtime_conv_subst conversion
    (rho := finfun_as_subst f)).
  intros p q evidence. rewrite !path_subst_as_rename.
  exact (map_paths p q evidence).
Defined.

Definition shape_runtime_conv_rename {n m : nat}
    {R : Path n -> Path n -> Type} {E : Path m -> Path m -> Type}
    {S0 T : Shape n} (f : FinFun n m)
    (map_paths : forall p q, R p q ->
      E (path_rename p f) (path_rename q f))
    (conversion : ShapeRuntimeConv R S0 T) :
    ShapeRuntimeConv E (shape_rename S0 f) (shape_rename T f).
Proof.
  rewrite <- !shape_subst_as_rename.
  apply (shape_runtime_conv_subst conversion
    (rho := finfun_as_subst f)).
  intros p q evidence. rewrite !path_subst_as_rename.
  exact (map_paths p q evidence).
Defined.

Definition tau_runtime_conv_rename {n m : nat}
    {R : Path n -> Path n -> Type} {E : Path m -> Path m -> Type}
    {k : Kind} {d e : Tau n k} (f : FinFun n m)
    (map_paths : forall p q, R p q ->
      E (path_rename p f) (path_rename q f))
    (conversion : TauRuntimeConv R d e) :
    TauRuntimeConv E (tau_rename d f) (tau_rename e f).
Proof.
  rewrite <- !tau_subst_as_rename.
  apply (tau_runtime_conv_subst conversion
    (rho := finfun_as_subst f)).
  intros p q evidence. rewrite !path_subst_as_rename.
  exact (map_paths p q evidence).
Defined.

(** Scoped type conversion is stable under ambient allocation. *)
Definition ty_runtime_conv_weaken_scoped {n : nat} {sigma : Store n}
    {T U : Ty (S n)}
    (conversion : TyRuntimeConv
      (PathScopedLift (PathRuntimeEq sigma)) T U)
    (v : Tm n) (is_value : Tm_IsValue v) :
    TyRuntimeConv
      (PathScopedLift (PathRuntimeEq (StoreVal sigma v is_value)))
      (ty_rename T (ext (weaken n)))
      (ty_rename U (ext (weaken n))).
Proof.
  exact (ty_runtime_conv_rename (f := ext (weaken n))
    (fun p q evidence =>
      path_scoped_lift_weaken_runtime evidence (v := v) is_value)
    conversion).
Defined.

(** Opening scoped conversions with the same ambient argument. *)
Definition capture_runtime_conv_open_same {n : nat}
    {R : Path n -> Path n -> Type} {C D : CaptureSet (S n)}
    (operations : PathEqCongruence R)
    (conversion : CaptureRuntimeConv (PathScopedLift R) C D)
    (argument : Path n) :
    CaptureRuntimeConv R (capture_open C argument) (capture_open D argument).
Proof.
  unfold capture_open.
  apply (capture_runtime_conv_subst conversion
    (rho := path_subst_openAt argument)).
  intros p q evidence.
  exact (path_scoped_lift_open operations evidence
    (eq_refl operations argument)).
Defined.

Definition ty_runtime_conv_open_same {n : nat}
    {R : Path n -> Path n -> Type} {T U : Ty (S n)}
    (operations : PathEqCongruence R)
    (conversion : TyRuntimeConv (PathScopedLift R) T U)
    (argument : Path n) :
    TyRuntimeConv R (ty_open T argument) (ty_open U argument).
Proof.
  unfold ty_open.
  apply (ty_runtime_conv_subst conversion
    (rho := path_subst_openAt argument)).
  intros p q evidence.
  exact (path_scoped_lift_open operations evidence
    (eq_refl operations argument)).
Defined.

Definition shape_runtime_conv_open_same {n : nat}
    {R : Path n -> Path n -> Type} {S0 T : Shape (S n)}
    (operations : PathEqCongruence R)
    (conversion : ShapeRuntimeConv (PathScopedLift R) S0 T)
    (argument : Path n) :
    ShapeRuntimeConv R (shape_open S0 argument) (shape_open T argument).
Proof.
  unfold shape_open.
  apply (shape_runtime_conv_subst conversion
    (rho := path_subst_openAt argument)).
  intros p q evidence.
  exact (path_scoped_lift_open operations evidence
    (eq_refl operations argument)).
Defined.

Definition tau_runtime_conv_open_same {n : nat}
    {R : Path n -> Path n -> Type} {k : Kind} {d e : Tau (S n) k}
    (operations : PathEqCongruence R)
    (conversion : TauRuntimeConv (PathScopedLift R) d e)
    (argument : Path n) :
    TauRuntimeConv R (tau_open d argument) (tau_open e argument).
Proof.
  unfold tau_open.
  apply (tau_runtime_conv_subst conversion
    (rho := path_subst_openAt argument)).
  intros p q evidence.
  exact (path_scoped_lift_open operations evidence
    (eq_refl operations argument)).
Defined.

(** Unscoped conversions survive allocation. *)
Definition capture_runtime_conv_weaken {n : nat} {sigma : Store n}
    {C D : CaptureSet n}
    (conversion : CaptureRuntimeConv (PathRuntimeEq sigma) C D)
    (v : Tm n) (is_value : Tm_IsValue v) :
    CaptureRuntimeConv (PathRuntimeEq (StoreVal sigma v is_value))
      (capture_weaken C) (capture_weaken D).
Proof.
  unfold capture_weaken.
  exact (capture_runtime_conv_rename (f := weaken n)
    (fun p q evidence => path_runtime_eq_weaken evidence (v := v) is_value)
    conversion).
Defined.

Definition ty_runtime_conv_weaken {n : nat} {sigma : Store n}
    {T U : Ty n} (conversion : TyRuntimeConv (PathRuntimeEq sigma) T U)
    (v : Tm n) (is_value : Tm_IsValue v) :
    TyRuntimeConv (PathRuntimeEq (StoreVal sigma v is_value))
      (ty_weaken T) (ty_weaken U).
Proof.
  unfold ty_weaken.
  exact (ty_runtime_conv_rename (f := weaken n)
    (fun p q evidence => path_runtime_eq_weaken evidence (v := v) is_value)
    conversion).
Defined.

Definition shape_runtime_conv_weaken {n : nat} {sigma : Store n}
    {S0 T : Shape n}
    (conversion : ShapeRuntimeConv (PathRuntimeEq sigma) S0 T)
    (v : Tm n) (is_value : Tm_IsValue v) :
    ShapeRuntimeConv (PathRuntimeEq (StoreVal sigma v is_value))
      (shape_weaken S0) (shape_weaken T).
Proof.
  unfold shape_weaken.
  exact (shape_runtime_conv_rename (f := weaken n)
    (fun p q evidence => path_runtime_eq_weaken evidence (v := v) is_value)
    conversion).
Defined.

Definition tau_runtime_conv_weaken {n : nat} {sigma : Store n}
    {k : Kind} {d e : Tau n k}
    (conversion : TauRuntimeConv (PathRuntimeEq sigma) d e)
    (v : Tm n) (is_value : Tm_IsValue v) :
    TauRuntimeConv (PathRuntimeEq (StoreVal sigma v is_value))
      (tau_weaken d) (tau_weaken e).
Proof.
  unfold tau_weaken.
  exact (tau_runtime_conv_rename (f := weaken n)
    (fun p q evidence => path_runtime_eq_weaken evidence (v := v) is_value)
    conversion).
Defined.

(** Pointwise-related substitutions remain related after binder lifting. *)
Definition path_scoped_lift_pointwise {l n : nat}
    {R : Path n -> Path n -> Type} {rho1 rho2 : PathSubst l n}
    (related : forall x, R (subst_apply rho1 x) (subst_apply rho2 x)) :
    forall x, PathScopedLift R
      (subst_apply (path_subst_lift rho1) x)
      (subst_apply (path_subst_lift rho2) x).
Proof.
  intro x.
  refine (fin_case (P := fun x => PathScopedLift R
      (subst_apply (path_subst_lift rho1) x)
      (subst_apply (path_subst_lift rho2) x)) _ _ x).
  - rewrite !subst_lift_zero. exact SL_bound.
  - intro i. rewrite !subst_lift_succ. exact (SL_old (related i)).
Defined.

(** Componentwise structural view of runtime conversion. *)
Inductive CaptureRuntimeCongruent :
    forall {n : nat}, (Path n -> Path n -> Type) ->
      CaptureSet n -> CaptureSet n -> Type :=
| CRCG_empty {n : nat} {R : Path n -> Path n -> Type} :
    CaptureRuntimeCongruent R CEmpty CEmpty
| CRCG_union {n : nat} {R : Path n -> Path n -> Type}
    {C C' D D' : CaptureSet n} :
    CaptureRuntimeCongruent R C C' -> CaptureRuntimeCongruent R D D' ->
    CaptureRuntimeCongruent R (CUnion C D) (CUnion C' D')
| CRCG_singleton {n : nat} {R : Path n -> Path n -> Type}
    {p q : Path n} : R p q ->
    CaptureRuntimeCongruent R (CSingleton p) (CSingleton q)
| CRCG_select {n : nat} {R : Path n -> Path n -> Type}
    {p q : Path n} {a : Name} : R p q ->
    CaptureRuntimeCongruent R (CSelect p a) (CSelect q a)
with TyRuntimeCongruent :
    forall {n : nat}, (Path n -> Path n -> Type) -> Ty n -> Ty n -> Type :=
| TRCG_capt {n : nat} {R : Path n -> Path n -> Type}
    {C D : CaptureSet n} {S0 T : Shape n} :
    CaptureRuntimeCongruent R C D -> ShapeRuntimeCongruent R S0 T ->
    TyRuntimeCongruent R (TyCapt C S0) (TyCapt D T)
with ShapeRuntimeCongruent :
    forall {n : nat}, (Path n -> Path n -> Type) ->
      Shape n -> Shape n -> Type :=
| SRCG_top {n : nat} {R : Path n -> Path n -> Type} :
    ShapeRuntimeCongruent R ShTop ShTop
| SRCG_bot {n : nat} {R : Path n -> Path n -> Type} :
    ShapeRuntimeCongruent R ShBot ShBot
| SRCG_fun {n : nat} {R : Path n -> Path n -> Type}
    {S0 S' : Ty n} {T T' : Ty (S n)} :
    TyRuntimeCongruent R S0 S' ->
    TyRuntimeCongruent (PathScopedLift R) T T' ->
    ShapeRuntimeCongruent R (ShFun S0 T) (ShFun S' T')
| SRCG_pair {n : nat} {R : Path n -> Path n -> Type}
    {k : Kind} {S0 S' : Ty n} {a : Name} {d d' : Tau (S n) k} :
    TyRuntimeCongruent R S0 S' ->
    TauRuntimeCongruent (PathScopedLift R) d d' ->
    ShapeRuntimeCongruent R (ShPair S0 a d) (ShPair S' a d')
| SRCG_single {n : nat} {R : Path n -> Path n -> Type}
    {p q : Path n} : R p q ->
    ShapeRuntimeCongruent R (ShSingle p) (ShSingle q)
| SRCG_selection {n : nat} {R : Path n -> Path n -> Type}
    {p q : Path n} {a : Name} : R p q ->
    ShapeRuntimeCongruent R (ShTSel p a) (ShTSel q a)
with TauRuntimeCongruent :
    forall {n : nat}, (Path n -> Path n -> Type) ->
      forall {k : Kind}, Tau n k -> Tau n k -> Type :=
| TaRCG_term {n : nat} {R : Path n -> Path n -> Type}
    {T U : Ty n} : TyRuntimeCongruent R T U ->
    TauRuntimeCongruent R (TauTerm T) (TauTerm U)
| TaRCG_type {n : nat} {R : Path n -> Path n -> Type}
    {L L' U U' : Shape n} :
    ShapeRuntimeCongruent R L L' -> ShapeRuntimeCongruent R U U' ->
    TauRuntimeCongruent R (TauType L U) (TauType L' U')
| TaRCG_capture {n : nat} {R : Path n -> Path n -> Type}
    {C C' D D' : CaptureSet n} :
    CaptureRuntimeCongruent R C C' ->
    CaptureRuntimeCongruent R D D' ->
    TauRuntimeCongruent R (TauCapture C D) (TauCapture C' D').

Arguments CRCG_empty {n R}.
Arguments CRCG_union {n R C C' D D'} _ _.
Arguments CRCG_singleton {n R p q} _.
Arguments CRCG_select {n R p q a} _.
Arguments TRCG_capt {n R C D S0 T} _ _.
Arguments SRCG_top {n R}.
Arguments SRCG_bot {n R}.
Arguments SRCG_fun {n R S0 S' T T'} _ _.
Arguments SRCG_pair {n R k S0 S' a d d'} _ _.
Arguments SRCG_single {n R p q} _.
Arguments SRCG_selection {n R p q a} _.
Arguments TaRCG_term {n R T U} _.
Arguments TaRCG_type {n R L L' U U'} _ _.
Arguments TaRCG_capture {n R C C' D D'} _ _.

(** Reflexivity for the structural view. *)
Equations capture_runtime_congruent_refl {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    (C : CaptureSet n) : CaptureRuntimeCongruent R C C
    by struct C :=
capture_runtime_congruent_refl operations CEmpty := CRCG_empty;
capture_runtime_congruent_refl operations (CUnion C D) :=
  CRCG_union (capture_runtime_congruent_refl operations C)
    (capture_runtime_congruent_refl operations D);
capture_runtime_congruent_refl operations (CSingleton p) :=
  CRCG_singleton (eq_refl operations p);
capture_runtime_congruent_refl operations (CSelect p a) :=
  CRCG_select (eq_refl operations p).

Equations ty_runtime_congruent_refl {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    (T : Ty n) : TyRuntimeCongruent R T T by struct T :=
ty_runtime_congruent_refl operations (TyCapt C shape) :=
  TRCG_capt (capture_runtime_congruent_refl operations C)
    (shape_runtime_congruent_refl operations shape)
with shape_runtime_congruent_refl {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    (shape : Shape n) : ShapeRuntimeCongruent R shape shape
    by struct shape :=
shape_runtime_congruent_refl operations ShTop := SRCG_top;
shape_runtime_congruent_refl operations ShBot := SRCG_bot;
shape_runtime_congruent_refl operations (ShFun dom cod) :=
  SRCG_fun (ty_runtime_congruent_refl operations dom)
    (ty_runtime_congruent_refl
      (path_scoped_lift_congruence operations) cod);
shape_runtime_congruent_refl operations (ShPair first a member) :=
  SRCG_pair (ty_runtime_congruent_refl operations first)
    (tau_runtime_congruent_refl
      (path_scoped_lift_congruence operations) member);
shape_runtime_congruent_refl operations (ShSingle p) :=
  SRCG_single (eq_refl operations p);
shape_runtime_congruent_refl operations (ShTSel p a) :=
  SRCG_selection (eq_refl operations p)
with tau_runtime_congruent_refl {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    {k : Kind} (d : Tau n k) : TauRuntimeCongruent R d d by struct d :=
tau_runtime_congruent_refl operations (TauTerm T) :=
  TaRCG_term (ty_runtime_congruent_refl operations T);
tau_runtime_congruent_refl operations (TauType lower upper) :=
  TaRCG_type (shape_runtime_congruent_refl operations lower)
    (shape_runtime_congruent_refl operations upper);
tau_runtime_congruent_refl operations (TauCapture lower upper) :=
  TaRCG_capture (capture_runtime_congruent_refl operations lower)
    (capture_runtime_congruent_refl operations upper).

(** Symmetry for the structural view. *)
Fixpoint capture_runtime_congruent_symm {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    {C D : CaptureSet n} (conversion : CaptureRuntimeCongruent R C D)
    {struct conversion} : CaptureRuntimeCongruent R D C.
Proof.
  destruct conversion.
  - exact CRCG_empty.
  - exact (CRCG_union
      (@capture_runtime_congruent_symm _ _ operations _ _ conversion1)
      (@capture_runtime_congruent_symm _ _ operations _ _ conversion2)).
  - exact (CRCG_singleton (eq_symm operations r)).
  - exact (CRCG_select (eq_symm operations r)).
Defined.

Fixpoint ty_runtime_congruent_symm {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    {T U : Ty n} (conversion : TyRuntimeCongruent R T U)
    {struct conversion} : TyRuntimeCongruent R U T
with shape_runtime_congruent_symm {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    {S0 T : Shape n} (conversion : ShapeRuntimeCongruent R S0 T)
    {struct conversion} : ShapeRuntimeCongruent R T S0
with tau_runtime_congruent_symm {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    {k : Kind} {d e : Tau n k} (conversion : TauRuntimeCongruent R d e)
    {struct conversion} : TauRuntimeCongruent R e d.
Proof.
  - destruct conversion.
    exact (TRCG_capt
      (capture_runtime_congruent_symm operations c)
      (@shape_runtime_congruent_symm _ _ operations _ _ s)).
  - destruct conversion.
    + exact SRCG_top.
    + exact SRCG_bot.
    + exact (SRCG_fun
        (@ty_runtime_congruent_symm _ _ operations _ _ t)
        (@ty_runtime_congruent_symm _ _
          (path_scoped_lift_congruence operations) _ _ t0)).
    + exact (SRCG_pair
        (@ty_runtime_congruent_symm _ _ operations _ _ t)
        (@tau_runtime_congruent_symm _ _
          (path_scoped_lift_congruence operations) _ _ _ t0)).
    + exact (SRCG_single (eq_symm operations r)).
    + exact (SRCG_selection (eq_symm operations r)).
  - destruct conversion.
    + exact (TaRCG_term
        (@ty_runtime_congruent_symm _ _ operations _ _ t)).
    + exact (TaRCG_type
        (@shape_runtime_congruent_symm _ _ operations _ _ s)
        (@shape_runtime_congruent_symm _ _ operations _ _ s0)).
    + exact (TaRCG_capture
        (capture_runtime_congruent_symm operations c)
        (capture_runtime_congruent_symm operations c0)).
Defined.

(** A path congruence maps pointwise-related substitutions to related
    paths. *)
Fixpoint path_eq_congruence_of_subst {l n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    (rho1 rho2 : PathSubst l n)
    (related : forall x, R (subst_apply rho1 x) (subst_apply rho2 x))
    (p : Path l) {struct p} :
    R (path_subst p rho1) (path_subst p rho2).
Proof.
  destruct p.
  - exact (related f).
  - simp path_subst. apply (eq_fst operations).
    exact (@path_eq_congruence_of_subst _ _ _ operations rho1 rho2
      related p).
  - simp path_subst. apply (eq_sel operations).
    exact (@path_eq_congruence_of_subst _ _ _ operations rho1 rho2
      related p).
Defined.

Fixpoint capture_runtime_congruent_of_subst {l n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    (rho1 rho2 : PathSubst l n)
    (related : forall x, R (subst_apply rho1 x) (subst_apply rho2 x))
    (C : CaptureSet l) {struct C} :
    CaptureRuntimeCongruent R (capture_subst C rho1) (capture_subst C rho2)
    .
Proof.
  destruct C.
  - exact CRCG_empty.
  - simp capture_subst. exact (CRCG_union
      (@capture_runtime_congruent_of_subst _ _ _ operations rho1 rho2
        related C1)
      (@capture_runtime_congruent_of_subst _ _ _ operations rho1 rho2
        related C2)).
  - simp capture_subst. exact (CRCG_singleton
      (path_eq_congruence_of_subst operations
        (rho1 := rho1) (rho2 := rho2) related p)).
  - simp capture_subst. exact (CRCG_select
      (path_eq_congruence_of_subst operations
        (rho1 := rho1) (rho2 := rho2) related p)).
Defined.

Unset Implicit Arguments.

Equations ty_runtime_congruent_of_subst {l n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    (rho1 rho2 : PathSubst l n)
    (related : forall x, R (subst_apply rho1 x) (subst_apply rho2 x))
    (T : Ty l) : TyRuntimeCongruent R (ty_subst T rho1) (ty_subst T rho2)
    by struct T :=
ty_runtime_congruent_of_subst operations rho1 rho2 related
    (TyCapt C shape) :=
  TRCG_capt
    (capture_runtime_congruent_of_subst operations
      (rho1 := rho1) (rho2 := rho2) related C)
    (shape_runtime_congruent_of_subst operations rho1 rho2 related shape)
with shape_runtime_congruent_of_subst {l n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    (rho1 rho2 : PathSubst l n)
    (related : forall x, R (subst_apply rho1 x) (subst_apply rho2 x))
    (shape : Shape l) :
    ShapeRuntimeCongruent R
      (shape_subst shape rho1) (shape_subst shape rho2)
    by struct shape :=
shape_runtime_congruent_of_subst operations rho1 rho2 related ShTop :=
  SRCG_top;
shape_runtime_congruent_of_subst operations rho1 rho2 related ShBot :=
  SRCG_bot;
shape_runtime_congruent_of_subst operations rho1 rho2 related
    (ShFun dom cod) :=
  SRCG_fun
    (ty_runtime_congruent_of_subst operations rho1 rho2 related dom)
    (ty_runtime_congruent_of_subst
      (path_scoped_lift_congruence operations)
      (path_subst_lift rho1) (path_subst_lift rho2)
      (path_scoped_lift_pointwise related) cod);
shape_runtime_congruent_of_subst operations rho1 rho2 related
    (ShPair first a member) :=
  SRCG_pair
    (ty_runtime_congruent_of_subst operations rho1 rho2 related first)
    (tau_runtime_congruent_of_subst
      (path_scoped_lift_congruence operations)
      (path_subst_lift rho1) (path_subst_lift rho2)
      (path_scoped_lift_pointwise related) member);
shape_runtime_congruent_of_subst operations rho1 rho2 related
    (ShSingle p) :=
  SRCG_single (path_eq_congruence_of_subst operations
    (rho1 := rho1) (rho2 := rho2) related p);
shape_runtime_congruent_of_subst operations rho1 rho2 related
    (ShTSel p a) :=
  SRCG_selection
    (path_eq_congruence_of_subst operations
      (rho1 := rho1) (rho2 := rho2) related p)
with tau_runtime_congruent_of_subst {l n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    (rho1 rho2 : PathSubst l n)
    (related : forall x, R (subst_apply rho1 x) (subst_apply rho2 x))
    {k : Kind} (d : Tau l k) :
    TauRuntimeCongruent R (tau_subst d rho1) (tau_subst d rho2)
    by struct d :=
tau_runtime_congruent_of_subst operations rho1 rho2 related (TauTerm T) :=
  TaRCG_term (ty_runtime_congruent_of_subst operations rho1 rho2 related T);
tau_runtime_congruent_of_subst operations rho1 rho2 related
    (TauType lower upper) :=
  TaRCG_type
    (shape_runtime_congruent_of_subst operations rho1 rho2 related lower)
    (shape_runtime_congruent_of_subst operations rho1 rho2 related upper);
tau_runtime_congruent_of_subst operations rho1 rho2 related
    (TauCapture lower upper) :=
  TaRCG_capture
    (capture_runtime_congruent_of_subst operations
      (rho1 := rho1) (rho2 := rho2) related lower)
    (capture_runtime_congruent_of_subst operations
      (rho1 := rho1) (rho2 := rho2) related upper).

Set Implicit Arguments.

(** Embed structural congruence into general runtime conversion. *)
Fixpoint capture_runtime_congruent_to_conv {n : nat}
    {R : Path n -> Path n -> Type} {C D : CaptureSet n}
    (conversion : CaptureRuntimeCongruent R C D) {struct conversion} :
    CaptureRuntimeConv R C D.
Proof.
  destruct conversion.
  - exact CRC_empty.
  - exact (CRC_union
      (@capture_runtime_congruent_to_conv _ _ _ _ conversion1)
      (@capture_runtime_congruent_to_conv _ _ _ _ conversion2)).
  - exact (CRC_singleton r).
  - exact (CRC_select r).
Defined.

Fixpoint ty_runtime_congruent_to_conv {n : nat}
    {R : Path n -> Path n -> Type} {T U : Ty n}
    (conversion : TyRuntimeCongruent R T U) {struct conversion} :
    TyRuntimeConv R T U
with shape_runtime_congruent_to_conv {n : nat}
    {R : Path n -> Path n -> Type} {S0 T : Shape n}
    (conversion : ShapeRuntimeCongruent R S0 T) {struct conversion} :
    ShapeRuntimeConv R S0 T
with tau_runtime_congruent_to_conv {n : nat}
    {R : Path n -> Path n -> Type} {k : Kind} {d e : Tau n k}
    (conversion : TauRuntimeCongruent R d e) {struct conversion} :
    TauRuntimeConv R d e.
Proof.
  - destruct conversion.
    exact (TRC_capt (capture_runtime_congruent_to_conv c)
      (@shape_runtime_congruent_to_conv _ _ _ _ s)).
  - destruct conversion.
    + exact SRC_top.
    + exact SRC_bot.
    + exact (SRC_fun
        (@ty_runtime_congruent_to_conv _ _ _ _ t)
        (@ty_runtime_congruent_to_conv _ _ _ _ t0)).
    + exact (SRC_pair
        (@ty_runtime_congruent_to_conv _ _ _ _ t)
        (@tau_runtime_congruent_to_conv _ _ _ _ _ t0)).
    + exact (SRC_single r).
    + exact (SRC_selection r).
  - destruct conversion.
    + exact (TaRC_term (@ty_runtime_congruent_to_conv _ _ _ _ t)).
    + exact (TaRC_type
        (@shape_runtime_congruent_to_conv _ _ _ _ s)
        (@shape_runtime_congruent_to_conv _ _ _ _ s0)).
    + exact (TaRC_capture
        (capture_runtime_congruent_to_conv c)
        (capture_runtime_congruent_to_conv c0)).
Defined.

(** Opening substitutions at related paths are pointwise related. *)
Definition path_openAt_related {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    {p q : Path n} (evidence : R p q) :
    forall x, R
      (subst_apply (path_subst_openAt p) x)
      (subst_apply (path_subst_openAt q) x).
Proof.
  intro x.
  refine (fin_case (P := fun x => R
      (subst_apply (path_subst_openAt p) x)
      (subst_apply (path_subst_openAt q) x)) _ _ x).
  - rewrite !subst_openAt_zero. exact evidence.
  - intro i. rewrite !subst_openAt_succ. exact (eq_refl operations (PVar i)).
Defined.

(** Normalize arbitrary replacement conversion to componentwise path
    congruence. *)
Fixpoint capture_runtime_conv_congruent {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    {C D : CaptureSet n} (conversion : CaptureRuntimeConv R C D)
    {struct conversion} : CaptureRuntimeCongruent R C D.
Proof.
  destruct conversion.
  - exact (capture_runtime_congruent_refl operations C).
  - exact (capture_runtime_congruent_of_subst operations
      (rho1 := path_subst_openAt p) (rho2 := path_subst_openAt q)
      (path_openAt_related operations r) context).
  - exact CRCG_empty.
  - exact (CRCG_union
      (@capture_runtime_conv_congruent _ _ operations _ _ conversion1)
      (@capture_runtime_conv_congruent _ _ operations _ _ conversion2)).
  - exact (CRCG_singleton r).
  - exact (CRCG_select r).
Defined.

Fixpoint ty_runtime_conv_congruent {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    {T U : Ty n} (conversion : TyRuntimeConv R T U)
    {struct conversion} : TyRuntimeCongruent R T U
with shape_runtime_conv_congruent {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    {S0 T : Shape n} (conversion : ShapeRuntimeConv R S0 T)
    {struct conversion} : ShapeRuntimeCongruent R S0 T
with tau_runtime_conv_congruent {n : nat}
    {R : Path n -> Path n -> Type} (operations : PathEqCongruence R)
    {k : Kind} {d e : Tau n k} (conversion : TauRuntimeConv R d e)
    {struct conversion} : TauRuntimeCongruent R d e.
Proof.
  - destruct conversion.
    + exact (ty_runtime_congruent_refl operations T).
    + exact (ty_runtime_congruent_of_subst operations
        (path_subst_openAt p) (path_subst_openAt q)
        (path_openAt_related operations r) context).
    + exact (TRCG_capt
        (capture_runtime_conv_congruent operations c)
        (@shape_runtime_conv_congruent _ _ operations _ _ s)).
  - destruct conversion.
    + exact (shape_runtime_congruent_refl operations S0).
    + exact (shape_runtime_congruent_of_subst operations
        (path_subst_openAt p) (path_subst_openAt q)
        (path_openAt_related operations r) context).
    + exact SRCG_top.
    + exact SRCG_bot.
    + exact (SRCG_fun
        (@ty_runtime_conv_congruent _ _ operations _ _ t)
        (@ty_runtime_conv_congruent _ _
          (path_scoped_lift_congruence operations) _ _ t0)).
    + exact (SRCG_pair
        (@ty_runtime_conv_congruent _ _ operations _ _ t)
        (@tau_runtime_conv_congruent _ _
          (path_scoped_lift_congruence operations) _ _ _ t0)).
    + exact (SRCG_single r).
    + exact (SRCG_selection r).
  - destruct conversion.
    + exact (tau_runtime_congruent_refl operations d).
    + exact (tau_runtime_congruent_of_subst operations
        (path_subst_openAt p) (path_subst_openAt q)
        (path_openAt_related operations r) context).
    + exact (TaRCG_term
        (@ty_runtime_conv_congruent _ _ operations _ _ t)).
    + exact (TaRCG_type
        (@shape_runtime_conv_congruent _ _ operations _ _ s)
        (@shape_runtime_conv_congruent _ _ operations _ _ s0)).
    + exact (TaRCG_capture
        (capture_runtime_conv_congruent operations c)
        (capture_runtime_conv_congruent operations c0)).
Defined.

Print Assumptions path_runtime_eq_resolve_iff.
Print Assumptions ty_runtime_conv_weaken_scoped.
Print Assumptions tau_runtime_conv_congruent.
