import LambdaPFC.Runtime

/-!
Proof-relevant runtime equality and type conversion.

Runtime equality is generated by paths resolving to the same generalized
referent, then closed under equivalence and path contexts.  Its scoped lift
extends the relation below a source binder without giving the fresh variable
any equations beyond reflexivity.  Generalized-type conversion records
replacement of runtime-equal paths in an arbitrary type context.
-/

namespace LambdaPFC

/-! ## Substitution and generalized resolution -/

/-- Pointwise agreement of generalized resolution is stable under path
substitution. -/
theorem Path.Resolve.subst_congr
    {l n : Nat} {sigma : Store n} {r : Path l}
    {rho1 rho2 : PathSubst l n} {referent : Path.Referent n}
    (agree : forall x referent,
      Path.Resolve (rho1 x) sigma referent <->
        Path.Resolve (rho2 x) sigma referent)
    (resolution : Path.Resolve (r.subst rho1) sigma referent) :
    Path.Resolve (r.subst rho2) sigma referent := by
  induction r generalizing referent with
  | var x => exact (agree x referent).mp resolution
  | fst r ih =>
      simp only [Path.subst] at resolution |-
      cases resolution with
      | fst pathResolution binding =>
          exact .fst (ih pathResolution) binding
  | sel r a ih =>
      simp only [Path.subst] at resolution |-
      cases resolution with
      | sel pathResolution binding =>
          exact .sel (ih pathResolution) binding
      | sel_miss pathResolution binding distinct tail =>
          exact .sel_miss (ih pathResolution) binding distinct tail

theorem Path.Resolve.subst_iff
    {l n : Nat} {sigma : Store n} {r : Path l}
    {rho1 rho2 : PathSubst l n} {referent : Path.Referent n}
    (agree : forall x referent,
      Path.Resolve (rho1 x) sigma referent <->
        Path.Resolve (rho2 x) sigma referent) :
    Path.Resolve (r.subst rho1) sigma referent <->
      Path.Resolve (r.subst rho2) sigma referent :=
  Iff.intro (Path.Resolve.subst_congr agree)
    (Path.Resolve.subst_congr fun x referent => (agree x referent).symm)

/-- Replacing the hole of a path context by paths with the same resolution
graph preserves the result of the context. -/
theorem Path.Resolve.open_iff
    {n : Nat} {sigma : Store n} {p q : Path n}
    {referent : Path.Referent n}
    (agree : forall referent,
      Path.Resolve p sigma referent <-> Path.Resolve q sigma referent)
    (context : Path (n + 1)) :
    Path.Resolve (context.open p) sigma referent <->
      Path.Resolve (context.open q) sigma referent := by
  apply Path.Resolve.subst_iff
  intro x referent
  refine Fin.cases ?_ (fun _ => ?_) x
  · exact agree referent
  · exact Iff.rfl

/-! ## Runtime path equality -/

/-- Finite evidence for store-indexed runtime path equality. -/
inductive Path.RuntimeEq (sigma : Store n) : Path n -> Path n -> Type where
| refl : Path.RuntimeEq sigma p p
| symm : Path.RuntimeEq sigma p q -> Path.RuntimeEq sigma q p
| trans :
    Path.RuntimeEq sigma p q ->
    Path.RuntimeEq sigma q r ->
    Path.RuntimeEq sigma p r
| coresolve {referent : Path.Referent n} :
    Path.Resolve p sigma referent ->
    Path.Resolve q sigma referent ->
    Path.RuntimeEq sigma p q
| congr :
    Path.RuntimeEq sigma p q ->
    (context : Path (n + 1)) ->
    Path.RuntimeEq sigma (context.open p) (context.open q)

def Path.RuntimeEq.ofResolve
    (left : Path.Resolve p sigma referent)
    (right : Path.Resolve q sigma referent) :
    Path.RuntimeEq sigma p q :=
  .coresolve left right

def Path.RuntimeEq.fst
    (evidence : Path.RuntimeEq sigma p q) :
    Path.RuntimeEq sigma p.fst q.fst := by
  simpa [Path.open, Path.subst] using
    Path.RuntimeEq.congr evidence (Path.fst (Path.var 0))

def Path.RuntimeEq.sel
    (evidence : Path.RuntimeEq sigma p q) (a : Name) :
    Path.RuntimeEq sigma (p.sel a) (q.sel a) := by
  simpa [Path.open, Path.subst] using
    Path.RuntimeEq.congr evidence (Path.sel (Path.var 0) a)

/-- Runtime equality preserves the complete generalized-resolution graph. -/
theorem Path.RuntimeEq.resolve_iff
    {n : Nat} {sigma : Store n} {p q : Path n}
    (evidence : Path.RuntimeEq sigma p q) (referent : Path.Referent n) :
    Path.Resolve p sigma referent <-> Path.Resolve q sigma referent := by
  induction evidence generalizing referent with
  | refl => exact Iff.rfl
  | symm _ ih => exact (ih referent).symm
  | trans _ _ ih1 ih2 => exact (ih1 referent).trans (ih2 referent)
  | coresolve commonLeft commonRight =>
      constructor
      · intro left
        have referents := commonLeft.deterministic left
        cases referents
        exact commonRight
      · intro right
        have referents := commonRight.deterministic right
        cases referents
        exact commonLeft
  | congr _ context ih =>
      exact Path.Resolve.open_iff (fun referent => ih referent) context

noncomputable def Path.RuntimeEq.weaken
    {n : Nat} {sigma : Store n} {p q : Path n}
    (evidence : Path.RuntimeEq sigma p q)
    (v : Tm n) (vv : v.IsValue) :
    Path.RuntimeEq (Store.val sigma v vv) p.weaken q.weaken := by
  induction evidence with
  | refl => exact .refl
  | symm _ ih => exact .symm ih
  | trans _ _ ih1 ih2 => exact .trans ih1 ih2
  | coresolve left right =>
      exact .coresolve (left.weaken v vv) (right.weaken v vv)
  | congr _ context ih =>
      simpa [Path.weaken, Path.open_rename] using
        Path.RuntimeEq.congr ih (context.rename FinFun.weaken.ext)

/-! ## Generic equivalence and binder lifting -/

/-- Operations required of proof-relevant path equality. -/
structure Path.EqCongruence
    (R : Path n -> Path n -> Type) : Type where
  refl : forall p, R p p
  symm : forall {p q}, R p q -> R q p
  trans : forall {p q r}, R p q -> R q r -> R p r
  fst : forall {p q}, R p q -> R p.fst q.fst
  sel : forall {p q}, R p q -> forall a, R (p.sel a) (q.sel a)

def Path.RuntimeEq.eqCongruence (sigma : Store n) :
    Path.EqCongruence (Path.RuntimeEq sigma) where
  refl _ := .refl
  symm evidence := .symm evidence
  trans first second := .trans first second
  fst evidence := evidence.fst
  sel evidence a := evidence.sel a

/-- Least path congruence below a binder.  Ambient equations are weakened;
the fresh variable has only its reflexive seed. -/
inductive Path.ScopedLift
    (R : Path n -> Path n -> Type) :
    Path (n + 1) -> Path (n + 1) -> Type where
| bound : Path.ScopedLift R (.var 0) (.var 0)
| old : R p q -> Path.ScopedLift R p.weaken q.weaken
| symm : Path.ScopedLift R p q -> Path.ScopedLift R q p
| trans :
    Path.ScopedLift R p q ->
    Path.ScopedLift R q r ->
    Path.ScopedLift R p r
| fst : Path.ScopedLift R p q -> Path.ScopedLift R p.fst q.fst
| sel : Path.ScopedLift R p q -> Path.ScopedLift R (p.sel a) (q.sel a)

noncomputable def Path.ScopedLift.refl
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R) (p : Path (n + 1)) :
    Path.ScopedLift R p p := by
  induction p with
  | var x =>
      refine Fin.cases ?_ (fun y => ?_) x
      · exact .bound
      · simpa [Path.weaken, Path.rename] using
          Path.ScopedLift.old (operations.refl (Path.var y))
  | fst p ih => exact .fst ih
  | sel p a ih => exact .sel ih

noncomputable def Path.ScopedLift.eqCongruence
    (operations : Path.EqCongruence R) :
    Path.EqCongruence (Path.ScopedLift R) where
  refl := Path.ScopedLift.refl operations
  symm evidence := .symm evidence
  trans first second := .trans first second
  fst evidence := .fst evidence
  sel evidence _ := .sel evidence

/-- A relation morphism for simultaneous path substitution. -/
abbrev Path.SubstHom
    (R : Path n -> Path n -> Type)
    (E : Path m -> Path m -> Type)
    (rho : PathSubst n m) : Type :=
  forall {p q}, R p q -> E (p.subst rho) (q.subst rho)

/-- Substitution beneath a binder maps the scoped lift of a relation to the
scoped lift of its image. -/
noncomputable def Path.ScopedLift.subst
    {R : Path n -> Path n -> Type}
    {E : Path m -> Path m -> Type}
    {rho : PathSubst n m}
    (mapOld : Path.SubstHom R E rho)
    (evidence : Path.ScopedLift R p q) :
    Path.ScopedLift E (p.subst rho.lift) (q.subst rho.lift) := by
  induction evidence with
  | bound => exact .bound
  | old evidence =>
      simpa only [Path.weaken_subst_lift] using
        Path.ScopedLift.old (mapOld evidence)
  | symm _ ih => exact .symm ih
  | trans _ _ ih1 ih2 => exact .trans ih1 ih2
  | fst _ ih => exact .fst ih
  | sel _ ih => exact .sel ih

/-- Instantiating scoped equality with related paths yields ambient runtime
equality. -/
noncomputable def Path.ScopedLift.open
    {n : Nat} {R : Path n -> Path n -> Type}
    {p q : Path (n + 1)} {r s : Path n}
    (operations : Path.EqCongruence R)
    (evidence : Path.ScopedLift R p q)
    (arguments : R r s) :
    R (p.open r) (q.open s) := by
  induction evidence generalizing r s with
  | bound => exact arguments
  | old evidence =>
      simpa only [Path.weaken_open] using evidence
  | symm _ ih => exact operations.symm (ih (operations.symm arguments))
  | trans _ _ ih1 ih2 =>
      exact operations.trans (ih1 arguments) (ih2 (operations.refl s))
  | fst _ ih => exact operations.fst (ih arguments)
  | sel _ ih => exact operations.sel (ih arguments) _

/-! ## Proof-relevant generalized-type conversion -/

/-- Finite conversion evidence generated by replacement of related paths. -/
inductive Tau.RuntimeConv :
    {n : Nat} -> (Path n -> Path n -> Type) ->
    {k : Kind} -> Tau n k -> Tau n k -> Type 1 where
| refl : Tau.RuntimeConv R d d
| symm : Tau.RuntimeConv R d1 d2 -> Tau.RuntimeConv R d2 d1
| trans :
    Tau.RuntimeConv R d1 d2 ->
    Tau.RuntimeConv R d2 d3 ->
    Tau.RuntimeConv R d1 d3
| replace :
    (context : Tau (n + 1) k) ->
    R p q ->
    Tau.RuntimeConv R (context.open p) (context.open q)
| fun :
    Tau.RuntimeConv R (.ty S) (.ty S') ->
    Tau.RuntimeConv (Path.ScopedLift R) (.ty T) (.ty T') ->
    Tau.RuntimeConv R (.ty (.Fun S T)) (.ty (.Fun S' T'))
| pair :
    Tau.RuntimeConv R (.ty S) (.ty S') ->
    Tau.RuntimeConv (Path.ScopedLift R) d d' ->
    Tau.RuntimeConv R
      (.ty (.Pair S a d)) (.ty (.Pair S' a d'))
| single :
    R p q ->
    Tau.RuntimeConv R (.ty (.Single p)) (.ty (.Single q))
| selection :
    R p q ->
    Tau.RuntimeConv R (.ty (.TSel p A)) (.ty (.TSel q A))
| interval :
    Tau.RuntimeConv R (.ty L) (.ty L') ->
    Tau.RuntimeConv R (.ty U) (.ty U') ->
    Tau.RuntimeConv R (.intv L U) (.intv L' U')

/-- Conversion is natural with respect to simultaneous substitution and a
map of the underlying path relation. -/
noncomputable def Tau.RuntimeConv.subst
    {n m : Nat}
    {R : Path n -> Path n -> Type}
    {E : Path m -> Path m -> Type}
    {rho : PathSubst n m} {k : Kind} {d1 d2 : Tau n k}
    (mapPaths : Path.SubstHom R E rho)
    (conversion : Tau.RuntimeConv R d1 d2) :
    Tau.RuntimeConv E (d1.subst rho) (d2.subst rho) :=
  match conversion with
  | .refl => .refl
  | .symm code => .symm (code.subst mapPaths)
  | .trans first second =>
      .trans (first.subst mapPaths) (second.subst mapPaths)
  | .replace context evidence => by
      simpa only [Tau.open_subst] using
        Tau.RuntimeConv.replace (context.subst rho.lift)
          (mapPaths evidence)
  | .fun domain codomain =>
      .fun (domain.subst mapPaths)
        (codomain.subst (rho := rho.lift)
          fun evidence => evidence.subst mapPaths)
  | .pair first member =>
      .pair (first.subst mapPaths)
        (member.subst (rho := rho.lift)
          fun evidence => evidence.subst mapPaths)
  | .single evidence => .single (mapPaths evidence)
  | .selection evidence => .selection (mapPaths evidence)
  | .interval lower upper =>
      .interval (lower.subst mapPaths) (upper.subst mapPaths)

/-- Renaming is the variable-only instance of conversion substitution. -/
noncomputable def Tau.RuntimeConv.rename
    {R : Path n -> Path n -> Type}
    {E : Path m -> Path m -> Type}
    (f : FinFun n m)
    (mapPaths : forall {p q}, R p q -> E (p.rename f) (q.rename f))
    (conversion : Tau.RuntimeConv R d1 d2) :
    Tau.RuntimeConv E (d1.rename f) (d2.rename f) := by
  simpa only [Tau.subst_asSubst] using
    conversion.subst (rho := f.asSubst) (fun evidence => by
      simpa only [Path.subst_asSubst] using mapPaths evidence)

/-- Opening a scoped conversion at one path. -/
noncomputable def Tau.RuntimeConv.openSame
    {n : Nat} {R : Path n -> Path n -> Type}
    {d1 d2 : Tau (n + 1) k}
    (operations : Path.EqCongruence R)
    (conversion : Tau.RuntimeConv (Path.ScopedLift R) d1 d2)
    (argument : Path n) :
    Tau.RuntimeConv R (d1.open argument) (d2.open argument) := by
  exact conversion.subst (rho := PathSubst.openAt argument)
    (fun evidence => evidence.open operations (operations.refl argument))

/-- Runtime conversion survives allocation. -/
noncomputable def Tau.RuntimeConv.weaken
    {n : Nat} {sigma : Store n} {d1 d2 : Tau n k}
    (conversion : Tau.RuntimeConv (Path.RuntimeEq sigma) d1 d2)
    (v : Tm n) (vv : v.IsValue) :
    Tau.RuntimeConv (Path.RuntimeEq (Store.val sigma v vv))
      d1.weaken d2.weaken := by
  simpa only [Tau.weaken] using
    conversion.rename FinFun.weaken (fun evidence => evidence.weaken v vv)

/-! ## Structural view -/

mutual

/-- Structural normal form for runtime conversion of proper types. -/
inductive Ty.RuntimeCongruent :
    {n : Nat} -> (Path n -> Path n -> Type) ->
      Ty n -> Ty n -> Type 1 where
| top : Ty.RuntimeCongruent R .Top .Top
| bot : Ty.RuntimeCongruent R .Bot .Bot
| fun :
    Ty.RuntimeCongruent R S S' ->
    Ty.RuntimeCongruent (Path.ScopedLift R) T T' ->
    Ty.RuntimeCongruent R (.Fun S T) (.Fun S' T')
| pair :
    Ty.RuntimeCongruent R S S' ->
    Tau.RuntimeCongruent (Path.ScopedLift R) d d' ->
    Ty.RuntimeCongruent R (.Pair S a d) (.Pair S' a d')
| single : R p q -> Ty.RuntimeCongruent R (.Single p) (.Single q)
| selection : R p q -> Ty.RuntimeCongruent R (.TSel p A) (.TSel q A)

/-- Structural normal form for runtime conversion of generalized types. -/
inductive Tau.RuntimeCongruent :
    {n : Nat} -> (Path n -> Path n -> Type) ->
      {k : Kind} -> Tau n k -> Tau n k -> Type 1 where
| proper : Ty.RuntimeCongruent R S T ->
    Tau.RuntimeCongruent R (.ty S) (.ty T)
| interval :
    Ty.RuntimeCongruent R L L' ->
    Ty.RuntimeCongruent R U U' ->
    Tau.RuntimeCongruent R (.intv L U) (.intv L' U')

end

/-- Pointwise related substitutions remain related after lifting through one
binder. -/
def Path.ScopedLift.pointwise
    {R : Path n -> Path n -> Type}
    {rho1 rho2 : PathSubst l n}
    (related : forall x, R (rho1 x) (rho2 x)) :
    forall x, Path.ScopedLift R (rho1.lift x) (rho2.lift x) := by
  intro x
  refine Fin.cases ?_ (fun i => ?_) x
  · exact .bound
  · exact .old (related i)

mutual

noncomputable def Ty.RuntimeCongruent.refl
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R) :
    (T : Ty n) -> Ty.RuntimeCongruent R T T
| .Top => .top
| .Bot => .bot
| .Fun S T =>
    .fun (Ty.RuntimeCongruent.refl operations S)
      (Ty.RuntimeCongruent.refl
        (Path.ScopedLift.eqCongruence operations) T)
| .Pair S _ d =>
    .pair (Ty.RuntimeCongruent.refl operations S)
      (Tau.RuntimeCongruent.refl
        (Path.ScopedLift.eqCongruence operations) d)
| .Single p => .single (operations.refl p)
| .TSel p _ => .selection (operations.refl p)

noncomputable def Tau.RuntimeCongruent.refl
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R) :
    (d : Tau n k) -> Tau.RuntimeCongruent R d d
| .ty T => .proper (Ty.RuntimeCongruent.refl operations T)
| .intv L U =>
    .interval (Ty.RuntimeCongruent.refl operations L)
      (Ty.RuntimeCongruent.refl operations U)

end

mutual

noncomputable def Ty.RuntimeCongruent.symm :
    (operations : Path.EqCongruence R) ->
    Ty.RuntimeCongruent R S T -> Ty.RuntimeCongruent R T S
| _, .top => .top
| _, .bot => .bot
| operations, .fun domain codomain =>
    .fun (domain.symm operations)
      (codomain.symm (Path.ScopedLift.eqCongruence operations))
| operations, .pair first member =>
    .pair (first.symm operations)
      (member.symm (Path.ScopedLift.eqCongruence operations))
| operations, .single path => .single (operations.symm path)
| operations, .selection path => .selection (operations.symm path)

noncomputable def Tau.RuntimeCongruent.symm :
    (operations : Path.EqCongruence R) ->
    Tau.RuntimeCongruent R d1 d2 -> Tau.RuntimeCongruent R d2 d1
| operations, .proper types => .proper (types.symm operations)
| operations, .interval lower upper =>
    .interval (lower.symm operations) (upper.symm operations)

end


mutual

noncomputable def Ty.RuntimeCongruent.trans :
    (operations : Path.EqCongruence R) ->
    Ty.RuntimeCongruent R S T ->
    Ty.RuntimeCongruent R T U ->
    Ty.RuntimeCongruent R S U
| _, .top, .top => .top
| _, .bot, .bot => .bot
| operations, .fun domain1 codomain1, .fun domain2 codomain2 =>
    .fun (domain1.trans operations domain2)
      (codomain1.trans (Path.ScopedLift.eqCongruence operations) codomain2)
| operations, .pair first1 member1, .pair first2 member2 =>
    .pair (first1.trans operations first2)
      (member1.trans (Path.ScopedLift.eqCongruence operations) member2)
| operations, .single first, .single second =>
    .single (operations.trans first second)
| operations, .selection first, .selection second =>
    .selection (operations.trans first second)

noncomputable def Tau.RuntimeCongruent.trans :
    (operations : Path.EqCongruence R) ->
    Tau.RuntimeCongruent R d1 d2 ->
    Tau.RuntimeCongruent R d2 d3 ->
    Tau.RuntimeCongruent R d1 d3
| operations, .proper first, .proper second =>
    .proper (first.trans operations second)
| operations, .interval lower1 upper1, .interval lower2 upper2 =>
    .interval (lower1.trans operations lower2)
      (upper1.trans operations upper2)

end

mutual

/-- Pointwise related substitutions induce structural conversion of a type. -/
noncomputable def Ty.RuntimeCongruent.ofSubst
    {l n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R)
    (rho1 rho2 : PathSubst l n)
    (related : forall x, R (rho1 x) (rho2 x)) :
    (T : Ty l) ->
      Ty.RuntimeCongruent R (T.subst rho1) (T.subst rho2)
| .Top => .top
| .Bot => .bot
| .Fun S T =>
    .fun (Ty.RuntimeCongruent.ofSubst operations rho1 rho2 related S)
      (Ty.RuntimeCongruent.ofSubst
        (Path.ScopedLift.eqCongruence operations) rho1.lift rho2.lift
        (Path.ScopedLift.pointwise related) T)
| .Pair S a d =>
    .pair (Ty.RuntimeCongruent.ofSubst operations rho1 rho2 related S)
      (Tau.RuntimeCongruent.ofSubst
        (Path.ScopedLift.eqCongruence operations) rho1.lift rho2.lift
        (Path.ScopedLift.pointwise related) d)
| .Single p => .single (relatedPath p)
| .TSel p A => .selection (relatedPath p)
where
  relatedPath (p : Path l) : R (p.subst rho1) (p.subst rho2) := by
    induction p with
    | var x => exact related x
    | fst p ih => exact operations.fst ih
    | sel p a ih => exact operations.sel ih a

noncomputable def Tau.RuntimeCongruent.ofSubst
    {l n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R)
    (rho1 rho2 : PathSubst l n)
    (related : forall x, R (rho1 x) (rho2 x)) :
    (d : Tau l k) ->
      Tau.RuntimeCongruent R (d.subst rho1) (d.subst rho2)
| .ty T =>
    .proper (Ty.RuntimeCongruent.ofSubst operations rho1 rho2 related T)
| .intv L U =>
    .interval (Ty.RuntimeCongruent.ofSubst operations rho1 rho2 related L)
      (Ty.RuntimeCongruent.ofSubst operations rho1 rho2 related U)

end

mutual

/-- Re-encode structural proper-type conversion as ordinary conversion code. -/
noncomputable def Ty.RuntimeCongruent.toRuntimeConv :
    Ty.RuntimeCongruent R S T -> Tau.RuntimeConv R (.ty S) (.ty T)
| .top => .refl
| .bot => .refl
| .fun domain codomain =>
    .fun domain.toRuntimeConv codomain.toRuntimeConv
| .pair first member =>
    .pair first.toRuntimeConv member.toRuntimeConv
| .single path => .single path
| .selection path => .selection path

/-- Re-encode structural generalized-type conversion. -/
noncomputable def Tau.RuntimeCongruent.toRuntimeConv :
    Tau.RuntimeCongruent R d1 d2 -> Tau.RuntimeConv R d1 d2
| .proper types => types.toRuntimeConv
| .interval lower upper =>
    .interval lower.toRuntimeConv upper.toRuntimeConv

end


/-- Invert the proper-type wrapper of structural conversion. -/
def Tau.RuntimeCongruent.properTypes
    (conversion : Tau.RuntimeCongruent R (.ty S) (.ty T)) :
    Ty.RuntimeCongruent R S T :=
  match conversion with
  | .proper types => types

/-- Normalize arbitrary conversion evidence, including transitivity and
one-hole replacement, to its structural component form. -/
noncomputable def Tau.RuntimeConv.runtimeCongruent
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R)
    {k : Kind} {d1 d2 : Tau n k}
    (conversion : Tau.RuntimeConv R d1 d2) :
    Tau.RuntimeCongruent R d1 d2 :=
  match conversion with
  | .refl => Tau.RuntimeCongruent.refl operations _
  | .symm code => (code.runtimeCongruent operations).symm operations
  | .trans first second =>
      (first.runtimeCongruent operations).trans operations
        (second.runtimeCongruent operations)
  | .replace (p := p) (q := q) context evidence =>
      Tau.RuntimeCongruent.ofSubst operations
        (PathSubst.openAt p) (PathSubst.openAt q)
        (fun x => Fin.cases evidence
          (fun i => operations.refl (.var i)) x)
        context
  | .fun domain codomain =>
      .proper (.fun
        (domain.runtimeCongruent operations).properTypes
        (codomain.runtimeCongruent
          (Path.ScopedLift.eqCongruence operations)).properTypes)
  | .pair first member =>
      .proper (.pair
        (first.runtimeCongruent operations).properTypes
        (member.runtimeCongruent
          (Path.ScopedLift.eqCongruence operations)))
  | .single path => .proper (.single path)
  | .selection path => .proper (.selection path)
  | .interval lower upper =>
      .interval
        (lower.runtimeCongruent operations).properTypes
        (upper.runtimeCongruent operations).properTypes

end LambdaPFC
