import LambdaPFC.Runtime
import LambdaPFC.StaticMetatheory

/-!
Proof-relevant runtime equality and type conversion.

Runtime equality is generated by paths resolving to the same generalized
endpoint, then closed under equivalence and path contexts.  Its scoped lift
extends the relation below a source binder without giving the fresh variable
any equations beyond reflexivity.  Generalized-type conversion records
replacement of runtime-equal paths in an arbitrary type context.
-/

namespace LambdaPFC

/-! ## Proof-relevant co-resolution -/

/-- Data witnessing that two paths resolve to the same endpoint. -/
structure Path.CoResolve (sigma : Store n) (p q : Path n) : Type where
  endpoint : Path.Endpoint n
  left : Path.Resolve p sigma endpoint
  right : Path.Resolve q sigma endpoint

/-- The proposition obtained by forgetting the endpoint witness. -/
abbrev Path.CoResolved (sigma : Store n) (p q : Path n) : Prop :=
  Exists fun endpoint =>
    Path.Resolve p sigma endpoint /\ Path.Resolve q sigma endpoint

/-- Forget the proof-relevant co-resolution witness. -/
theorem Path.CoResolve.erase
    (evidence : Path.CoResolve sigma p q) :
    Path.CoResolved sigma p q :=
  Exists.intro evidence.endpoint (And.intro evidence.left evidence.right)

/-- Every propositionally witnessed co-resolution has proof-relevant data. -/
theorem Path.CoResolve.nonempty_of_erased
    (evidence : Path.CoResolved sigma p q) :
    Nonempty (Path.CoResolve sigma p q) := by
  obtain ⟨endpoint, left, right⟩ := evidence
  exact ⟨Path.CoResolve.mk endpoint left right⟩

def Path.CoResolve.symm
    (evidence : Path.CoResolve sigma p q) :
    Path.CoResolve sigma q p :=
  Path.CoResolve.mk evidence.endpoint evidence.right evidence.left

noncomputable def Path.CoResolve.trans
    (first : Path.CoResolve sigma p q)
    (second : Path.CoResolve sigma q r) :
    Path.CoResolve sigma p r := by
  rcases first with ⟨firstEndpoint, firstLeft, firstRight⟩
  rcases second with ⟨secondEndpoint, secondLeft, secondRight⟩
  have endpoints := firstRight.deterministic secondLeft
  subst secondEndpoint
  exact Path.CoResolve.mk firstEndpoint firstLeft secondRight

/-- Reduction to a common term location is proof-relevant co-resolution. -/
def Path.CoResolve.ofReduce
    (left : Path.reduce p sigma x)
    (right : Path.reduce q sigma x) :
    Path.CoResolve sigma p q :=
  Path.CoResolve.mk (.val x) left.toResolve right.toResolve

/-- Co-resolution survives allocation of a fresh store cell. -/
def Path.CoResolve.weaken
    {n : Nat} {sigma : Store n} {p q : Path n}
    (evidence : Path.CoResolve sigma p q)
    (v : Tm n) (vv : v.IsValue) :
    Path.CoResolve (Store.val sigma v vv) p.weaken q.weaken :=
  Path.CoResolve.mk evidence.endpoint.weaken
    (evidence.left.weaken v vv) (evidence.right.weaken v vv)

/-! ## Substitution and generalized resolution -/

/-- Pointwise agreement of generalized resolution is stable under path
substitution. -/
theorem Path.Resolve.subst_congr
    {l n : Nat} {sigma : Store n} {r : Path l}
    {rho1 rho2 : PathSubst l n} {endpoint : Path.Endpoint n}
    (agree : forall x endpoint,
      Path.Resolve (rho1 x) sigma endpoint <->
        Path.Resolve (rho2 x) sigma endpoint)
    (resolution : Path.Resolve (r.subst rho1) sigma endpoint) :
    Path.Resolve (r.subst rho2) sigma endpoint := by
  induction r generalizing endpoint with
  | var x => exact (agree x endpoint).mp resolution
  | fst r ih =>
      simp only [Path.subst] at resolution |-
      cases resolution with
      | fst pathResolution binding =>
          exact .fst (ih pathResolution) binding
  | sel r a ih =>
      simp only [Path.subst] at resolution |-
      cases resolution with
      | sel_val pathResolution binding =>
          exact .sel_val (ih pathResolution) binding
      | sel_type pathResolution binding =>
          exact .sel_type (ih pathResolution) binding
      | sel_miss pathResolution binding distinct tail =>
          exact .sel_miss (ih pathResolution) binding distinct tail

theorem Path.Resolve.subst_iff
    {l n : Nat} {sigma : Store n} {r : Path l}
    {rho1 rho2 : PathSubst l n} {endpoint : Path.Endpoint n}
    (agree : forall x endpoint,
      Path.Resolve (rho1 x) sigma endpoint <->
        Path.Resolve (rho2 x) sigma endpoint) :
    Path.Resolve (r.subst rho1) sigma endpoint <->
      Path.Resolve (r.subst rho2) sigma endpoint :=
  Iff.intro (Path.Resolve.subst_congr agree)
    (Path.Resolve.subst_congr fun x e => (agree x e).symm)

/-- Replacing the hole of a path context by paths with the same resolution
graph preserves the result of the context. -/
theorem Path.Resolve.open_iff
    {n : Nat} {sigma : Store n} {p q : Path n}
    {endpoint : Path.Endpoint n}
    (agree : forall endpoint,
      Path.Resolve p sigma endpoint <-> Path.Resolve q sigma endpoint)
    (context : Path (n + 1)) :
    Path.Resolve (context.open p) sigma endpoint <->
      Path.Resolve (context.open q) sigma endpoint := by
  apply Path.Resolve.subst_iff
  intro x e
  refine Fin.cases ?_ (fun _ => ?_) x
  · exact agree e
  · exact Iff.rfl

/-! ## Runtime path equality -/

/-- Finite evidence for store-indexed runtime path equality. -/
inductive Path.RuntimeEq (sigma : Store n) : Path n -> Path n -> Type where
| refl : Path.RuntimeEq sigma p p
| symm : Path.RuntimeEq sigma p q -> Path.RuntimeEq sigma q p
| trans :
    Path.RuntimeEq sigma p q ->
    Path.RuntimeEq sigma q r ->
    Path.RuntimeEq sigma p r
| coresolve : Path.CoResolve sigma p q -> Path.RuntimeEq sigma p q
| congr :
    Path.RuntimeEq sigma p q ->
    (context : Path (n + 1)) ->
    Path.RuntimeEq sigma (context.open p) (context.open q)

/-- Propositional runtime equality obtained by truncating its evidence. -/
abbrev Path.RuntimeEquivalent
    (sigma : Store n) (p q : Path n) : Prop :=
  Nonempty (Path.RuntimeEq sigma p q)

theorem Path.RuntimeEq.erase
    (evidence : Path.RuntimeEq sigma p q) :
    Path.RuntimeEquivalent sigma p q :=
  ⟨evidence⟩

def Path.RuntimeEq.ofResolve
    (left : Path.Resolve p sigma endpoint)
    (right : Path.Resolve q sigma endpoint) :
    Path.RuntimeEq sigma p q :=
  .coresolve (Path.CoResolve.mk endpoint left right)

def Path.RuntimeEq.ofReduce
    (reduction : Path.reduce p sigma x) :
    Path.RuntimeEq sigma p (.var x) :=
  .coresolve (Path.CoResolve.ofReduce reduction .var)

def Path.RuntimeEq.fst
    (evidence : Path.RuntimeEq sigma p q) :
    Path.RuntimeEq sigma p.fst q.fst := by
  simpa [Path.open, Path.subst] using
    Path.RuntimeEq.congr evidence (Path.fst (Path.var 0))

def Path.RuntimeEq.sel
    (evidence : Path.RuntimeEq sigma p q) (a : Name) :
    Path.RuntimeEq sigma (p.sel a) (q.sel a) := by
  simpa [Path.open, Path.subst] using
    Path.RuntimeEq.congr evidence (Path.sel (Path.var 0) a)

/-- Runtime equality preserves the complete generalized-resolution graph. -/
theorem Path.RuntimeEq.resolve_iff
    {n : Nat} {sigma : Store n} {p q : Path n}
    (evidence : Path.RuntimeEq sigma p q) (endpoint : Path.Endpoint n) :
    Path.Resolve p sigma endpoint <-> Path.Resolve q sigma endpoint := by
  induction evidence generalizing endpoint with
  | refl => exact Iff.rfl
  | symm _ ih => exact (ih endpoint).symm
  | trans _ _ ih1 ih2 => exact (ih1 endpoint).trans (ih2 endpoint)
  | coresolve evidence =>
      constructor
      · intro left
        have endpoints := evidence.left.deterministic left
        cases endpoints
        exact evidence.right
      · intro right
        have endpoints := evidence.right.deterministic right
        cases endpoints
        exact evidence.left
  | congr _ context ih =>
      exact Path.Resolve.open_iff (fun e => ih e) context

theorem Path.RuntimeEquivalent.resolve_iff
    {n : Nat} {sigma : Store n} {p q : Path n}
    (evidence : Path.RuntimeEquivalent sigma p q)
    (endpoint : Path.Endpoint n) :
    Path.Resolve p sigma endpoint <-> Path.Resolve q sigma endpoint := by
  obtain ⟨code⟩ := evidence
  exact code.resolve_iff endpoint

noncomputable def Path.RuntimeEq.weaken
    {n : Nat} {sigma : Store n} {p q : Path n}
    (evidence : Path.RuntimeEq sigma p q)
    (v : Tm n) (vv : v.IsValue) :
    Path.RuntimeEq (Store.val sigma v vv) p.weaken q.weaken := by
  induction evidence with
  | refl => exact .refl
  | symm _ ih => exact .symm ih
  | trans _ _ ih1 ih2 => exact .trans ih1 ih2
  | coresolve endpoints => exact .coresolve (endpoints.weaken v vv)
  | congr _ context ih =>
      simpa [Path.weaken, Path.open_rename] using
        Path.RuntimeEq.congr ih (context.rename FinFun.weaken.ext)

theorem Path.RuntimeEquivalent.refl :
    Path.RuntimeEquivalent sigma p p :=
  ⟨.refl⟩

theorem Path.RuntimeEquivalent.symm
    (evidence : Path.RuntimeEquivalent sigma p q) :
    Path.RuntimeEquivalent sigma q p := by
  obtain ⟨code⟩ := evidence
  exact ⟨.symm code⟩

theorem Path.RuntimeEquivalent.trans
    (first : Path.RuntimeEquivalent sigma p q)
    (second : Path.RuntimeEquivalent sigma q r) :
    Path.RuntimeEquivalent sigma p r := by
  obtain ⟨firstCode⟩ := first
  obtain ⟨secondCode⟩ := second
  exact ⟨.trans firstCode secondCode⟩

/-! ## Generic equivalence and binder lifting -/

/-- Operations required of proof-relevant path equality. -/
structure Path.EqCongruence
    (R : Path n -> Path n -> Type) : Type where
  refl : forall p, R p p
  symm : forall {p q}, R p q -> R q p
  trans : forall {p q r}, R p q -> R q r -> R p r
  fst : forall {p q}, R p q -> R p.fst q.fst
  sel : forall {p q}, R p q -> forall a, R (p.sel a) (q.sel a)

def Path.RuntimeEq.eqCongruence (sigma : Store n) :
    Path.EqCongruence (Path.RuntimeEq sigma) where
  refl _ := .refl
  symm evidence := .symm evidence
  trans first second := .trans first second
  fst evidence := evidence.fst
  sel evidence a := evidence.sel a

/-- Least path congruence below a binder.  Ambient equations are weakened;
the fresh variable has only its reflexive seed. -/
inductive Path.ScopedLift
    (R : Path n -> Path n -> Type) :
    Path (n + 1) -> Path (n + 1) -> Type where
| bound : Path.ScopedLift R (.var 0) (.var 0)
| old : R p q -> Path.ScopedLift R p.weaken q.weaken
| symm : Path.ScopedLift R p q -> Path.ScopedLift R q p
| trans :
    Path.ScopedLift R p q ->
    Path.ScopedLift R q r ->
    Path.ScopedLift R p r
| fst : Path.ScopedLift R p q -> Path.ScopedLift R p.fst q.fst
| sel : Path.ScopedLift R p q -> Path.ScopedLift R (p.sel a) (q.sel a)

noncomputable def Path.ScopedLift.refl
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R) (p : Path (n + 1)) :
    Path.ScopedLift R p p := by
  induction p with
  | var x =>
      refine Fin.cases ?_ (fun y => ?_) x
      · exact .bound
      · simpa [Path.weaken, Path.rename] using
          Path.ScopedLift.old (operations.refl (Path.var y))
  | fst p ih => exact .fst ih
  | sel p a ih => exact .sel ih

noncomputable def Path.ScopedLift.eqCongruence
    (operations : Path.EqCongruence R) :
    Path.EqCongruence (Path.ScopedLift R) where
  refl := Path.ScopedLift.refl operations
  symm evidence := .symm evidence
  trans first second := .trans first second
  fst evidence := .fst evidence
  sel evidence _ := .sel evidence

/-- A relation morphism for simultaneous path substitution. -/
abbrev Path.SubstHom
    (R : Path n -> Path n -> Type)
    (E : Path m -> Path m -> Type)
    (rho : PathSubst n m) : Type :=
  forall {p q}, R p q -> E (p.subst rho) (q.subst rho)

/-- Substitution beneath a binder maps the scoped lift of a relation to the
scoped lift of its image. -/
noncomputable def Path.ScopedLift.subst
    {R : Path n -> Path n -> Type}
    {E : Path m -> Path m -> Type}
    {rho : PathSubst n m}
    (mapOld : Path.SubstHom R E rho)
    (evidence : Path.ScopedLift R p q) :
    Path.ScopedLift E (p.subst rho.lift) (q.subst rho.lift) := by
  induction evidence with
  | bound => exact .bound
  | old evidence =>
      simpa only [Path.weaken_subst_lift] using
        Path.ScopedLift.old (mapOld evidence)
  | symm _ ih => exact .symm ih
  | trans _ _ ih1 ih2 => exact .trans ih1 ih2
  | fst _ ih => exact .fst ih
  | sel _ ih => exact .sel ih

/-- Instantiating scoped equality with related paths yields ambient runtime
equality. -/
noncomputable def Path.ScopedLift.open
    {n : Nat} {R : Path n -> Path n -> Type}
    {p q : Path (n + 1)} {r s : Path n}
    (operations : Path.EqCongruence R)
    (evidence : Path.ScopedLift R p q)
    (arguments : R r s) :
    R (p.open r) (q.open s) := by
  induction evidence generalizing r s with
  | bound => exact arguments
  | old evidence =>
      simpa only [Path.weaken_open] using evidence
  | symm _ ih => exact operations.symm (ih (operations.symm arguments))
  | trans _ _ ih1 ih2 =>
      exact operations.trans (ih1 arguments) (ih2 (operations.refl s))
  | fst _ ih => exact operations.fst (ih arguments)
  | sel _ ih => exact operations.sel (ih arguments) _

/-! ## Proof-relevant generalized-type conversion -/

/-- Finite conversion evidence generated by replacement of related paths. -/
inductive Tau.RuntimeConv :
    {n : Nat} -> (Path n -> Path n -> Type) ->
    {k : Kind} -> Tau n k -> Tau n k -> Type 1 where
| refl : Tau.RuntimeConv R d d
| symm : Tau.RuntimeConv R d1 d2 -> Tau.RuntimeConv R d2 d1
| trans :
    Tau.RuntimeConv R d1 d2 ->
    Tau.RuntimeConv R d2 d3 ->
    Tau.RuntimeConv R d1 d3
| replace :
    (context : Tau (n + 1) k) ->
    R p q ->
    Tau.RuntimeConv R (context.open p) (context.open q)
| fun :
    Tau.RuntimeConv R (.ty S) (.ty S') ->
    Tau.RuntimeConv (Path.ScopedLift R) (.ty T) (.ty T') ->
    Tau.RuntimeConv R (.ty (.Fun S T)) (.ty (.Fun S' T'))
| pair :
    Tau.RuntimeConv R (.ty S) (.ty S') ->
    Tau.RuntimeConv (Path.ScopedLift R) d d' ->
    Tau.RuntimeConv R
      (.ty (.Pair S a d)) (.ty (.Pair S' a d'))
| single :
    R p q ->
    Tau.RuntimeConv R (.ty (.Single p)) (.ty (.Single q))
| selection :
    R p q ->
    Tau.RuntimeConv R (.ty (.TSel p A)) (.ty (.TSel q A))
| interval :
    Tau.RuntimeConv R (.ty L) (.ty L') ->
    Tau.RuntimeConv R (.ty U) (.ty U') ->
    Tau.RuntimeConv R (.intv L U) (.intv L' U')

/-- Propositional conversion obtained by truncating finite evidence. -/
abbrev Tau.RuntimeConvertible
    (R : Path n -> Path n -> Type) (d1 d2 : Tau n k) : Prop :=
  Nonempty (Tau.RuntimeConv R d1 d2)

theorem Tau.RuntimeConv.erase
    (conversion : Tau.RuntimeConv R d1 d2) :
    Tau.RuntimeConvertible R d1 d2 :=
  ⟨conversion⟩

theorem Tau.RuntimeConvertible.refl :
    Tau.RuntimeConvertible R d d :=
  ⟨.refl⟩

theorem Tau.RuntimeConvertible.symm
    (conversion : Tau.RuntimeConvertible R d1 d2) :
    Tau.RuntimeConvertible R d2 d1 := by
  obtain ⟨code⟩ := conversion
  exact ⟨.symm code⟩

theorem Tau.RuntimeConvertible.trans
    (first : Tau.RuntimeConvertible R d1 d2)
    (second : Tau.RuntimeConvertible R d2 d3) :
    Tau.RuntimeConvertible R d1 d3 := by
  obtain ⟨firstCode⟩ := first
  obtain ⟨secondCode⟩ := second
  exact ⟨.trans firstCode secondCode⟩

/-- Conversion is natural with respect to simultaneous substitution and a
map of the underlying path relation. -/
noncomputable def Tau.RuntimeConv.subst
    {n m : Nat}
    {R : Path n -> Path n -> Type}
    {E : Path m -> Path m -> Type}
    {rho : PathSubst n m} {k : Kind} {d1 d2 : Tau n k}
    (mapPaths : Path.SubstHom R E rho)
    (conversion : Tau.RuntimeConv R d1 d2) :
    Tau.RuntimeConv E (d1.subst rho) (d2.subst rho) :=
  match conversion with
  | .refl => .refl
  | .symm code => .symm (code.subst mapPaths)
  | .trans first second =>
      .trans (first.subst mapPaths) (second.subst mapPaths)
  | .replace context evidence => by
      simpa only [Tau.open_subst] using
        Tau.RuntimeConv.replace (context.subst rho.lift)
          (mapPaths evidence)
  | .fun domain codomain =>
      .fun (domain.subst mapPaths)
        (codomain.subst (rho := rho.lift)
          fun evidence => evidence.subst mapPaths)
  | .pair first member =>
      .pair (first.subst mapPaths)
        (member.subst (rho := rho.lift)
          fun evidence => evidence.subst mapPaths)
  | .single evidence => .single (mapPaths evidence)
  | .selection evidence => .selection (mapPaths evidence)
  | .interval lower upper =>
      .interval (lower.subst mapPaths) (upper.subst mapPaths)

/-- Renaming is the variable-only instance of conversion substitution. -/
noncomputable def Tau.RuntimeConv.rename
    {R : Path n -> Path n -> Type}
    {E : Path m -> Path m -> Type}
    (f : FinFun n m)
    (mapPaths : forall {p q}, R p q -> E (p.rename f) (q.rename f))
    (conversion : Tau.RuntimeConv R d1 d2) :
    Tau.RuntimeConv E (d1.rename f) (d2.rename f) := by
  simpa only [Tau.subst_asSubst] using
    conversion.subst (rho := f.asSubst) (fun evidence => by
      simpa only [Path.subst_asSubst] using mapPaths evidence)

/-- Ambient conversion can be placed below a fresh binder. -/
noncomputable def Tau.RuntimeConv.lift
    (conversion : Tau.RuntimeConv R d1 d2) :
    Tau.RuntimeConv (Path.ScopedLift R) d1.weaken d2.weaken := by
  simpa only [Tau.weaken] using
    conversion.rename FinFun.weaken (fun evidence =>
      Path.ScopedLift.old evidence)

/-- Opening a scoped conversion at one path. -/
noncomputable def Tau.RuntimeConv.openSame
    {n : Nat} {R : Path n -> Path n -> Type}
    {d1 d2 : Tau (n + 1) k}
    (operations : Path.EqCongruence R)
    (conversion : Tau.RuntimeConv (Path.ScopedLift R) d1 d2)
    (argument : Path n) :
    Tau.RuntimeConv R (d1.open argument) (d2.open argument) := by
  exact conversion.subst (rho := PathSubst.openAt argument)
    (fun evidence => evidence.open operations (operations.refl argument))

/-- Opening a scoped conversion at related source and target paths. -/
noncomputable def Tau.RuntimeConv.open
    {n : Nat} {R : Path n -> Path n -> Type}
    {d1 d2 : Tau (n + 1) k} {p q : Path n}
    (operations : Path.EqCongruence R)
    (conversion : Tau.RuntimeConv (Path.ScopedLift R) d1 d2)
    (arguments : R p q) :
    Tau.RuntimeConv R (d1.open p) (d2.open q) :=
  .trans (.replace d1 arguments) (conversion.openSame operations q)

/-- Runtime conversion survives allocation. -/
noncomputable def Tau.RuntimeConv.weaken
    {n : Nat} {sigma : Store n} {d1 d2 : Tau n k}
    (conversion : Tau.RuntimeConv (Path.RuntimeEq sigma) d1 d2)
    (v : Tm n) (vv : v.IsValue) :
    Tau.RuntimeConv (Path.RuntimeEq (Store.val sigma v vv))
      d1.weaken d2.weaken := by
  simpa only [Tau.weaken] using
    conversion.rename FinFun.weaken (fun evidence => evidence.weaken v vv)

/-! ## Conversion shape -/

/-- The outer constructor of a proper type.  Pair heads retain the label and
the kind of their member. -/
inductive Ty.Head : Type where
| top
| bot
| fun
| pair (label : Name) (memberKind : Kind)
| single
| selection
deriving DecidableEq

def Ty.head : Ty n -> Ty.Head
| .Top => .top
| .Bot => .bot
| .Fun _ _ => .fun
| .Pair (k := k) _ label _ => .pair label k
| .Single _ => .single
| .TSel _ _ => .selection

inductive Tau.Head : Kind -> Type where
| type : Ty.Head -> Tau.Head .star
| interval : Tau.Head .iota
deriving DecidableEq

def Tau.head : Tau n k -> Tau.Head k
| .ty T => .type T.head
| .intv _ _ => .interval

@[simp] theorem Ty.head_subst (T : Ty n) (rho : PathSubst n m) :
    (T.subst rho).head = T.head := by
  cases T <;> rfl

@[simp] theorem Tau.head_subst (d : Tau n k) (rho : PathSubst n m) :
    (d.subst rho).head = d.head := by
  cases d with
  | ty T => simp only [Tau.subst, Tau.head, Ty.head_subst]
  | intv => rfl

/-- Runtime conversion cannot change the outer generalized-type shape. -/
theorem Tau.RuntimeConv.head_eq
    (conversion : Tau.RuntimeConv R d1 d2) : d1.head = d2.head := by
  induction conversion with
  | refl => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih1 ih2 => exact ih1.trans ih2
  | replace context evidence =>
      simp only [Tau.open, Tau.head_subst]
  | «fun» => rfl
  | pair => rfl
  | single => rfl
  | selection => rfl
  | interval => rfl

/-- Runtime endpoints are sorted by the kind of the generalized type they
can realize. -/
inductive Path.Endpoint.HasKind : Path.Endpoint n -> Kind -> Type where
| val : Path.Endpoint.HasKind (.val x) .star
| type : Path.Endpoint.HasKind (.type T) .iota

def Tau.EndpointShape :
    (d : Tau n k) -> Path.Endpoint n -> Type
| .ty _, endpoint => Path.Endpoint.HasKind endpoint .star
| .intv _ _, endpoint => Path.Endpoint.HasKind endpoint .iota

/-- Conversion preserves whether its endpoint is a value location or a type
definition. -/
def Tau.RuntimeConv.endpointShape
    (_conversion : Tau.RuntimeConv R d1 d2) :
    Tau.EndpointShape d1 endpoint -> Tau.EndpointShape d2 endpoint :=
  by
    cases d1 <;> cases d2
    · exact fun shape => shape
    · exact fun shape => shape

/-! ## Structural view and component inversion -/

mutual

/-- Structural normal form for runtime conversion of proper types. -/
inductive Ty.RuntimeCongruent :
    {n : Nat} -> (Path n -> Path n -> Type) ->
      Ty n -> Ty n -> Type 1 where
| top : Ty.RuntimeCongruent R .Top .Top
| bot : Ty.RuntimeCongruent R .Bot .Bot
| fun :
    Ty.RuntimeCongruent R S S' ->
    Ty.RuntimeCongruent (Path.ScopedLift R) T T' ->
    Ty.RuntimeCongruent R (.Fun S T) (.Fun S' T')
| pair :
    Ty.RuntimeCongruent R S S' ->
    Tau.RuntimeCongruent (Path.ScopedLift R) d d' ->
    Ty.RuntimeCongruent R (.Pair S a d) (.Pair S' a d')
| single : R p q -> Ty.RuntimeCongruent R (.Single p) (.Single q)
| selection : R p q -> Ty.RuntimeCongruent R (.TSel p A) (.TSel q A)

/-- Structural normal form for runtime conversion of generalized types. -/
inductive Tau.RuntimeCongruent :
    {n : Nat} -> (Path n -> Path n -> Type) ->
      {k : Kind} -> Tau n k -> Tau n k -> Type 1 where
| proper : Ty.RuntimeCongruent R S T ->
    Tau.RuntimeCongruent R (.ty S) (.ty T)
| interval :
    Ty.RuntimeCongruent R L L' ->
    Ty.RuntimeCongruent R U U' ->
    Tau.RuntimeCongruent R (.intv L U) (.intv L' U')

end

/-- Pointwise related substitutions remain related after lifting through one
binder. -/
def Path.ScopedLift.pointwise
    {R : Path n -> Path n -> Type}
    {rho1 rho2 : PathSubst l n}
    (related : forall x, R (rho1 x) (rho2 x)) :
    forall x, Path.ScopedLift R (rho1.lift x) (rho2.lift x) := by
  intro x
  refine Fin.cases ?_ (fun i => ?_) x
  · exact .bound
  · exact .old (related i)

mutual

noncomputable def Ty.RuntimeCongruent.refl
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R) :
    (T : Ty n) -> Ty.RuntimeCongruent R T T
| .Top => .top
| .Bot => .bot
| .Fun S T =>
    .fun (Ty.RuntimeCongruent.refl operations S)
      (Ty.RuntimeCongruent.refl
        (Path.ScopedLift.eqCongruence operations) T)
| .Pair S _ d =>
    .pair (Ty.RuntimeCongruent.refl operations S)
      (Tau.RuntimeCongruent.refl
        (Path.ScopedLift.eqCongruence operations) d)
| .Single p => .single (operations.refl p)
| .TSel p _ => .selection (operations.refl p)

noncomputable def Tau.RuntimeCongruent.refl
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R) :
    (d : Tau n k) -> Tau.RuntimeCongruent R d d
| .ty T => .proper (Ty.RuntimeCongruent.refl operations T)
| .intv L U =>
    .interval (Ty.RuntimeCongruent.refl operations L)
      (Ty.RuntimeCongruent.refl operations U)

end

mutual

noncomputable def Ty.RuntimeCongruent.symm :
    (operations : Path.EqCongruence R) ->
    Ty.RuntimeCongruent R S T -> Ty.RuntimeCongruent R T S
| _, .top => .top
| _, .bot => .bot
| operations, .fun domain codomain =>
    .fun (domain.symm operations)
      (codomain.symm (Path.ScopedLift.eqCongruence operations))
| operations, .pair first member =>
    .pair (first.symm operations)
      (member.symm (Path.ScopedLift.eqCongruence operations))
| operations, .single path => .single (operations.symm path)
| operations, .selection path => .selection (operations.symm path)

noncomputable def Tau.RuntimeCongruent.symm :
    (operations : Path.EqCongruence R) ->
    Tau.RuntimeCongruent R d1 d2 -> Tau.RuntimeCongruent R d2 d1
| operations, .proper types => .proper (types.symm operations)
| operations, .interval lower upper =>
    .interval (lower.symm operations) (upper.symm operations)

end


mutual

noncomputable def Ty.RuntimeCongruent.trans :
    (operations : Path.EqCongruence R) ->
    Ty.RuntimeCongruent R S T ->
    Ty.RuntimeCongruent R T U ->
    Ty.RuntimeCongruent R S U
| _, .top, .top => .top
| _, .bot, .bot => .bot
| operations, .fun domain1 codomain1, .fun domain2 codomain2 =>
    .fun (domain1.trans operations domain2)
      (codomain1.trans (Path.ScopedLift.eqCongruence operations) codomain2)
| operations, .pair first1 member1, .pair first2 member2 =>
    .pair (first1.trans operations first2)
      (member1.trans (Path.ScopedLift.eqCongruence operations) member2)
| operations, .single first, .single second =>
    .single (operations.trans first second)
| operations, .selection first, .selection second =>
    .selection (operations.trans first second)

noncomputable def Tau.RuntimeCongruent.trans :
    (operations : Path.EqCongruence R) ->
    Tau.RuntimeCongruent R d1 d2 ->
    Tau.RuntimeCongruent R d2 d3 ->
    Tau.RuntimeCongruent R d1 d3
| operations, .proper first, .proper second =>
    .proper (first.trans operations second)
| operations, .interval lower1 upper1, .interval lower2 upper2 =>
    .interval (lower1.trans operations lower2)
      (upper1.trans operations upper2)

end

mutual

/-- Pointwise related substitutions induce structural conversion of a type. -/
noncomputable def Ty.RuntimeCongruent.ofSubst
    {l n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R)
    (rho1 rho2 : PathSubst l n)
    (related : forall x, R (rho1 x) (rho2 x)) :
    (T : Ty l) ->
      Ty.RuntimeCongruent R (T.subst rho1) (T.subst rho2)
| .Top => .top
| .Bot => .bot
| .Fun S T =>
    .fun (Ty.RuntimeCongruent.ofSubst operations rho1 rho2 related S)
      (Ty.RuntimeCongruent.ofSubst
        (Path.ScopedLift.eqCongruence operations) rho1.lift rho2.lift
        (Path.ScopedLift.pointwise related) T)
| .Pair S a d =>
    .pair (Ty.RuntimeCongruent.ofSubst operations rho1 rho2 related S)
      (Tau.RuntimeCongruent.ofSubst
        (Path.ScopedLift.eqCongruence operations) rho1.lift rho2.lift
        (Path.ScopedLift.pointwise related) d)
| .Single p => .single (relatedPath p)
| .TSel p A => .selection (relatedPath p)
where
  relatedPath (p : Path l) : R (p.subst rho1) (p.subst rho2) := by
    induction p with
    | var x => exact related x
    | fst p ih => exact operations.fst ih
    | sel p a ih => exact operations.sel ih a

noncomputable def Tau.RuntimeCongruent.ofSubst
    {l n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R)
    (rho1 rho2 : PathSubst l n)
    (related : forall x, R (rho1 x) (rho2 x)) :
    (d : Tau l k) ->
      Tau.RuntimeCongruent R (d.subst rho1) (d.subst rho2)
| .ty T =>
    .proper (Ty.RuntimeCongruent.ofSubst operations rho1 rho2 related T)
| .intv L U =>
    .interval (Ty.RuntimeCongruent.ofSubst operations rho1 rho2 related L)
      (Ty.RuntimeCongruent.ofSubst operations rho1 rho2 related U)

end

mutual

/-- Re-encode structural proper-type conversion as ordinary conversion code. -/
noncomputable def Ty.RuntimeCongruent.toRuntimeConv :
    Ty.RuntimeCongruent R S T -> Tau.RuntimeConv R (.ty S) (.ty T)
| .top => .refl
| .bot => .refl
| .fun domain codomain =>
    .fun domain.toRuntimeConv codomain.toRuntimeConv
| .pair first member =>
    .pair first.toRuntimeConv member.toRuntimeConv
| .single path => .single path
| .selection path => .selection path

/-- Re-encode structural generalized-type conversion. -/
noncomputable def Tau.RuntimeCongruent.toRuntimeConv :
    Tau.RuntimeCongruent R d1 d2 -> Tau.RuntimeConv R d1 d2
| .proper types => types.toRuntimeConv
| .interval lower upper =>
    .interval lower.toRuntimeConv upper.toRuntimeConv

end


/-- Invert the proper-type wrapper of structural conversion. -/
def Tau.RuntimeCongruent.properTypes
    (conversion : Tau.RuntimeCongruent R (.ty S) (.ty T)) :
    Ty.RuntimeCongruent R S T :=
  match conversion with
  | .proper types => types

/-- Normalize arbitrary conversion evidence, including transitivity and
one-hole replacement, to its structural component form. -/
noncomputable def Tau.RuntimeConv.runtimeCongruent
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R)
    {k : Kind} {d1 d2 : Tau n k}
    (conversion : Tau.RuntimeConv R d1 d2) :
    Tau.RuntimeCongruent R d1 d2 :=
  match conversion with
  | .refl => Tau.RuntimeCongruent.refl operations _
  | .symm code => (code.runtimeCongruent operations).symm operations
  | .trans first second =>
      (first.runtimeCongruent operations).trans operations
        (second.runtimeCongruent operations)
  | .replace (p := p) (q := q) context evidence =>
      Tau.RuntimeCongruent.ofSubst operations
        (PathSubst.openAt p) (PathSubst.openAt q)
        (fun x => Fin.cases evidence
          (fun i => operations.refl (.var i)) x)
        context
  | .fun domain codomain =>
      .proper (.fun
        (domain.runtimeCongruent operations).properTypes
        (codomain.runtimeCongruent
          (Path.ScopedLift.eqCongruence operations)).properTypes)
  | .pair first member =>
      .proper (.pair
        (first.runtimeCongruent operations).properTypes
        (member.runtimeCongruent
          (Path.ScopedLift.eqCongruence operations)))
  | .single path => .proper (.single path)
  | .selection path => .proper (.selection path)
  | .interval lower upper =>
      .interval
        (lower.runtimeCongruent operations).properTypes
        (upper.runtimeCongruent operations).properTypes

structure Tau.RuntimeConv.FunComponents
    (R : Path n -> Path n -> Type)
    (S S' : Ty n) (T T' : Ty (n + 1)) : Type 1 where
  domain : Tau.RuntimeConv R (.ty S) (.ty S')
  codomain :
    Tau.RuntimeConv (Path.ScopedLift R) (.ty T) (.ty T')

noncomputable def Tau.RuntimeConv.funComponents
    (operations : Path.EqCongruence R)
    (conversion : Tau.RuntimeConv R
      (.ty (.Fun S T)) (.ty (.Fun S' T'))) :
    Tau.RuntimeConv.FunComponents R S S' T T' := by
  have normal := conversion.runtimeCongruent operations
  cases normal with
  | proper types =>
      cases types with
      | «fun» domain codomain =>
          exact ⟨domain.toRuntimeConv, codomain.toRuntimeConv⟩

structure Tau.RuntimeConv.PairComponents
    (R : Path n -> Path n -> Type)
    {k1 k2 : Kind} (S S' : Ty n) (a b : Name)
    (d1 : Tau (n + 1) k1) (d2 : Tau (n + 1) k2) : Type 1 where
  labelEq : a = b
  kindEq : k1 = k2
  first : Tau.RuntimeConv R (.ty S) (.ty S')
  member :
    Tau.RuntimeConv (Path.ScopedLift R) d1 (kindEq.symm ▸ d2)

noncomputable def Tau.RuntimeConv.pairComponents
    (operations : Path.EqCongruence R)
    (conversion : Tau.RuntimeConv R
      (.ty (.Pair S a d1)) (.ty (.Pair S' b d2))) :
    Tau.RuntimeConv.PairComponents R S S' a b d1 d2 := by
  have normal := conversion.runtimeCongruent operations
  cases normal with
  | proper types =>
      cases types with
      | pair first member =>
          exact ⟨rfl, rfl, first.toRuntimeConv, member.toRuntimeConv⟩

theorem Tau.RuntimeConv.pairLabelEq
    (operations : Path.EqCongruence R)
    (conversion : Tau.RuntimeConv R
      (.ty (.Pair S a d1)) (.ty (.Pair S' b d2))) :
    a = b :=
  (conversion.pairComponents operations).labelEq

theorem Tau.RuntimeConv.pairKindEq
    {n : Nat} {R : Path n -> Path n -> Type}
    {k1 k2 : Kind} {S S' : Ty n} {a b : Name}
    {d1 : Tau (n + 1) k1} {d2 : Tau (n + 1) k2}
    (operations : Path.EqCongruence R)
    (conversion : Tau.RuntimeConv R
      (.ty (.Pair S a d1)) (.ty (.Pair S' b d2))) :
    k1 = k2 :=
  (conversion.pairComponents operations).kindEq

/-- A converted singleton exposes equality evidence for its paths. -/
noncomputable def Tau.RuntimeConv.singlePath
    (operations : Path.EqCongruence R)
    (conversion : Tau.RuntimeConv R
      (.ty (.Single p)) (.ty (.Single q))) :
    R p q := by
  have normal := conversion.runtimeCongruent operations
  cases normal with
  | proper types =>
      cases types with
      | single path => exact path

structure Tau.RuntimeConv.SelectionComponents
    (R : Path n -> Path n -> Type)
    (p q : Path n) (A B : Name) : Type 1 where
  labelEq : A = B
  path : R p q

noncomputable def Tau.RuntimeConv.selectionComponents
    (operations : Path.EqCongruence R)
    (conversion : Tau.RuntimeConv R
      (.ty (.TSel p A)) (.ty (.TSel q B))) :
    Tau.RuntimeConv.SelectionComponents R p q A B := by
  have normal := conversion.runtimeCongruent operations
  cases normal with
  | proper types =>
      cases types with
      | selection path => exact ⟨rfl, path⟩

theorem Tau.RuntimeConv.selectionLabelEq
    (operations : Path.EqCongruence R)
    (conversion : Tau.RuntimeConv R
      (.ty (.TSel p A)) (.ty (.TSel q B))) :
    A = B :=
  (conversion.selectionComponents operations).labelEq

structure Tau.RuntimeConv.IntervalComponents
    (R : Path n -> Path n -> Type)
    (L U L' U' : Ty n) : Type 1 where
  lower : Tau.RuntimeConv R (.ty L) (.ty L')
  upper : Tau.RuntimeConv R (.ty U) (.ty U')

noncomputable def Tau.RuntimeConv.intervalComponents
    (operations : Path.EqCongruence R)
    (conversion : Tau.RuntimeConv R
      (.intv L U) (.intv L' U')) :
    Tau.RuntimeConv.IntervalComponents R L U L' U' := by
  have normal := conversion.runtimeCongruent operations
  cases normal with
  | interval lower upper =>
      exact ⟨lower.toRuntimeConv, upper.toRuntimeConv⟩


end LambdaPFC
