import DotToFCsub.M7.Elaboration
import FCsub.ClosedArtifact
import FCsub.Normalization

/-!
# M7 certificate-producing compiler

The emitted closed term performs two static tasks in one client:

1. inside the finite M6 alias scope, define a path-dependent `rekey` function
   from `leftPath.A` to `rightPath.A`; its body is only an explicit equality
   cast, so no inhabitant of either member is assumed;
2. discard that function and return the M5 recursive object package.

Every alias name/equality pair is then closed with existing `FCsub.newtype`.
The proof-free result is consumed independently through `FCsub.ClosedArtifact`.

The rekey function is a certified target client instantiated from the supplied
source-endpoint and co-resolution certificates.  It is not claimed to be the
translation of a `DotFCRP` source term.  M7's sole source term preservation
result remains the reused M5 recursive-object theorem.
-/

namespace DotToFCsub.M7.Compiler

open DotToFCsub.M6

/-- Complete target scope containing one fresh name/equality pair for every
syntactic member key in the supplied path layout. -/
abbrev AliasTarget {program : Surface.Program}
    (certificate : Certificate program) : FCsub.Sig :=
  AliasScope.Scope [] certificate.layout.count

/-- Target context generated by those alias pairs. -/
abbrev AliasContext {program : Surface.Program}
    (certificate : Certificate program) : FCsub.Ctx (AliasTarget certificate) :=
  AliasScope.extend FCsub.Ctx.nil certificate.layout.anchorType

/-- Type of the generated path-dependent method. -/
def rekeyType {program : Surface.Program}
    (certificate : Certificate program) : FCsub.Ty (AliasTarget certificate) :=
  .arr certificate.leftImage.aliasType
    (certificate.rightImage.aliasType.weaken (kind := .term))

/-- `lambda (x : leftPath.A). x cast pathEquality`.

The body contains no constant or assumed value of either selected member.
Its only non-variable syntax is the explicit, erasable equality cast. -/
def rekey {program : Surface.Program}
    (certificate : Certificate program) : FCsub.Tm (AliasTarget certificate) :=
  .lam certificate.leftImage.aliasType
    (.cast (.var .here)
      (.eqToLe (certificate.memberEquality.evidence.normalize.weaken
        (kind := .term))))

/-- Rename the M5 recursive package below all generated alias pairs. -/
def recursiveObjectInAliases {program : Surface.Program}
    (certificate : Certificate program) : FCsub.Tm (AliasTarget certificate) :=
  certificate.encoding.object.rename
    (AliasScope.weaken certificate.layout.count)

/-- The target client within the private alias scope.  The rekey method is
locally checked and discarded; the recursive package is the result. -/
def body {program : Surface.Program}
    (certificate : Certificate program) : FCsub.Tm (AliasTarget certificate) :=
  .let' (rekey certificate) (recursiveObjectInAliases certificate).weaken

/-- Close every private path-member name and equality around the client. -/
def target {program : Surface.Program}
    (certificate : Certificate program) : FCsub.Tm [] :=
  AliasScope.close certificate.layout.anchorType (body certificate)

/-- The claimed result remains exactly the M5 recursive package type; no M6
private alias is allowed to escape. -/
def targetType {program : Surface.Program}
    (certificate : Certificate program) : FCsub.Ty [] :=
  certificate.encoding.objectType

/-- Proof-free compiler output for the standalone FCsub checker. -/
def compile {program : Surface.Program}
    (certificate : Certificate program) : FCsub.ClosedArtifact :=
  { term := target certificate
    type := targetType certificate }

/-- Runtime program expected after erasing the generated artifact.  The
recursive package erases to unit; the path-dependent cast erases from the
dead identity lambda. -/
def expectedRuntime : FCsub.Runtime.Tm [] :=
  .let' (.lam (.var .here)) .unit

end DotToFCsub.M7.Compiler
