name = "path-dependent"
version = "0.1.0"
srcDir = "lean"
defaultTargets = ["LambdaP", "LambdaPFC", "LambdaPCC", "LambdaPFCI", "LambdaPCCI", "SystemFCo", "SystemFSub", "LambdaPToFCo"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = true
relaxedAutoImplicit = true

[[lean_lib]]
name = "LambdaP"

[[lean_lib]]
name = "LambdaPFC"

[[lean_lib]]
name = "LambdaPCC"

[[lean_lib]]
name = "LambdaPFCI"

[[lean_lib]]
name = "LambdaPCCI"

[[lean_lib]]
name = "SystemFCo"

[[lean_lib]]
name = "SystemFSub"

[[lean_lib]]
name = "LambdaPToFCo"
