From Equations Require Import Equations.
From PathDependent.LambdaP Require Import FinFun Syntax Context Typing
  Renaming ScopedRuntimeEq Opening.

Set Implicit Arguments.
Unset Strict Implicit.
Set Default Proof Using "Type".

Local Coercion FinFun.apply : FinFun.t >-> Funclass.

(** Symmetric generalized-type conversion generated by an abstract path
    equivalence/congruence. *)
Inductive Tau_StructConv {n : nat} {k : Kind}
    (R : Path n -> Path n -> Prop) : Tau n k -> Tau n k -> Prop :=
| tau_struct_conv_refl (d : Tau n k) : Tau_StructConv R d d
| tau_struct_conv_symm {d1 d2 : Tau n k} :
    Tau_StructConv R d1 d2 -> Tau_StructConv R d2 d1
| tau_struct_conv_trans {d1 d2 d3 : Tau n k} :
    Tau_StructConv R d1 d2 -> Tau_StructConv R d2 d3 ->
    Tau_StructConv R d1 d3
| tau_struct_conv_replace (template : Tau (S n) k) {p q : Path n} :
    R p q -> Tau_StructConv R
      (Tau_open template p) (Tau_open template q).

Arguments tau_struct_conv_refl {n k R} d.
Arguments tau_struct_conv_symm {n k R d1 d2} _.
Arguments tau_struct_conv_trans {n k R d1 d2 d3} _ _.
Arguments tau_struct_conv_replace {n k R} template {p q} _.

(** Mutually structural path checking and generalized subtyping. *)
Inductive Path_StructCheck : forall {n : nat},
    Ctx n -> (Path n -> Path n -> Prop) ->
    forall {k : Kind}, Path n -> Tau n k -> Prop :=
| path_struct_check_var {n : nat} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (x : Fin.t n) (T : Ty n) :
    Ctx_Binds G x T ->
    Path_StructCheck G R (path_var x) (tau_ty T)
| path_struct_check_sub {n : nat} {k : Kind} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (p : Path n)
    (d1 d2 : Tau n k) :
    Path_StructCheck G R p d1 ->
    Tau_StructSub G R d1 d2 ->
    Path_StructCheck G R p d2
| path_struct_check_promote {n : nat} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (p : Path n) (U T : Ty n) :
    Path_StructCheck G R p (tau_ty U) ->
    Tau_StructSub G R (tau_ty (ty_single p)) (tau_ty T) ->
    Path_StructCheck G R p (tau_ty T)
| path_struct_check_fst {n : nat} {k : Kind} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (p : Path n)
    (S0 : Ty n) (a : Name) (d : Tau (S n) k) :
    Path_StructCheck G R p (tau_ty (ty_pair S0 a d)) ->
    Path_StructCheck G R (path_fst p) (tau_ty S0)
| path_struct_check_sel_r {n : nat} {k : Kind} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (p : Path n)
    (S0 : Ty n) (a : Name) (d : Tau (S n) k) :
    Path_StructCheck G R p (tau_ty (ty_pair S0 a d)) ->
    Path_StructCheck G R (path_sel p a) (Tau_open d (path_fst p))
| path_struct_check_sel_l {n : nat} {k k' : Kind} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (p : Path n)
    (S0 : Ty n) (a b : Name) (d : Tau n k)
    (d' : Tau (S n) k') :
    Path_StructCheck G R p (tau_ty (ty_pair S0 b d')) ->
    Path_StructCheck G R (path_sel (path_fst p) a) d ->
    a <> b ->
    Path_StructCheck G R (path_sel p a) d
with Tau_StructSub : forall {n : nat},
    Ctx n -> (Path n -> Path n -> Prop) ->
    forall {k : Kind}, Tau n k -> Tau n k -> Prop :=
| tau_struct_sub_refl {n : nat} {k : Kind} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (d : Tau n k) :
    Tau_StructSub G R d d
| tau_struct_sub_trans {n : nat} {k : Kind} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (d1 d2 d3 : Tau n k) :
    Tau_StructSub G R d1 d2 -> Tau_StructSub G R d2 d3 ->
    Tau_StructSub G R d1 d3
| tau_struct_sub_conv {n : nat} {k : Kind} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (d1 d2 : Tau n k) :
    Tau_StructConv R d1 d2 -> Tau_StructSub G R d1 d2
| tau_struct_sub_bot {n : nat} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (T : Ty n) :
    Tau_StructSub G R (tau_ty ty_bot) (tau_ty T)
| tau_struct_sub_top {n : nat} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (T : Ty n) :
    Tau_StructSub G R (tau_ty T) (tau_ty ty_top)
| tau_struct_sub_widen {n : nat} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (p : Path n) (T : Ty n) :
    Path_StructCheck G R p (tau_ty T) ->
    Tau_StructSub G R (tau_ty (ty_single p)) (tau_ty T)
| tau_struct_sub_symm {n : nat} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (p q : Path n) :
    Path_StructCheck G R p (tau_ty (ty_single q)) ->
    Tau_StructSub G R
      (tau_ty (ty_single q)) (tau_ty (ty_single p))
| tau_struct_sub_sel_hi {n : nat} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (p : Path n) (A : Name)
    (S0 T : Ty n) :
    Path_StructCheck G R (path_sel p A) (tau_intv S0 T) ->
    Tau_StructSub G R (tau_ty S0) (tau_ty T) ->
    Tau_StructSub G R (tau_ty (ty_tsel p A)) (tau_ty T)
| tau_struct_sub_sel_lo {n : nat} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (p : Path n) (A : Name)
    (S0 T : Ty n) :
    Path_StructCheck G R (path_sel p A) (tau_intv S0 T) ->
    Tau_StructSub G R (tau_ty S0) (tau_ty T) ->
    Tau_StructSub G R (tau_ty S0) (tau_ty (ty_tsel p A))
| tau_struct_sub_fun {n : nat} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (S0 S' : Ty n)
    (T T' : Ty (S n)) :
    Tau_StructSub G R (tau_ty S') (tau_ty S0) ->
    Tau_StructSub (ctx_snoc G S') (Path_ScopedLift R)
      (tau_ty T) (tau_ty T') ->
    Tau_StructSub G R
      (tau_ty (ty_fun S0 T)) (tau_ty (ty_fun S' T'))
| tau_struct_sub_pair_fst {n : nat} {k : Kind} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (S0 S' : Ty n)
    (a : Name) (d : Tau (S n) k) :
    Tau_StructSub G R (tau_ty S0) (tau_ty S') ->
    Tau_StructSub G R
      (tau_ty (ty_pair S0 a d)) (tau_ty (ty_pair S' a d))
| tau_struct_sub_pair_single_member {n : nat} {k : Kind}
    (G : Ctx n) (R : Path n -> Path n -> Prop)
    (p : Path n) (P : Ty n) (a : Name)
    (d d' : Tau (S n) k) :
    Path_StructCheck G R p (tau_ty P) ->
    Tau_StructSub (ctx_snoc G (ty_single p)) (Path_ScopedLift R) d d' ->
    Tau_StructSub G R (Tau_open d p) (Tau_open d' p) ->
    Tau_StructSub G R
      (tau_ty (ty_pair (ty_single p) a d))
      (tau_ty (ty_pair (ty_single p) a d'))
| tau_struct_sub_bounds {n : nat} (G : Ctx n)
    (R : Path n -> Path n -> Prop) (S0 S' T T' : Ty n) :
    Tau_StructSub G R (tau_ty S') (tau_ty S0) ->
    Tau_StructSub G R (tau_ty T) (tau_ty T') ->
    Tau_StructSub G R (tau_ty S0) (tau_ty T) ->
    Tau_StructSub G R (tau_intv S0 T) (tau_intv S' T').

Scheme Path_StructCheck_mut := Induction for Path_StructCheck Sort Prop
with Tau_StructSub_mut := Induction for Tau_StructSub Sort Prop.
Combined Scheme PathStruct_mutind
  from Path_StructCheck_mut, Tau_StructSub_mut.

(** Every source precise path derivation embeds for every abstract relation. *)
Theorem Path_StructCheck_of_source {n : nat} {G : Ctx n}
    {p : Path n} {k : Kind} {d : Tau n k}
    (H : Path_Ty G p d) (R : Path n -> Path n -> Prop) :
    Path_StructCheck G R p d.
Proof.
  induction H.
  - now apply path_struct_check_var.
  - eapply path_struct_check_fst. exact (IHPath_Ty R).
  - eapply path_struct_check_sel_r. exact (IHPath_Ty R).
  - eapply path_struct_check_sel_l;
      [exact (IHPath_Ty1 R) | exact (IHPath_Ty2 R) | assumption].
Qed.

(** Every source generalized-subtyping derivation embeds, including below
    binders. *)
Theorem Tau_StructSub_of_source {n : nat} {G : Ctx n}
    {k : Kind} {d1 d2 : Tau n k} (H : Tau_Sub G d1 d2) :
    forall R : Path n -> Path n -> Prop, Tau_StructSub G R d1 d2.
Proof.
  induction H; intro R.
  - apply tau_struct_sub_refl.
  - eapply tau_struct_sub_trans;
      [exact (IHTau_Sub1 R) | exact (IHTau_Sub2 R)].
  - apply tau_struct_sub_bot.
  - apply tau_struct_sub_top.
  - apply tau_struct_sub_widen. now apply Path_StructCheck_of_source.
  - apply tau_struct_sub_symm. now apply Path_StructCheck_of_source.
  - eapply tau_struct_sub_sel_hi.
    + eapply Path_StructCheck_of_source; eassumption.
    + exact (IHTau_Sub R).
  - eapply tau_struct_sub_sel_lo.
    + eapply Path_StructCheck_of_source; eassumption.
    + exact (IHTau_Sub R).
  - eapply tau_struct_sub_fun.
    + exact (IHTau_Sub1 R).
    + exact (IHTau_Sub2 (Path_ScopedLift R)).
  - apply tau_struct_sub_pair_fst. exact (IHTau_Sub R).
  - eapply tau_struct_sub_pair_single_member.
    + eapply Path_StructCheck_of_source; eassumption.
    + exact (IHTau_Sub1 (Path_ScopedLift R)).
    + exact (IHTau_Sub2 R).
  - eapply tau_struct_sub_bounds;
      [exact (IHTau_Sub1 R) | exact (IHTau_Sub2 R) |
       exact (IHTau_Sub3 R)].
Qed.

(** A renaming transports one abstract path relation into another. *)
Definition Path_RelHom {n m : nat}
    (R : Path n -> Path n -> Prop)
    (E : Path m -> Path m -> Prop) (f : FinFun.t n m) : Prop :=
  forall p q, R p q -> E (Path_rename p f) (Path_rename q f).

(** A relation morphism lifts through a source binder. *)
Theorem Path_RelHom_scoped {n m : nat}
    {R : Path n -> Path n -> Prop} {E : Path m -> Path m -> Prop}
    {f : FinFun.t n m} (H : Path_RelHom R E f) :
    Path_RelHom (Path_ScopedLift R) (Path_ScopedLift E) (FinFun.ext f).
Proof.
  intros p q Hpq.
  exact (@Path_ScopedLift_rename n m R E f H p q Hpq).
Qed.

(** Weakening maps an ambient relation into its scoped lift. *)
Theorem Path_RelHom_weaken {n : nat} {R : Path n -> Path n -> Prop} :
    Path_RelHom R (Path_ScopedLift R) (FinFun.weaken n).
Proof. intros p q Hpq. now apply path_scoped_lift_old. Qed.

(** Abstract type conversion is natural with respect to a relation
    morphism. *)
Theorem Tau_StructConv_rename {n m : nat} {k : Kind}
    {R : Path n -> Path n -> Prop} {E : Path m -> Path m -> Prop}
    {f : FinFun.t n m} {d1 d2 : Tau n k}
    (H : Tau_StructConv R d1 d2) (Hrel : Path_RelHom R E f) :
    Tau_StructConv E (Tau_rename d1 f) (Tau_rename d2 f).
Proof.
  induction H.
  - apply tau_struct_conv_refl.
  - now apply tau_struct_conv_symm.
  - eapply tau_struct_conv_trans; eassumption.
  - rewrite !Tau_open_rename.
    apply tau_struct_conv_replace. now apply Hrel.
Qed.

Definition Path_RenameExactMotive {n : nat} (G : Ctx n)
    (R : Path n -> Path n -> Prop) {k : Kind}
    (p : Path n) (d : Tau n k) (_ : Path_StructCheck G R p d) : Prop :=
  forall (m : nat) (f : FinFun.t n m) (D : Ctx m)
    (E : Path m -> Path m -> Prop),
    Renaming G f D -> Path_RelHom R E f ->
    Path_StructCheck D E (Path_rename p f) (Tau_rename d f).

Definition Sub_RenameExactMotive {n : nat} (G : Ctx n)
    (R : Path n -> Path n -> Prop) {k : Kind}
    (d1 d2 : Tau n k) (_ : Tau_StructSub G R d1 d2) : Prop :=
  forall (m : nat) (f : FinFun.t n m) (D : Ctx m)
    (E : Path m -> Path m -> Prop),
    Renaming G f D -> Path_RelHom R E f ->
    Tau_StructSub D E (Tau_rename d1 f) (Tau_rename d2 f).

Lemma Path_Sub_renameExact_mut :
    (forall n G R k p d (H : Path_StructCheck G R p d),
      @Path_RenameExactMotive n G R k p d H) /\
    (forall n G R k d1 d2 (H : Tau_StructSub G R d1 d2),
      @Sub_RenameExactMotive n G R k d1 d2 H).
Proof.
  apply PathStruct_mutind;
    unfold Path_RenameExactMotive, Sub_RenameExactMotive.
  - intros n G R x T Hb m f D E rho Hrel.
    cbn [Path_rename Tau_rename]. apply path_struct_check_var.
    exact (rho x T Hb).
  - intros n k G R p d1 d2 Hp IHp Hs IHs m f D E rho Hrel.
    eapply path_struct_check_sub.
    + exact (IHp _ _ _ _ rho Hrel).
    + exact (IHs _ _ _ _ rho Hrel).
  - intros n G R p U T Hp IHp Hs IHs m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename].
    eapply path_struct_check_promote.
    + exact (IHp _ _ _ _ rho Hrel).
    + exact (IHs _ _ _ _ rho Hrel).
  - intros n k G R p S0 a d Hp IHp m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename].
    eapply path_struct_check_fst. exact (IHp _ _ _ _ rho Hrel).
  - intros n k G R p S0 a d Hp IHp m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename]. rewrite Tau_open_rename.
    eapply path_struct_check_sel_r. exact (IHp _ _ _ _ rho Hrel).
  - intros n k k' G R p S0 a b d d' Hp IHp Htail IHtail Hne
      m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename].
    eapply path_struct_check_sel_l.
    + exact (IHp _ _ _ _ rho Hrel).
    + exact (IHtail _ _ _ _ rho Hrel).
    + exact Hne.
  - intros n k G R d m f D E rho Hrel.
    apply tau_struct_sub_refl.
  - intros n k G R d1 d2 d3 H1 IH1 H2 IH2 m f D E rho Hrel.
    eapply tau_struct_sub_trans.
    + exact (IH1 _ _ _ _ rho Hrel).
    + exact (IH2 _ _ _ _ rho Hrel).
  - intros n k G R d1 d2 Hconv m f D E rho Hrel.
    apply tau_struct_sub_conv.
    exact (@Tau_StructConv_rename n m k R E f d1 d2 Hconv Hrel).
  - intros n G R T m f D E rho Hrel.
    cbn [Ty_rename Tau_rename]. apply tau_struct_sub_bot.
  - intros n G R T m f D E rho Hrel.
    cbn [Ty_rename Tau_rename]. apply tau_struct_sub_top.
  - intros n G R p T Hp IHp m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename].
    apply tau_struct_sub_widen. exact (IHp _ _ _ _ rho Hrel).
  - intros n G R p q Hp IHp m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename].
    apply tau_struct_sub_symm. exact (IHp _ _ _ _ rho Hrel).
  - intros n G R p A S0 T Hp IHp Hs IHs m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename].
    eapply tau_struct_sub_sel_hi.
    + exact (IHp _ _ _ _ rho Hrel).
    + exact (IHs _ _ _ _ rho Hrel).
  - intros n G R p A S0 T Hp IHp Hs IHs m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename].
    eapply tau_struct_sub_sel_lo.
    + exact (IHp _ _ _ _ rho Hrel).
    + exact (IHs _ _ _ _ rho Hrel).
  - intros n G R S0 S' T T' Hdom IHdom Hcod IHcod
      m f D E rho Hrel.
    cbn [Ty_rename Tau_rename]. eapply tau_struct_sub_fun.
    + exact (IHdom _ _ _ _ rho Hrel).
    + exact (IHcod _ _ _ _ (Renaming_ext rho)
        (Path_RelHom_scoped Hrel)).
  - intros n k G R S0 S' a d Hfst IHfst m f D E rho Hrel.
    cbn [Ty_rename Tau_rename]. apply tau_struct_sub_pair_fst.
    exact (IHfst _ _ _ _ rho Hrel).
  - intros n k G R p P a d d' Hp IHp Hsnd IHsnd Hopen IHopen
      m f D E rho Hrel.
    pose proof (IHopen _ _ _ _ rho Hrel) as Hopen'.
    rewrite !Tau_open_rename in Hopen'.
    cbn [Path_rename Ty_rename Tau_rename].
    eapply tau_struct_sub_pair_single_member.
    + exact (IHp _ _ _ _ rho Hrel).
    + exact (IHsnd _ _ _ _ (Renaming_ext rho)
        (Path_RelHom_scoped Hrel)).
    + exact Hopen'.
  - intros n G R S0 S' T T' Hlo IHlo Hhi IHhi Hnon IHnon
      m f D E rho Hrel.
    cbn [Tau_rename]. eapply tau_struct_sub_bounds.
    + exact (IHlo _ _ _ _ rho Hrel).
    + exact (IHhi _ _ _ _ rho Hrel).
    + exact (IHnon _ _ _ _ rho Hrel).
Qed.

(** Structural path checking is preserved by an exact context-respecting
    renaming and compatible relation morphism. *)
Theorem Path_StructCheck_renameExact {n m : nat} {G : Ctx n}
    {R : Path n -> Path n -> Prop} {k : Kind}
    {p : Path n} {d : Tau n k} (H : Path_StructCheck G R p d)
    {f : FinFun.t n m} {D : Ctx m} {E : Path m -> Path m -> Prop}
    (rho : Renaming G f D) (Hrel : Path_RelHom R E f) :
    Path_StructCheck D E (Path_rename p f) (Tau_rename d f).
Proof.
  exact (proj1 Path_Sub_renameExact_mut _ _ _ _ _ _ H _ _ _ _ rho Hrel).
Qed.

(** Structural generalized subtyping is preserved by the same exact
    renaming. *)
Theorem Tau_StructSub_renameExact {n m : nat} {G : Ctx n}
    {R : Path n -> Path n -> Prop} {k : Kind}
    {d1 d2 : Tau n k} (H : Tau_StructSub G R d1 d2)
    {f : FinFun.t n m} {D : Ctx m} {E : Path m -> Path m -> Prop}
    (rho : Renaming G f D) (Hrel : Path_RelHom R E f) :
    Tau_StructSub D E (Tau_rename d1 f) (Tau_rename d2 f).
Proof.
  exact (proj2 Path_Sub_renameExact_mut _ _ _ _ _ _ H _ _ _ _ rho Hrel).
Qed.

(** A structural renaming maps every source variable to a path which checks
    at the renamed context type.  Unlike [Renaming], its evidence need not
    arise from a literal variable binding in the target context. *)
Definition Path_StructRenaming {n m : nat} (G : Ctx n)
    (f : FinFun.t n m) (D : Ctx m)
    (E : Path m -> Path m -> Prop) : Prop :=
  forall (x : Fin.t n) (T : Ty n), Ctx_Binds G x T ->
    Path_StructCheck D E (path_var (f x))
      (tau_ty (Ty_rename T f)).

(** Every exact context-respecting renaming is structural. *)
Theorem Path_StructRenaming_of_exact {n m : nat} {G : Ctx n}
    {f : FinFun.t n m} {D : Ctx m}
    {E : Path m -> Path m -> Prop} (rho : Renaming G f D) :
    Path_StructRenaming G f D E.
Proof.
  intros x T Hx. apply path_struct_check_var. exact (rho x T Hx).
Qed.

(** Structural renamings extend through one dependent binder.  Old images
    are weakened using exact renaming of their structural derivations. *)
Theorem Path_StructRenaming_ext {n m : nat} {G : Ctx n}
    {f : FinFun.t n m} {D : Ctx m}
    {E : Path m -> Path m -> Prop} {T : Ty n}
    (rho : Path_StructRenaming G f D E) :
    Path_StructRenaming (ctx_snoc G T) (FinFun.ext f)
      (ctx_snoc D (Ty_rename T f)) (Path_ScopedLift E).
Proof.
  intros x U Hx.
  refine (@Fin.cases' n x
    (fun x => Ctx_Binds (ctx_snoc G T) x U ->
      Path_StructCheck (ctx_snoc D (Ty_rename T f))
        (Path_ScopedLift E) (path_var (FinFun.ext f x))
        (tau_ty (Ty_rename U (FinFun.ext f)))) _ _ Hx).
  - intro H0.
    assert (U = Ty_weaken T) as ->.
    { exact (Ctx_Binds_unique H0 (binds_here G T)). }
    rewrite FinFun.ext_zero, <- Ty_weaken_rename.
    apply path_struct_check_var. apply binds_here.
  - intros y Hy.
    assert (U = Ty_weaken (Ctx_lookup G y)) as ->.
    { exact (Ctx_Binds_unique Hy
        (binds_there G T (Ctx_lookup G y) y (Ctx_lookup_binds G y))). }
    rewrite FinFun.ext_succ, <- Ty_weaken_rename.
    pose proof (Path_StructCheck_renameExact
      (rho y (Ctx_lookup G y) (Ctx_lookup_binds G y))
      (@Renaming_weaken m D (Ty_rename T f))
      (@Path_RelHom_weaken m E)) as Hweak.
    cbn [Path_rename Tau_rename] in Hweak.
    rewrite FinFun.weaken_apply in Hweak. exact Hweak.
Qed.

Definition Path_RenameMotive {n : nat} (G : Ctx n)
    (R : Path n -> Path n -> Prop) {k : Kind}
    (p : Path n) (d : Tau n k) (_ : Path_StructCheck G R p d) : Prop :=
  forall (m : nat) (f : FinFun.t n m) (D : Ctx m)
    (E : Path m -> Path m -> Prop),
    Path_StructRenaming G f D E -> Path_RelHom R E f ->
    Path_StructCheck D E (Path_rename p f) (Tau_rename d f).

Definition Sub_RenameMotive {n : nat} (G : Ctx n)
    (R : Path n -> Path n -> Prop) {k : Kind}
    (d1 d2 : Tau n k) (_ : Tau_StructSub G R d1 d2) : Prop :=
  forall (m : nat) (f : FinFun.t n m) (D : Ctx m)
    (E : Path m -> Path m -> Prop),
    Path_StructRenaming G f D E -> Path_RelHom R E f ->
    Tau_StructSub D E (Tau_rename d1 f) (Tau_rename d2 f).

Lemma Path_Sub_rename_mut :
    (forall n G R k p d (H : Path_StructCheck G R p d),
      @Path_RenameMotive n G R k p d H) /\
    (forall n G R k d1 d2 (H : Tau_StructSub G R d1 d2),
      @Sub_RenameMotive n G R k d1 d2 H).
Proof.
  apply PathStruct_mutind;
    unfold Path_RenameMotive, Sub_RenameMotive.
  - intros n G R x T Hb m f D E rho Hrel.
    cbn [Path_rename Tau_rename]. exact (rho x T Hb).
  - intros n k G R p d1 d2 Hp IHp Hs IHs m f D E rho Hrel.
    eapply path_struct_check_sub.
    + exact (IHp _ _ _ _ rho Hrel).
    + exact (IHs _ _ _ _ rho Hrel).
  - intros n G R p U T Hp IHp Hs IHs m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename].
    eapply path_struct_check_promote.
    + exact (IHp _ _ _ _ rho Hrel).
    + exact (IHs _ _ _ _ rho Hrel).
  - intros n k G R p S0 a d Hp IHp m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename].
    eapply path_struct_check_fst. exact (IHp _ _ _ _ rho Hrel).
  - intros n k G R p S0 a d Hp IHp m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename]. rewrite Tau_open_rename.
    eapply path_struct_check_sel_r. exact (IHp _ _ _ _ rho Hrel).
  - intros n k k' G R p S0 a b d d' Hp IHp Htail IHtail Hne
      m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename].
    eapply path_struct_check_sel_l.
    + exact (IHp _ _ _ _ rho Hrel).
    + exact (IHtail _ _ _ _ rho Hrel).
    + exact Hne.
  - intros n k G R d m f D E rho Hrel.
    apply tau_struct_sub_refl.
  - intros n k G R d1 d2 d3 H1 IH1 H2 IH2 m f D E rho Hrel.
    eapply tau_struct_sub_trans.
    + exact (IH1 _ _ _ _ rho Hrel).
    + exact (IH2 _ _ _ _ rho Hrel).
  - intros n k G R d1 d2 Hconv m f D E rho Hrel.
    apply tau_struct_sub_conv.
    exact (@Tau_StructConv_rename n m k R E f d1 d2 Hconv Hrel).
  - intros n G R T m f D E rho Hrel.
    cbn [Ty_rename Tau_rename]. apply tau_struct_sub_bot.
  - intros n G R T m f D E rho Hrel.
    cbn [Ty_rename Tau_rename]. apply tau_struct_sub_top.
  - intros n G R p T Hp IHp m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename].
    apply tau_struct_sub_widen. exact (IHp _ _ _ _ rho Hrel).
  - intros n G R p q Hp IHp m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename].
    apply tau_struct_sub_symm. exact (IHp _ _ _ _ rho Hrel).
  - intros n G R p A S0 T Hp IHp Hs IHs m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename].
    eapply tau_struct_sub_sel_hi.
    + exact (IHp _ _ _ _ rho Hrel).
    + exact (IHs _ _ _ _ rho Hrel).
  - intros n G R p A S0 T Hp IHp Hs IHs m f D E rho Hrel.
    cbn [Path_rename Ty_rename Tau_rename].
    eapply tau_struct_sub_sel_lo.
    + exact (IHp _ _ _ _ rho Hrel).
    + exact (IHs _ _ _ _ rho Hrel).
  - intros n G R S0 S' T T' Hdom IHdom Hcod IHcod
      m f D E rho Hrel.
    cbn [Ty_rename Tau_rename]. eapply tau_struct_sub_fun.
    + exact (IHdom _ _ _ _ rho Hrel).
    + exact (IHcod _ _ _ _ (Path_StructRenaming_ext rho)
        (Path_RelHom_scoped Hrel)).
  - intros n k G R S0 S' a d Hfst IHfst m f D E rho Hrel.
    cbn [Ty_rename Tau_rename]. apply tau_struct_sub_pair_fst.
    exact (IHfst _ _ _ _ rho Hrel).
  - intros n k G R p P a d d' Hp IHp Hsnd IHsnd Hopen IHopen
      m f D E rho Hrel.
    pose proof (IHopen _ _ _ _ rho Hrel) as Hopen'.
    rewrite !Tau_open_rename in Hopen'.
    cbn [Path_rename Ty_rename Tau_rename].
    eapply tau_struct_sub_pair_single_member.
    + exact (IHp _ _ _ _ rho Hrel).
    + exact (IHsnd _ _ _ _ (Path_StructRenaming_ext rho)
        (Path_RelHom_scoped Hrel)).
    + exact Hopen'.
  - intros n G R S0 S' T T' Hlo IHlo Hhi IHhi Hnon IHnon
      m f D E rho Hrel.
    cbn [Tau_rename]. eapply tau_struct_sub_bounds.
    + exact (IHlo _ _ _ _ rho Hrel).
    + exact (IHhi _ _ _ _ rho Hrel).
    + exact (IHnon _ _ _ _ rho Hrel).
Qed.

(** Structural path checking is stable under structural renaming. *)
Theorem Path_StructCheck_rename {n m : nat} {G : Ctx n}
    {R : Path n -> Path n -> Prop} {k : Kind}
    {p : Path n} {d : Tau n k} (H : Path_StructCheck G R p d)
    {f : FinFun.t n m} {D : Ctx m} {E : Path m -> Path m -> Prop}
    (rho : Path_StructRenaming G f D E) (Hrel : Path_RelHom R E f) :
    Path_StructCheck D E (Path_rename p f) (Tau_rename d f).
Proof.
  exact (proj1 Path_Sub_rename_mut _ _ _ _ _ _ H _ _ _ _ rho Hrel).
Qed.

(** Structural generalized subtyping is stable under structural renaming. *)
Theorem Tau_StructSub_rename {n m : nat} {G : Ctx n}
    {R : Path n -> Path n -> Prop} {k : Kind}
    {d1 d2 : Tau n k} (H : Tau_StructSub G R d1 d2)
    {f : FinFun.t n m} {D : Ctx m} {E : Path m -> Path m -> Prop}
    (rho : Path_StructRenaming G f D E) (Hrel : Path_RelHom R E f) :
    Tau_StructSub D E (Tau_rename d1 f) (Tau_rename d2 f).
Proof.
  exact (proj2 Path_Sub_rename_mut _ _ _ _ _ _ H _ _ _ _ rho Hrel).
Qed.

(** Opening discharges the scoped relation: the bound variable is replaced
    by [x], related to itself by ambient reflexivity. *)
Theorem Path_RelHom_openAt {n : nat}
    {R : Path n -> Path n -> Prop} (HR : Path_IsEquivCongr R)
    (x : Fin.t n) :
    Path_RelHom (Path_ScopedLift R) R (FinFun.openAt x).
Proof.
  intros p q Hpq.
  rewrite !Path_rename_openAt_eq_open_var.
  exact (Path_ScopedLift_open_paths HR Hpq
    (path_equiv_refl HR (path_var x))).
Qed.

(** If the replacement variable checks at the binder type, opening maps the
    extended context structurally into the outer context. *)
Theorem Path_StructRenaming_openAt {n : nat} {G : Ctx n}
    {R : Path n -> Path n -> Prop} {S : Ty n} {x : Fin.t n}
    (Hx : Path_StructCheck G R (path_var x) (tau_ty S)) :
    Path_StructRenaming (ctx_snoc G S) (FinFun.openAt x) G R.
Proof.
  intros y T Hy.
  refine (@Fin.cases' n y
    (fun y => Ctx_Binds (ctx_snoc G S) y T ->
      Path_StructCheck G R (path_var (FinFun.openAt x y))
        (tau_ty (Ty_rename T (FinFun.openAt x)))) _ _ Hy).
  - intro H0.
    assert (T = Ty_weaken S) as ->.
    { exact (Ctx_Binds_unique H0 (binds_here G S)). }
    rewrite FinFun.openAt_zero.
    unfold Ty_weaken. rewrite Ty_rename_rename,
      FinFun.openAt_weaken, Ty_rename_id. exact Hx.
  - intros z Hz.
    assert (T = Ty_weaken (Ctx_lookup G z)) as ->.
    { exact (Ctx_Binds_unique Hz
        (binds_there G S (Ctx_lookup G z) z (Ctx_lookup_binds G z))). }
    rewrite FinFun.openAt_succ.
    unfold Ty_weaken. rewrite Ty_rename_rename,
      FinFun.openAt_weaken, Ty_rename_id.
    apply path_struct_check_var. apply Ctx_lookup_binds.
Qed.

(** One-binder opening for structural path checking. *)
Theorem Path_StructCheck_open_var {n : nat} {G : Ctx n}
    {R : Path n -> Path n -> Prop} {S0 : Ty n} {x : Fin.t n}
    {k : Kind} {p : Path (S n)} {d : Tau (S n) k}
    (H : Path_StructCheck (ctx_snoc G S0) (Path_ScopedLift R) p d)
    (HR : Path_IsEquivCongr R)
    (Hx : Path_StructCheck G R (path_var x) (tau_ty S0)) :
    Path_StructCheck G R
      (Path_rename p (FinFun.openAt x))
      (Tau_rename d (FinFun.openAt x)).
Proof.
  exact (Path_StructCheck_rename H
    (Path_StructRenaming_openAt Hx) (Path_RelHom_openAt HR x)).
Qed.

(** One-binder opening for structural generalized subtyping. *)
Theorem Tau_StructSub_open_var {n : nat} {G : Ctx n}
    {R : Path n -> Path n -> Prop} {S0 : Ty n} {x : Fin.t n}
    {k : Kind} {d1 d2 : Tau (S n) k}
    (H : Tau_StructSub (ctx_snoc G S0) (Path_ScopedLift R) d1 d2)
    (HR : Path_IsEquivCongr R)
    (Hx : Path_StructCheck G R (path_var x) (tau_ty S0)) :
    Tau_StructSub G R
      (Tau_rename d1 (FinFun.openAt x))
      (Tau_rename d2 (FinFun.openAt x)).
Proof.
  exact (Tau_StructSub_rename H
    (Path_StructRenaming_openAt Hx) (Path_RelHom_openAt HR x)).
Qed.

(** Singleton promotion supplies the binder-checking premise expected by
    [Path_StructCheck_open_var]. *)
Theorem Path_StructCheck_open_var_of_singleton {n : nat} {G : Ctx n}
    {R : Path n -> Path n -> Prop} {S0 U : Ty n} {x : Fin.t n}
    {k : Kind} {p : Path (S n)} {d : Tau (S n) k}
    (H : Path_StructCheck (ctx_snoc G S0) (Path_ScopedLift R) p d)
    (HR : Path_IsEquivCongr R)
    (Hx : Path_StructCheck G R (path_var x) (tau_ty U))
    (Hsub : Tau_StructSub G R
      (tau_ty (ty_single (path_var x))) (tau_ty S0)) :
    Path_StructCheck G R
      (Path_rename p (FinFun.openAt x))
      (Tau_rename d (FinFun.openAt x)).
Proof.
  apply (Path_StructCheck_open_var H HR).
  exact (path_struct_check_promote Hx Hsub).
Qed.

(** Singleton-based form of one-binder opening for structural subtyping. *)
Theorem Tau_StructSub_open_var_of_singleton {n : nat} {G : Ctx n}
    {R : Path n -> Path n -> Prop} {S0 U : Ty n} {x : Fin.t n}
    {k : Kind} {d1 d2 : Tau (S n) k}
    (H : Tau_StructSub (ctx_snoc G S0) (Path_ScopedLift R) d1 d2)
    (HR : Path_IsEquivCongr R)
    (Hx : Path_StructCheck G R (path_var x) (tau_ty U))
    (Hsub : Tau_StructSub G R
      (tau_ty (ty_single (path_var x))) (tau_ty S0)) :
    Tau_StructSub G R
      (Tau_rename d1 (FinFun.openAt x))
      (Tau_rename d2 (FinFun.openAt x)).
Proof.
  apply (Tau_StructSub_open_var H HR).
  exact (path_struct_check_promote Hx Hsub).
Qed.

Print Assumptions Path_StructCheck_renameExact.
Print Assumptions Tau_StructSub_renameExact.
Print Assumptions Path_StructRenaming_ext.
Print Assumptions Tau_StructSub_rename.
Print Assumptions Tau_StructSub_open_var_of_singleton.
