import DotFC.Explicit.Syntax

/-!
# Heterogeneous target contexts

The context telescope is indexed by the same singular `Sig` as every syntax
category.  A binding's payload is scoped in the outer signature; lookup
weakens that payload through the binder that introduced it and through every
newer binder traversed by a `.there` variable.
-/

namespace DotFC.Explicit

open DotFC

/-- Payload associated with each heterogeneous binder kind. -/
inductive Binding : (s : Sig) → BinderKind → Type where
  | term {s : Sig} (type : Source.Ty s) : Binding s .term
  | typeVar {s : Sig} : Binding s .type
  | equality {s : Sig} (left right : Source.Ty s) :
      Binding s (.evidence .equality)
  | inclusion {s : Sig} (source target : Source.Ty s) :
      Binding s (.evidence .inclusion)
  | member {s : Sig} (specification : MemberSpec s) : Binding s .member
deriving DecidableEq

namespace Binding

/-- The type stored by a term binding. -/
def termType : Binding s .term → Source.Ty s
  | .term type => type

/-- Endpoints stored by an equality-evidence binding. -/
def equalityEndpoints : Binding s (.evidence .equality) → Source.Ty s × Source.Ty s
  | .equality left right => (left, right)

/-- Endpoints stored by an inclusion-evidence binding. -/
def inclusionEndpoints : Binding s (.evidence .inclusion) →
    Source.Ty s × Source.Ty s
  | .inclusion source target => (source, target)

/-- Fact stored by a reusable member binding. -/
def memberSpec : Binding s .member → MemberSpec s
  | .member specification => specification

/-- Rename a binding payload without changing the kind of binder it
describes. -/
def rename {s₁ s₂ : Sig} {kind : BinderKind} (binding : Binding s₁ kind)
    (rho : Rename s₁ s₂) : Binding s₂ kind :=
  match binding with
  | .term type => .term (type.rename rho)
  | .typeVar => .typeVar
  | .equality left right => .equality (left.rename rho) (right.rename rho)
  | .inclusion source target => .inclusion (source.rename rho) (target.rename rho)
  | .member specification => .member (specification.rename rho)

/-- Weaken a binding payload below a new binder of any kind. -/
def weaken {s : Sig} {kind newKind : BinderKind} (binding : Binding s kind) :
    Binding (s ▹ newKind) kind :=
  binding.rename Rename.succ

@[simp]
theorem rename_id {s : Sig} {kind : BinderKind} (binding : Binding s kind) :
    binding.rename Rename.id = binding := by
  cases binding <;> simp [rename]

@[simp]
theorem rename_comp {s₁ s₂ s₃ : Sig} {kind : BinderKind}
    (binding : Binding s₁ kind) (rho₁ : Rename s₁ s₂)
    (rho₂ : Rename s₂ s₃) :
    (binding.rename rho₁).rename rho₂ =
      binding.rename (rho₁.comp rho₂) := by
  cases binding <;> simp [rename, Source.Ty.rename_comp, MemberSpec.rename_comp]

end Binding

/-- A telescope whose shape is exactly its heterogeneous signature. -/
inductive Ctx : Sig → Type where
  | nil : Ctx []
  | extend {s : Sig} {kind : BinderKind} (outer : Ctx s)
      (binding : Binding s kind) : Ctx (s ▹ kind)
deriving DecidableEq

namespace Ctx

/-- Remove the newest term binding from a context whose signature guarantees
that such a binding is present. -/
def dropTerm {s : Sig} : Ctx (s ▹ .term) → Ctx s
  | .extend outer (.term _) => outer

/-- Payload of the newest term binding. -/
def newestTerm {s : Sig} : Ctx (s ▹ .term) → Source.Ty s
  | .extend _ (.term type) => type

/-- Total, kind-correct lookup.  Returned payloads live in the complete
ambient signature, so each recursive step weakens the older payload. -/
def lookup {s : Sig} {kind : BinderKind} (context : Ctx s)
    (index : BVar s kind) : Binding s kind :=
  match context, index with
  | .extend _ binding, .here => binding.weaken
  | .extend outer _, .there older => (lookup outer older).weaken

/-- Add a term variable. -/
def extendTerm {s : Sig} (context : Ctx s) (type : Source.Ty s) :
    Ctx (s ▹ .term) :=
  .extend context (.term type)

/-- Add a target type name.  Stage A reserves this binder; Stage B supplies
its generative package discipline. -/
def extendType {s : Sig} (context : Ctx s) : Ctx (s ▹ .type) :=
  .extend context .typeVar

/-- Add symmetric equality evidence. -/
def extendEquality {s : Sig} (context : Ctx s) (left right : Source.Ty s) :
    Ctx (s ▹ .evidence .equality) :=
  .extend context (.equality left right)

/-- Add directed inclusion evidence. -/
def extendInclusion {s : Sig} (context : Ctx s) (source target : Source.Ty s) :
    Ctx (s ▹ .evidence .inclusion) :=
  .extend context (.inclusion source target)

/-- Bind a reusable member handle. -/
def extendMember {s : Sig} (context : Ctx s) (specification : MemberSpec s) :
    Ctx (s ▹ .member) :=
  .extend context (.member specification)

/-- Context generated by `Tm.letExact`.  The equality binder is private and
newest; its endpoints are the stable selection of the freshly bound object and
the weakened implementation witness. -/
def extendExact {s : Sig} (context : Ctx s) (label : Name)
    (witness : Source.Ty s) :
    Ctx ((s ▹ .term) ▹ .evidence .equality) :=
  let withObject := context.extendTerm (Source.Ty.exact label witness)
  withObject.extendEquality
    (.sel (.here : BVar (s ▹ .term) .term) label)
    witness.weaken

@[simp]
theorem lookup_here {s : Sig} {kind : BinderKind} (context : Ctx s)
    (binding : Binding s kind) :
    (Ctx.extend context binding).lookup
      (.here : BVar (s ▹ kind) kind) = binding.weaken := rfl

@[simp]
theorem lookup_there {s : Sig} {kind olderKind : BinderKind}
    (context : Ctx s) (binding : Binding s kind)
    (index : BVar s olderKind) :
    (Ctx.extend context binding).lookup (.there index) =
      (context.lookup index).weaken := rfl

@[simp]
theorem lookup_extendTerm_here {s : Sig} (context : Ctx s)
    (type : Source.Ty s) :
    (context.extendTerm type).lookup
      (.here : BVar (s ▹ .term) .term) = (Binding.term type).weaken := rfl

@[simp]
theorem lookup_extendEquality_here {s : Sig} (context : Ctx s)
    (left right : Source.Ty s) :
    (context.extendEquality left right).lookup
      (.here : BVar (s ▹ .evidence .equality) (.evidence .equality)) =
      (Binding.equality left right).weaken := rfl

@[simp]
theorem lookup_extendInclusion_here {s : Sig} (context : Ctx s)
    (source target : Source.Ty s) :
    (context.extendInclusion source target).lookup
      (.here : BVar (s ▹ .evidence .inclusion) (.evidence .inclusion)) =
      (Binding.inclusion source target).weaken := rfl

@[simp]
theorem lookup_extendMember_here {s : Sig} (context : Ctx s)
    (specification : MemberSpec s) :
    (context.extendMember specification).lookup
      (.here : BVar (s ▹ .member) .member) =
      (Binding.member specification).weaken := rfl

end Ctx

end DotFC.Explicit
