import Coercions.ManySortedFC.Erasure

/-!
# Administrative equivalence after erasure

Structural adapters may expose function eta-expansions and administrative
identity lets even though their source and target annotations disappear.
`AdministrativeEq` is the least equivalence and term congruence containing
value eta and monadic let identity. It does not identify arbitrary runtime
reductions or make an observational-equivalence claim.
-/

namespace ManySortedFC.Runtime

/-- Equivalence generated by value eta, monadic let identity, and congruence
for the runtime term constructors.

The weakening in `eta` makes the bound variable fresh by construction. Its
value premise is essential for call-by-value: eta-expanding an arbitrary
computation would otherwise turn divergence into a lambda value. -/
inductive AdministrativeEq : {scope : Nat} -> Tm scope -> Tm scope -> Prop where
  | refl {scope : Nat} {term : Tm scope} : AdministrativeEq term term
  | symm {scope : Nat} {first second : Tm scope}
      (equivalent : AdministrativeEq first second) :
      AdministrativeEq second first
  | trans {scope : Nat} {first second third : Tm scope}
      (firstSecond : AdministrativeEq first second)
      (secondThird : AdministrativeEq second third) :
      AdministrativeEq first third
  | lam {scope : Nat} {first second : Tm (Nat.succ scope)}
      (body : AdministrativeEq first second) :
      AdministrativeEq (.lam first) (.lam second)
  | app {scope : Nat} {firstFunction secondFunction : Tm scope}
      {firstArgument secondArgument : Tm scope}
      (function : AdministrativeEq firstFunction secondFunction)
      (argument : AdministrativeEq firstArgument secondArgument) :
      AdministrativeEq (.app firstFunction firstArgument)
        (.app secondFunction secondArgument)
  | let' {scope : Nat} {firstRhs secondRhs : Tm scope}
      {firstBody secondBody : Tm (Nat.succ scope)}
      (rhs : AdministrativeEq firstRhs secondRhs)
      (body : AdministrativeEq firstBody secondBody) :
      AdministrativeEq (.let' firstRhs firstBody)
        (.let' secondRhs secondBody)
  | letId {scope : Nat} (term : Tm scope) :
      AdministrativeEq (.let' term (.var 0)) term
  | eta {scope : Nat} {term : Tm scope} (termValue : IsValue term) :
      AdministrativeEq
        (.lam (.app term.weaken (.var 0))) term

namespace AdministrativeEq

/-- Administrative equivalence is an equivalence relation at every runtime
scope. -/
theorem equivalence (scope : Nat) :
    Equivalence (@AdministrativeEq scope) :=
  ⟨fun _ => .refl, fun relation => relation.symm,
    fun firstSecond secondThird => firstSecond.trans secondThird⟩

/-- Congruence in only the function position of an application. -/
theorem appFunction {scope : Nat} {first second argument : Tm scope}
    (function : AdministrativeEq first second) :
    AdministrativeEq (.app first argument) (.app second argument) :=
  .app function .refl

/-- Congruence in only the argument position of an application. -/
theorem appArgument {scope : Nat} {function first second : Tm scope}
    (argument : AdministrativeEq first second) :
    AdministrativeEq (.app function first) (.app function second) :=
  .app .refl argument

/-- Congruence in only the right-hand side of a let. -/
theorem letRhs {scope : Nat} {first second : Tm scope}
    {body : Tm (Nat.succ scope)} (rhs : AdministrativeEq first second) :
    AdministrativeEq (.let' first body) (.let' second body) :=
  .let' rhs .refl

/-- Congruence in only the body of a let. -/
theorem letBody {scope : Nat} {rhs : Tm scope}
    {first second : Tm (Nat.succ scope)}
    (body : AdministrativeEq first second) :
    AdministrativeEq (.let' rhs first) (.let' rhs second) :=
  .let' .refl body

end AdministrativeEq

end ManySortedFC.Runtime

namespace ManySortedFC.Adapter

/-- Every structural adapter is transparent up to runtime administrative
equivalence.

Logical casts and identities are literally transparent.  Composition uses
transitivity, quantified adapters use the induction hypothesis directly, and
the function case evaluates the original call into an administrative let, reduces its
domain and codomain adapters under congruence, removes the identity let, and
then applies value eta. -/
theorem erase_admin {scope : Sig} (adapter : Adapter scope)
    {runtimeScope : Nat} (term : Runtime.Tm runtimeScope)
    (termValue : Runtime.IsValue term) :
    Runtime.AdministrativeEq (adapter.erase term) term := by
  induction adapter generalizing runtimeScope with
  | identity =>
      exact .refl
  | cast =>
      exact .refl
  | retagCapture =>
      exact .refl
  | compose first second firstInduction secondInduction =>
      exact
        (secondInduction (first.erase term)
          (first.erase_value termValue)).trans
        (firstInduction term termValue)
  | function domain codomain domainInduction codomainInduction =>
      apply Runtime.AdministrativeEq.trans
      · apply Runtime.AdministrativeEq.lam
        exact Runtime.AdministrativeEq.let'
          .refl (codomainInduction (.var 0) .var)
      · apply Runtime.AdministrativeEq.trans
        · apply Runtime.AdministrativeEq.lam
          exact .letId _
        · apply Runtime.AdministrativeEq.trans
          · apply Runtime.AdministrativeEq.lam
            exact Runtime.AdministrativeEq.appArgument
              (domainInduction (.var 0) .var)
          · exact .eta termValue
  | forallT theory body induction =>
      exact induction term termValue
  | existsT theory payload induction =>
      exact induction term termValue

end ManySortedFC.Adapter
