import Coercions.ManySortedFC.Erasure

/-!
# Administrative equivalence after erasure

Structural adapters may expose function eta-expansions, modal suspension
wrappers, and administrative identity lets even though their source and
target annotations disappear. `AdministrativeEq` is a typed-shape proof
relation: adapter typing supplies the function or modal boundary at which an
eta constructor is used, while the erased runtime value premise preserves
call-by-value timing. That premise alone does not characterize runtime shape;
in particular, `modalEta` must not be read as an untyped contextual-equivalence
law for every runtime value. The relation also contains monadic let identity.
It does not identify arbitrary runtime reductions or make an
observational-equivalence claim.
-/

namespace ManySortedFC.Runtime

/-- Equivalence generated by value eta, monadic let identity, and congruence
for the runtime term constructors.

The weakening in `eta` makes the bound variable fresh by construction. Its
value premise is essential for call-by-value: eta-expanding an arbitrary
computation would otherwise turn divergence into a lambda value. -/
inductive AdministrativeEq : {scope : Nat} -> Tm scope -> Tm scope -> Prop where
  | refl {scope : Nat} {term : Tm scope} : AdministrativeEq term term
  | symm {scope : Nat} {first second : Tm scope}
      (equivalent : AdministrativeEq first second) :
      AdministrativeEq second first
  | trans {scope : Nat} {first second third : Tm scope}
      (firstSecond : AdministrativeEq first second)
      (secondThird : AdministrativeEq second third) :
      AdministrativeEq first third
  | lam {scope : Nat} {first second : Tm (Nat.succ scope)}
      (body : AdministrativeEq first second) :
      AdministrativeEq (.lam first) (.lam second)
  | app {scope : Nat} {firstFunction secondFunction : Tm scope}
      {firstArgument secondArgument : Tm scope}
      (function : AdministrativeEq firstFunction secondFunction)
      (argument : AdministrativeEq firstArgument secondArgument) :
      AdministrativeEq (.app firstFunction firstArgument)
        (.app secondFunction secondArgument)
  | let' {scope : Nat} {firstRhs secondRhs : Tm scope}
      {firstBody secondBody : Tm (Nat.succ scope)}
      (rhs : AdministrativeEq firstRhs secondRhs)
      (body : AdministrativeEq firstBody secondBody) :
      AdministrativeEq (.let' firstRhs firstBody)
        (.let' secondRhs secondBody)
  | suspend {scope : Nat} {first second : Tm scope}
      (body : AdministrativeEq first second) :
      AdministrativeEq (.suspend first) (.suspend second)
  | force {scope : Nat} {first second : Tm scope}
      (suspension : AdministrativeEq first second) :
      AdministrativeEq (.force first) (.force second)
  | letId {scope : Nat} (term : Tm scope) :
      AdministrativeEq (.let' term (.var 0)) term
  | eta {scope : Nat} {term : Tm scope} (termValue : IsValue term) :
      AdministrativeEq
        (.lam (.app term.weaken (.var 0))) term
  /-- Typed modal eta.  Like function `eta`, this erased-only rule is used
  through a statically typed adapter: its value premise represents a source
  modal value at that boundary, not an untyped claim that every runtime value
  can be forced. -/
  | modalEta {scope : Nat} {term : Tm scope} (termValue : IsValue term) :
      AdministrativeEq
        (.suspend (.let' (.force term) (.var 0))) term

namespace AdministrativeEq

/-- Administrative equivalence is an equivalence relation at every runtime
scope. -/
theorem equivalence (scope : Nat) :
    Equivalence (@AdministrativeEq scope) :=
  ⟨fun _ => .refl, fun relation => relation.symm,
    fun firstSecond secondThird => firstSecond.trans secondThird⟩

/-- Congruence in only the function position of an application. -/
theorem appFunction {scope : Nat} {first second argument : Tm scope}
    (function : AdministrativeEq first second) :
    AdministrativeEq (.app first argument) (.app second argument) :=
  .app function .refl

/-- Congruence in only the argument position of an application. -/
theorem appArgument {scope : Nat} {function first second : Tm scope}
    (argument : AdministrativeEq first second) :
    AdministrativeEq (.app function first) (.app function second) :=
  .app .refl argument

/-- Congruence in only the right-hand side of a let. -/
theorem letRhs {scope : Nat} {first second : Tm scope}
    {body : Tm (Nat.succ scope)} (rhs : AdministrativeEq first second) :
    AdministrativeEq (.let' first body) (.let' second body) :=
  .let' rhs .refl

/-- Congruence in only the body of a let. -/
theorem letBody {scope : Nat} {rhs : Tm scope}
    {first second : Tm (Nat.succ scope)}
    (body : AdministrativeEq first second) :
    AdministrativeEq (.let' rhs first) (.let' rhs second) :=
  .let' .refl body

/-- Congruence under a runtime suspension. -/
theorem suspendBody {scope : Nat} {first second : Tm scope}
    (body : AdministrativeEq first second) :
    AdministrativeEq (.suspend first) (.suspend second) :=
  .suspend body

/-- Congruence in the suspension-producing operand of `force`. -/
theorem forceSuspension {scope : Nat} {first second : Tm scope}
    (suspension : AdministrativeEq first second) :
    AdministrativeEq (.force first) (.force second) :=
  .force suspension

end AdministrativeEq

end ManySortedFC.Runtime

namespace ManySortedFC.Adapter

/-- Every structural adapter is transparent up to runtime administrative
equivalence.

Logical casts and identities are literally transparent.  Composition uses
transitivity, quantified adapters use the induction hypothesis directly, and
the function case evaluates the original call into an administrative let, reduces its
domain and codomain adapters under congruence, removes the identity let, and
then applies value eta. -/
theorem erase_admin {scope : Sig} (adapter : Adapter scope)
    {runtimeScope : Nat} (term : Runtime.Tm runtimeScope)
    (termValue : Runtime.IsValue term) :
    Runtime.AdministrativeEq (adapter.erase term) term := by
  induction adapter generalizing runtimeScope with
  | identity =>
      exact .refl
  | cast =>
      exact .refl
  | retagCapture =>
      exact .refl
  | forgetEmptyCapture =>
      exact .refl
  | captured captures shape induction =>
      exact induction term termValue
  | compose first second firstInduction secondInduction =>
      exact
        (secondInduction (first.erase term)
          (first.erase_value termValue)).trans
        (firstInduction term termValue)
  | function domain codomain domainInduction codomainInduction =>
      apply Runtime.AdministrativeEq.trans
      · apply Runtime.AdministrativeEq.lam
        exact Runtime.AdministrativeEq.let'
          .refl (codomainInduction (.var 0) .var)
      · apply Runtime.AdministrativeEq.trans
        · apply Runtime.AdministrativeEq.lam
          exact .letId _
        · apply Runtime.AdministrativeEq.trans
          · apply Runtime.AdministrativeEq.lam
            exact Runtime.AdministrativeEq.appArgument
              (domainInduction (.var 0) .var)
          · exact .eta termValue
  | modal sourceRequirements targetRequirements requirements result
      induction =>
      apply Runtime.AdministrativeEq.trans
      · apply Runtime.AdministrativeEq.suspend
        exact Runtime.AdministrativeEq.let' .refl
          (induction (.var 0) .var)
      · exact .modalEta termValue
  | forallT theory body induction =>
      exact induction term termValue
  | existsT theory payload induction =>
      exact induction term termValue
  | forallMorphism sourceTheory targetTheory constraints body induction =>
      exact induction term termValue
  | existsMorphism sourceTheory targetTheory constraints payload induction =>
      exact induction term termValue

end ManySortedFC.Adapter
