import Coercions.ManySortedFC.ModalPreservation
import Coercions.ManySortedFC.TermChecker

/-!
# Primitive modal beta preservation regression

The outer lock below generates a `ReadOnly {}` evidence binder.  Its body uses
that generated variable to unlock a second suspension.  Modal beta replaces
the variable with evidence checked in the outer context, and the resulting
`Tm.use` retains the outer lock's capture certificate.
-/

namespace ManySortedFC.ModalPreservationExamples

def readOnlyEmptyRequirements {scope : Sig} :
    ModalContext 0 [.readOnly] scope :=
  .mk .nil (.cons .nil .empty)

def readOnlyEmptyEvidence {scope : Sig} :
    EvidenceArgs scope [.mode .readOnly] :=
  .cons (.modeEmpty .readOnly) .nil

abbrev OuterBodyScope : Sig := ModalScope [] 0 [.readOnly]

def outerBodyContext : Ctx OuterBodyScope :=
  Ctx.nil.extendModal readOnlyEmptyRequirements

/-- This argument is the evidence variable generated by the outer lock. -/
def generatedReadOnlyEvidence :
    EvidenceArgs OuterBodyScope [.mode .readOnly] :=
  .cons (.var .here) .nil

def innerLock : Tm OuterBodyScope :=
  .lock readOnlyEmptyRequirements .one .empty .unit
    (.captureEmpty .empty)

/-- The inner unlock deliberately supplies the outer lock's generated mode
assumption, exercising evidence-variable substitution at modal beta. -/
def outerBody : Tm OuterBodyScope :=
  .unlock readOnlyEmptyRequirements innerLock generatedReadOnlyEvidence

def outerCaptureCertificate :
    Evidence (.inclusion .capture) OuterBodyScope :=
  .captureEmpty .empty

def outerLock : Tm [] :=
  .lock readOnlyEmptyRequirements .one .empty outerBody
    outerCaptureCertificate

def outerRedex : Tm [] :=
  .unlock readOnlyEmptyRequirements outerLock readOnlyEmptyEvidence

def outerReduct : Tm [] :=
  .use (outerBody.instantiateModal readOnlyEmptyEvidence)
    (outerCaptureCertificate.substitute
      (TermStaticSubst.fromEvidenceArgs TermStaticSubst.id
        readOnlyEmptyEvidence))

theorem generated_evidence_is_consumed_by_inner_unlock :
    outerBody.instantiateModal readOnlyEmptyEvidence =
      .unlock readOnlyEmptyRequirements
        (.lock readOnlyEmptyRequirements .one .empty .unit
          (.captureEmpty .empty))
        readOnlyEmptyEvidence := rfl

theorem nested_modal_redex_is_accepted :
    Tm.synth Ctx.nil outerRedex = some (.empty, .one) := by
  native_decide

theorem nested_modal_reduct_is_accepted :
    Tm.synth Ctx.nil outerReduct = some (.empty, .one) := by
  native_decide

def outerRedexTyping : Tm.HasType Ctx.nil outerRedex .empty .one :=
  (Tm.check Ctx.nil outerRedex).get (by native_decide) |>.typing

/-- The concrete generated-evidence beta step uses the generic exact-index
subject-reduction theorem. -/
noncomputable def outerReductTyping :
    Tm.HasType Ctx.nil outerReduct .empty .one :=
  Tm.HasType.modalBeta_subjectReduction outerRedexTyping

theorem nested_modal_beta :
    Tm.ModalStep (fun {_} _ _ => False) outerRedex outerReduct :=
  .beta

theorem nested_modal_beta_erases_to_force_beta :
    Runtime.Step outerRedex.erase outerReduct.erase :=
  Tm.ModalStep.erase_beta

end ManySortedFC.ModalPreservationExamples
