import Coercions.ManySortedFC.TheoryModel

/-!
# Primitive modal-context metatheory

This module records the canonical shape of the theory generated by a
CoreCapybara modal context.  Mode obligations precede pairwise separation
obligations.  Positions, rather than capture equality, identify entries in a
separation list, so repeated captures still generate an obligation.
-/

namespace ManySortedFC

/-! ## Relation shape and size -/

/-- The number of unordered pairs of positions in a list of this length. -/
def separationPairCount : Nat → Nat
  | 0 => 0
  | count + 1 => count + separationPairCount count

@[simp]
theorem separationRelations_length (count : Nat) :
    (separationRelations count).length = separationPairCount count := by
  induction count with
  | zero => rfl
  | succ count induction =>
      simp [separationRelations, separationPairCount, induction]

@[simp]
theorem modeRelations_eq_map (modes : List CaptureMode) :
    modeRelations modes = modes.map Relation.mode := by
  induction modes with
  | nil => rfl
  | cons mode modes induction =>
      simp [modeRelations, induction]

@[simp]
theorem modeRelations_length (modes : List CaptureMode) :
    (modeRelations modes).length = modes.length := by
  simp

@[simp]
theorem modalRelations_length (count : Nat) (modes : List CaptureMode) :
    (modalRelations count modes).length =
      modes.length + separationPairCount count := by
  simp [modalRelations]

/-- The canonical order is all unary mode obligations followed by all
pairwise separation obligations. -/
theorem modalRelations_mode_then_separate (count : Nat)
    (modes : List CaptureMode) :
    modalRelations count modes =
      modeRelations modes ++ separationRelations count := rfl

theorem separationRelations_only_separate {count : Nat} {relation : Relation}
    (membership : relation ∈ separationRelations count) :
    relation = .separate := by
  induction count with
  | zero => simp [separationRelations] at membership
  | succ count induction =>
      simp only [separationRelations, List.mem_append,
        List.mem_replicate] at membership
      cases membership with
      | inl replicated => exact replicated.2
      | inr older => exact induction older

theorem modeRelations_only_mode {modes : List CaptureMode}
    {relation : Relation} (membership : relation ∈ modeRelations modes) :
    ∃ mode, relation = .mode mode := by
  induction modes with
  | nil => simp [modeRelations] at membership
  | cons mode modes induction =>
      simp only [modeRelations, List.mem_cons] at membership
      cases membership with
      | inl newest => exact ⟨mode, newest⟩
      | inr older => exact induction older

/-- Modal theories contain only mode and separation relations. -/
theorem modalRelations_shape {count : Nat} {modes : List CaptureMode}
    {relation : Relation} (membership : relation ∈ modalRelations count modes) :
    (∃ mode, relation = .mode mode) ∨ relation = .separate := by
  simp only [modalRelations, List.mem_append] at membership
  cases membership with
  | inl mode => exact .inl (modeRelations_only_mode mode)
  | inr separate =>
      exact .inr (separationRelations_only_separate separate)

theorem modalRelations_ne_disjoint (count : Nat) (modes : List CaptureMode) :
    Relation.disjoint ∉ modalRelations count modes := by
  intro membership
  cases modalRelations_shape membership with
  | inl mode =>
      obtain ⟨_, equality⟩ := mode
      cases equality
  | inr equality => cases equality

theorem modalRelations_ne_equality (count : Nat) (modes : List CaptureMode)
    (sort : StaticSort) :
    Relation.equality sort ∉ modalRelations count modes := by
  intro membership
  cases modalRelations_shape membership with
  | inl mode =>
      obtain ⟨_, equality⟩ := mode
      cases equality
  | inr equality => cases equality

theorem modalRelations_ne_inclusion (count : Nat) (modes : List CaptureMode)
    (sort : StaticSort) :
    Relation.inclusion sort ∉ modalRelations count modes := by
  intro membership
  cases modalRelations_shape membership with
  | inl mode =>
      obtain ⟨_, equality⟩ := mode
      cases equality
  | inr equality => cases equality

/-! ## Proposition membership -/

/-- An exact proposition occurs at some position in a theory. -/
inductive Theory.Contains {scope : Sig} {symbols : List StaticSort}
    {relation : Relation}
    (proposition : Proposition relation (SymbolScope scope symbols)) :
    {relations : List Relation} → Theory scope symbols relations → Prop where
  | here {relations : List Relation}
      {rest : Theory scope symbols relations} :
      Theory.Contains proposition (.cons proposition rest)
  | there {newestRelation : Relation} {relations : List Relation}
      {newest : Proposition newestRelation (SymbolScope scope symbols)}
      {rest : Theory scope symbols relations}
      (membership : Theory.Contains proposition rest) :
      Theory.Contains proposition (.cons newest rest)

namespace Theory.Contains

theorem append_left {scope : Sig} {symbols : List StaticSort}
    {relation : Relation}
    {proposition : Proposition relation (SymbolScope scope symbols)}
    {first second : List Relation}
    {left : Theory scope symbols first} {right : Theory scope symbols second}
    (membership : Theory.Contains proposition left) :
    Theory.Contains proposition (Theory.append left right) := by
  induction membership with
  | here => exact .here
  | there membership induction => exact .there induction

def append_right {scope : Sig} {symbols : List StaticSort}
    {relation : Relation}
    {proposition : Proposition relation (SymbolScope scope symbols)}
    {first second : List Relation}
    (left : Theory scope symbols first) {right : Theory scope symbols second}
    (membership : Theory.Contains proposition right) :
    Theory.Contains proposition (Theory.append left right) :=
  match left with
  | .nil => membership
  | .cons _ rest => .there (append_right rest membership)

end Theory.Contains

/-! ## Positional pair coverage -/

/-- A position in a separation list.  Its proof distinguishes duplicate
capture expressions occurring at different positions. -/
inductive SeparationPosition {scope : Sig} :
    {count : Nat} → SeparationContext count scope → Type where
  | here {count : Nat} {rest : SeparationContext count scope}
      {capture : Capture scope} :
      SeparationPosition (.cons rest capture)
  | there {count : Nat} {rest : SeparationContext count scope}
      {capture : Capture scope} :
      SeparationPosition rest → SeparationPosition (.cons rest capture)

namespace SeparationPosition

/-- The capture stored at a positional reference. -/
def capture {scope : Sig} {count : Nat}
    {context : SeparationContext count scope} :
    SeparationPosition context → Capture scope
  | @here _ _ _ capture => capture
  | there position => position.capture

/-- Canonical newest-before-older order on separation-list positions. -/
inductive Before {scope : Sig} : {count : Nat} →
    {context : SeparationContext count scope} →
    SeparationPosition context → SeparationPosition context → Prop where
  | here_there {count : Nat} {rest : SeparationContext count scope}
      {capture : Capture scope} (older : SeparationPosition rest) :
      Before (context := .cons rest capture) .here (.there older)
  | there {count : Nat} {rest : SeparationContext count scope}
      {capture : Capture scope} {left right : SeparationPosition rest}
      (before : Before left right) :
      Before (context := .cons rest capture) (.there left) (.there right)

theorem before_irrefl {scope : Sig} {count : Nat}
    {context : SeparationContext count scope}
    (position : SeparationPosition context) : ¬ Before position position := by
  induction position with
  | here => intro before; cases before
  | there position induction =>
      intro before
      cases before with
      | there before => exact induction before

theorem distinct_comparable {scope : Sig} {count : Nat}
    {context : SeparationContext count scope}
    (left right : SeparationPosition context) (distinct : left ≠ right) :
    Before left right ∨ Before right left := by
  induction left with
  | @here count rest capture =>
      cases right with
      | here => exact False.elim (distinct rfl)
      | there older => exact .inl (.here_there older)
  | @there count rest capture left induction =>
      cases right with
      | here => exact .inr (.here_there left)
      | there right =>
          have tailDistinct : left ≠ right := by
            intro equality
            exact distinct (by cases equality; rfl)
          cases induction right tailDistinct with
          | inl before => exact .inl (.there before)
          | inr before => exact .inr (.there before)

/-- Every canonical ordered pair is emitted as its exact `Separate`
proposition by separation-context elaboration. -/
theorem covered_by_toTheory {scope : Sig} {count : Nat}
    {context : SeparationContext count scope}
    {left right : SeparationPosition context}
    (before : Before left right) :
    Theory.Contains (symbols := [])
      (.separate left.capture right.capture) context.toTheory := by
  induction before with
  | @here_there count rest capture older =>
      apply Theory.Contains.append_left
      induction older with
      | here => exact .here
      | there older induction => exact .there induction
  | @there count rest capture left right before induction =>
      exact Theory.Contains.append_right (SeparationContext.against capture rest)
        induction

/-- Any two distinct positions generate a separation proposition, in the
canonical orientation determined by their list order. -/
theorem distinct_covered_by_toTheory {scope : Sig} {count : Nat}
    {context : SeparationContext count scope}
    (left right : SeparationPosition context) (distinct : left ≠ right) :
    Theory.Contains (symbols := [])
        (.separate left.capture right.capture) context.toTheory ∨
      Theory.Contains (symbols := [])
        (.separate right.capture left.capture)
        context.toTheory := by
  cases distinct_comparable left right distinct with
  | inl before => exact .inl (covered_by_toTheory before)
  | inr before => exact .inr (covered_by_toTheory before)

end SeparationPosition

namespace ModalContext

/-- The precise external satisfaction obligation for opening a modal lock. -/
abbrev SatisfiedBy {scope : Sig} (ambient : Ctx scope)
    {separationCount : Nat} {modes : List CaptureMode}
    (requirements : ModalContext separationCount modes scope)
    (evidence : EvidenceArgs scope (modalRelations separationCount modes)) :
    Type :=
  Theory.SatisfiedBy ambient (.nil : SymbolArgs scope [])
    requirements.toTheory evidence

/-- Pairwise separation obligations remain present after the mode prefix in
the complete modal theory. -/
theorem separation_covered_by_toTheory {scope : Sig}
    {separationCount : Nat} {modes : List CaptureMode}
    (requirements : ModalContext separationCount modes scope)
    {left right : SeparationPosition (match requirements with
      | .mk separation _ => separation)}
    (before : SeparationPosition.Before left right) :
    Theory.Contains (symbols := [])
      (.separate left.capture right.capture)
      requirements.toTheory := by
  cases requirements with
  | mk separation mode =>
      exact Theory.Contains.append_right mode.toTheory
        (SeparationPosition.covered_by_toTheory before)

/-- Every two distinct separation-list positions occur in the complete modal
theory, regardless of whether their capture expressions are syntactically
equal. -/
theorem distinct_separation_covered_by_toTheory {scope : Sig}
    {separationCount : Nat} {modes : List CaptureMode}
    (requirements : ModalContext separationCount modes scope)
    (left right : SeparationPosition (match requirements with
      | .mk separation _ => separation))
    (distinct : left ≠ right) :
    Theory.Contains (symbols := [])
        (.separate left.capture right.capture) requirements.toTheory ∨
      Theory.Contains (symbols := [])
        (.separate right.capture left.capture) requirements.toTheory := by
  cases requirements with
  | mk separation mode =>
      cases SeparationPosition.distinct_covered_by_toTheory
          left right distinct with
      | inl forward =>
          exact .inl (Theory.Contains.append_right mode.toTheory forward)
      | inr backward =>
          exact .inr (Theory.Contains.append_right mode.toTheory backward)

end ModalContext

/-! ## Naturality -/

namespace Theory

private def append_rename_go {source target : Sig}
    {symbols : List StaticSort}
    {first second : List Relation}
    (left : Theory source symbols first) (right : Theory source symbols second)
    (rho : Rename source target) :
    (Theory.append left right).rename rho =
      Theory.append (left.rename rho) (right.rename rho) :=
  match left with
  | .nil => rfl
  | .cons _ rest => by
      simp only [Theory.append, Theory.rename]
      rw [append_rename_go rest right rho]

theorem append_rename {source target : Sig} {symbols : List StaticSort}
    {first second : List Relation}
    (left : Theory source symbols first) (right : Theory source symbols second)
    (rho : Rename source target) :
    (Theory.append left right).rename rho =
      Theory.append (left.rename rho) (right.rename rho) :=
  append_rename_go left right rho

private def append_substitute_go {source target : Sig}
    {symbols : List StaticSort}
    {first second : List Relation}
    (left : Theory source symbols first) (right : Theory source symbols second)
    (substitution : StaticSubst source target) :
    (Theory.append left right).substitute substitution =
      Theory.append (left.substitute substitution)
        (right.substitute substitution) :=
  match left with
  | .nil => rfl
  | .cons _ rest => by
      simp only [Theory.append, Theory.substitute]
      rw [append_substitute_go rest right substitution]

theorem append_substitute {source target : Sig}
    {symbols : List StaticSort} {first second : List Relation}
    (left : Theory source symbols first) (right : Theory source symbols second)
    (substitution : StaticSubst source target) :
    (Theory.append left right).substitute substitution =
      Theory.append (left.substitute substitution)
        (right.substitute substitution) :=
  append_substitute_go left right substitution

end Theory

namespace SeparationContext

private def against_rename_go {source target : Sig} (head : Capture source)
    {count : Nat} (context : SeparationContext count source)
    (rho : Rename source target) :
    (against head context).rename rho =
      against (head.rename rho) (context.rename rho) :=
  match context with
  | .nil => rfl
  | .cons rest _ => by
      simp only [against, Theory.rename, SeparationContext.rename,
        Proposition.rename, Rename.liftSymbols, symbolKinds,
        Rename.liftMany]
      rw [against_rename_go head rest rho]
      rfl

theorem against_rename {source target : Sig} (head : Capture source)
    {count : Nat} (context : SeparationContext count source)
    (rho : Rename source target) :
    (against head context).rename rho =
      against (head.rename rho) (context.rename rho) :=
  against_rename_go head context rho

private def toTheory_rename_go {source target : Sig} {count : Nat}
    (context : SeparationContext count source) (rho : Rename source target) :
    (context.toTheory).rename rho = (context.rename rho).toTheory :=
  match context with
  | .nil => rfl
  | .cons rest capture => by
      simp only [toTheory, SeparationContext.rename]
      calc
        (Theory.append (against capture rest) rest.toTheory).rename rho =
            Theory.append ((against capture rest).rename rho)
              (rest.toTheory.rename rho) :=
          Theory.append_rename _ _ _
        _ = Theory.append
              (against (capture.rename rho) (rest.rename rho))
              (rest.rename rho).toTheory := by
          rw [against_rename, toTheory_rename_go]

theorem toTheory_rename {source target : Sig} {count : Nat}
    (context : SeparationContext count source) (rho : Rename source target) :
    context.toTheory.rename rho = (context.rename rho).toTheory :=
  toTheory_rename_go context rho

private def against_substitute_go {source target : Sig}
    (head : Capture source)
    {count : Nat} (context : SeparationContext count source)
    (substitution : StaticSubst source target) :
    (against head context).substitute substitution =
      against (head.substitute substitution)
        (context.substitute substitution) :=
  match context with
  | .nil => rfl
  | .cons rest _ => by
      simp only [against, Theory.substitute, SeparationContext.substitute,
        Proposition.substitute, StaticSubst.liftSymbols, symbolKinds,
        StaticSubst.liftMany]
      rw [against_substitute_go head rest substitution]
      rfl

theorem against_substitute {source target : Sig} (head : Capture source)
    {count : Nat} (context : SeparationContext count source)
    (substitution : StaticSubst source target) :
    (against head context).substitute substitution =
      against (head.substitute substitution)
        (context.substitute substitution) :=
  against_substitute_go head context substitution

private def toTheory_substitute_go {source target : Sig} {count : Nat}
    (context : SeparationContext count source)
    (substitution : StaticSubst source target) :
    context.toTheory.substitute substitution =
      (context.substitute substitution).toTheory :=
  match context with
  | .nil => rfl
  | .cons rest capture => by
      simp only [toTheory, SeparationContext.substitute]
      calc
        (Theory.append (against capture rest) rest.toTheory).substitute
            substitution =
          Theory.append ((against capture rest).substitute substitution)
            (rest.toTheory.substitute substitution) :=
          Theory.append_substitute _ _ _
        _ = Theory.append
              (against (capture.substitute substitution)
                (rest.substitute substitution))
              (rest.substitute substitution).toTheory := by
          rw [against_substitute, toTheory_substitute_go]

theorem toTheory_substitute {source target : Sig} {count : Nat}
    (context : SeparationContext count source)
    (substitution : StaticSubst source target) :
    context.toTheory.substitute substitution =
      (context.substitute substitution).toTheory :=
  toTheory_substitute_go context substitution

end SeparationContext

namespace ModeContext

private def toTheory_rename_go {source target : Sig}
    {modes : List CaptureMode}
    (context : ModeContext modes source) (rho : Rename source target) :
    context.toTheory.rename rho = (context.rename rho).toTheory :=
  match context with
  | .nil => rfl
  | .cons rest _ => by
      simp only [toTheory, Theory.rename, ModeContext.rename,
        Proposition.rename, Rename.liftSymbols, symbolKinds,
        Rename.liftMany]
      rw [toTheory_rename_go rest rho]
      rfl

theorem toTheory_rename {source target : Sig} {modes : List CaptureMode}
    (context : ModeContext modes source) (rho : Rename source target) :
    context.toTheory.rename rho = (context.rename rho).toTheory :=
  toTheory_rename_go context rho

private def toTheory_substitute_go {source target : Sig}
    {modes : List CaptureMode} (context : ModeContext modes source)
    (substitution : StaticSubst source target) :
    context.toTheory.substitute substitution =
      (context.substitute substitution).toTheory :=
  match context with
  | .nil => rfl
  | .cons rest _ => by
      simp only [toTheory, Theory.substitute, ModeContext.substitute,
        Proposition.substitute, StaticSubst.liftSymbols, symbolKinds,
        StaticSubst.liftMany]
      rw [toTheory_substitute_go rest substitution]
      rfl

theorem toTheory_substitute {source target : Sig}
    {modes : List CaptureMode} (context : ModeContext modes source)
    (substitution : StaticSubst source target) :
    context.toTheory.substitute substitution =
      (context.substitute substitution).toTheory :=
  toTheory_substitute_go context substitution

end ModeContext

namespace ModalContext

@[simp]
theorem toTheory_rename {source target : Sig} {separationCount : Nat}
    {modes : List CaptureMode}
    (context : ModalContext separationCount modes source)
    (rho : Rename source target) :
    context.toTheory.rename rho = (context.rename rho).toTheory := by
  cases context with
  | mk separation mode =>
      simp only [ModalContext.toTheory, ModalContext.rename]
      calc
        (Theory.append mode.toTheory separation.toTheory).rename rho =
            Theory.append (mode.toTheory.rename rho)
              (separation.toTheory.rename rho) :=
          Theory.append_rename _ _ _
        _ = Theory.append (mode.rename rho).toTheory
              (separation.rename rho).toTheory := by
          rw [ModeContext.toTheory_rename,
            SeparationContext.toTheory_rename]

@[simp]
theorem toTheory_substitute {source target : Sig}
    {separationCount : Nat} {modes : List CaptureMode}
    (context : ModalContext separationCount modes source)
    (substitution : StaticSubst source target) :
    context.toTheory.substitute substitution =
      (context.substitute substitution).toTheory := by
  cases context with
  | mk separation mode =>
      simp only [ModalContext.toTheory, ModalContext.substitute]
      calc
        (Theory.append mode.toTheory separation.toTheory).substitute
            substitution =
          Theory.append (mode.toTheory.substitute substitution)
            (separation.toTheory.substitute substitution) :=
          Theory.append_substitute _ _ _
        _ = Theory.append (mode.substitute substitution).toTheory
              (separation.substitute substitution).toTheory := by
          rw [ModeContext.toTheory_substitute,
            SeparationContext.toTheory_substitute]

end ModalContext

end ManySortedFC
