import Coercions.ManySortedFC.Scope
import Coercions.ManySortedFC.Classifier.Kind

/-!
# Static syntax for many-sorted FC

The initial target has two static sorts.  Type expressions and capture
expressions are intrinsically separated, while `StaticExpr` exposes the small
uniform interface needed by heterogeneous theories.  A theory allocates all
of its symbols before any evidence binder: its propositions therefore see the
complete symbol block but cannot refer to evidence exported by that same
theory.

Capture expressions deliberately have no top element.  An omitted capture
upper bound is represented by omitting a proposition from a theory, not by a
distinguished capture expression.
-/

namespace ManySortedFC

/-- Binder kinds contributed by a heterogeneous block of static symbols. -/
def symbolKinds : List StaticSort → Sig
  | [] => []
  | sort :: rest => .symbol sort :: symbolKinds rest

/-- Binder kinds contributed by a heterogeneous block of propositions. -/
def evidenceKinds : List Relation → Sig
  | [] => []
  | relation :: rest => .evidence relation :: evidenceKinds rest

/-- Scope after all symbols of a names-first theory have been allocated. -/
@[reducible]
def SymbolScope (scope : Sig) (symbols : List StaticSort) : Sig :=
  Sig.extendMany scope (symbolKinds symbols)

/-- Scope after both the symbol and evidence blocks of a theory. -/
@[reducible]
def StaticScope (scope : Sig) (symbols : List StaticSort)
    (relations : List Relation) : Sig :=
  Sig.extendMany (SymbolScope scope symbols) (evidenceKinds relations)

/-! ## Primitive modal contexts

CoreCapybara modal contexts have two independent components.  A separation
context is a list of captures and contributes one `Separate` obligation for
every pair of distinct list positions.  A mode context is a list of captures
tagged with their required access mode.  The relation shape depends only on
the number of separation entries and the list of mode tags, so renaming and
substitution preserve the modal scope definitionally. -/

/-- Relations generated by a separation list of the given length. -/
def separationRelations : Nat → List Relation
  | 0 => []
  | count + 1 => List.replicate count .separate ++
      separationRelations count

/-- Relations generated by the entries of a mode context. -/
def modeRelations : List CaptureMode → List Relation
  | [] => []
  | mode :: modes => .mode mode :: modeRelations modes

/-- Canonical proof-binder shape of a modal context. -/
def modalRelations (separationCount : Nat) (modes : List CaptureMode) :
    List Relation :=
  modeRelations modes ++ separationRelations separationCount

/-- Scope available while checking a suspended modal body. -/
@[reducible]
def ModalScope (scope : Sig) (separationCount : Nat)
    (modes : List CaptureMode) : Sig :=
  Sig.extendMany scope (evidenceKinds (modalRelations separationCount modes))

namespace Rename

/-- Lift below a heterogeneous block of static symbols. -/
def liftSymbols {source target : Sig} (rho : Rename source target)
    (symbols : List StaticSort) :
    Rename (SymbolScope source symbols) (SymbolScope target symbols) :=
  rho.liftMany (symbolKinds symbols)

/-- Lift below the evidence block of a theory. -/
def liftEvidence {source target : Sig} (rho : Rename source target)
    (relations : List Relation) :
    Rename (Sig.extendMany source (evidenceKinds relations))
      (Sig.extendMany target (evidenceKinds relations)) :=
  rho.liftMany (evidenceKinds relations)

/-- Lift below a complete names-first theory. -/
def liftStatic {source target : Sig} (rho : Rename source target)
    (symbols : List StaticSort) (relations : List Relation) :
    Rename (StaticScope source symbols relations)
      (StaticScope target symbols relations) :=
  (rho.liftSymbols symbols).liftEvidence relations

/-- Lift below the proof-only assumptions contributed by a modal lock. -/
def liftModal {source target : Sig} (rho : Rename source target)
    (separationCount : Nat) (modes : List CaptureMode) :
    Rename (ModalScope source separationCount modes)
      (ModalScope target separationCount modes) :=
  rho.liftEvidence (modalRelations separationCount modes)

/-- Weaken an ambient scope below a heterogeneous binder block. -/
def weakenMany (scope : Sig) : (kinds : Sig) →
    Rename scope (Sig.extendMany scope kinds)
  | [] => id
  | kind :: rest => (weakenMany scope rest).comp (succ (kind := kind))

/-- Weaken an ambient scope below a heterogeneous symbol block. -/
def weakenSymbols {scope : Sig} (symbols : List StaticSort) :
    Rename scope (SymbolScope scope symbols) :=
  weakenMany scope (symbolKinds symbols)

/-- Weaken an ambient scope below a complete theory. -/
def weakenStatic {scope : Sig} (symbols : List StaticSort)
    (relations : List Relation) :
    Rename scope (StaticScope scope symbols relations) :=
  (weakenSymbols symbols).comp
    (weakenMany (SymbolScope scope symbols) (evidenceKinds relations))

/-- Weaken an ambient scope below a primitive modal lock. -/
def weakenModal (scope : Sig) (separationCount : Nat)
    (modes : List CaptureMode) :
    Rename scope (ModalScope scope separationCount modes) :=
  weakenMany scope
    (evidenceKinds (modalRelations separationCount modes))

@[simp]
theorem liftSymbols_id {scope : Sig} (symbols : List StaticSort) :
    (id (scope := scope)).liftSymbols symbols = id := by
  unfold liftSymbols
  exact liftMany_id _

@[simp]
theorem liftEvidence_id {scope : Sig} (relations : List Relation) :
    (id (scope := scope)).liftEvidence relations = id := by
  unfold liftEvidence
  exact liftMany_id _

@[simp]
theorem liftStatic_id {scope : Sig} (symbols : List StaticSort)
    (relations : List Relation) :
    (id (scope := scope)).liftStatic symbols relations = id := by
  unfold liftStatic
  simp

theorem liftSymbols_comp {first second third : Sig}
    (rho₁ : Rename first second) (rho₂ : Rename second third)
    (symbols : List StaticSort) :
    (rho₁.comp rho₂).liftSymbols symbols =
      (rho₁.liftSymbols symbols).comp (rho₂.liftSymbols symbols) := by
  unfold liftSymbols
  exact liftMany_comp _ _ _

theorem liftEvidence_comp {first second third : Sig}
    (rho₁ : Rename first second) (rho₂ : Rename second third)
    (relations : List Relation) :
    (rho₁.comp rho₂).liftEvidence relations =
      (rho₁.liftEvidence relations).comp (rho₂.liftEvidence relations) := by
  unfold liftEvidence
  exact liftMany_comp _ _ _

theorem liftStatic_comp {first second third : Sig}
    (rho₁ : Rename first second) (rho₂ : Rename second third)
    (symbols : List StaticSort) (relations : List Relation) :
    (rho₁.comp rho₂).liftStatic symbols relations =
      (rho₁.liftStatic symbols relations).comp
        (rho₂.liftStatic symbols relations) := by
  unfold liftStatic
  rw [liftSymbols_comp, liftEvidence_comp]

@[simp]
theorem liftModal_id {scope : Sig} (separationCount : Nat)
    (modes : List CaptureMode) :
    (id (scope := scope)).liftModal separationCount modes = id := by
  unfold liftModal
  simp

theorem liftModal_comp {first second third : Sig}
    (rho₁ : Rename first second) (rho₂ : Rename second third)
    (separationCount : Nat) (modes : List CaptureMode) :
    (rho₁.comp rho₂).liftModal separationCount modes =
      (rho₁.liftModal separationCount modes).comp
        (rho₂.liftModal separationCount modes) := by
  unfold liftModal
  exact liftEvidence_comp _ _ _

end Rename

/-- Capture expressions.  `singleton` denotes an ordinary term capability;
`cvar` denotes an abstract capture symbol. -/
inductive Capture : Sig → Type where
  | empty {scope : Sig} : Capture scope
  | union {scope : Sig} (left right : Capture scope) : Capture scope
  /-- A read-only view of the same capabilities.  It changes access mode, not
  capability identity. -/
  | readOnly {scope : Sig} (capture : Capture scope) : Capture scope
  | singleton {scope : Sig} (capability : BVar scope .term) : Capture scope
  | cvar {scope : Sig}
      (name : BVar scope (.symbol .capture)) : Capture scope
  /-- Restrict a capture to capabilities whose closed classifier belongs to
  `kind`.  Classifier kinds are ground filters, not a third bindable static
  sort. -/
  | project {scope : Sig} (capture : Capture scope)
      (kind : Classifier.Kind) : Capture scope

/-- Captures whose distinct list positions must be separated while a modal
body is checked.  Repeated captures remain distinct entries. -/
inductive SeparationContext : Nat → Sig → Type where
  | nil {scope : Sig} : SeparationContext 0 scope
  | cons {scope : Sig} {count : Nat}
      (rest : SeparationContext count scope) (capture : Capture scope) :
      SeparationContext (count + 1) scope

/-- Capture-mode obligations made available under a modal lock.  The mode
list is an intrinsic index so it is stable under renaming. -/
inductive ModeContext : List CaptureMode → Sig → Type where
  | nil {scope : Sig} : ModeContext [] scope
  | cons {scope : Sig} {modes : List CaptureMode} {mode : CaptureMode}
      (rest : ModeContext modes scope) (capture : Capture scope) :
      ModeContext (mode :: modes) scope

/-- The exact CoreCapybara modal context `[Psi, Phi]`. -/
inductive ModalContext : Nat → List CaptureMode → Sig → Type where
  | mk {scope : Sig} {separationCount : Nat}
      {modes : List CaptureMode}
      (separation : SeparationContext separationCount scope)
      (mode : ModeContext modes scope) :
      ModalContext separationCount modes scope

mutual

/-- Types of the many-sorted target.  Static quantifiers bind an entire local
theory, including a heterogeneous names-first symbol block. -/
inductive Ty : Sig → Type where
  | top {scope : Sig} : Ty scope
  | bot {scope : Sig} : Ty scope
  | one {scope : Sig} : Ty scope
  | tvar {scope : Sig} (name : BVar scope (.symbol .type)) : Ty scope
  | capturing {scope : Sig} (captures : Capture scope)
      (shape : Ty scope) : Ty scope
  | arr {scope : Sig} (domain codomain : Ty scope) : Ty scope
  | modal {scope : Sig} {separationCount : Nat}
      {modes : List CaptureMode}
      (requirements : ModalContext separationCount modes scope)
      (body : Ty scope) : Ty scope
  | forallT {scope : Sig} {symbols : List StaticSort}
      {relations : List Relation}
      (theory : Theory scope symbols relations)
      (body : Ty (StaticScope scope symbols relations)) : Ty scope
  | existsT {scope : Sig} {symbols : List StaticSort}
      {relations : List Relation}
      (theory : Theory scope symbols relations)
      (payload : Ty (StaticScope scope symbols relations)) : Ty scope
  /-- One projection from a complete simultaneous recursive type block. -/
  | recProj {scope : Sig} {names : Nat}
      (bodies : RecBodies scope names names) (index : Fin names) : Ty scope

/-- A simultaneous recursive type block under construction.

Every body sees the same homogeneous suffix of `bound` type self names.
`count` records the bodies supplied so far; only `RecBodies scope n n` may be
projected as a closed recursive block.  Capture symbols remain ambient and
acyclic in this first recursive target layer. -/
inductive RecBodies : (scope : Sig) → (bound count : Nat) → Type where
  | nil {scope : Sig} {bound : Nat} : RecBodies scope bound 0
  | snoc {scope : Sig} {bound count : Nat}
      (initial : RecBodies scope bound count)
      (body : Ty (TypeScope scope bound)) :
      RecBodies scope bound (count + 1)

/-- A static expression indexed by its sort. -/
inductive StaticExpr : StaticSort → Sig → Type where
  | type {scope : Sig} (type : Ty scope) : StaticExpr .type scope
  | capture {scope : Sig} (capture : Capture scope) :
      StaticExpr .capture scope

/-- An intrinsically sorted static proposition. -/
inductive Proposition : Relation → Sig → Type where
  | equality {scope : Sig} {sort : StaticSort}
      (left right : StaticExpr sort scope) :
      Proposition (.equality sort) scope
  | inclusion {scope : Sig} {sort : StaticSort}
      (lower upper : StaticExpr sort scope) :
      Proposition (.inclusion sort) scope
  | separate {scope : Sig} (left right : Capture scope) :
      Proposition .separate scope
  | disjoint {scope : Sig} (left right : Capture scope) :
      Proposition .disjoint scope
  | mode {scope : Sig} {mode : CaptureMode} (capture : Capture scope) :
      Proposition (.mode mode) scope

/-- A names-first local theory.  Every proposition is scoped after all symbols
but before every evidence binder, preventing a theory from citing its own
exported evidence. -/
inductive Theory : (scope : Sig) → (symbols : List StaticSort) →
    List Relation → Type where
  | nil {scope : Sig} {symbols : List StaticSort} : Theory scope symbols []
  | cons {scope : Sig} {symbols : List StaticSort}
      {relation : Relation} {relations : List Relation}
      (proposition : Proposition relation (SymbolScope scope symbols))
      (rest : Theory scope symbols relations) :
      Theory scope symbols (relation :: relations)

end

deriving instance DecidableEq for Capture
deriving instance DecidableEq for SeparationContext
deriving instance DecidableEq for ModeContext
deriving instance DecidableEq for ModalContext
deriving instance DecidableEq for Ty, RecBodies, StaticExpr, Proposition, Theory

namespace Ty

/-- Capabilities retained by the outermost capturing annotation.

For a bare type this projection returns the empty capture as the neutral
accounting default; in particular, a bare callable type is treated as
pure/untracked by application prediction. That projection alone does not
justify contracting a variable singleton to empty: bare bindings still export
no logical root contraction, and `Evidence.captureVariable` requires an
explicit `capturing` binding. -/
def outerCapture {scope : Sig} : Ty scope → Capture scope
  | .capturing captures _ => captures
  | _ => .empty

/-- Remove one outer capturing annotation, if present. -/
def stripCapture {scope : Sig} : Ty scope → Ty scope
  | .capturing _ shape => shape
  | type => type

/-- Install one canonical outer capture, replacing any previous outer
annotation instead of constructing nested capturing types. -/
def withCapture {scope : Sig} (captures : Capture scope)
    (type : Ty scope) : Ty scope :=
  .capturing captures type.stripCapture

/-- Give a variable of capturing type its precise singleton capture. Bare
types, including callable shapes, remain pure/untracked and export no logical
variable-root contraction evidence. -/
def precise {scope : Sig} (capability : BVar scope .term) :
    Ty scope → Ty scope
  | .capturing _ shape => .capturing (.singleton capability) shape
  | type => type

end Ty

mutual

/-- Rename a capture expression through a heterogeneous scope map. -/
def Capture.rename {source target : Sig} (capture : Capture source)
    (rho : Rename source target) : Capture target :=
  match capture with
  | .empty => .empty
  | .union left right => .union (left.rename rho) (right.rename rho)
  | .readOnly capture => .readOnly (capture.rename rho)
  | .singleton capability => .singleton (rho.var capability)
  | .cvar name => .cvar (rho.var name)
  | .project capture kind => .project (capture.rename rho) kind

/-- Rename every capture in a separation context. -/
def SeparationContext.rename {count : Nat} {source target : Sig}
    (context : SeparationContext count source) (rho : Rename source target) :
    SeparationContext count target :=
  match context with
  | .nil => .nil
  | .cons rest capture => .cons (rest.rename rho) (capture.rename rho)

/-- Rename every capture in a mode context. -/
def ModeContext.rename {modes : List CaptureMode} {source target : Sig}
    (context : ModeContext modes source) (rho : Rename source target) :
    ModeContext modes target :=
  match context with
  | .nil => .nil
  | .cons rest capture => .cons (rest.rename rho) (capture.rename rho)

/-- Rename both components of a modal context. -/
def ModalContext.rename {separationCount : Nat}
    {modes : List CaptureMode} {source target : Sig}
    (context : ModalContext separationCount modes source)
    (rho : Rename source target) :
    ModalContext separationCount modes target :=
  match context with
  | .mk separation mode => .mk (separation.rename rho) (mode.rename rho)

/-- Rename a type, lifting through every local theory. -/
def Ty.rename {source target : Sig} (type : Ty source)
    (rho : Rename source target) : Ty target :=
  match type with
  | .top => .top
  | .bot => .bot
  | .one => .one
  | .tvar name => .tvar (rho.var name)
  | .capturing captures shape =>
      .capturing (captures.rename rho) (shape.rename rho)
  | .arr domain codomain => .arr (domain.rename rho) (codomain.rename rho)
  | .modal requirements body =>
      .modal (requirements.rename rho) (body.rename rho)
  | @Ty.forallT _ symbols relations theory body =>
      .forallT (theory.rename rho)
        (body.rename (rho.liftStatic symbols relations))
  | @Ty.existsT _ symbols relations theory payload =>
      .existsT (theory.rename rho)
        (payload.rename (rho.liftStatic symbols relations))
  | .recProj bodies index => .recProj (bodies.rename rho) index

/-- Rename the ambient scope of every recursive body while preserving its
shared homogeneous suffix of self names. -/
def RecBodies.rename {source target : Sig} {bound count : Nat}
    (bodies : RecBodies source bound count) (rho : Rename source target) :
    RecBodies target bound count :=
  match bodies with
  | .nil => .nil
  | .snoc initial body =>
      .snoc (initial.rename rho) (body.rename (rho.liftTypes bound))

/-- Rename a static expression without changing its sort. -/
def StaticExpr.rename {sort : StaticSort} {source target : Sig}
    (expression : StaticExpr sort source) (rho : Rename source target) :
    StaticExpr sort target :=
  match expression with
  | .type type => .type (type.rename rho)
  | .capture capture => .capture (capture.rename rho)

/-- Rename every static expression in a proposition. -/
def Proposition.rename {relation : Relation} {source target : Sig}
    (proposition : Proposition relation source) (rho : Rename source target) :
    Proposition relation target :=
  match proposition with
  | .equality left right => .equality (left.rename rho) (right.rename rho)
  | .inclusion lower upper => .inclusion (lower.rename rho) (upper.rename rho)
  | .separate left right => .separate (left.rename rho) (right.rename rho)
  | .disjoint left right => .disjoint (left.rename rho) (right.rename rho)
  | .mode capture => .mode (capture.rename rho)

/-- Rename the ambient scope of a theory without changing its interface. -/
def Theory.rename {source target : Sig} {symbols : List StaticSort}
    {relations : List Relation} (theory : Theory source symbols relations)
    (rho : Rename source target) : Theory target symbols relations :=
  match theory with
  | .nil => .nil
  | .cons proposition rest =>
      .cons (proposition.rename (rho.liftSymbols symbols)) (rest.rename rho)

end

namespace Theory

/-- Concatenate two theories over the same already-allocated symbol block. -/
def append {scope : Sig} {symbols : List StaticSort}
    {first second : List Relation}
    (left : Theory scope symbols first)
    (right : Theory scope symbols second) :
    Theory scope symbols (first ++ second) :=
  match left with
  | .nil => right
  | .cons proposition rest => .cons proposition (rest.append right)

end Theory

namespace SeparationContext

/-- Separation obligations between one new entry and every older position. -/
def against {scope : Sig} (head : Capture scope) :
    {count : Nat} → SeparationContext count scope →
      Theory scope [] (List.replicate count .separate)
  | 0, .nil => .nil
  | _ + 1, .cons rest capture =>
      .cons (.separate head capture) (against head rest)

/-- Canonical `i < j` expansion of every distinct pair of list positions. -/
def toTheory {scope : Sig} : {count : Nat} →
    SeparationContext count scope →
      Theory scope [] (separationRelations count)
  | 0, .nil => .nil
  | _ + 1, .cons rest capture =>
      Theory.append (against capture rest) (toTheory rest)

end SeparationContext

namespace ModeContext

/-- Turn every mode entry into one explicit target proposition. -/
def toTheory {scope : Sig} : {modes : List CaptureMode} →
    ModeContext modes scope → Theory scope [] (modeRelations modes)
  | [], .nil => .nil
  | _ :: _, .cons rest capture =>
      .cons (.mode capture) (toTheory rest)

end ModeContext

namespace ModalContext

/-- Canonical explicit theory contributed by a primitive modal lock. -/
def toTheory {scope : Sig} {separationCount : Nat}
    {modes : List CaptureMode}
    (context : ModalContext separationCount modes scope) :
    Theory scope [] (modalRelations separationCount modes) :=
  match context with
  | .mk separation mode =>
      Theory.append mode.toTheory separation.toTheory

end ModalContext

namespace Capture

/-- Sequence an immediate-use prediction before the uses that follow it.

The syntactic empty prediction is omitted, so admitting a computation where a
value was previously required does not perturb existing indices when that
computation has no immediate use.  A nonempty prediction remains explicit as
the left branch of a union. -/
def sequence {scope : Sig} : Capture scope → Capture scope → Capture scope
  | .empty, following => following
  | immediate, following => .union immediate following

/-- Weaken a capture expression below one binder. -/
def weaken {scope : Sig} {kind : BinderKind} (capture : Capture scope) :
    Capture (scope ▹ kind) :=
  capture.rename Rename.succ

@[simp]
theorem sequence_empty {scope : Sig} (following : Capture scope) :
    sequence .empty following = following := rfl

@[simp]
theorem sequence_rename {source target : Sig}
    (immediate following : Capture source) (rho : Rename source target) :
    (sequence immediate following).rename rho =
      sequence (immediate.rename rho) (following.rename rho) := by
  cases immediate <;> rfl

end Capture

namespace Ty

/-- Weaken a type below one binder. -/
def weaken {scope : Sig} {kind : BinderKind} (type : Ty scope) :
    Ty (scope ▹ kind) :=
  type.rename Rename.succ

end Ty

namespace RecBodies

/-- Weaken the ambient scope of a recursive block below one binder. -/
def weaken {scope : Sig} {kind : BinderKind} {bound count : Nat}
    (bodies : RecBodies scope bound count) :
    RecBodies (scope ▹ kind) bound count :=
  bodies.rename Rename.succ

end RecBodies

namespace StaticExpr

/-- Weaken a static expression below one binder. -/
def weaken {scope : Sig} {kind : BinderKind} {sort : StaticSort}
    (expression : StaticExpr sort scope) : StaticExpr sort (scope ▹ kind) :=
  expression.rename Rename.succ

end StaticExpr

mutual

@[simp]
def Capture.rename_id {scope : Sig} (capture : Capture scope) :
    capture.rename Rename.id = capture :=
  match capture with
  | .empty => rfl
  | .union left right => by
      simp only [Capture.rename, Capture.rename_id left,
        Capture.rename_id right]
  | .readOnly capture => by
      simp only [Capture.rename, Capture.rename_id capture]
  | .singleton _ => rfl
  | .cvar _ => rfl
  | .project capture _ => by
      simp only [Capture.rename, Capture.rename_id capture]

@[simp]
def SeparationContext.rename_id {scope : Sig} {count : Nat}
    (context : SeparationContext count scope) :
    context.rename Rename.id = context :=
  match context with
  | .nil => rfl
  | .cons rest capture => by
      simp only [SeparationContext.rename,
        SeparationContext.rename_id rest, Capture.rename_id capture]

@[simp]
def ModeContext.rename_id {scope : Sig} {modes : List CaptureMode}
    (context : ModeContext modes scope) :
    context.rename Rename.id = context :=
  match context with
  | .nil => rfl
  | .cons rest capture => by
      simp only [ModeContext.rename, ModeContext.rename_id rest,
        Capture.rename_id capture]

@[simp]
def ModalContext.rename_id {scope : Sig} {separationCount : Nat}
    {modes : List CaptureMode}
    (context : ModalContext separationCount modes scope) :
    context.rename Rename.id = context :=
  match context with
  | .mk separation mode => by
      simp only [ModalContext.rename, SeparationContext.rename_id separation,
        ModeContext.rename_id mode]

@[simp]
def Ty.rename_id {scope : Sig} (type : Ty scope) :
    type.rename Rename.id = type :=
  match type with
  | .top => rfl
  | .bot => rfl
  | .one => rfl
  | .tvar _ => rfl
  | .capturing captures shape => by
      simp only [Ty.rename, Capture.rename_id captures, Ty.rename_id shape]
  | .arr domain codomain => by
      simp only [Ty.rename, Ty.rename_id domain, Ty.rename_id codomain]
  | .modal requirements body => by
      simp only [Ty.rename, ModalContext.rename_id requirements,
        Ty.rename_id body]
  | @Ty.forallT _ symbols relations theory body => by
      simp only [Ty.rename, Theory.rename_id theory, Rename.liftStatic_id,
        Ty.rename_id body]
  | @Ty.existsT _ symbols relations theory payload => by
      simp only [Ty.rename, Theory.rename_id theory, Rename.liftStatic_id,
        Ty.rename_id payload]
  | .recProj bodies index => by
      simp only [Ty.rename, RecBodies.rename_id bodies]

@[simp]
def RecBodies.rename_id {scope : Sig} {bound count : Nat}
    (bodies : RecBodies scope bound count) :
    bodies.rename Rename.id = bodies :=
  match bodies with
  | .nil => rfl
  | .snoc initial body => by
      simp only [RecBodies.rename, RecBodies.rename_id initial,
        Rename.liftTypes_id, Ty.rename_id body]

@[simp]
def StaticExpr.rename_id {scope : Sig} {sort : StaticSort}
    (expression : StaticExpr sort scope) :
    expression.rename Rename.id = expression :=
  match expression with
  | .type type => by
      simp only [StaticExpr.rename, Ty.rename_id type]
  | .capture capture => by
      simp only [StaticExpr.rename, Capture.rename_id capture]

@[simp]
def Proposition.rename_id {scope : Sig} {relation : Relation}
    (proposition : Proposition relation scope) :
    proposition.rename Rename.id = proposition :=
  match proposition with
  | .equality left right => by
      simp only [Proposition.rename, StaticExpr.rename_id left,
        StaticExpr.rename_id right]
  | .inclusion lower upper => by
      simp only [Proposition.rename, StaticExpr.rename_id lower,
        StaticExpr.rename_id upper]
  | .separate left right => by
      simp only [Proposition.rename, Capture.rename_id left,
        Capture.rename_id right]
  | .disjoint left right => by
      simp only [Proposition.rename, Capture.rename_id left,
        Capture.rename_id right]
  | .mode capture => by
      simp only [Proposition.rename, Capture.rename_id capture]

@[simp]
def Theory.rename_id {scope : Sig} {symbols : List StaticSort}
    {relations : List Relation} (theory : Theory scope symbols relations) :
    theory.rename Rename.id = theory :=
  match theory with
  | .nil => rfl
  | .cons proposition rest => by
      simp only [Theory.rename, Rename.liftSymbols_id,
        Proposition.rename_id proposition, Theory.rename_id rest]

end

@[simp]
theorem Ty.outerCapture_rename {source target : Sig} (type : Ty source)
    (rho : Rename source target) :
    (type.rename rho).outerCapture = type.outerCapture.rename rho := by
  cases type <;> rfl

@[simp]
theorem Ty.stripCapture_rename {source target : Sig} (type : Ty source)
    (rho : Rename source target) :
    (type.rename rho).stripCapture = type.stripCapture.rename rho := by
  cases type <;> rfl

@[simp]
theorem Ty.withCapture_rename {source target : Sig}
    (captures : Capture source) (type : Ty source)
    (rho : Rename source target) :
    (type.withCapture captures).rename rho =
      (type.rename rho).withCapture (captures.rename rho) := by
  simp [Ty.withCapture, Ty.rename]

@[simp]
theorem Ty.precise_rename {source target : Sig}
    (capability : BVar source .term) (type : Ty source)
    (rho : Rename source target) :
    (type.precise capability).rename rho =
      (type.rename rho).precise (rho.var capability) := by
  cases type <;> rfl

mutual

@[simp]
def Capture.rename_comp {first second third : Sig}
    (capture : Capture first) (rho₁ : Rename first second)
    (rho₂ : Rename second third) :
    (capture.rename rho₁).rename rho₂ = capture.rename (rho₁.comp rho₂) :=
  match capture with
  | .empty => rfl
  | .union left right => by
      simp only [Capture.rename, Capture.rename_comp left,
        Capture.rename_comp right]
  | .readOnly capture => by
      simp only [Capture.rename, Capture.rename_comp capture]
  | .singleton _ => rfl
  | .cvar _ => rfl
  | .project capture _ => by
      simp only [Capture.rename, Capture.rename_comp capture]

@[simp]
def SeparationContext.rename_comp {count : Nat}
    {first second third : Sig} (context : SeparationContext count first)
    (rho₁ : Rename first second) (rho₂ : Rename second third) :
    (context.rename rho₁).rename rho₂ =
      context.rename (rho₁.comp rho₂) :=
  match context with
  | .nil => rfl
  | .cons rest capture => by
      simp only [SeparationContext.rename,
        SeparationContext.rename_comp rest, Capture.rename_comp capture]

@[simp]
def ModeContext.rename_comp {modes : List CaptureMode}
    {first second third : Sig} (context : ModeContext modes first)
    (rho₁ : Rename first second) (rho₂ : Rename second third) :
    (context.rename rho₁).rename rho₂ =
      context.rename (rho₁.comp rho₂) :=
  match context with
  | .nil => rfl
  | .cons rest capture => by
      simp only [ModeContext.rename, ModeContext.rename_comp rest,
        Capture.rename_comp capture]

@[simp]
def ModalContext.rename_comp {separationCount : Nat}
    {modes : List CaptureMode} {first second third : Sig}
    (context : ModalContext separationCount modes first)
    (rho₁ : Rename first second) (rho₂ : Rename second third) :
    (context.rename rho₁).rename rho₂ =
      context.rename (rho₁.comp rho₂) :=
  match context with
  | .mk separation mode => by
      simp only [ModalContext.rename,
        SeparationContext.rename_comp separation,
        ModeContext.rename_comp mode]

@[simp]
def Ty.rename_comp {first second third : Sig} (type : Ty first)
    (rho₁ : Rename first second) (rho₂ : Rename second third) :
    (type.rename rho₁).rename rho₂ = type.rename (rho₁.comp rho₂) :=
  match type with
  | .top => rfl
  | .bot => rfl
  | .one => rfl
  | .tvar _ => rfl
  | .capturing captures shape => by
      simp only [Ty.rename, Capture.rename_comp captures,
        Ty.rename_comp shape]
  | .arr domain codomain => by
      simp only [Ty.rename, Ty.rename_comp domain, Ty.rename_comp codomain]
  | .modal requirements body => by
      simp only [Ty.rename, ModalContext.rename_comp requirements,
        Ty.rename_comp body]
  | @Ty.forallT _ symbols relations theory body => by
      simp only [Ty.rename, Theory.rename_comp theory,
        Ty.rename_comp body, Rename.liftStatic_comp]
  | @Ty.existsT _ symbols relations theory payload => by
      simp only [Ty.rename, Theory.rename_comp theory,
        Ty.rename_comp payload, Rename.liftStatic_comp]
  | .recProj bodies index => by
      simp only [Ty.rename, RecBodies.rename_comp bodies]

@[simp]
def RecBodies.rename_comp {first second third : Sig}
    {bound count : Nat} (bodies : RecBodies first bound count)
    (rho₁ : Rename first second) (rho₂ : Rename second third) :
    (bodies.rename rho₁).rename rho₂ =
      bodies.rename (rho₁.comp rho₂) :=
  match bodies with
  | .nil => rfl
  | .snoc initial body => by
      simp only [RecBodies.rename, RecBodies.rename_comp initial,
        Ty.rename_comp body, Rename.liftTypes_comp]

@[simp]
def StaticExpr.rename_comp {sort : StaticSort} {first second third : Sig}
    (expression : StaticExpr sort first) (rho₁ : Rename first second)
    (rho₂ : Rename second third) :
    (expression.rename rho₁).rename rho₂ =
      expression.rename (rho₁.comp rho₂) :=
  match expression with
  | .type type => by
      simp only [StaticExpr.rename, Ty.rename_comp type]
  | .capture capture => by
      simp only [StaticExpr.rename, Capture.rename_comp capture]

@[simp]
def Proposition.rename_comp {relation : Relation}
    {first second third : Sig} (proposition : Proposition relation first)
    (rho₁ : Rename first second) (rho₂ : Rename second third) :
    (proposition.rename rho₁).rename rho₂ =
      proposition.rename (rho₁.comp rho₂) :=
  match proposition with
  | .equality left right => by
      simp only [Proposition.rename, StaticExpr.rename_comp left,
        StaticExpr.rename_comp right]
  | .inclusion lower upper => by
      simp only [Proposition.rename, StaticExpr.rename_comp lower,
        StaticExpr.rename_comp upper]
  | .separate left right => by
      simp only [Proposition.rename, Capture.rename_comp left,
        Capture.rename_comp right]
  | .disjoint left right => by
      simp only [Proposition.rename, Capture.rename_comp left,
        Capture.rename_comp right]
  | .mode capture => by
      simp only [Proposition.rename, Capture.rename_comp capture]

@[simp]
def Theory.rename_comp {first second third : Sig}
    {symbols : List StaticSort} {relations : List Relation}
    (theory : Theory first symbols relations) (rho₁ : Rename first second)
    (rho₂ : Rename second third) :
    (theory.rename rho₁).rename rho₂ = theory.rename (rho₁.comp rho₂) :=
  match theory with
  | .nil => rfl
  | .cons proposition rest => by
      simp only [Theory.rename, Proposition.rename_comp proposition,
        Theory.rename_comp rest, Rename.liftSymbols_comp]

end


/-! ## Homogeneous recursive type arguments -/

/-- Simultaneous type witnesses for the self names of a recursive block. -/
inductive TypeArgs (scope : Sig) : Nat → Type where
  | nil : TypeArgs scope 0
  | snoc {count : Nat} (initial : TypeArgs scope count) (type : Ty scope) :
      TypeArgs scope (count + 1)
deriving DecidableEq

namespace TypeArgs

/-- Rename every type witness. -/
def rename {source target : Sig} {count : Nat}
    (arguments : TypeArgs source count) (rho : Rename source target) :
    TypeArgs target count :=
  match arguments with
  | .nil => .nil
  | .snoc initial type => .snoc (initial.rename rho) (type.rename rho)

@[simp]
theorem rename_id {scope : Sig} {count : Nat}
    (arguments : TypeArgs scope count) :
    arguments.rename Rename.id = arguments := by
  induction arguments with
  | nil => rfl
  | snoc initial type induction => simp [rename, induction]

@[simp]
theorem rename_comp {first second third : Sig} {count : Nat}
    (arguments : TypeArgs first count) (rho₁ : Rename first second)
    (rho₂ : Rename second third) :
    (arguments.rename rho₁).rename rho₂ =
      arguments.rename (rho₁.comp rho₂) := by
  induction arguments with
  | nil => rfl
  | snoc initial type induction =>
      simp [rename, induction, Ty.rename_comp]

end TypeArgs

end ManySortedFC
