import LambdaP.ScopedRuntimeEq
import LambdaP.Opening

/-!
Structural runtime path checking and subtyping.

Unlike `DeepRuntimeTyping`, this file does not embed an opaque source
`Tau.Sub` derivation.  Path checking and generalized subtyping are defined
mutually, and every source constructor is represented explicitly.  Abstract
path conversion is generated by a relation `R`; under function and pair
binders the relation is `Path.ScopedLift R`, so the fresh variable cannot
acquire ambient runtime equations.

The opening development below is phrased through a structural renaming
environment.  This is the standard strengthening needed for recursive binder
cases: opening the outer binder below a function or pair binder uses
`(FinFun.openAt x).ext`, not another top-level `openAt`.
-/

namespace LambdaP

/-! ## Abstract conversion -/

/-- Symmetric generalized-type conversion generated by an abstract path
equivalence/congruence.  The algebraic laws required of `R` are supplied to
theorems, rather than stored redundantly in each derivation. -/
inductive Tau.StructConv (R : Path n -> Path n -> Prop) :
    Tau n k -> Tau n k -> Prop where
| refl : Tau.StructConv R d d
| symm : Tau.StructConv R d1 d2 -> Tau.StructConv R d2 d1
| trans :
    Tau.StructConv R d1 d2 ->
    Tau.StructConv R d2 d3 ->
    Tau.StructConv R d1 d3
| replace (template : Tau (n + 1) k) (h : R p q) :
    Tau.StructConv R (template.open p) (template.open q)

/-! ## Mutually structural path checking and subtyping -/

mutual

/-- Path checking with structural subtyping/conversion available before any
elimination. -/
inductive Path.StructCheck : {n : Nat} -> (Gamma : Ctx n) ->
    (R : Path n -> Path n -> Prop) -> {k : Kind} ->
    Path n -> Tau n k -> Prop where
| var :
    Ctx.Binds Gamma x T ->
    Path.StructCheck Gamma R (.var x) (Tau.ty T)
| sub :
    Path.StructCheck Gamma R p d1 ->
    Tau.StructSub Gamma R d1 d2 ->
    Path.StructCheck Gamma R p d2
/-- Singleton promotion used by term/path substitution.  If `p` checks at
some precise type `U`, the premise normally available from term subsumption
is `{p} <: T`, not `U <: T`; consequently the ordinary `sub` constructor
cannot consume that premise. -/
| promote :
    Path.StructCheck Gamma R p (Tau.ty U) ->
    Tau.StructSub Gamma R
      (Tau.ty (Ty.Single p)) (Tau.ty T) ->
    Path.StructCheck Gamma R p (Tau.ty T)
| fst :
    Path.StructCheck Gamma R p
      (Tau.ty (Ty.Pair S a d)) ->
    Path.StructCheck Gamma R p.fst (Tau.ty S)
| sel_r :
    Path.StructCheck Gamma R p
      (Tau.ty (Ty.Pair S a d)) ->
    Path.StructCheck Gamma R (p.sel a) (d.open p.fst)
| sel_l :
    Path.StructCheck Gamma R p
      (Tau.ty (Ty.Pair S b d')) ->
    Path.StructCheck Gamma R (p.fst.sel a) d ->
    a ≠ b ->
    Path.StructCheck Gamma R (p.sel a) d

/-- Generalized subtyping with every source rule exposed and all of its path
premises interpreted by `Path.StructCheck`. -/
inductive Tau.StructSub : {n : Nat} -> (Gamma : Ctx n) ->
    (R : Path n -> Path n -> Prop) -> {k : Kind} ->
    Tau n k -> Tau n k -> Prop where
| refl : Tau.StructSub Gamma R d d
| trans :
    Tau.StructSub Gamma R d1 d2 ->
    Tau.StructSub Gamma R d2 d3 ->
    Tau.StructSub Gamma R d1 d3
| conv :
    Tau.StructConv R d1 d2 ->
    Tau.StructSub Gamma R d1 d2
| bot :
    Tau.StructSub Gamma R (Tau.ty Ty.Bot) (Tau.ty T)
| top :
    Tau.StructSub Gamma R (Tau.ty T) (Tau.ty Ty.Top)
| widen :
    Path.StructCheck Gamma R p (Tau.ty T) ->
    Tau.StructSub Gamma R
      (Tau.ty (Ty.Single p)) (Tau.ty T)
| symm :
    Path.StructCheck Gamma R p (Tau.ty (Ty.Single q)) ->
    Tau.StructSub Gamma R
      (Tau.ty (Ty.Single q)) (Tau.ty (Ty.Single p))
| sel_hi :
    Path.StructCheck Gamma R (Path.sel p A) (Tau.intv S T) ->
    Tau.StructSub Gamma R (Tau.ty S) (Tau.ty T) ->
    Tau.StructSub Gamma R
      (Tau.ty (Ty.TSel p A)) (Tau.ty T)
| sel_lo :
    Path.StructCheck Gamma R (Path.sel p A) (Tau.intv S T) ->
    Tau.StructSub Gamma R (Tau.ty S) (Tau.ty T) ->
    Tau.StructSub Gamma R
      (Tau.ty S) (Tau.ty (Ty.TSel p A))
| «fun» :
    Tau.StructSub Gamma R (Tau.ty S') (Tau.ty S) ->
    Tau.StructSub (Gamma.snoc S') (Path.ScopedLift R)
      (Tau.ty T) (Tau.ty T') ->
    Tau.StructSub Gamma R
      (Tau.ty (Ty.Fun S T)) (Tau.ty (Ty.Fun S' T'))
/-- Covariance of the first component, leaving the dependent member
unchanged. -/
| pair_fst :
    Tau.StructSub Gamma R (Tau.ty S) (Tau.ty S') ->
    Tau.StructSub Gamma R
      (Tau.ty (Ty.Pair S a d)) (Tau.ty (Ty.Pair S' a d))
/-- A dependent member may change only when the first component is the
singleton of a properly checked path.  The member comparison is recorded
both under the singleton binder and after opening it at that path. -/
| pair_single_member :
    Path.StructCheck Gamma R p (Tau.ty P) ->
    Tau.StructSub (Gamma.snoc (Ty.Single p)) (Path.ScopedLift R) d d' ->
    Tau.StructSub Gamma R (d.open p) (d'.open p) ->
    Tau.StructSub Gamma R
      (Tau.ty (Ty.Pair (Ty.Single p) a d))
      (Tau.ty (Ty.Pair (Ty.Single p) a d'))
| bounds :
    Tau.StructSub Gamma R (Tau.ty S') (Tau.ty S) ->
    Tau.StructSub Gamma R (Tau.ty T) (Tau.ty T') ->
    Tau.StructSub Gamma R (Tau.ty S) (Tau.ty T) ->
    Tau.StructSub Gamma R
      (Tau.intv S T) (Tau.intv S' T')

end

/-! ## Complete source embeddings -/

/-- Every source precise path derivation embeds for every abstract relation. -/
theorem Path.StructCheck.of_source
    {n : Nat} {Gamma : Ctx n} {p : Path n} {k : Kind}
    {d : Tau n k} (h : Path.Ty Gamma p d)
    (R : Path n -> Path n -> Prop) :
    Path.StructCheck Gamma R p d := by
  induction h with
  | var hb => exact .var hb
  | fst _ ih => exact .fst ih
  | sel_r _ ih => exact .sel_r ih
  | sel_l _ _ hne ihp ihtail => exact .sel_l ihp ihtail hne

/-- Every source generalized-subtyping derivation embeds, including recursive
premises below binders. -/
theorem Tau.StructSub.of_source
    {n : Nat} {Gamma : Ctx n} {k : Kind} {d1 d2 : Tau n k}
    (h : Tau.Sub Gamma d1 d2) :
    forall R : Path n -> Path n -> Prop,
      Tau.StructSub Gamma R d1 d2 := by
  induction h with
  | refl => intro R; exact .refl
  | trans _ _ ih1 ih2 =>
      intro R
      exact .trans (ih1 R) (ih2 R)
  | bot => intro R; exact .bot
  | top => intro R; exact .top
  | widen hp =>
      intro R
      exact .widen (Path.StructCheck.of_source hp R)
  | symm hp =>
      intro R
      exact .symm (Path.StructCheck.of_source hp R)
  | sel_hi hp hbounds ihbounds =>
      intro R
      exact .sel_hi (Path.StructCheck.of_source hp R) (ihbounds R)
  | sel_lo hp hbounds ihbounds =>
      intro R
      exact .sel_lo (Path.StructCheck.of_source hp R) (ihbounds R)
  | «fun» hdom hcod ihdom ihcod =>
      intro R
      exact .fun (ihdom R) (ihcod (Path.ScopedLift R))
  | pair_fst hfst ihfst =>
      intro R
      exact .pair_fst (ihfst R)
  | pair_single_member hp hsnd hopen ihsnd ihopen =>
      intro R
      exact .pair_single_member
        (Path.StructCheck.of_source hp R)
        (ihsnd (Path.ScopedLift R)) (ihopen R)
  | bounds hlo hhi hnonempty ihlo ihhi ihnonempty =>
      intro R
      exact .bounds (ihlo R) (ihhi R) (ihnonempty R)

/-! ## Relation morphisms and exact renaming -/

/-- A renaming transports one abstract path relation into another. -/
abbrev Path.RelHom
    (R : Path n -> Path n -> Prop)
    (E : Path m -> Path m -> Prop) (f : FinFun n m) : Prop :=
  ∀ {p q}, R p q -> E (p.rename f) (q.rename f)

/-- A relation morphism lifts through a source binder. -/
theorem Path.RelHom.scoped
    (h : Path.RelHom R E f) :
    Path.RelHom (Path.ScopedLift R) (Path.ScopedLift E) f.ext := by
  intro p q hpq
  induction hpq with
  | bound => exact .bound
  | old hpq =>
      simpa only [Path.weaken_rename] using
        (Path.ScopedLift.old (h hpq))
  | symm _ ih => exact .symm ih
  | trans _ _ ih1 ih2 => exact .trans ih1 ih2
  | fst _ ih => exact .fst ih
  | sel _ ih => exact .sel ih

/-- Weakening maps an ambient relation into its scoped lift. -/
theorem Path.RelHom.weaken :
    Path.RelHom R (Path.ScopedLift R) FinFun.weaken := by
  intro p q hpq
  exact Path.ScopedLift.old hpq

/-- Abstract type conversion is natural with respect to a relation
morphism. -/
theorem Tau.StructConv.rename
    (h : Tau.StructConv R d1 d2)
    (hrel : Path.RelHom R E f) :
    Tau.StructConv E (d1.rename f) (d2.rename f) := by
  induction h with
  | refl => exact .refl
  | symm _ ih => exact .symm ih
  | trans _ _ ih1 ih2 => exact .trans ih1 ih2
  | replace template hpq =>
      simpa only [Tau.open_rename] using
        (Tau.StructConv.replace (template.rename f.ext) (hrel hpq))

private abbrev PathRenameExactMotive
    {n : Nat} (Gamma : Ctx n) (R : Path n -> Path n -> Prop)
    {k : Kind} (p : Path n) (d : Tau n k)
    (_ : Path.StructCheck Gamma R p d) : Prop :=
  forall {m : Nat} {f : FinFun n m} {Delta : Ctx m}
    {E : Path m -> Path m -> Prop},
    Renaming Gamma f Delta ->
    Path.RelHom R E f ->
    Path.StructCheck Delta E (p.rename f) (d.rename f)

private abbrev SubRenameExactMotive
    {n : Nat} (Gamma : Ctx n) (R : Path n -> Path n -> Prop)
    {k : Kind} (d1 d2 : Tau n k)
    (_ : Tau.StructSub Gamma R d1 d2) : Prop :=
  forall {m : Nat} {f : FinFun n m} {Delta : Ctx m}
    {E : Path m -> Path m -> Prop},
    Renaming Gamma f Delta ->
    Path.RelHom R E f ->
    Tau.StructSub Delta E (d1.rename f) (d2.rename f)

mutual

/-- Structural path checking is preserved by an exact context-respecting
renaming and a compatible relation morphism. -/
theorem Path.StructCheck.renameExact
    {n : Nat} {Gamma : Ctx n}
    {R : Path n -> Path n -> Prop} {k : Kind}
    {p : Path n} {d : Tau n k}
    (h : Path.StructCheck Gamma R p d) :
    ∀ {m : Nat} {f : FinFun n m} {Delta : Ctx m}
      {E : Path m -> Path m -> Prop},
      Renaming Gamma f Delta ->
      Path.RelHom R E f ->
      Path.StructCheck Delta E (p.rename f) (d.rename f) := by
  induction h using Path.StructCheck.rec
      (motive_2 := SubRenameExactMotive) with
  | var hb =>
      intro m f Delta E rho hrel
      simpa [Path.rename, Tau.rename] using
        (Path.StructCheck.var (R := E) (rho hb))
  | sub hp hs ihp ihs =>
      intro m f Delta E rho hrel
      exact .sub (ihp rho hrel) (ihs rho hrel)
  | promote hp hs ihp ihs =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Path.StructCheck.promote (ihp rho hrel) (ihs rho hrel)
  | fst hp ih =>
      intro m f Delta E rho hrel
      simpa [Path.rename, Tau.rename, Ty.rename] using
        Path.StructCheck.fst (ih rho hrel)
  | sel_r hp ih =>
      intro m f Delta E rho hrel
      simpa [Path.rename, Tau.rename, Ty.rename, Tau.open_rename] using
        Path.StructCheck.sel_r (ih rho hrel)
  | sel_l hp htail hne ihp ihtail =>
      intro m f Delta E rho hrel
      simpa [Path.rename, Tau.rename, Ty.rename] using
        Path.StructCheck.sel_l (ihp rho hrel) (ihtail rho hrel) hne
  | refl =>
      intro m f Delta E rho hrel
      exact .refl
  | trans h1 h2 ih1 ih2 =>
      intro m f Delta E rho hrel
      exact .trans (ih1 rho hrel) (ih2 rho hrel)
  | conv hconv =>
      intro m f Delta E rho hrel
      exact .conv (hconv.rename hrel)
  | bot =>
      intro m f Delta E rho hrel
      simp only [Tau.rename, Ty.rename]
      exact .bot
  | top =>
      intro m f Delta E rho hrel
      simp only [Tau.rename, Ty.rename]
      exact .top
  | widen hp ih =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.widen (ih rho hrel)
  | symm hp ih =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.symm (ih rho hrel)
  | sel_hi hp hbounds ihp ihbounds =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.sel_hi (ihp rho hrel) (ihbounds rho hrel)
  | sel_lo hp hbounds ihp ihbounds =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.sel_lo (ihp rho hrel) (ihbounds rho hrel)
  | «fun» hdom hcod ihdom ihcod =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename] using
        Tau.StructSub.fun (ihdom rho hrel)
          (ihcod (Renaming.ext rho) hrel.scoped)
  | pair_fst hfst ihfst =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename] using
        Tau.StructSub.pair_fst (ihfst rho hrel)
  | pair_single_member hp hsnd hopen ihp ihsnd ihopen =>
      intro m f Delta E rho hrel
      have hopen' := ihopen rho hrel
      rw [Tau.open_rename, Tau.open_rename] at hopen'
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.pair_single_member (ihp rho hrel)
          (ihsnd (Renaming.ext rho) hrel.scoped) hopen'
  | bounds hlo hhi hnonempty ihlo ihhi ihnonempty =>
      intro m f Delta E rho hrel
      simpa [Tau.rename] using
        Tau.StructSub.bounds (ihlo rho hrel) (ihhi rho hrel)
          (ihnonempty rho hrel)

/-- Structural generalized subtyping is preserved by the same exact
renaming. -/
theorem Tau.StructSub.renameExact
    {n : Nat} {Gamma : Ctx n}
    {R : Path n -> Path n -> Prop} {k : Kind}
    {d1 d2 : Tau n k}
    (h : Tau.StructSub Gamma R d1 d2) :
    ∀ {m : Nat} {f : FinFun n m} {Delta : Ctx m}
      {E : Path m -> Path m -> Prop},
      Renaming Gamma f Delta ->
      Path.RelHom R E f ->
      Tau.StructSub Delta E (d1.rename f) (d2.rename f) := by
  induction h using Tau.StructSub.rec
      (motive_1 := PathRenameExactMotive)
      with
  | var hb =>
      intro m f Delta E rho hrel
      simpa [Path.rename, Tau.rename] using
        (Path.StructCheck.var (R := E) (rho hb))
  | sub hp hs ihp ihs =>
      intro m f Delta E rho hrel
      exact .sub (ihp rho hrel) (ihs rho hrel)
  | promote hp hs ihp ihs =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Path.StructCheck.promote (ihp rho hrel) (ihs rho hrel)
  | fst hp ih =>
      intro m f Delta E rho hrel
      simpa [Path.rename, Tau.rename, Ty.rename] using
        Path.StructCheck.fst (ih rho hrel)
  | sel_r hp ih =>
      intro m f Delta E rho hrel
      simpa [Path.rename, Tau.rename, Ty.rename, Tau.open_rename] using
        Path.StructCheck.sel_r (ih rho hrel)
  | sel_l hp htail hne ihp ihtail =>
      intro m f Delta E rho hrel
      simpa [Path.rename, Tau.rename, Ty.rename] using
        Path.StructCheck.sel_l (ihp rho hrel) (ihtail rho hrel) hne
  | refl =>
      intro m f Delta E rho hrel
      exact .refl
  | trans h1 h2 ih1 ih2 =>
      intro m f Delta E rho hrel
      exact .trans (ih1 rho hrel) (ih2 rho hrel)
  | conv hconv =>
      intro m f Delta E rho hrel
      exact .conv (hconv.rename hrel)
  | bot =>
      intro m f Delta E rho hrel
      simp only [Tau.rename, Ty.rename]
      exact .bot
  | top =>
      intro m f Delta E rho hrel
      simp only [Tau.rename, Ty.rename]
      exact .top
  | widen hp ih =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.widen (ih rho hrel)
  | symm hp ih =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.symm (ih rho hrel)
  | sel_hi hp hbounds ihp ihbounds =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.sel_hi (ihp rho hrel) (ihbounds rho hrel)
  | sel_lo hp hbounds ihp ihbounds =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.sel_lo (ihp rho hrel) (ihbounds rho hrel)
  | «fun» hdom hcod ihdom ihcod =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename] using
        Tau.StructSub.fun (ihdom rho hrel)
          (ihcod (Renaming.ext rho) hrel.scoped)
  | pair_fst hfst ihfst =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename] using
        Tau.StructSub.pair_fst (ihfst rho hrel)
  | pair_single_member hp hsnd hopen ihp ihsnd ihopen =>
      intro m f Delta E rho hrel
      have hopen' := ihopen rho hrel
      rw [Tau.open_rename, Tau.open_rename] at hopen'
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.pair_single_member (ihp rho hrel)
          (ihsnd (Renaming.ext rho) hrel.scoped) hopen'
  | bounds hlo hhi hnonempty ihlo ihhi ihnonempty =>
      intro m f Delta E rho hrel
      simpa [Tau.rename] using
        Tau.StructSub.bounds (ihlo rho hrel) (ihhi rho hrel)
          (ihnonempty rho hrel)

end

/-! ## Structural renaming environments -/

/-- A structural renaming maps every source variable to a path which checks
at the renamed context type.  Unlike `Renaming`, it does not require the
image to be a variable whose type occurs literally in the target context. -/
abbrev Path.StructRenaming
    (Gamma : Ctx n) (f : FinFun n m) (Delta : Ctx m)
    (E : Path m -> Path m -> Prop) : Prop :=
  forall {x T}, Ctx.Binds Gamma x T ->
    Path.StructCheck Delta E (.var (f x)) (Tau.ty (T.rename f))

/-- An ordinary context-respecting renaming induces a structural one. -/
theorem Path.StructRenaming.of_exact
    (rho : Renaming Gamma f Delta) :
    Path.StructRenaming Gamma f Delta E := by
  intro x T hx
  exact Path.StructCheck.var (R := E) (rho hx)

/-- Structural renamings extend through one dependent binder.  The old
images are weakened using the already established exact renaming theorem. -/
theorem Path.StructRenaming.ext
    (rho : Path.StructRenaming Gamma f Delta E) :
    Path.StructRenaming (Gamma.snoc T) f.ext
      (Delta.snoc (T.rename f)) (Path.ScopedLift E) := by
  intro x U hx
  cases hx with
  | here =>
      simpa only [FinFun.ext_zero, Path.rename, Tau.rename,
        ← Ty.weaken_rename] using
        (Path.StructCheck.var (R := Path.ScopedLift E)
          (Ctx.Binds.here (Γ := Delta) (T := T.rename f)))
  | there hx =>
      simpa only [FinFun.ext_succ, Path.rename, Tau.rename,
        ← Ty.weaken_rename] using
        (Path.StructCheck.renameExact (rho hx)
          (Renaming.weaken (S := T.rename f))
          (Path.RelHom.weaken (R := E)))

private abbrev PathRenameMotive
    {n : Nat} (Gamma : Ctx n) (R : Path n -> Path n -> Prop)
    {k : Kind} (p : Path n) (d : Tau n k)
    (_ : Path.StructCheck Gamma R p d) : Prop :=
  forall {m : Nat} {f : FinFun n m} {Delta : Ctx m}
    {E : Path m -> Path m -> Prop},
    Path.StructRenaming Gamma f Delta E ->
    Path.RelHom R E f ->
    Path.StructCheck Delta E (p.rename f) (d.rename f)

private abbrev SubRenameMotive
    {n : Nat} (Gamma : Ctx n) (R : Path n -> Path n -> Prop)
    {k : Kind} (d1 d2 : Tau n k)
    (_ : Tau.StructSub Gamma R d1 d2) : Prop :=
  forall {m : Nat} {f : FinFun n m} {Delta : Ctx m}
    {E : Path m -> Path m -> Prop},
    Path.StructRenaming Gamma f Delta E ->
    Path.RelHom R E f ->
    Tau.StructSub Delta E (d1.rename f) (d2.rename f)

mutual

/-- Structural path checking is stable under structural renaming. -/
theorem Path.StructCheck.rename
    {n : Nat} {Gamma : Ctx n}
    {R : Path n -> Path n -> Prop} {k : Kind}
    {p : Path n} {d : Tau n k}
    (h : Path.StructCheck Gamma R p d) :
    forall {m : Nat} {f : FinFun n m} {Delta : Ctx m}
      {E : Path m -> Path m -> Prop},
      Path.StructRenaming Gamma f Delta E ->
      Path.RelHom R E f ->
      Path.StructCheck Delta E (p.rename f) (d.rename f) := by
  induction h using Path.StructCheck.rec
      (motive_2 := SubRenameMotive) with
  | var hb =>
      intro m f Delta E rho hrel
      exact rho hb
  | sub hp hs ihp ihs =>
      intro m f Delta E rho hrel
      exact .sub (ihp rho hrel) (ihs rho hrel)
  | promote hp hs ihp ihs =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Path.StructCheck.promote (ihp rho hrel) (ihs rho hrel)
  | fst hp ih =>
      intro m f Delta E rho hrel
      simpa [Path.rename, Tau.rename, Ty.rename] using
        Path.StructCheck.fst (ih rho hrel)
  | sel_r hp ih =>
      intro m f Delta E rho hrel
      simpa [Path.rename, Tau.rename, Ty.rename, Tau.open_rename] using
        Path.StructCheck.sel_r (ih rho hrel)
  | sel_l hp htail hne ihp ihtail =>
      intro m f Delta E rho hrel
      simpa [Path.rename, Tau.rename, Ty.rename] using
        Path.StructCheck.sel_l (ihp rho hrel) (ihtail rho hrel) hne
  | refl =>
      intro m f Delta E rho hrel
      exact .refl
  | trans h1 h2 ih1 ih2 =>
      intro m f Delta E rho hrel
      exact .trans (ih1 rho hrel) (ih2 rho hrel)
  | conv hconv =>
      intro m f Delta E rho hrel
      exact .conv (hconv.rename hrel)
  | bot =>
      intro m f Delta E rho hrel
      simp only [Tau.rename, Ty.rename]
      exact .bot
  | top =>
      intro m f Delta E rho hrel
      simp only [Tau.rename, Ty.rename]
      exact .top
  | widen hp ih =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.widen (ih rho hrel)
  | symm hp ih =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.symm (ih rho hrel)
  | sel_hi hp hbounds ihp ihbounds =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.sel_hi (ihp rho hrel) (ihbounds rho hrel)
  | sel_lo hp hbounds ihp ihbounds =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.sel_lo (ihp rho hrel) (ihbounds rho hrel)
  | «fun» hdom hcod ihdom ihcod =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename] using
        Tau.StructSub.fun (ihdom rho hrel)
          (ihcod rho.ext hrel.scoped)
  | pair_fst hfst ihfst =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename] using
        Tau.StructSub.pair_fst (ihfst rho hrel)
  | pair_single_member hp hsnd hopen ihp ihsnd ihopen =>
      intro m f Delta E rho hrel
      have hopen' := ihopen rho hrel
      rw [Tau.open_rename, Tau.open_rename] at hopen'
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.pair_single_member (ihp rho hrel)
          (ihsnd rho.ext hrel.scoped) hopen'
  | bounds hlo hhi hnonempty ihlo ihhi ihnonempty =>
      intro m f Delta E rho hrel
      simpa [Tau.rename] using
        Tau.StructSub.bounds (ihlo rho hrel) (ihhi rho hrel)
          (ihnonempty rho hrel)

/-- Structural generalized subtyping is stable under structural renaming. -/
theorem Tau.StructSub.rename
    {n : Nat} {Gamma : Ctx n}
    {R : Path n -> Path n -> Prop} {k : Kind}
    {d1 d2 : Tau n k}
    (h : Tau.StructSub Gamma R d1 d2) :
    forall {m : Nat} {f : FinFun n m} {Delta : Ctx m}
      {E : Path m -> Path m -> Prop},
      Path.StructRenaming Gamma f Delta E ->
      Path.RelHom R E f ->
      Tau.StructSub Delta E (d1.rename f) (d2.rename f) := by
  induction h using Tau.StructSub.rec
      (motive_1 := PathRenameMotive) with
  | var hb =>
      intro m f Delta E rho hrel
      exact rho hb
  | sub hp hs ihp ihs =>
      intro m f Delta E rho hrel
      exact .sub (ihp rho hrel) (ihs rho hrel)
  | promote hp hs ihp ihs =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Path.StructCheck.promote (ihp rho hrel) (ihs rho hrel)
  | fst hp ih =>
      intro m f Delta E rho hrel
      simpa [Path.rename, Tau.rename, Ty.rename] using
        Path.StructCheck.fst (ih rho hrel)
  | sel_r hp ih =>
      intro m f Delta E rho hrel
      simpa [Path.rename, Tau.rename, Ty.rename, Tau.open_rename] using
        Path.StructCheck.sel_r (ih rho hrel)
  | sel_l hp htail hne ihp ihtail =>
      intro m f Delta E rho hrel
      simpa [Path.rename, Tau.rename, Ty.rename] using
        Path.StructCheck.sel_l (ihp rho hrel) (ihtail rho hrel) hne
  | refl =>
      intro m f Delta E rho hrel
      exact .refl
  | trans h1 h2 ih1 ih2 =>
      intro m f Delta E rho hrel
      exact .trans (ih1 rho hrel) (ih2 rho hrel)
  | conv hconv =>
      intro m f Delta E rho hrel
      exact .conv (hconv.rename hrel)
  | bot =>
      intro m f Delta E rho hrel
      simp only [Tau.rename, Ty.rename]
      exact .bot
  | top =>
      intro m f Delta E rho hrel
      simp only [Tau.rename, Ty.rename]
      exact .top
  | widen hp ih =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.widen (ih rho hrel)
  | symm hp ih =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.symm (ih rho hrel)
  | sel_hi hp hbounds ihp ihbounds =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.sel_hi (ihp rho hrel) (ihbounds rho hrel)
  | sel_lo hp hbounds ihp ihbounds =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.sel_lo (ihp rho hrel) (ihbounds rho hrel)
  | «fun» hdom hcod ihdom ihcod =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename] using
        Tau.StructSub.fun (ihdom rho hrel)
          (ihcod rho.ext hrel.scoped)
  | pair_fst hfst ihfst =>
      intro m f Delta E rho hrel
      simpa [Tau.rename, Ty.rename] using
        Tau.StructSub.pair_fst (ihfst rho hrel)
  | pair_single_member hp hsnd hopen ihp ihsnd ihopen =>
      intro m f Delta E rho hrel
      have hopen' := ihopen rho hrel
      rw [Tau.open_rename, Tau.open_rename] at hopen'
      simpa [Tau.rename, Ty.rename, Path.rename] using
        Tau.StructSub.pair_single_member (ihp rho hrel)
          (ihsnd rho.ext hrel.scoped) hopen'
  | bounds hlo hhi hnonempty ihlo ihhi ihnonempty =>
      intro m f Delta E rho hrel
      simpa [Tau.rename] using
        Tau.StructSub.bounds (ihlo rho hrel) (ihhi rho hrel)
          (ihnonempty rho hrel)

end

/-! ## One-binder opening -/

/-- Renaming the newest variable to `x` is the same operation on paths as
opening by the variable path `x`. -/
theorem Path.rename_openAt_eq_open_var
    (p : Path (n + 1)) (x : Fin n) :
    p.rename (FinFun.openAt x) = p.open (.var x) := by
  induction p with
  | var y =>
      refine Fin.cases ?_ (fun z => ?_) y <;> rfl
  | fst p ih =>
      simpa [Path.rename, Path.open, Path.subst] using congrArg Path.fst ih
  | sel p a ih =>
      simpa [Path.rename, Path.open, Path.subst] using
        congrArg (fun q => Path.sel q a) ih

/-- Opening discharges the scoped relation: the bound variable is replaced
by `x`, related to itself by ambient reflexivity. -/
theorem Path.RelHom.openAt
    {n : Nat} {R : Path n -> Path n -> Prop}
    (hR : Path.IsEquivCongr R) (x : Fin n) :
    Path.RelHom (Path.ScopedLift R) R (FinFun.openAt x) := by
  intro p q hpq
  rw [Path.rename_openAt_eq_open_var, Path.rename_openAt_eq_open_var]
  exact Path.ScopedLift.open_paths hR hpq (hR.refl (.var x))

/-- If the replacement variable checks at the binder type, opening maps the
extended context structurally into the outer context. -/
theorem Path.StructRenaming.openAt
    (hx : Path.StructCheck Gamma R (.var x) (Tau.ty S)) :
    Path.StructRenaming (Gamma.snoc S) (FinFun.openAt x) Gamma R := by
  intro y T hy
  cases hy with
  | here =>
      simpa only [FinFun.openAt_zero, Path.rename, Tau.rename,
        LambdaP.Ty.weaken,
        LambdaP.Ty.rename_rename, FinFun.openAt_weaken,
        LambdaP.Ty.rename_id] using hx
  | there hy =>
      simpa only [FinFun.openAt_succ, Path.rename, Tau.rename,
        LambdaP.Ty.weaken,
        LambdaP.Ty.rename_rename, FinFun.openAt_weaken,
        LambdaP.Ty.rename_id] using
        (Path.StructCheck.var (R := R) hy)

/-- One-binder opening for structural path checking. -/
theorem Path.StructCheck.open_var
    (h : Path.StructCheck (Gamma.snoc S) (Path.ScopedLift R) p d)
    (hR : Path.IsEquivCongr R)
    (hx : Path.StructCheck Gamma R (.var x) (Tau.ty S)) :
    Path.StructCheck Gamma R
      (p.rename (FinFun.openAt x))
      (d.rename (FinFun.openAt x)) :=
  h.rename (Path.StructRenaming.openAt hx) (Path.RelHom.openAt hR x)

/-- One-binder opening for structural generalized subtyping. -/
theorem Tau.StructSub.open_var
    (h : Tau.StructSub (Gamma.snoc S) (Path.ScopedLift R) d1 d2)
    (hR : Path.IsEquivCongr R)
    (hx : Path.StructCheck Gamma R (.var x) (Tau.ty S)) :
    Tau.StructSub Gamma R
      (d1.rename (FinFun.openAt x))
      (d2.rename (FinFun.openAt x)) :=
  h.rename (Path.StructRenaming.openAt hx) (Path.RelHom.openAt hR x)

/-- Operational typing normally supplies a precise/checkable type for `x`
and a separate singleton subtyping premise `{x} <: S`.  Singleton promotion
turns exactly those premises into the hypothesis of `open_var`. -/
theorem Path.StructCheck.open_var_of_singleton
    (h : Path.StructCheck (Gamma.snoc S) (Path.ScopedLift R) p d)
    (hR : Path.IsEquivCongr R)
    (hx : Path.StructCheck Gamma R (.var x) (Tau.ty U))
    (hsub : Tau.StructSub Gamma R
      (Tau.ty (Ty.Single (.var x))) (Tau.ty S)) :
    Path.StructCheck Gamma R
      (p.rename (FinFun.openAt x))
      (d.rename (FinFun.openAt x)) :=
  h.open_var hR (Path.StructCheck.promote hx hsub)

/-- Singleton-based form of one-binder opening for subtyping. -/
theorem Tau.StructSub.open_var_of_singleton
    (h : Tau.StructSub (Gamma.snoc S) (Path.ScopedLift R) d1 d2)
    (hR : Path.IsEquivCongr R)
    (hx : Path.StructCheck Gamma R (.var x) (Tau.ty U))
    (hsub : Tau.StructSub Gamma R
      (Tau.ty (Ty.Single (.var x))) (Tau.ty S)) :
    Tau.StructSub Gamma R
      (d1.rename (FinFun.openAt x))
      (d2.rename (FinFun.openAt x)) :=
  h.open_var hR (Path.StructCheck.promote hx hsub)

end LambdaP
