import LambdaP.StructuralPathSubstitution

/-!
Outer-constructor inversion for structural runtime conversion.

The only subtle case is `StructConv.replace` below a function or pair
binder.  Opening the outer replacement variable after entering that binder
does not use `open p.weaken` directly: the fresh component binder occupies
index zero.  We first swap indices zero and one, then open at `p.weaken`.
The `swap01_open_weaken` lemma identifies that expression with the lifted
opening substitution generated by `Ty.subst`/`Tau.subst`.
-/

namespace LambdaP

namespace PathSubst

/-- Exchange the two newest variables and leave all older variables fixed. -/
def swap01 : PathSubst (n + 2) (n + 2) := fun x =>
  Fin.cases (.var 1)
    (fun y => Fin.cases (.var 0)
      (fun z => .var z.succ.succ) y) x

@[simp] theorem swap01_zero :
    swap01 (n := n) 0 = Path.var 1 := rfl

@[simp] theorem swap01_one :
    swap01 (n := n) 1 = Path.var 0 := rfl

@[simp] theorem swap01_succ_succ (x : Fin n) :
    swap01 (n := n) x.succ.succ = Path.var x.succ.succ := rfl

end PathSubst

/-- Swapping the component binder with the outer replacement variable and
then opening is exactly capture-avoiding lifted opening. -/
theorem Tau.swap01_open_weaken
    (template : Tau (n + 2) k) (p : Path n) :
    (template.subst PathSubst.swap01).open p.weaken =
      template.subst (PathSubst.openAt p).lift := by
  unfold Tau.open
  rw [Tau.subst_subst]
  apply congrArg (fun rho => template.subst rho)
  funext x
  refine Fin.cases ?_ (fun y => ?_) x
  · rfl
  · refine Fin.cases ?_ (fun z => ?_) y
    · rfl
    · rfl

/-! ## Constructor tags -/

private inductive Tau.ConvTag : Type where
| top | bot | function | pair (a : Name) (k : Kind)
| single | tsel | interval
deriving DecidableEq

private def Ty.convTag : Ty n -> Tau.ConvTag
| .Top => .top
| .Bot => .bot
| .Fun _ _ => .function
| .Pair (k := k) _ a _ => .pair a k
| .Single _ => .single
| .TSel _ _ => .tsel

private def Tau.convTag : Tau n k -> Tau.ConvTag
| .ty T => T.convTag
| .intv _ _ => .interval

@[simp] private theorem Ty.convTag_open (T : Ty (n + 1)) (p : Path n) :
    (T.open p).convTag = T.convTag := by
  cases T <;> rfl

@[simp] private theorem Tau.convTag_open
    (d : Tau (n + 1) k) (p : Path n) :
    (d.open p).convTag = d.convTag := by
  cases d with
  | ty T => exact Ty.convTag_open T p
  | intv L U => rfl

private theorem Tau.StructConv.convTag_eq
    (h : Tau.StructConv R d1 d2) : d1.convTag = d2.convTag := by
  induction h with
  | refl => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih1 ih2 => exact ih1.trans ih2
  | replace template hpq => simp only [Tau.convTag_open]

/-! ## Function conversion -/

private theorem Tau.StructConv.fun_parts_aux
    {n : Nat} {R : Path n -> Path n -> Prop}
    {d1 d2 : Tau n .star}
    (h : Tau.StructConv R d1 d2) :
    forall S1 U1, d1 = Tau.ty (Ty.Fun S1 U1) ->
    forall S2 U2, d2 = Tau.ty (Ty.Fun S2 U2) ->
      Tau.StructConv R (Tau.ty S1) (Tau.ty S2) /\
      Tau.StructConv (Path.ScopedLift R)
        (Tau.ty U1) (Tau.ty U2) := by
  induction h with
  | refl =>
      intro S1 U1 h1 S2 U2 h2
      cases h1
      cases h2
      exact ⟨.refl, .refl⟩
  | @symm d1 d2 h ih =>
      intro S1 U1 h1 S2 U2 h2
      obtain ⟨hdom, hcod⟩ := ih S2 U2 h2 S1 U1 h1
      exact ⟨hdom.symm, hcod.symm⟩
  | @trans d1 d2 d3 h1 h2 ih1 ih2 =>
      intro S1 U1 hstart S3 U3 hend
      cases hstart
      cases hend
      have htag := h1.convTag_eq
      cases d2 with
      | ty T2 =>
          cases T2 with
          | Top => cases htag
          | Bot => cases htag
          | Fun S2 U2 =>
              obtain ⟨hdom1, hcod1⟩ := ih1 S1 U1 rfl S2 U2 rfl
              obtain ⟨hdom2, hcod2⟩ := ih2 S2 U2 rfl S3 U3 rfl
              exact ⟨hdom1.trans hdom2, hcod1.trans hcod2⟩
          | Pair S2 a d => cases htag
          | Single p => cases htag
          | TSel p A => cases htag
  | @replace p q template hpq =>
      intro S1 U1 h1 S2 U2 h2
      cases template with
      | ty T =>
          cases T with
          | Top => cases h1
          | Bot => cases h1
          | Fun A B =>
              simp only [Tau.open, Tau.subst, Ty.subst] at h1 h2
              cases h1
              cases h2
              constructor
              · exact Tau.StructConv.replace (template := Tau.ty A) hpq
              · have hc := Tau.StructConv.replace
                  (R := Path.ScopedLift R)
                  (template := (Tau.ty B).subst PathSubst.swap01)
                  (Path.ScopedLift.old hpq)
                simpa only [Tau.swap01_open_weaken] using hc
          | Pair A a d => cases h1
          | Single r => cases h1
          | TSel r A => cases h1

/-- Runtime conversion between function types decomposes into conversion of
the domains and conversion of the codomains under the scoped relation. -/
theorem Tau.StructConv.fun_parts
    (h : Tau.StructConv R
      (Tau.ty (Ty.Fun S1 U1)) (Tau.ty (Ty.Fun S2 U2))) :
    Tau.StructConv R (Tau.ty S1) (Tau.ty S2) /\
      Tau.StructConv (Path.ScopedLift R)
        (Tau.ty U1) (Tau.ty U2) :=
  h.fun_parts_aux S1 U1 rfl S2 U2 rfl

/-! ## Pair conversion -/

private theorem Tau.StructConv.pair_parts_aux
    {n : Nat} {R : Path n -> Path n -> Prop}
    {d1 d2 : Tau n .star}
    (h : Tau.StructConv R d1 d2) :
    forall S1 a1 k1 (m1 : Tau (n + 1) k1),
      d1 = Tau.ty (Ty.Pair S1 a1 m1) ->
    forall S2 a2 k2 (m2 : Tau (n + 1) k2),
      d2 = Tau.ty (Ty.Pair S2 a2 m2) ->
      a1 = a2 /\ k1 = k2 := by
  induction h with
  | refl =>
      intro S1 a1 k1 m1 h1 S2 a2 k2 m2 h2
      cases h1
      cases h2
      exact ⟨rfl, rfl⟩
  | @symm d1 d2 h ih =>
      intro S1 a1 k1 m1 h1 S2 a2 k2 m2 h2
      obtain ⟨ha, hk⟩ := ih S2 a2 k2 m2 h2 S1 a1 k1 m1 h1
      exact ⟨ha.symm, hk.symm⟩
  | @trans d1 d2 d3 h1 h2 ih1 ih2 =>
      intro S1 a1 k1 m1 hstart S3 a3 k3 m3 hend
      cases hstart
      cases hend
      have htag := h1.convTag_eq
      cases d2 with
      | ty T2 =>
          cases T2 with
          | Top => cases htag
          | Bot => cases htag
          | Fun S U => cases htag
          | Pair S2 a2 m2 =>
              obtain ⟨ha1, hk1⟩ :=
                ih1 S1 a1 k1 m1 rfl S2 a2 _ m2 rfl
              obtain ⟨ha2, hk2⟩ :=
                ih2 S2 a2 _ m2 rfl S3 a3 k3 m3 rfl
              exact ⟨ha1.trans ha2, hk1.trans hk2⟩
          | Single p => cases htag
          | TSel p A => cases htag
  | @replace p q template hpq =>
      intro S1 a1 k1 m1 h1 S2 a2 k2 m2 h2
      cases template with
      | ty T =>
          cases T with
          | Top => cases h1
          | Bot => cases h1
          | Fun A B => cases h1
          | Pair A a d =>
              simp only [Tau.open, Tau.subst, Ty.subst] at h1 h2
              cases h1
              cases h2
              exact ⟨rfl, rfl⟩
          | Single r => cases h1
          | TSel r A => cases h1

/-- Conversion between pair types preserves the member label and kind. -/
theorem Tau.StructConv.pair_label_kind
    {k1 k2 : Kind}
    {m1 : Tau (n + 1) k1} {m2 : Tau (n + 1) k2}
    (h : Tau.StructConv R
      (Tau.ty (Ty.Pair S1 a1 m1)) (Tau.ty (Ty.Pair S2 a2 m2))) :
    a1 = a2 /\ k1 = k2 :=
  h.pair_parts_aux S1 a1 k1 m1 rfl S2 a2 k2 m2 rfl

private theorem Tau.StructConv.pair_components_aux
    {n : Nat} {R : Path n -> Path n -> Prop}
    {d1 d2 : Tau n .star}
    (h : Tau.StructConv R d1 d2) :
    forall S1 a k (m1 : Tau (n + 1) k),
      d1 = Tau.ty (Ty.Pair S1 a m1) ->
    forall S2 (m2 : Tau (n + 1) k),
      d2 = Tau.ty (Ty.Pair S2 a m2) ->
      Tau.StructConv R (Tau.ty S1) (Tau.ty S2) /\
      Tau.StructConv (Path.ScopedLift R) m1 m2 := by
  induction h with
  | refl =>
      intro S1 a k m1 h1 S2 m2 h2
      cases h1
      cases h2
      exact ⟨.refl, .refl⟩
  | @symm d1 d2 h ih =>
      intro S1 a k m1 h1 S2 m2 h2
      obtain ⟨hfirst, hmember⟩ := ih S2 a k m2 h2 S1 m1 h1
      exact ⟨hfirst.symm, hmember.symm⟩
  | @trans d1 d2 d3 h1 h2 ih1 ih2 =>
      intro S1 a k m1 hstart S3 m3 hend
      cases hstart
      cases hend
      have htag := h1.convTag_eq
      cases d2 with
      | ty T2 =>
          cases T2 with
          | Top => cases htag
          | Bot => cases htag
          | Fun S U => cases htag
          | Pair S2 a2 m2 =>
              simp only [Tau.convTag, Ty.convTag] at htag
              injection htag with hlabel hkind
              cases hlabel
              cases hkind
              obtain ⟨hfirst1, hmember1⟩ :=
                ih1 S1 a k m1 rfl S2 m2 rfl
              obtain ⟨hfirst2, hmember2⟩ :=
                ih2 S2 a k m2 rfl S3 m3 rfl
              exact ⟨hfirst1.trans hfirst2,
                hmember1.trans hmember2⟩
          | Single p => cases htag
          | TSel p A => cases htag
  | @replace p q template hpq =>
      intro S1 a k m1 h1 S2 m2 h2
      cases template with
      | ty T =>
          cases T with
          | Top => cases h1
          | Bot => cases h1
          | Fun A B => cases h1
          | Pair A b d =>
              simp only [Tau.open, Tau.subst, Ty.subst] at h1 h2
              cases h1
              cases h2
              constructor
              · exact Tau.StructConv.replace (template := Tau.ty A) hpq
              · have hc := Tau.StructConv.replace
                  (R := Path.ScopedLift R)
                  (template := d.subst PathSubst.swap01)
                  (Path.ScopedLift.old hpq)
                simpa only [Tau.swap01_open_weaken] using hc
          | Single r => cases h1
          | TSel r A => cases h1

/-- Once the common label and member kind have been exposed, pair conversion
decomposes into first-component conversion and scoped member conversion. -/
theorem Tau.StructConv.pair_components
    {k : Kind} {m1 m2 : Tau (n + 1) k}
    (h : Tau.StructConv R
      (Tau.ty (Ty.Pair S1 a m1)) (Tau.ty (Ty.Pair S2 a m2))) :
    Tau.StructConv R (Tau.ty S1) (Tau.ty S2) /\
      Tau.StructConv (Path.ScopedLift R) m1 m2 :=
  h.pair_components_aux S1 a k m1 rfl S2 m2 rfl

/-! ## Leaf conversion -/

private theorem Tau.StructConv.single_paths_aux
    (hR : Path.IsEquivCongr R)
    (h : Tau.StructConv R d1 d2) :
    forall p, d1 = Tau.ty (Ty.Single p) ->
    forall q, d2 = Tau.ty (Ty.Single q) -> R p q := by
  induction h with
  | refl =>
      intro p h1 q h2
      cases h1
      cases h2
      exact hR.refl p
  | @symm d1 d2 h ih =>
      intro p h1 q h2
      exact hR.symm (ih q h2 p h1)
  | @trans d1 d2 d3 h1 h2 ih1 ih2 =>
      intro p hstart r hend
      cases hstart
      cases hend
      have htag := h1.convTag_eq
      cases d2 with
      | ty T2 =>
          cases T2 with
          | Top => cases htag
          | Bot => cases htag
          | Fun S U => cases htag
          | Pair S a d => cases htag
          | Single q =>
              exact hR.trans (ih1 p rfl q rfl) (ih2 q rfl r rfl)
          | TSel q A => cases htag
  | @replace p q template hpq =>
      intro r h1 s h2
      cases template with
      | ty T =>
          cases T with
          | Top => cases h1
          | Bot => cases h1
          | Fun A B => cases h1
          | Pair A a d => cases h1
          | Single template =>
              simp only [Tau.open, Tau.subst, Ty.subst] at h1 h2
              cases h1
              cases h2
              exact hR.open_context hpq template
          | TSel template A => cases h1

/-- Conversion of singleton types is generated by the underlying path
relation, provided that relation supplies its advertised equivalence and
congruence laws. -/
theorem Tau.StructConv.single_paths
    (hR : Path.IsEquivCongr R)
    (h : Tau.StructConv R
      (Tau.ty (Ty.Single p)) (Tau.ty (Ty.Single q))) :
    R p q :=
  h.single_paths_aux hR p rfl q rfl

private theorem Tau.StructConv.tsel_parts_aux
    (hR : Path.IsEquivCongr R)
    (h : Tau.StructConv R d1 d2) :
    forall p A, d1 = Tau.ty (Ty.TSel p A) ->
    forall q B, d2 = Tau.ty (Ty.TSel q B) ->
      A = B /\ R p q := by
  induction h with
  | refl =>
      intro p A h1 q B h2
      cases h1
      cases h2
      exact ⟨rfl, hR.refl p⟩
  | @symm d1 d2 h ih =>
      intro p A h1 q B h2
      obtain ⟨hlabel, hpath⟩ := ih q B h2 p A h1
      exact ⟨hlabel.symm, hR.symm hpath⟩
  | @trans d1 d2 d3 h1 h2 ih1 ih2 =>
      intro p A hstart r C hend
      cases hstart
      cases hend
      have htag := h1.convTag_eq
      cases d2 with
      | ty T2 =>
          cases T2 with
          | Top => cases htag
          | Bot => cases htag
          | Fun S U => cases htag
          | Pair S a d => cases htag
          | Single q => cases htag
          | TSel q B =>
              obtain ⟨hab, hpq⟩ := ih1 p A rfl q B rfl
              obtain ⟨hbc, hqr⟩ := ih2 q B rfl r C rfl
              exact ⟨hab.trans hbc, hR.trans hpq hqr⟩
  | @replace p q template hpq =>
      intro r A h1 s B h2
      cases template with
      | ty T =>
          cases T with
          | Top => cases h1
          | Bot => cases h1
          | Fun X Y => cases h1
          | Pair X a d => cases h1
          | Single template => cases h1
          | TSel template C =>
              simp only [Tau.open, Tau.subst, Ty.subst] at h1 h2
              cases h1
              cases h2
              exact ⟨rfl, hR.open_context hpq template⟩

/-- Type-selection conversion preserves the label and converts only the
selected receiver path. -/
theorem Tau.StructConv.tsel_parts
    (hR : Path.IsEquivCongr R)
    (h : Tau.StructConv R
      (Tau.ty (Ty.TSel p A)) (Tau.ty (Ty.TSel q B))) :
    A = B /\ R p q :=
  h.tsel_parts_aux hR p A rfl q B rfl

/-! ## Nullary and interval conversion -/

theorem Tau.StructConv.top_target_eq
    (h : Tau.StructConv R (Tau.ty Ty.Top) (Tau.ty T)) :
    T = Ty.Top := by
  have htag := h.convTag_eq
  cases T <;> simp_all [Tau.convTag, Ty.convTag]

theorem Tau.StructConv.top_source_eq
    (h : Tau.StructConv R (Tau.ty T) (Tau.ty Ty.Top)) :
    T = Ty.Top :=
  h.symm.top_target_eq

theorem Tau.StructConv.bot_target_eq
    (h : Tau.StructConv R (Tau.ty Ty.Bot) (Tau.ty T)) :
    T = Ty.Bot := by
  have htag := h.convTag_eq
  cases T <;> simp_all [Tau.convTag, Ty.convTag]

theorem Tau.StructConv.bot_source_eq
    (h : Tau.StructConv R (Tau.ty T) (Tau.ty Ty.Bot)) :
    T = Ty.Bot :=
  h.symm.bot_target_eq

private theorem Tau.StructConv.interval_components_aux
    (h : Tau.StructConv R d1 d2) :
    forall L1 U1, d1 = Tau.intv L1 U1 ->
    forall L2 U2, d2 = Tau.intv L2 U2 ->
      Tau.StructConv R (Tau.ty L1) (Tau.ty L2) /\
      Tau.StructConv R (Tau.ty U1) (Tau.ty U2) := by
  induction h with
  | refl =>
      intro L1 U1 h1 L2 U2 h2
      cases h1
      cases h2
      exact ⟨.refl, .refl⟩
  | @symm d1 d2 h ih =>
      intro L1 U1 h1 L2 U2 h2
      obtain ⟨hlo, hhi⟩ := ih L2 U2 h2 L1 U1 h1
      exact ⟨hlo.symm, hhi.symm⟩
  | @trans d1 d2 d3 h1 h2 ih1 ih2 =>
      intro L1 U1 hstart L3 U3 hend
      cases hstart
      cases hend
      cases d2 with
      | intv L2 U2 =>
          obtain ⟨hlo1, hhi1⟩ := ih1 L1 U1 rfl L2 U2 rfl
          obtain ⟨hlo2, hhi2⟩ := ih2 L2 U2 rfl L3 U3 rfl
          exact ⟨hlo1.trans hlo2, hhi1.trans hhi2⟩
  | @replace p q template hpq =>
      intro L1 U1 h1 L2 U2 h2
      cases template with
      | intv L U =>
          cases h1
          cases h2
          exact ⟨.replace (Tau.ty L) hpq,
            .replace (Tau.ty U) hpq⟩

/-- Interval conversion acts componentwise (contravariance belongs to
subtyping, not conversion, so both components have the same direction). -/
theorem Tau.StructConv.interval_components
    (h : Tau.StructConv R
      (Tau.intv L1 U1) (Tau.intv L2 U2)) :
    Tau.StructConv R (Tau.ty L1) (Tau.ty L2) /\
      Tau.StructConv R (Tau.ty U1) (Tau.ty U2) :=
  h.interval_components_aux L1 U1 rfl L2 U2 rfl

end LambdaP
