import LambdaPToFCo.Full.TypingViews
import LambdaPToFCo.Full.ValueTypingViews
import LambdaPToFCo.Full.ContextWellFormed
import LambdaPToFCo.Full.PathTermWellFormed
import LambdaPToFCo.Full.IntroductionResultWellFormed
import LambdaPToFCo.Full.IdentityRegression
import LambdaPToFCo.Full.IllWfSubtypingRegression
import LambdaPToFCo.Full.PathTypingUniqueness
import LambdaPToFCo.Full.PathRootFactorizationRegression
import LambdaPToFCo.Full.ContextSubtyping
import LambdaPToFCo.Full.TranslationOrigins
import LambdaPToFCo.Full.OriginConstruction
import LambdaPToFCo.Full.ValueModel
import LambdaPToFCo.Full.AtomicModels
import LambdaPToFCo.Full.FunctionModel
import LambdaPToFCo.Full.PairModel
import LambdaPToFCo.Full.ValueInterface
import LambdaPToFCo.Full.PlanScope
import LambdaPToFCo.Full.ScopeView
import LambdaPToFCo.Full.InterfaceSubstitution
import LambdaPToFCo.Full.InterfaceArgumentCancellation
import LambdaPToFCo.Full.InterfacePackageBridge
import LambdaPToFCo.Full.FunctionInterface
import LambdaPToFCo.Full.PairInterface
import LambdaPToFCo.Full.TelescopeArgumentSplit
import LambdaPToFCo.Full.PathPackageZipper
import LambdaPToFCo.Full.PathPackageClosure
import LambdaPToFCo.Full.StableIdentity
import LambdaPToFCo.Full.StableIdentitySubstitution
import LambdaPToFCo.Full.FunctionStableAdapter
import LambdaPToFCo.Full.PairStableAdapter
import LambdaPToFCo.Full.StableIdentityReduction
import LambdaPToFCo.Full.TranslationModelCore
import LambdaPToFCo.Full.TranslationInterfaces
import LambdaPToFCo.Full.TargetModelRenaming
import LambdaPToFCo.Full.ScopeModelBinding
import LambdaPToFCo.Full.PairedInstantiation
import LambdaPToFCo.Full.ConstructedScopeInstantiation
import LambdaPToFCo.Full.ProducerPairHead
import LambdaPToFCo.Full.ModelInstantiationCoherence
import LambdaPToFCo.Full.ProducerPairProjection
import LambdaPToFCo.Full.ProperMemberOpening
import LambdaPToFCo.Full.ProperPairMemberPackage
import LambdaPToFCo.Full.ScopedPathResolution
import LambdaPToFCo.Full.FocusedPathTranslationCore
import LambdaPToFCo.Full.ProperSelectionConstruction
import LambdaPToFCo.Full.WfPlan
import LambdaPToFCo.Full.SubtypingCompilerCore
import LambdaPToFCo.Full.IntervalSubtypingCompilerCore
import LambdaPToFCo.Full.AtomicSubtypingCompiler
import LambdaPToFCo.Full.TranslationModelRebase
import LambdaPToFCo.Full.DemandDirectedSubtyping
import LambdaPToFCo.Full.HeterogeneousAdaptation
import LambdaPToFCo.Full.HeterogeneousPlanAdaptation
import LambdaPToFCo.Full.FunctionCodeBridgeConstruction
import LambdaPToFCo.Full.FunctionSubtypingRuleConstruction
import LambdaPToFCo.Full.PairRepresentationBridgeConstruction
import LambdaPToFCo.Full.PairSubtypingRuleConstruction
import LambdaPToFCo.Full.IntervalPairRepresentationBridgeConstruction
import LambdaPToFCo.Full.IntervalPairSubtypingRuleConstruction
import LambdaPToFCo.Full.DemandDirectedPairSubtyping
import LambdaPToFCo.Full.IntroductionCompiler
import LambdaPToFCo.Full.PairIntroductionCompiler
import LambdaPToFCo.Full.RecordIntroductionStaticRegression
import LambdaPToFCo.Full.GeneralPairIntroductionStaticRegression
import LambdaPToFCo.Full.GeneralPairLetPlanningRegression
import LambdaPToFCo.Full.GeneralPairObservedIntervalSubtypingRegression
import LambdaPToFCo.Full.GeneralPairCanonicalIntervalSubtypingRegression
import LambdaPToFCo.Full.GeneralPairClosedStaticRegression
import LambdaPToFCo.Full.ApplicationCompilerCore
import LambdaPToFCo.Full.ApplicationPlanning
import LambdaPToFCo.Full.LetCompilerCore
import LambdaPToFCo.Full.LetPlanning

/-!
# Full LambdaPFC compilation track

This aggregate exposes the constructor-complete compiler development that
targets the separate `SystemFCoExt` calculus.  It is intentionally distinct
from the existing restricted `LambdaPToFCo` aggregate and will become the
public full compiler entry point as the remaining path, subtyping, term, and
operational layers land.

No module imported here changes or extends the original `SystemFCo` library.
-/
