import LambdaPToFCo.OperationalApplication

/-!
# Value normalization for generated application-result contexts

`OperationalApplication.ResultContext` deliberately promises only closure
under reduction.  That is the correct interface for an arbitrary result
context: a structural cast around a value is itself an observable target
value and does not discharge to the original expression.

The contexts generated by the application macro satisfy one additional,
separate property in the closed target language.  If their hole contains a
value, they reduce to *some* value.  Transparent `Resume` administration
discharges, while a structural cast may remain in the resulting value.

This module packages that stronger generated-context property without
changing the target-only `ApplicationView` API.
-/

namespace LambdaPToFCo
namespace OperationalResultContext

open SystemFCo
open OperationalApplication
open OperationalBindingView

/-- A closed target expression reduces to a target value.  The endpoint is
explicit because structural casts need not disappear. -/
structure ValueNormalization (expression : Exp []) : Type where
  result : Exp []
  ready : Exp.IsValue result
  reductions : Exp.Steps expression result

/-- A result context generated from transparent resumes and closed casts.

Besides ordinary reduction closure, it records that plugging a ready
expression can be normalized to some ready target expression.  Indexing the
property by the underlying `ResultContext` lets it attach directly to the
context field of an existing `ApplicationView`. -/
structure GeneratedResultContext (context : ResultContext []) : Type where
  normalize : forall {value : Exp []}, Exp.IsValue value ->
    ValueNormalization (context.plug value)

namespace GeneratedResultContext

/-- The empty generated context leaves a ready expression unchanged. -/
def identity : GeneratedResultContext .identity where
  normalize := fun ready =>
    { result := _
      ready := ready
      reductions := .refl }

/-- A transparent administrative resume normalizes back to the same value. -/
def ofResume (resume : Resume []) :
    GeneratedResultContext (.ofResume resume) where
  normalize := fun ready =>
    { result := _
      ready := ready
      reductions := resume.discharge ready }

/-- Add one genuine closed cast outside a generated context.

The inner context first reaches a value.  Closed-cast normalization then
performs only reflexive/transitive administration; structural casts remain
as value wrappers. -/
def cast {context : ResultContext []}
    (inner : GeneratedResultContext context) (coercion : Co []) :
    GeneratedResultContext (context.cast coercion) where
  normalize := fun ready =>
    let innerNormalization := inner.normalize ready
    let castNormalization := CastNormalization.closed
      innerNormalization.ready coercion
    { result := castNormalization.result
      ready := castNormalization.ready
      reductions :=
        (OperationalApplication.Steps.castExpression
          innerNormalization.reductions).trans
            castNormalization.reductions }

/-- Compose generated contexts, keeping `outer` syntactically outside
`inner`. -/
def compose {outerContext innerContext : ResultContext []}
    (outer : GeneratedResultContext outerContext)
    (inner : GeneratedResultContext innerContext) :
    GeneratedResultContext (outerContext.compose innerContext) where
  normalize := fun ready =>
    let innerNormalization := inner.normalize ready
    let outerNormalization := outer.normalize innerNormalization.ready
    { result := outerNormalization.result
      ready := outerNormalization.ready
      reductions :=
        (outerContext.steps innerNormalization.reductions).trans
          outerNormalization.reductions }

end GeneratedResultContext

/-- Proof that the residual context of one existing application view is a
generated, value-normalizing context. -/
abbrev GeneratedApplicationView
    {plan : Interface.BinderPlan []} {body : Exp plan.scope}
    {function argument : Exp []}
    (application : ApplicationView body function argument) : Type :=
  GeneratedResultContext application.context

end OperationalResultContext

namespace OperationalApplication

open OperationalResultContext

namespace FunctionValue

/-- The residual context produced by canonical function application carries
the stronger closed value-normalization property. -/
def generatedApplication
    (functionView : FunctionValue plan result body)
    (argumentView : ArgumentView functionView argument) :
    GeneratedApplicationView (functionView.application argumentView) :=
  match functionView, argumentView with
  | .lambda, .lambda view =>
      GeneratedResultContext.ofResume (view.resume result)
  | .arrow innerFunction _ codomain,
      .arrow _ _ innerArgument =>
      GeneratedResultContext.cast
        (innerFunction.generatedApplication innerArgument) codomain

end FunctionValue

namespace FunctionView

/-- Normalizing reflexive/transitive function administration does not change
the residual result context produced by canonical application. -/
def generatedApplication
    (code : FunctionView plan result body)
    (argumentView : ArgumentView code.normalize.value argument) :
    GeneratedApplicationView (code.application argumentView) := by
  simpa only [FunctionView.application] using
    code.normalize.value.generatedApplication argumentView

end FunctionView

end OperationalApplication
end LambdaPToFCo
