import LambdaPToFCo.OperationalMemberView
import LambdaPToFCo.OperationalSubstitution

/-!
# Closed behavioral views of compiled source packages

Package payloads compile from source paths.  In an open compiler scope those
paths are generally target variables, hence not target values.  Behavioral
package elimination is therefore stated only after the lexical closing
substitution has been applied.  This is the boundary at which the source
store supplies a ready target payload.

The constructions here cover exact package introduction and the direct
interval-covariance subsumption generated by `Fragment.Sub.package`.  They
produce precisely the closed `EliminationView` and normalization proof
consumed by `OperationalStoreEnvironment.CompiledSlot`.
-/

namespace LambdaPToFCo
namespace OperationalPackageBehavior

open SystemFCo
open StaticTranslation
open OperationalBindingView
open OperationalEnvironment

/-- A derivation-directed elaboration together with its closed behavioral
binding view. -/
structure ClosedView
    {n : Nat} {sourceContext : LambdaPFC.Ctx n}
    {sig : Sig} {targetContext : Ctx sig}
    (scope : Scope sourceContext targetContext)
    {sourceTerm : LambdaPFC.Tm n} {sourceType : LambdaPFC.Ty n}
    (typing : Fragment.HasType sourceContext sourceTerm sourceType)
    (environment : ClosingEnv sig []) : Type where
  view : EliminationView
    ((TermTranslation.compileBinder scope typing.typeWf).plan.subst
      environment.substitution)
  normalizes : Exp.Steps
    (environment.closeExp (TermTranslation.elaborate scope typing))
    view.argument

/-- Closed behavioral view of an exact source package.  Readiness is needed
only for the closed translation of the package's first path. -/
noncomputable def exact
    {n : Nat} {sourceContext : LambdaPFC.Ctx n}
    {sig : Sig} {targetContext : Ctx sig}
    (scope : Scope sourceContext targetContext)
    (first : Fin n) (label : LambdaPFC.Name)
    {witness : LambdaPFC.Ty n}
    (witnessWf : Fragment.Wf sourceContext witness)
    (environment : ClosingEnv sig [])
    (payloadReady : Exp.IsValue
      (environment.closeExp
        (translatePath scope
          (Fragment.PathTy.var
            (Γ := sourceContext) (x := first))).expression)) :
    ClosedView scope
      (Fragment.HasType.typePackage (first := first) (label := label)
        witnessWf)
      environment := by
  let targetWitness := translateType scope witnessWf
  let firstTranslation := translatePath scope
    (Fragment.PathTy.var (Γ := sourceContext) (x := first))
  let actual : Instantiation
      (.exact targetWitness targetWitness
        (payloadFamily firstTranslation.targetType)) :=
    .exact targetWitness (.refl targetWitness) (.refl targetWitness)
      firstTranslation.expression
  let closedActual := environment.closeInstantiation actual
  let direct := BindingView.ofInstantiation closedActual payloadReady
  refine
    { view := EliminationView.ofDirect direct
      normalizes := ?_ }
  change Exp.Steps
    (actual.argument.subst environment.substitution) closedActual.argument
  rw [Instantiation.argument_subst]
  exact .refl

/-- Closed behavioral view for the direct interval-covariance step used by
the current LambdaP fragment: an exact package is subsumed once with
`Fragment.Sub.package`.  The two bound adapters may themselves contain
arbitrary source subtyping structure; they are passed through as explicit
target coercions. -/
noncomputable def directPackage
    {n : Nat} {sourceContext : LambdaPFC.Ctx n}
    {sig : Sig} {targetContext : Ctx sig}
    (scope : Scope sourceContext targetContext)
    (first : Fin n) (label : LambdaPFC.Name)
    {witness targetLower targetUpper : LambdaPFC.Ty n}
    (witnessWf : Fragment.Wf sourceContext witness)
    (lowerAdapter : Fragment.Sub sourceContext targetLower witness)
    (upperAdapter : Fragment.Sub sourceContext witness targetUpper)
    (sourceNonempty : Fragment.Sub sourceContext witness witness)
    (environment : ClosingEnv sig [])
    (payloadReady : Exp.IsValue
      (environment.closeExp
        (translatePath scope
          (Fragment.PathTy.var
            (Γ := sourceContext) (x := first))).expression)) :
    ClosedView scope
      (Fragment.HasType.sub
        (Fragment.HasType.typePackage (first := first) (label := label)
          witnessWf)
        (Fragment.Sub.package lowerAdapter upperAdapter sourceNonempty))
      environment := by
  let sourceWitness := translateType scope witnessWf
  let targetLowerTy := translateType scope lowerAdapter.sourceWf
  let targetUpperTy := translateType scope upperAdapter.targetWf
  let firstTranslation := translatePath scope
    (Fragment.PathTy.var (Γ := sourceContext) (x := first))
  let payloadType := payloadFamily firstTranslation.targetType
  let lowerCo := CoercionTranslation.elaborateSub scope lowerAdapter
  let upperCo := CoercionTranslation.elaborateSub scope upperAdapter
  let closedWitness := sourceWitness.subst environment.substitution
  let closedLower := targetLowerTy.subst environment.substitution
  let closedUpper := targetUpperTy.subst environment.substitution
  let closedPayloadType :=
    payloadType.subst (environment.substitution.lift .tvar)
  let closedLowerCo := lowerCo.subst environment.substitution
  let closedUpperCo := upperCo.subst environment.substitution
  let closedPayload :=
    environment.closeExp firstTranslation.expression
  let behavior := OperationalMemberView.eliminationView
    closedLower closedUpper closedWitness closedWitness closedWitness
    closedPayloadType (.refl closedWitness) (.refl closedWitness)
    closedLowerCo closedUpperCo closedPayload payloadReady
  refine
    { view := behavior
      normalizes := ?_ }
  change Exp.Steps
    ((TermTranslation.elaborate scope
      (Fragment.HasType.sub
        (Fragment.HasType.typePackage (first := first) (label := label)
          witnessWf)
        (Fragment.Sub.package lowerAdapter upperAdapter sourceNonempty))).subst
      environment.substitution)
    behavior.argument
  simp only [TermTranslation.elaborate]
  simp only [Exp.subst, CoercionTranslation.elaborateSub]
  rw [Exp.packMember_subst, Co.member_subst]
  exact .refl

end OperationalPackageBehavior
end LambdaPToFCo
