import LambdaPToFCo.OperationalApplication
import LambdaPToFCo.OperationalSubstitution

/-!
# Closed compiler provenance for target application

`OperationalApplication` proves the application macro once two behavioral
facts are available: the function really is a compiled lambda surrounded only
by supported function-coercion administration, and the contravariantly cast
argument reaches the binder interface expected by that lambda.

This file is the smallest bridge from derivation-directed LambdaP compilation
to those target-only views.  It deliberately does not claim that an arbitrary
ready `BindingView` is a closure.  Instead:

* `ClosedFunctionCo` identifies one *generated and closed* source coercion
  with `FunctionCo` syntax;
* `ClosedFunctionEvidence` retains that a typing derivation for a syntactic
  abstraction starts at `HasType.abs` and records the evidence for every
  surrounding source subsumption;
* `ArgumentEvidence` records, layer by layer, the behavioral view obtained
  after each pushed contravariant cast.

Direct reflexive/transitive/arrow source subtyping produces
`ClosedFunctionCo` automatically.  A derivation that detours through a type
selection needs a separately supplied closed view: before closing, its
generated coercion is a `cvar`, so raw syntax alone cannot establish the
function shape.  This is the explicit provenance obligation for the store
simulation, not a semantic realization relation.
-/

namespace LambdaPToFCo

open SystemFCo
open StaticTranslation
open OperationalApplication
open OperationalBindingView
open OperationalEnvironment

/-! ## Closing compiled lambdas -/

namespace Interface.BinderPlan

/-- Substitution commutes with both ordinary and exact compiled lambdas. -/
theorem lambda_subst (plan : Interface.BinderPlan source)
    (result : Ty source) (body : Exp plan.scope)
    (substitution : Subst source target) :
    (plan.lambda result body).subst substitution =
      (plan.subst substitution).lambda (result.subst substitution)
        (body.subst (plan.scopeSubst substitution)) := by
  cases plan with
  | ordinary valueType => rfl
  | exact lower upper payloadType =>
      unfold Interface.BinderPlan.lambda Interface.BinderPlan.subst
        Interface.BinderPlan.scopeSubst
      simp only [Exp.subst, Ty.member_subst]
      rw [Exp.unpackMemberBody_subst]
      simp only [Interface.BinderPlan.rawLower_subst,
        Interface.BinderPlan.rawUpper_subst,
        Interface.BinderPlan.rawPayload_subst]
      rw [← Ty.weaken_subst_comm_base result substitution]
      rfl

end Interface.BinderPlan

namespace OperationalApplicationTranslation

/-! ## Generated coercion provenance -/

/-- The outer source-subtyping constructors that generate function-compatible
target administration.  The domain and codomain derivations beneath an
`arrow` node may use the full fragment: they become the two children of the
single structural target `Co.arrow` node. -/
inductive FragmentFunctionCo
    {n : Nat} {sourceContext : LambdaPFC.Ctx n} :
    {source target : LambdaPFC.Ty n} ->
    Fragment.Sub sourceContext source target -> Type where
  | refl (wf : Fragment.Wf sourceContext ty) :
      FragmentFunctionCo (.refl wf)
  | trans {source middle target : LambdaPFC.Ty n}
      {first : Fragment.Sub sourceContext source middle}
      {second : Fragment.Sub sourceContext middle target} :
      FragmentFunctionCo first -> FragmentFunctionCo second ->
      FragmentFunctionCo (.trans first second)
  | arrow
      (domain : Fragment.Sub sourceContext targetDomain sourceDomain)
      (codomain : Fragment.Sub sourceContext sourceCodomain targetCodomain) :
      FragmentFunctionCo (.arrow domain codomain)

namespace FragmentFunctionCo

/-- Close the exact target syntax generated by a direct function-subtyping
shape. -/
noncomputable def close
    {sig : Sig} {targetContext : Ctx sig}
    {sourceContext : LambdaPFC.Ctx n}
    (scope : Scope sourceContext targetContext)
    (environment : ClosingEnv sig []) :
    {source target : LambdaPFC.Ty n} ->
    {subtype : Fragment.Sub sourceContext source target} ->
    FragmentFunctionCo subtype -> FunctionCo []
  | _, _, _, .refl wf =>
      .refl (environment.closeTy (translateType scope wf))
  | _, _, _, .trans first second =>
      .trans (close scope environment first) (close scope environment second)
  | _, _, _, .arrow domain codomain =>
      .arrow
        (environment.closeCo
          (CoercionTranslation.elaborateSub scope domain))
        (environment.closeCo
          (CoercionTranslation.elaborateSub scope codomain))

/-- The closed view denotes literally the closed coercion emitted by the
subtyping compiler. -/
theorem close_coercion
    {sig : Sig} {targetContext : Ctx sig}
    {sourceContext : LambdaPFC.Ctx n}
    (scope : Scope sourceContext targetContext)
    (environment : ClosingEnv sig [])
    {source target : LambdaPFC.Ty n}
    {subtype : Fragment.Sub sourceContext source target}
    (shape : FragmentFunctionCo subtype) :
    (shape.close scope environment).coercion =
      environment.closeCo
        (CoercionTranslation.elaborateSub scope subtype) := by
  induction shape with
  | refl => rfl
  | trans first second firstIH secondIH =>
      simp only [close, FunctionCo.coercion,
        CoercionTranslation.elaborateSub, ClosingEnv.closeCo, Co.subst]
      rw [firstIH, secondIH]
      rfl
  | arrow => rfl

end FragmentFunctionCo

/-- Evidence that one generated source coercion, after closing, has exactly
the target function-administration syntax consumed by `FunctionView`.

The record form also admits future canonical-form proofs for selection
evidence without changing the application API. -/
structure ClosedFunctionCo
    {sig : Sig} {targetContext : Ctx sig}
    {sourceContext : LambdaPFC.Ctx n}
    (scope : Scope sourceContext targetContext)
    (environment : ClosingEnv sig [])
    {source target : LambdaPFC.Ty n}
    (subtype : Fragment.Sub sourceContext source target) : Type where
  view : FunctionCo []
  coercion_eq : view.coercion =
    environment.closeCo (CoercionTranslation.elaborateSub scope subtype)

namespace ClosedFunctionCo

/-- Direct reflexive/transitive/arrow fragment subtyping needs no extra
runtime premise. -/
noncomputable def ofFragment
    {n : Nat} {sig : Sig} {targetContext : Ctx sig}
    {sourceContext : LambdaPFC.Ctx n}
    {source target : LambdaPFC.Ty n}
    {scope : Scope sourceContext targetContext}
    {environment : ClosingEnv sig []}
    {subtype : Fragment.Sub sourceContext source target}
    (shape : FragmentFunctionCo subtype) :
    ClosedFunctionCo scope environment subtype where
  view := shape.close scope environment
  coercion_eq := shape.close_coercion scope environment

end ClosedFunctionCo

/-! ## Closed abstraction images -/

/-- A closed target compilation whose source syntax is an abstraction and
whose derivation retains enough coercion provenance to expose a
`FunctionView`. -/
structure ClosedFunctionImage
    {sig : Sig} {targetContext : Ctx sig}
    {sourceContext : LambdaPFC.Ctx n}
    (scope : Scope sourceContext targetContext)
    (environment : ClosingEnv sig [])
    {domain : LambdaPFC.Ty n} {sourceBody : LambdaPFC.Tm (n + 1)}
    {sourceType : LambdaPFC.Ty n}
    (typing : Fragment.HasType sourceContext (.abs domain sourceBody)
      sourceType) : Type where
  plan : Interface.BinderPlan []
  result : Ty []
  body : Exp plan.scope
  view : FunctionView plan result body
  expression_eq : view.expression =
    environment.closeExp (TermTranslation.elaborate scope typing)

/-- Proof-relevant closure provenance for a typing derivation of a syntactic
source abstraction.  The base constructor remembers the actual `abs`
derivation; every `sub` constructor supplies the view of its generated closed
coercion. -/
inductive ClosedFunctionEvidence
    {sig : Sig} {targetContext : Ctx sig}
    {sourceContext : LambdaPFC.Ctx n}
    (scope : Scope sourceContext targetContext)
    (environment : ClosingEnv sig [])
    {domain : LambdaPFC.Ty n} {sourceBody : LambdaPFC.Tm (n + 1)} :
    {sourceType : LambdaPFC.Ty n} ->
    (typing : Fragment.HasType sourceContext (.abs domain sourceBody)
      sourceType) -> Type where
  | abs
      {codomain : LambdaPFC.Ty n}
      (bodyTyping : Fragment.HasType (sourceContext.snoc domain) sourceBody
        codomain.weaken)
      (domainWf : Fragment.Wf sourceContext domain)
      (codomainWf : Fragment.Wf sourceContext codomain) :
      ClosedFunctionEvidence scope environment
        (.abs bodyTyping domainWf codomainWf)
  | sub
      {source target : LambdaPFC.Ty n}
      {innerTyping : Fragment.HasType sourceContext
        (.abs domain sourceBody) source}
      {subtype : Fragment.Sub sourceContext source target}
      (inner : ClosedFunctionEvidence scope environment innerTyping)
      (coercion : ClosedFunctionCo scope environment subtype) :
      ClosedFunctionEvidence scope environment (.sub innerTyping subtype)

namespace ClosedFunctionEvidence

/-- Construct the exact target `FunctionView` denoted by retained source
closure provenance. -/
noncomputable def image
    {n : Nat} {sig : Sig} {targetContext : Ctx sig}
    {sourceContext : LambdaPFC.Ctx n}
    {domain : LambdaPFC.Ty n} {sourceBody : LambdaPFC.Tm (n + 1)}
    {sourceType : LambdaPFC.Ty n}
    {scope : Scope sourceContext targetContext}
    {environment : ClosingEnv sig []}
    {typing : Fragment.HasType sourceContext (.abs domain sourceBody)
      sourceType} :
    ClosedFunctionEvidence scope environment typing ->
      ClosedFunctionImage scope environment typing
  | .abs bodyTyping domainWf codomainWf => by
      let binder := TermTranslation.compileBinder scope domainWf
      let closedPlan := binder.plan.subst environment.substitution
      let closedResult := environment.closeTy
        (translateType scope codomainWf)
      let closedBody := environment.closeBody binder.plan
        (TermTranslation.elaborate binder.extended bodyTyping)
      refine
        { plan := closedPlan
          result := closedResult
          body := closedBody
          view := .lambda
          expression_eq := ?_ }
      change closedPlan.lambda closedResult closedBody =
        environment.closeExp
          (binder.plan.lambda (translateType scope codomainWf)
            (TermTranslation.elaborate binder.extended bodyTyping))
      exact
        (Interface.BinderPlan.lambda_subst binder.plan
          (translateType scope codomainWf)
          (TermTranslation.elaborate binder.extended bodyTyping)
          environment.substitution).symm
  | .sub inner coercion => by
      let innerImage := inner.image
      refine
        { plan := innerImage.plan
          result := innerImage.result
          body := innerImage.body
          view := .cast innerImage.view coercion.view
          expression_eq := ?_ }
      simp only [FunctionView.expression, TermTranslation.elaborate,
        ClosingEnv.closeExp, Exp.subst]
      rw [innerImage.expression_eq, coercion.coercion_eq]
      rfl

end ClosedFunctionEvidence

namespace ClosedFunctionImage

/-- Apply the closed compiled abstraction using the target macro.  The
function endpoint is rewritten back to the actual closed derivation-directed
elaboration, while the instantiated body and residual context remain exposed
by `ApplicationView`. -/
noncomputable def application
    (image : ClosedFunctionImage scope environment typing)
    {argument : Exp []}
    (argumentView : ArgumentView image.view.normalize.value argument) :
    ApplicationView image.body
      (environment.closeExp (TermTranslation.elaborate scope typing))
      argument := by
  rw [← image.expression_eq]
  exact image.view.application argumentView

end ClosedFunctionImage

/-! ## Closed argument adaptation -/

/-- One contravariant target cast takes an outer behavioral argument view to
the behavioral view expected by the next inner function layer. -/
structure AdaptedArgument
    (domain : Co []) {outerPlan : Interface.BinderPlan []}
    (outer : EliminationView outerPlan) : Type where
  plan : Interface.BinderPlan []
  view : EliminationView plan
  reductions : Exp.Steps (.cast outer.argument domain) view.argument

namespace AdaptedArgument

/-- A reflexive domain coercion preserves any ordinary or exact behavioral
view after its one administrative cast step. -/
def reflexive {outerPlan : Interface.BinderPlan []}
    (outer : EliminationView outerPlan) (ty : Ty []) :
    AdaptedArgument (.refl ty) outer where
  plan := outerPlan
  view := outer
  reductions := .single (.castRefl outer.ready)

/-- Compose two behavioral argument adaptations through an explicit target
`Co.trans`.  This is the exact operation needed for reflexive/transitive
contravariant evidence over an exact-package view: each component may retain
the exact five-slot interface rather than collapsing it to an ordinary slot. -/
def trans {outerPlan : Interface.BinderPlan []}
    (outer : EliminationView outerPlan) {first second : Co []}
    (firstAdapted : AdaptedArgument first outer)
    (secondAdapted : AdaptedArgument second firstAdapted.view) :
    AdaptedArgument (.trans first second) outer where
  plan := secondAdapted.plan
  view := secondAdapted.view
  reductions :=
    (Exp.Steps.single (.castTrans outer.ready)).trans
      ((OperationalApplication.Steps.castExpression
        firstAdapted.reductions).trans secondAdapted.reductions)

/-- Every closed cast can feed an ordinary binder.  Reflexive/transitive
administration is normalized; a structural cast remains as the ordinary
slot's ready target value. -/
def ordinary {outerPlan : Interface.BinderPlan []}
    (outer : EliminationView outerPlan) (domain : Co [])
    (valueType : Ty []) : AdaptedArgument domain outer :=
  let normalization := CastNormalization.closed outer.ready domain
  let actual : Instantiation (.ordinary valueType) :=
    .ordinary normalization.result
  let direct := BindingView.ofInstantiation actual normalization.ready
  { plan := .ordinary valueType
    view := EliminationView.ofDirect direct
    reductions := normalization.reductions }

/-- Package conversion and other structural adapters can supply their own
target reduction and `EliminationView` (for example
`OperationalMemberView.eliminationView`). -/
def ofView {outerPlan innerPlan : Interface.BinderPlan []}
    (outer : EliminationView outerPlan) (domain : Co [])
    (inner : EliminationView innerPlan)
    (reductions : Exp.Steps (.cast outer.argument domain) inner.argument) :
    AdaptedArgument domain outer where
  plan := innerPlan
  view := inner
  reductions := reductions

end AdaptedArgument

/-- Behavioral argument provenance aligned with the normalized arrow-cast
tower of a compiled function. -/
inductive ArgumentEvidence
    {plan : Interface.BinderPlan []} {result : Ty []}
    {body : Exp plan.scope} :
    (function : FunctionValue plan result body) ->
    {outerPlan : Interface.BinderPlan []} ->
    EliminationView outerPlan -> Type where
  | lambda (view : EliminationView plan) :
      ArgumentEvidence (.lambda : FunctionValue plan result body) view
  | arrow
      {innerFunction : FunctionValue plan result body}
      {domain codomain : Co []}
      {outerPlan : Interface.BinderPlan []}
      (outer : EliminationView outerPlan)
      (adapted : AdaptedArgument domain outer)
      (inner : ArgumentEvidence innerFunction adapted.view) :
      ArgumentEvidence (.arrow innerFunction domain codomain) outer

namespace ArgumentEvidence

/-- Forget the compiler/store provenance wrapper and recover the target-only
argument view consumed by the application theorem. -/
def toArgumentView :
    ArgumentEvidence function outer -> ArgumentView function outer.argument
  | .lambda view => .lambda view
  | .arrow outer adapted inner =>
      .arrow outer.ready adapted.reductions inner.toArgumentView

end ArgumentEvidence

end OperationalApplicationTranslation
end LambdaPToFCo
