import LambdaPHistory.RuntimeChecking

/-!
A prototype deep runtime typing layer.

The store-indexed relation in `RuntimeChecking` identifies the missing local
rule--conversion must be available before path elimination--but a concrete
`Store n` cannot be extended under a source binder without manufacturing a
runtime value.  The judgments below therefore take an abstract relation on
paths.  Entering a binder uses `Path.ConvLift`: the fresh variable is related
to itself and every old relation is weakened.

No semantic property of the abstract relation is assumed in this file.
Consequently these definitions are constructor infrastructure, not yet a
soundness theorem.  A later fundamental lemma must supply a typed conversion
environment showing that related paths check at the transported types.  In
particular, this file does not claim machine preservation or a general
substitution theorem.
-/

namespace LambdaPHistory

/-! ## Abstract path conversion and its binder lift -/

/-- A path-conversion relation at one intrinsic scope. -/
abbrev Path.ConvRel (n : Nat) : Type := Path n -> Path n -> Prop

/-- Syntactic lifting of a path relation under one fresh source binder. -/
inductive Path.ConvLift (R : Path.ConvRel n) : Path.ConvRel (n + 1) where
| bound : Path.ConvLift R (.var 0) (.var 0)
| weaken : R p q -> Path.ConvLift R p.weaken q.weaken

/-! ## Type conversion and mixed subtyping over an abstract relation -/

/-- Symmetric type conversion generated by abstractly related paths and
arbitrary generalized-type templates. -/
inductive Tau.DeepConv (R : Path.ConvRel n) :
    Tau n k -> Tau n k -> Prop where
| refl : Tau.DeepConv R d d
| symm : Tau.DeepConv R d1 d2 -> Tau.DeepConv R d2 d1
| trans :
    Tau.DeepConv R d1 d2 ->
    Tau.DeepConv R d2 d3 ->
    Tau.DeepConv R d1 d3
| replace (template : Tau (n + 1) k) (h : R p q) :
    Tau.DeepConv R (template.open p) (template.open q)

/-- Reflexive-transitive closure of source subtyping and abstract path
conversion. -/
inductive Tau.DeepSub (Gamma : Ctx n) (R : Path.ConvRel n) :
    Tau n k -> Tau n k -> Prop where
| refl : Tau.DeepSub Gamma R d d
| source : Tau.Sub Gamma d1 d2 -> Tau.DeepSub Gamma R d1 d2
| conv : Tau.DeepConv R d1 d2 -> Tau.DeepSub Gamma R d1 d2
| trans :
    Tau.DeepSub Gamma R d1 d2 ->
    Tau.DeepSub Gamma R d2 d3 ->
    Tau.DeepSub Gamma R d1 d3

/-- Concrete store conversion embeds by choosing `Path.RuntimeEq sigma` as
the abstract relation. -/
theorem Tau.DeepConv.of_runtime
    (h : Tau.RuntimeConv sigma d1 d2) :
    Tau.DeepConv (Path.RuntimeEq sigma) d1 d2 := by
  induction h with
  | refl => exact .refl
  | symm _ ih => exact .symm ih
  | trans _ _ ih1 ih2 => exact .trans ih1 ih2
  | replace template hpq => exact .replace template hpq

/-- The existing store-indexed mixed subtyping embeds in abstract deep
subtyping. -/
theorem Tau.DeepSub.of_runtime
    (h : Tau.RuntimeSub Gamma sigma d1 d2) :
    Tau.DeepSub Gamma (Path.RuntimeEq sigma) d1 d2 := by
  induction h with
  | refl => exact .refl
  | source hsub => exact .source hsub
  | conv hconv => exact .conv (Tau.DeepConv.of_runtime hconv)
  | trans _ _ ih1 ih2 => exact .trans ih1 ih2

/-! ## Deep checking for paths -/

/-- Structural path checking with conversion available both before and after
elimination. -/
inductive Path.DeepCheck (Gamma : Ctx n) (R : Path.ConvRel n) :
    Path n -> Tau n k -> Prop where
| var :
    Ctx.Binds Gamma x T ->
    Path.DeepCheck Gamma R (.var x) (Tau.ty T)
| sub :
    Path.DeepCheck Gamma R p d1 ->
    Tau.DeepSub Gamma R d1 d2 ->
    Path.DeepCheck Gamma R p d2
| fst :
    Path.DeepCheck Gamma R p
      (Tau.ty (Ty.Pair S a d)) ->
    Path.DeepCheck Gamma R p.fst (Tau.ty S)
| sel_r :
    Path.DeepCheck Gamma R p
      (Tau.ty (Ty.Pair S a d)) ->
    Path.DeepCheck Gamma R (p.sel a) (d.open p.fst)
| sel_l :
    Path.DeepCheck Gamma R p
      (Tau.ty (Ty.Pair S b d')) ->
    Path.DeepCheck Gamma R (p.fst.sel a) d ->
    a ≠ b ->
    Path.DeepCheck Gamma R (p.sel a) d

/-- Source precise path typing embeds structurally. -/
theorem Path.DeepCheck.of_source
    {n : Nat} {Gamma : Ctx n} {p : Path n} {k : Kind}
    {d : Tau n k}
    (h : Path.Ty Gamma p d) (R : Path.ConvRel n) :
    Path.DeepCheck Gamma R p d := by
  induction h with
  | var hb => exact .var hb
  | fst _ ih => exact .fst ih
  | sel_r _ ih => exact .sel_r ih
  | sel_l _ _ hne ihp ihtail => exact .sel_l ihp ihtail hne

/-- The first, store-indexed checking prototype embeds at the concrete runtime
relation. -/
theorem Path.DeepCheck.of_runtime
    {n : Nat} {Gamma : Ctx n} {sigma : Store n}
    {p : Path n} {k : Kind} {d : Tau n k}
    (h : Path.RuntimeCheck Gamma sigma p d) :
    Path.DeepCheck Gamma (Path.RuntimeEq sigma) p d := by
  induction h with
  | source hp => exact Path.DeepCheck.of_source hp _
  | sub _ hs ih => exact .sub ih (Tau.DeepSub.of_runtime hs)
  | fst _ ih => exact .fst ih
  | sel_r _ ih => exact .sel_r ih
  | sel_l _ _ hne ihp ihtail => exact .sel_l ihp ihtail hne

/-! ## Deep generalized-type well-formedness -/

/-- Generalized-type well-formedness whose path premises use deep checking
and whose recursive binder premises use the lifted conversion relation. -/
inductive Tau.DeepWf : {n : Nat} -> (Gamma : Ctx n) ->
    Path.ConvRel n -> {k : Kind} -> Tau n k -> Prop where
| bot : Tau.DeepWf Gamma R (Tau.ty Ty.Bot)
| top : Tau.DeepWf Gamma R (Tau.ty Ty.Top)
| path :
    Path.DeepCheck Gamma R p (Tau.ty T) ->
    Tau.DeepWf Gamma R (Tau.ty (Ty.Single p))
| sel :
    Path.DeepCheck Gamma R p
      (Tau.ty (Ty.Pair S A (Tau.intv T U))) ->
    Tau.DeepWf Gamma R (Tau.ty (Ty.Single (p.sel A)))
| «fun» :
    Tau.DeepWf Gamma R (Tau.ty S) ->
    Tau.DeepWf (Gamma.snoc S) (Path.ConvLift R) (Tau.ty T) ->
    Tau.DeepWf Gamma R (Tau.ty (Ty.Fun S T))
| pair :
    Tau.DeepWf Gamma R (Tau.ty S) ->
    Tau.DeepWf (Gamma.snoc S) (Path.ConvLift R) d ->
    Tau.DeepWf Gamma R (Tau.ty (Ty.Pair S a d))
| bounds_wf :
    Tau.DeepWf Gamma R (Tau.ty S) ->
    Tau.DeepWf Gamma R (Tau.ty T) ->
    Tau.DeepSub Gamma R (Tau.ty S) (Tau.ty T) ->
    Tau.DeepWf Gamma R (Tau.intv S T)

/-- Source well-formedness embeds at every abstract conversion relation. -/
theorem Tau.DeepWf.of_source
    {n : Nat} {Gamma : Ctx n} {k : Kind} {d : Tau n k}
    (h : Tau.Wf Gamma d) :
    forall R : Path.ConvRel n, Tau.DeepWf Gamma R d := by
  induction h with
  | bot => intro R; exact .bot
  | top => intro R; exact .top
  | path hp =>
      intro R
      exact .path (Path.DeepCheck.of_source hp R)
  | sel hp =>
      intro R
      exact .sel (Path.DeepCheck.of_source hp R)
  | «fun» _ _ ihS ihT =>
      intro R
      exact .fun (ihS R) (ihT (Path.ConvLift R))
  | pair _ _ ihS ihd =>
      intro R
      exact .pair (ihS R) (ihd (Path.ConvLift R))
  | bounds_wf _ _ hsub ihS ihT =>
      intro R
      exact .bounds_wf (ihS R) (ihT R) (.source hsub)

/-! ## Deep checking for every term constructor -/

/-- A structural runtime-checking judgment mirroring every source term rule.
Path premises use `Path.DeepCheck`, well-formedness premises use `Tau.DeepWf`,
and source binders lift the abstract path relation. -/
inductive Tm.DeepCheck : {n : Nat} -> (Gamma : Ctx n) ->
    Path.ConvRel n -> Tm n -> LambdaPHistory.Ty n -> Prop where
| path :
    Path.DeepCheck Gamma R p (Tau.ty T) ->
    Tm.DeepCheck Gamma R (Tm.path p) (Ty.Single p)
| abs :
    Tm.DeepCheck (Gamma.snoc S) (Path.ConvLift R) t T ->
    Tau.DeepWf Gamma R (Tau.ty S) ->
    Tm.DeepCheck Gamma R (Tm.abs S t) (Ty.Fun S T)
| app :
    Tm.DeepCheck Gamma R (Tm.path p) (Ty.Fun S T) ->
    Tm.DeepCheck Gamma R (Tm.path q) S ->
    Tm.DeepCheck Gamma R (Tm.app p q) (T.open q)
| pair :
    Ctx.Binds Gamma y S ->
    Ctx.Binds Gamma z T ->
    Tm.DeepCheck Gamma R (Tm.pair y a (Def.val z))
      (Ty.Pair (Ty.Single (Path.var y)) a
        (Tau.ty (Ty.Single (Path.var z).weaken)))
| tpair :
    Ctx.Binds Gamma y S ->
    Tau.DeepWf Gamma R (Tau.ty T) ->
    Tm.DeepCheck Gamma R (Tm.pair y A (Def.type T))
      (Ty.Pair (Ty.Single (Path.var y)) A (Tau.intv T T).weaken)
| «let» :
    Tm.DeepCheck Gamma R s S ->
    Tau.DeepWf Gamma R (Tau.ty T) ->
    Tm.DeepCheck (Gamma.snoc S) (Path.ConvLift R) t T.weaken ->
    Tm.DeepCheck Gamma R (Tm.let s t) T
| typed :
    Tm.DeepCheck Gamma R t T ->
    Tau.DeepWf Gamma R (Tau.ty T) ->
    Tm.DeepCheck Gamma R (Tm.typed t T) T
| sub :
    Tm.DeepCheck Gamma R t S ->
    Tau.DeepSub Gamma R (Tau.ty S) (Tau.ty T) ->
    Tau.DeepWf Gamma R (Tau.ty T) ->
    Tm.DeepCheck Gamma R t T

/-- Every source term typing derivation embeds at every abstract conversion
relation.  The binder cases are the reason the judgment is parameterized by a
liftable relation rather than a concrete store. -/
theorem Tm.DeepCheck.of_source
    {n : Nat} {Gamma : Ctx n} {t : Tm n}
    {T : LambdaPHistory.Ty n}
    (h : Tm.Ty Gamma t T) :
    forall R : Path.ConvRel n, Tm.DeepCheck Gamma R t T := by
  induction h with
  | path hp =>
      intro R
      exact .path (Path.DeepCheck.of_source hp R)
  | abs ht hwf iht =>
      intro R
      exact .abs (iht (Path.ConvLift R))
        (Tau.DeepWf.of_source hwf R)
  | app hp hq ihp ihq =>
      intro R
      exact .app (ihp R) (ihq R)
  | pair hy hz =>
      intro R
      exact .pair hy hz
  | tpair hy hwf =>
      intro R
      exact .tpair hy (Tau.DeepWf.of_source hwf R)
  | «let» hs hwf ht ihs iht =>
      intro R
      exact .let (ihs R) (Tau.DeepWf.of_source hwf R)
        (iht (Path.ConvLift R))
  | typed ht hwf iht =>
      intro R
      exact .typed (iht R) (Tau.DeepWf.of_source hwf R)
  | sub ht hsub hwf iht =>
      intro R
      exact .sub (iht R) (.source hsub)
        (Tau.DeepWf.of_source hwf R)

/-
There is deliberately no unconditional embedding from `Tm.RuntimeCheck`.
That earlier path-term prototype does not retain well-formedness of the target
of trailing runtime subsumption, while the full `Tm.DeepCheck.sub` constructor
does.  Such an embedding needs a separate deep-well-formedness premise.
-/

/-! ## Basic inversion for the deep judgments -/

/-- Inversion for the path-term fragment, collecting every trailing deep
subsumption step. -/
theorem Tm.DeepCheck.path_inversion
    {n : Nat} {Gamma : Ctx n} {R : Path.ConvRel n}
    {t : Tm n} {T : LambdaPHistory.Ty n}
    (h : Tm.DeepCheck Gamma R t T) :
    forall {p : Path n}, t = Tm.path p ->
      exists U,
        Path.DeepCheck Gamma R p (Tau.ty U) /\
        Tau.DeepSub Gamma R
          (Tau.ty (Ty.Single p)) (Tau.ty T) := by
  induction h with
  | path hp =>
      intro p heq
      cases heq
      exact ⟨_, hp, .refl⟩
  | abs _ _ _ =>
      intro p heq
      cases heq
  | app _ _ _ _ =>
      intro p heq
      cases heq
  | pair _ _ =>
      intro p heq
      cases heq
  | tpair _ _ =>
      intro p heq
      cases heq
  | «let» _ _ _ _ _ =>
      intro p heq
      cases heq
  | typed _ _ _ =>
      intro p heq
      cases heq
  | sub _ hs _ ih =>
      intro p heq
      obtain ⟨U, hp, hbase⟩ := ih heq
      exact ⟨U, hp, .trans hbase hs⟩

/-! ## Deliberate boundary of this prototype

`Tau.DeepSub` above is still the reflexive-transitive union of an existing
source `Tau.Sub` derivation and abstract conversion.  A substitution theorem
for non-exact environments cannot simply transport the embedded source
derivation: the `widen`, singleton symmetry, and abstract-bound rules contain
their own precise `Path.Ty` premises.  Making those premises deep requires a
mutually defined structural subtyping/path-checking family (or an equivalent
typed logical-environment interpretation).  That is the next real proof
obligation; silently treating source subtyping as stable under the abstract
relation would assume the theorem at issue.
-/

end LambdaPHistory
