import LambdaPHistory.ScopedRuntimeEq

/-!
Structural type conversion generated by a path equivalence.

The path relation is lifted with `Path.ScopedLift` whenever conversion enters
a function or pair binder.  The substitution lemmas are deliberately stated
before the opening corollaries: under a nested binder, opening is represented
by a lifted substitution rather than another top-level `open`.
-/

namespace LambdaPHistory

mutual

/-- Structural equality of proper types modulo a relation on paths.  Scope is
an index (not a parameter), since the relation changes under binders. -/
inductive Ty.PathConv : {n : Nat} ->
    (Path n -> Path n -> Prop) -> Ty n -> Ty n -> Prop where
| top {n} {E : Path n -> Path n -> Prop} : Ty.PathConv E .Top .Top
| bot {n} {E : Path n -> Path n -> Prop} : Ty.PathConv E .Bot .Bot
| fun {n} {E : Path n -> Path n -> Prop}
    {S₁ S₂ : Ty n} {T₁ T₂ : Ty (n + 1)} :
    Ty.PathConv E S₁ S₂ ->
    Ty.PathConv (Path.ScopedLift E) T₁ T₂ ->
    Ty.PathConv E (Ty.Fun S₁ T₁) (Ty.Fun S₂ T₂)
| pair {n k} {E : Path n -> Path n -> Prop}
    {S₁ S₂ : Ty n} {a : Name} {d₁ d₂ : Tau (n + 1) k} :
    Ty.PathConv E S₁ S₂ ->
    Tau.PathConv (Path.ScopedLift E) d₁ d₂ ->
    Ty.PathConv E (Ty.Pair S₁ a d₁) (Ty.Pair S₂ a d₂)
| single {n} {E : Path n -> Path n -> Prop} {p q : Path n} :
    E p q -> Ty.PathConv E (Ty.Single p) (Ty.Single q)

/-- Structural equality of generalized types modulo a relation on paths. -/
inductive Tau.PathConv : {n : Nat} ->
    (Path n -> Path n -> Prop) -> {k : Kind} -> Tau n k -> Tau n k -> Prop where
| ty {n} {E : Path n -> Path n -> Prop} {T₁ T₂ : Ty n} :
    Ty.PathConv E T₁ T₂ -> Tau.PathConv E (Tau.ty T₁) (Tau.ty T₂)
| intv {n} {E : Path n -> Path n -> Prop}
    {L₁ L₂ U₁ U₂ : Ty n} :
    Ty.PathConv E L₁ L₂ ->
    Ty.PathConv E U₁ U₂ ->
    Tau.PathConv E (Tau.intv L₁ U₁) (Tau.intv L₂ U₂)

end

/-! ## Equivalence laws -/

mutual

theorem Ty.PathConv.refl
    {E : Path n -> Path n -> Prop}
    (hE : Path.IsEquivCongr E) (T : Ty n) : Ty.PathConv E T T :=
  match T with
  | .Top => .top
  | .Bot => .bot
  | .Fun S T =>
      .fun (Ty.PathConv.refl hE S)
        (Ty.PathConv.refl (Path.ScopedLift.isEquivCongr hE) T)
  | .Pair S a d =>
      .pair (a := a) (Ty.PathConv.refl hE S)
        (Tau.PathConv.refl (Path.ScopedLift.isEquivCongr hE) d)
  | .Single p => .single (hE.refl p)

theorem Tau.PathConv.refl
    {E : Path n -> Path n -> Prop}
    (hE : Path.IsEquivCongr E) (d : Tau n k) : Tau.PathConv E d d :=
  match d with
  | .ty T => .ty (Ty.PathConv.refl hE T)
  | .intv L U => .intv (Ty.PathConv.refl hE L) (Ty.PathConv.refl hE U)

end


mutual

theorem Ty.PathConv.symm
    {E : Path n -> Path n -> Prop}
    (hE : Path.IsEquivCongr E) (h : Ty.PathConv E S T) :
    Ty.PathConv E T S :=
  match h with
  | .top => .top
  | .bot => .bot
  | .fun hS hT =>
      .fun (Ty.PathConv.symm hE hS)
        (Ty.PathConv.symm (Path.ScopedLift.isEquivCongr hE) hT)
  | .pair hS hd =>
      .pair (Ty.PathConv.symm hE hS)
        (Tau.PathConv.symm (Path.ScopedLift.isEquivCongr hE) hd)
  | .single hp => .single (hE.symm hp)

theorem Tau.PathConv.symm
    {E : Path n -> Path n -> Prop}
    (hE : Path.IsEquivCongr E) (h : Tau.PathConv E d₁ d₂) :
    Tau.PathConv E d₂ d₁ :=
  match h with
  | .ty hT => .ty (Ty.PathConv.symm hE hT)
  | .intv hL hU => .intv (Ty.PathConv.symm hE hL) (Ty.PathConv.symm hE hU)

end


mutual

theorem Ty.PathConv.trans
    {E : Path n -> Path n -> Prop}
    (hE : Path.IsEquivCongr E)
    (h₁ : Ty.PathConv E S T) (h₂ : Ty.PathConv E T U) :
    Ty.PathConv E S U :=
  match h₁, h₂ with
  | .top, .top => .top
  | .bot, .bot => .bot
  | .fun hS hT, .fun hS' hT' =>
      .fun (Ty.PathConv.trans hE hS hS')
        (Ty.PathConv.trans (Path.ScopedLift.isEquivCongr hE) hT hT')
  | .pair hS hd, .pair hS' hd' =>
      .pair (Ty.PathConv.trans hE hS hS')
        (Tau.PathConv.trans (Path.ScopedLift.isEquivCongr hE) hd hd')
  | .single hp, .single hq => .single (hE.trans hp hq)

theorem Tau.PathConv.trans
    {E : Path n -> Path n -> Prop}
    (hE : Path.IsEquivCongr E)
    (h₁ : Tau.PathConv E d₁ d₂) (h₂ : Tau.PathConv E d₂ d₃) :
    Tau.PathConv E d₁ d₃ :=
  match h₁, h₂ with
  | .ty hT, .ty hT' => .ty (Ty.PathConv.trans hE hT hT')
  | .intv hL hU, .intv hL' hU' =>
      .intv (Ty.PathConv.trans hE hL hL') (Ty.PathConv.trans hE hU hU')

end

/-! ## Substitutions and binder lifting -/

/-- A same-substitution morphism between ambient path relations lifts through
one binder.  Using one substitution is essential for symmetry/transitivity
of the generated scoped relation. -/
theorem Path.ScopedLift.subst_same
    {E₁ : Path n -> Path n -> Prop}
    {E₂ : Path m -> Path m -> Prop}
    {ρ : PathSubst n m}
    (hmap : ∀ {p q}, E₁ p q -> E₂ (p.subst ρ) (q.subst ρ))
    (h : Path.ScopedLift E₁ p q) :
    Path.ScopedLift E₂ (p.subst ρ.lift) (q.subst ρ.lift) := by
  induction h with
  | bound => exact .bound
  | @old p q hpq =>
      have hold := Path.ScopedLift.old (hmap hpq)
      simpa [Path.weaken, Path.rename_subst, Path.subst_rename] using hold
  | symm hpq ih => exact .symm ih
  | trans hpq hqr ih₁ ih₂ => exact .trans ih₁ ih₂
  | fst hpq ih => exact .fst ih
  | sel hpq ih => exact .sel ih

/-- Pointwise ambient equivalence lifts pointwise through a substitution
binder. -/
theorem Path.ScopedLift.subst_pointwise
    {E : Path m -> Path m -> Prop}
    {ρ₁ ρ₂ : PathSubst n m}
    (hρ : ∀ x, E (ρ₁ x) (ρ₂ x)) :
    ∀ x, Path.ScopedLift E (ρ₁.lift x) (ρ₂.lift x) := by
  intro x
  refine Fin.cases ?_ (fun y => ?_) x
  · exact .bound
  · exact .old (hρ y)

mutual

/-- Structural conversion is preserved by a substitution that maps every
source path equation to a target path equation. -/
theorem Ty.PathConv.subst_same
    {E₁ : Path n -> Path n -> Prop}
    {E₂ : Path m -> Path m -> Prop}
    {ρ : PathSubst n m}
    (hmap : ∀ {p q}, E₁ p q -> E₂ (p.subst ρ) (q.subst ρ))
    (h : Ty.PathConv E₁ S T) :
    Ty.PathConv E₂ (S.subst ρ) (T.subst ρ) :=
  match h with
  | .top => .top
  | .bot => .bot
  | .fun hS hT =>
      .fun (Ty.PathConv.subst_same hmap hS)
        (Ty.PathConv.subst_same (Path.ScopedLift.subst_same hmap) hT)
  | .pair hS hd =>
      .pair (Ty.PathConv.subst_same hmap hS)
        (Tau.PathConv.subst_same (Path.ScopedLift.subst_same hmap) hd)
  | .single hp => .single (hmap hp)

theorem Tau.PathConv.subst_same
    {E₁ : Path n -> Path n -> Prop}
    {E₂ : Path m -> Path m -> Prop}
    {ρ : PathSubst n m}
    (hmap : ∀ {p q}, E₁ p q -> E₂ (p.subst ρ) (q.subst ρ))
    (h : Tau.PathConv E₁ d₁ d₂) :
    Tau.PathConv E₂ (d₁.subst ρ) (d₂.subst ρ) :=
  match h with
  | .ty hT => .ty (Ty.PathConv.subst_same hmap hT)
  | .intv hL hU =>
      .intv (Ty.PathConv.subst_same hmap hL)
        (Ty.PathConv.subst_same hmap hU)

end


mutual

/-- Substituting pointwise-equivalent paths into one type template produces
structurally converted types. -/
theorem Ty.PathConv.subst_congr
    {E : Path m -> Path m -> Prop}
    (hE : Path.IsEquivCongr E)
    {ρ₁ ρ₂ : PathSubst n m}
    (hρ : ∀ x, E (ρ₁ x) (ρ₂ x)) (T : Ty n) :
    Ty.PathConv E (T.subst ρ₁) (T.subst ρ₂) :=
  match T with
  | .Top => .top
  | .Bot => .bot
  | .Fun S T =>
      .fun (Ty.PathConv.subst_congr hE hρ S)
        (Ty.PathConv.subst_congr
          (Path.ScopedLift.isEquivCongr hE)
          (Path.ScopedLift.subst_pointwise hρ) T)
  | .Pair S a d =>
      .pair (a := a) (Ty.PathConv.subst_congr hE hρ S)
        (Tau.PathConv.subst_congr
          (Path.ScopedLift.isEquivCongr hE)
          (Path.ScopedLift.subst_pointwise hρ) d)
  | .Single p => .single (hE.subst hρ p)

theorem Tau.PathConv.subst_congr
    {E : Path m -> Path m -> Prop}
    (hE : Path.IsEquivCongr E)
    {ρ₁ ρ₂ : PathSubst n m}
    (hρ : ∀ x, E (ρ₁ x) (ρ₂ x)) (d : Tau n k) :
    Tau.PathConv E (d.subst ρ₁) (d.subst ρ₂) :=
  match d with
  | .ty T => .ty (Ty.PathConv.subst_congr hE hρ T)
  | .intv L U =>
      .intv (Ty.PathConv.subst_congr hE hρ L)
        (Ty.PathConv.subst_congr hE hρ U)

end

/-! ## Opening compatibility -/

private theorem PathSubst.openAt_pointwise
    {E : Path n -> Path n -> Prop}
    (hE : Path.IsEquivCongr E) (hpq : E p q) :
    ∀ x, E (PathSubst.openAt p x) (PathSubst.openAt q x) := by
  intro x
  refine Fin.cases ?_ (fun y => ?_) x
  · exact hpq
  · exact hE.refl (.var y)

/-- Opening structurally converted types with equivalent actual paths
preserves structural conversion in the outer scope. -/
theorem Ty.PathConv.open_paths
    {E : Path n -> Path n -> Prop}
    (hE : Path.IsEquivCongr E)
    (h : Ty.PathConv (Path.ScopedLift E) S T)
    (hpq : E p q) :
    Ty.PathConv E (S.open p) (T.open q) := by
  have hleft : Ty.PathConv E (S.open p) (T.open p) := by
    apply h.subst_same
    intro r s hrs
    exact hrs.subst_openAt hE (hE.refl p)
  have hright : Ty.PathConv E (T.open p) (T.open q) := by
    exact Ty.PathConv.subst_congr hE
      (PathSubst.openAt_pointwise hE hpq) T
  exact hleft.trans hE hright

/-- Generalized-type form of `Ty.PathConv.open_paths`. -/
theorem Tau.PathConv.open_paths
    {E : Path n -> Path n -> Prop}
    (hE : Path.IsEquivCongr E)
    (h : Tau.PathConv (Path.ScopedLift E) d₁ d₂)
    (hpq : E p q) :
    Tau.PathConv E (d₁.open p) (d₂.open q) := by
  have hleft : Tau.PathConv E (d₁.open p) (d₂.open p) := by
    apply h.subst_same
    intro r s hrs
    exact hrs.subst_openAt hE (hE.refl p)
  have hright : Tau.PathConv E (d₂.open p) (d₂.open q) := by
    exact Tau.PathConv.subst_congr hE
      (PathSubst.openAt_pointwise hE hpq) d₂
  exact hleft.trans hE hright

/-! ## Runtime specialization -/

abbrev Ty.RuntimeConv (sigma : Store n) : Ty n -> Ty n -> Prop :=
  Ty.PathConv (Path.RuntimeEq sigma)

/-- Structural generalized-type conversion induced by store-indexed runtime
path equality.  Unlike the shallow replacement closure `Tau.RuntimeConv`, it
descends under binders using `ScopedRuntimeEq`. -/
abbrev Tau.ScopedRuntimeConv (sigma : Store n) :
    Tau n k -> Tau n k -> Prop :=
  Tau.PathConv (Path.RuntimeEq sigma)

theorem Ty.RuntimeConv.open_paths
    (h : Ty.PathConv (Path.ScopedRuntimeEq sigma) S T)
    (hpq : Path.RuntimeEq sigma p q) :
    Ty.RuntimeConv sigma (S.open p) (T.open q) :=
  h.open_paths (Path.RuntimeEq.isEquivCongr sigma) hpq

theorem Tau.ScopedRuntimeConv.open_paths
    (h : Tau.PathConv (Path.ScopedRuntimeEq sigma) d₁ d₂)
    (hpq : Path.RuntimeEq sigma p q) :
    Tau.ScopedRuntimeConv sigma (d₁.open p) (d₂.open q) :=
  h.open_paths (Path.RuntimeEq.isEquivCongr sigma) hpq

end LambdaPHistory
