import LambdaPToFCo.Full.ContextSubtyping
import LambdaPToFCo.Full.DemandDirectedSubtyping

/-!
# Sealed heterogeneous-context adaptation

Pair and function rules compare dependent members under different source
contexts. `HeterogeneousAdaptation` retains that context relation explicitly:
the subtyping derivation and producer remain under the left context, while the
demand and its structural model remain under the right context. No source
path typing, well-formedness proof, or plan model is transported between
those contexts.

The initial family has only two closed realizations. Equal contexts delegate
to an existing sealed `FusedAdaptation`; arbitrary related contexts may erase
observations into the exact opaque demand. A structural heterogeneous member
adapter will require further derivation-specific constructors rather than a
free stable adapter.
-/

namespace LambdaPToFCo.Full

open LambdaPFC
open SystemFCoExt
open TranslationInterfaces
open DemandDirectedSubtyping
open SubtypingCompilerCore

namespace ContextSubtyping

/-- The exact context relation generated by the first premise of a dependent
pair rule. The member premise is checked under the left/source binder, while
the target member model remains under the right/target binder. -/
def underBinder
    {n : Nat} {context : Ctx n} {sourceType targetType : Ty n}
    (first : Tau.Sub context (.ty sourceType) (.ty targetType)) :
    ContextSubtyping (context.snoc sourceType) (context.snoc targetType) :=
  .snoc (.identity context) first

end ContextSubtyping

/-- A sealed static adaptation whose source and demand may inhabit related,
but nonidentical, LambdaPFC contexts. Both target scope views still inhabit
one concrete SystemFCoExt context, so their stable fields can be aligned
without claiming that their source models were transported. -/
inductive HeterogeneousAdaptation
    {sig : Sig} (targetContext : SystemFCoExt.Ctx sig) :
    {n : Nat} ->
    {leftContext rightContext : Ctx n} ->
    (contexts : ContextSubtyping leftContext rightContext) ->
    {leftScope : ScopeModel leftContext targetContext} ->
    {rightScope : ScopeModel rightContext targetContext} ->
    (alignment : ScopeAlignment leftScope.view rightScope.view) ->
    {sourceType targetType : Ty n} ->
    (subtyping : Tau.Sub leftContext (.ty sourceType) (.ty targetType)) ->
    (source : OrdinaryProducer leftContext targetContext leftScope sourceType) ->
    (demand : ProperDemand rightContext targetContext rightScope targetType) ->
    Type where
  | ofFused
      {n : Nat} {context : Ctx n}
      {leftScope rightScope : ScopeModel context targetContext}
      {alignment : ScopeAlignment leftScope.view rightScope.view}
      {sourceType targetType : Ty n}
      {subtyping : Tau.Sub context (.ty sourceType) (.ty targetType)}
      {source : OrdinaryProducer context targetContext leftScope sourceType}
      {demand : ProperDemand context targetContext rightScope targetType}
      (adaptation : FusedAdaptation alignment subtyping (.ordinary source)
        demand) :
      @HeterogeneousAdaptation sig targetContext n context context
        (.identity context) leftScope rightScope alignment sourceType
        targetType subtyping source demand
  | toOpaque
      {n : Nat} {leftContext rightContext : Ctx n}
      (contexts : ContextSubtyping leftContext rightContext)
      {leftScope : ScopeModel leftContext targetContext}
      {rightScope : ScopeModel rightContext targetContext}
      (alignment : ScopeAlignment leftScope.view rightScope.view)
      {sourceType targetType : Ty n}
      (subtyping : Tau.Sub leftContext (.ty sourceType) (.ty targetType))
      (source : OrdinaryProducer leftContext targetContext leftScope sourceType)
      (trace : DemandTrace rightContext targetType) :
      HeterogeneousAdaptation targetContext contexts alignment subtyping source
        (opaqueDemand rightScope trace)

namespace HeterogeneousAdaptation

/-- The target adapter is determined by the sealed evidence. No constructor
accepts one as an input. -/
noncomputable def adapter
    (adaptation : HeterogeneousAdaptation targetContext contexts alignment
      subtyping source demand) :
    StableIdentity.Adapter targetContext source.plan demand.plan :=
  match adaptation with
  | .ofFused fused => fused.adapter
  | .toOpaque _ _ _ source _ =>
      StableIdentity.Adapter.toTop targetContext source.plan

/-- Equal-context fused adaptation embeds without rebuilding or exposing its
stable adapter. -/
noncomputable def fromFused
    {n : Nat} {sourceContext : Ctx n}
    {sig : Sig} {targetContext : SystemFCoExt.Ctx sig}
    {leftScope rightScope : ScopeModel sourceContext targetContext}
    {alignment : ScopeAlignment leftScope.view rightScope.view}
    {sourceType targetType : Ty n}
    {subtyping : Tau.Sub sourceContext (.ty sourceType) (.ty targetType)}
    {source : OrdinaryProducer sourceContext targetContext leftScope sourceType}
    {demand : ProperDemand sourceContext targetContext rightScope targetType}
    (adaptation : FusedAdaptation alignment subtyping (.ordinary source)
      demand) :
    HeterogeneousAdaptation targetContext (.identity sourceContext) alignment
      subtyping source demand :=
  .ofFused adaptation

/-- Observation erasure is sound for every context relation because the
right demand is forced to canonical `Top.plan`. -/
noncomputable def observationFree
    (contexts : ContextSubtyping leftContext rightContext)
    (alignment : ScopeAlignment leftScope.view rightScope.view)
    (subtyping : Tau.Sub leftContext (.ty sourceType) (.ty targetType))
    (source : OrdinaryProducer leftContext targetContext leftScope sourceType)
    (trace : DemandTrace rightContext targetType) :
    HeterogeneousAdaptation targetContext contexts alignment subtyping source
      (opaqueDemand rightScope trace) :=
  .toOpaque contexts alignment subtyping source trace

/-- Apply the sealed adapter to the exact source package. This remains a
static package construction, not operational readiness evidence. -/
noncomputable def package
    (adaptation : HeterogeneousAdaptation targetContext contexts alignment
      subtyping source demand) : CompiledPackage targetContext demand.plan :=
  source.package.adapt adaptation.adapter

end HeterogeneousAdaptation

end LambdaPToFCo.Full
