import LambdaPToFCo.Full.ContextSubtyping
import LambdaPToFCo.Full.DemandDirectedSubtyping

/-!
# Sealed heterogeneous-context adaptation

Pair and function rules compare dependent members under different source
contexts. `HeterogeneousAdaptation` retains that context relation explicitly:
the subtyping derivation and producer remain under the left context, while the
demand and its structural model remain under the right context. No source
path typing, well-formedness proof, or plan model is transported between
those contexts.

The initial producer-left family has only two closed realizations. Equal
contexts delegate to an existing sealed `FusedAdaptation`; arbitrary related
contexts may erase observations into the exact opaque demand. Its
producer-right dual records the orientation required by contravariant
function domains: the codomain derivation and demand remain on the left while
the retained source result producer remains on the right. Neither family
claims arbitrary observed recursive construction; that requires further
derivation-specific constructors rather than a free stable adapter.
-/

namespace LambdaPToFCo.Full

open LambdaPFC
open SystemFCoExt
open TranslationInterfaces
open DemandDirectedSubtyping
open SubtypingCompilerCore

namespace ContextSubtyping

/-- The exact context relation generated by the first premise of a dependent
pair rule. The member premise is checked under the left/source binder, while
the target member model remains under the right/target binder. -/
def underBinder
    {n : Nat} {context : Ctx n} {sourceType targetType : Ty n}
    (first : Tau.Sub context (.ty sourceType) (.ty targetType)) :
    ContextSubtyping (context.snoc sourceType) (context.snoc targetType) :=
  .snoc (.identity context) first

end ContextSubtyping

/-- A sealed static adaptation whose source and demand may inhabit related,
but nonidentical, LambdaPFC contexts. Both target scope views still inhabit
one concrete SystemFCoExt context, so their stable fields can be aligned
without claiming that their source models were transported. -/
inductive HeterogeneousAdaptation
    {sig : Sig} (targetContext : SystemFCoExt.Ctx sig) :
    {n : Nat} ->
    {leftContext rightContext : Ctx n} ->
    (contexts : ContextSubtyping leftContext rightContext) ->
    {leftScope : ScopeModel leftContext targetContext} ->
    {rightScope : ScopeModel rightContext targetContext} ->
    (alignment : ScopeAlignment leftScope.view rightScope.view) ->
    {sourceType targetType : Ty n} ->
    (subtyping : Tau.Sub leftContext (.ty sourceType) (.ty targetType)) ->
    (source : OrdinaryProducer leftContext targetContext leftScope sourceType) ->
    (demand : ProperDemand rightContext targetContext rightScope targetType) ->
    Type where
  | ofFused
      {n : Nat} {context : Ctx n}
      {leftScope rightScope : ScopeModel context targetContext}
      {alignment : ScopeAlignment leftScope.view rightScope.view}
      {sourceType targetType : Ty n}
      {subtyping : Tau.Sub context (.ty sourceType) (.ty targetType)}
      {source : OrdinaryProducer context targetContext leftScope sourceType}
      {demand : ProperDemand context targetContext rightScope targetType}
      (adaptation : FusedAdaptation alignment subtyping (.ordinary source)
        demand) :
      @HeterogeneousAdaptation sig targetContext n context context
        (.identity context) leftScope rightScope alignment sourceType
        targetType subtyping source demand
  | toOpaque
      {n : Nat} {leftContext rightContext : Ctx n}
      (contexts : ContextSubtyping leftContext rightContext)
      {leftScope : ScopeModel leftContext targetContext}
      {rightScope : ScopeModel rightContext targetContext}
      (alignment : ScopeAlignment leftScope.view rightScope.view)
      {sourceType targetType : Ty n}
      (subtyping : Tau.Sub leftContext (.ty sourceType) (.ty targetType))
      (source : OrdinaryProducer leftContext targetContext leftScope sourceType)
      (trace : DemandTrace rightContext targetType) :
      HeterogeneousAdaptation targetContext contexts alignment subtyping source
        (opaqueDemand rightScope trace)

namespace HeterogeneousAdaptation

/-- The target adapter is determined by the sealed evidence. No constructor
accepts one as an input. -/
noncomputable def adapter
    (adaptation : HeterogeneousAdaptation targetContext contexts alignment
      subtyping source demand) :
    StableIdentity.Adapter targetContext source.plan demand.plan :=
  match adaptation with
  | .ofFused fused => fused.adapter
  | .toOpaque _ _ _ source _ =>
      StableIdentity.Adapter.toTop targetContext source.plan

/-- Equal-context fused adaptation embeds without rebuilding or exposing its
stable adapter. -/
noncomputable def fromFused
    {n : Nat} {sourceContext : Ctx n}
    {sig : Sig} {targetContext : SystemFCoExt.Ctx sig}
    {leftScope rightScope : ScopeModel sourceContext targetContext}
    {alignment : ScopeAlignment leftScope.view rightScope.view}
    {sourceType targetType : Ty n}
    {subtyping : Tau.Sub sourceContext (.ty sourceType) (.ty targetType)}
    {source : OrdinaryProducer sourceContext targetContext leftScope sourceType}
    {demand : ProperDemand sourceContext targetContext rightScope targetType}
    (adaptation : FusedAdaptation alignment subtyping (.ordinary source)
      demand) :
    HeterogeneousAdaptation targetContext (.identity sourceContext) alignment
      subtyping source demand :=
  .ofFused adaptation

/-- Observation erasure is sound for every context relation because the
right demand is forced to canonical `Top.plan`. -/
noncomputable def observationFree
    (contexts : ContextSubtyping leftContext rightContext)
    (alignment : ScopeAlignment leftScope.view rightScope.view)
    (subtyping : Tau.Sub leftContext (.ty sourceType) (.ty targetType))
    (source : OrdinaryProducer leftContext targetContext leftScope sourceType)
    (trace : DemandTrace rightContext targetType) :
    HeterogeneousAdaptation targetContext contexts alignment subtyping source
      (opaqueDemand rightScope trace) :=
  .toOpaque contexts alignment subtyping source trace

/-- Apply the sealed adapter to the exact source package. This remains a
static package construction, not operational readiness evidence. -/
noncomputable def package
    (adaptation : HeterogeneousAdaptation targetContext contexts alignment
      subtyping source demand) : CompiledPackage targetContext demand.plan :=
  source.package.adapt adaptation.adapter

end HeterogeneousAdaptation

/-! ## Producer-right heterogeneous adaptation

For a function premise `targetDomain <: sourceDomain`, context subtyping runs
from `Γ,targetDomain` to `Γ,sourceDomain`. The codomain derivation and target
demand inhabit the left context, but the retained source-function codomain
producer is modeled under the right context. Reversing `ContextSubtyping`
would be invalid, so this dual family records that orientation directly. -/

/-- A sealed static adaptation whose source producer inhabits the right side
of a context refinement while its derivation and demand inhabit the left.
Both target scope views still share one concrete System FCo context. -/
inductive ContravariantHeterogeneousAdaptation
    {sig : Sig} (targetContext : SystemFCoExt.Ctx sig) :
    {n : Nat} ->
    {leftContext rightContext : Ctx n} ->
    (contexts : ContextSubtyping leftContext rightContext) ->
    {sourceScope : ScopeModel rightContext targetContext} ->
    {demandScope : ScopeModel leftContext targetContext} ->
    (alignment : ScopeAlignment sourceScope.view demandScope.view) ->
    {sourceType targetType : Ty n} ->
    (subtyping : Tau.Sub leftContext (.ty sourceType) (.ty targetType)) ->
    (source : OrdinaryProducer rightContext targetContext sourceScope
      sourceType) ->
    (demand : ProperDemand leftContext targetContext demandScope targetType) ->
    Type where
  | ofFused
      {n : Nat} {context : Ctx n}
      {sourceScope demandScope : ScopeModel context targetContext}
      {alignment : ScopeAlignment sourceScope.view demandScope.view}
      {sourceType targetType : Ty n}
      {subtyping : Tau.Sub context (.ty sourceType) (.ty targetType)}
      {source : OrdinaryProducer context targetContext sourceScope sourceType}
      {demand : ProperDemand context targetContext demandScope targetType}
      (adaptation : FusedAdaptation alignment subtyping (.ordinary source)
        demand) :
      @ContravariantHeterogeneousAdaptation sig targetContext n context context
        (.identity context) sourceScope demandScope alignment sourceType
        targetType subtyping source demand
  | toOpaque
      {n : Nat} {leftContext rightContext : Ctx n}
      (contexts : ContextSubtyping leftContext rightContext)
      {sourceScope : ScopeModel rightContext targetContext}
      {demandScope : ScopeModel leftContext targetContext}
      (alignment : ScopeAlignment sourceScope.view demandScope.view)
      {sourceType targetType : Ty n}
      (subtyping : Tau.Sub leftContext (.ty sourceType) (.ty targetType))
      (source : OrdinaryProducer rightContext targetContext sourceScope
        sourceType)
      (trace : DemandTrace leftContext targetType) :
      ContravariantHeterogeneousAdaptation targetContext contexts alignment
        subtyping source (opaqueDemand demandScope trace)

namespace ContravariantHeterogeneousAdaptation

/-- The exact stable adapter determined by the sealed dual evidence. -/
noncomputable def adapter
    (adaptation : ContravariantHeterogeneousAdaptation targetContext contexts
      alignment subtyping source demand) :
    StableIdentity.Adapter targetContext source.plan demand.plan :=
  match adaptation with
  | .ofFused fused => fused.adapter
  | .toOpaque _ _ _ source _ =>
      StableIdentity.Adapter.toTop targetContext source.plan

/-- Equal-context fused evidence embeds without changing either endpoint. -/
noncomputable def fromFused
    {n : Nat} {context : Ctx n}
    {sig : Sig} {targetContext : SystemFCoExt.Ctx sig}
    {sourceScope demandScope : ScopeModel context targetContext}
    {alignment : ScopeAlignment sourceScope.view demandScope.view}
    {sourceType targetType : Ty n}
    {subtyping : Tau.Sub context (.ty sourceType) (.ty targetType)}
    {source : OrdinaryProducer context targetContext sourceScope sourceType}
    {demand : ProperDemand context targetContext demandScope targetType}
    (adaptation : FusedAdaptation alignment subtyping (.ordinary source)
      demand) :
    ContravariantHeterogeneousAdaptation targetContext (.identity context)
      alignment subtyping source demand :=
  .ofFused adaptation

/-- Observation erasure is sound at any related producer-right/demand-left
contexts. -/
noncomputable def observationFree
    (contexts : ContextSubtyping leftContext rightContext)
    (alignment : ScopeAlignment sourceScope.view demandScope.view)
    (subtyping : Tau.Sub leftContext (.ty sourceType) (.ty targetType))
    (source : OrdinaryProducer rightContext targetContext sourceScope
      sourceType)
    (trace : DemandTrace leftContext targetType) :
    ContravariantHeterogeneousAdaptation targetContext contexts alignment
      subtyping source (opaqueDemand demandScope trace) :=
  .toOpaque contexts alignment subtyping source trace

end ContravariantHeterogeneousAdaptation

end LambdaPToFCo.Full
