import LambdaPToFCo.Full.DemandDirectedSubtyping
import LambdaPToFCo.Full.HeterogeneousAdaptation
import LambdaPToFCo.Full.PairRepresentationBridgeConstruction

/-!
# Closed contextual proper-pair subtyping seams

This leaf constructs the representation adapter for one source
`Tau.Sub.pair` rule without transporting the target member model from
`Γ.snoc S'` to `Γ.snoc S`.

The enclosing source producer and target demand expose their exact proper-pair
models.  The first adapter is projected from a sealed `FusedAdaptation`
indexed by the exact first premise.  The member seam retains the exact outer
endpoint models and the exact member premise, but asks only for the adapter
needed in the common target context generated by
`PairRepresentationBridgeConstruction`.

Observation erasure remains a closed base case. Observed members may instead
consume a recursive `HeterogeneousAdaptation` whose left producer stays under
the source-first binder and whose right demand stays under the target-first
binder. The exact first premise indexes their `ContextSubtyping` relation.
There is no generic callback, prebuilt member adapter, representation
coercion, path substitution, or homogeneous model transport.
-/

namespace LambdaPToFCo.Full.PairSubtypingRuleConstruction

open LambdaPFC
open SystemFCoExt
open TranslationInterfaces
open DemandDirectedSubtyping

variable {n : Nat} {sourceContext : LambdaPFC.Ctx n}
variable {sig : Sig} {targetContext : SystemFCoExt.Ctx sig}

/-- Exact structural views of the two enclosing proper-pair endpoints. -/
structure EndpointModels
    {sourceScope demandScope : ScopeModel sourceContext targetContext}
    {sourceFirst targetFirst : LambdaPFC.Ty n}
    {sourceMember targetMember : LambdaPFC.Ty (n + 1)}
    {label : LambdaPFC.Name}
    (source : OrdinaryProducer sourceContext targetContext sourceScope
      (.Pair sourceFirst label (.ty sourceMember)))
    (demand : ProperDemand sourceContext targetContext demandScope
      (.Pair targetFirst label (.ty targetMember))) : Type where
  sourceFirstPlan : ValuePlan sig
  sourceMemberPlan : ValuePlan sourceFirstPlan.scope
  sourceFirstModel : ProducerPlanModel sourceContext targetContext
    sourceScope.view sourceFirst sourceFirstPlan
  sourceMemberModel : ProducerPlanModel (sourceContext.snoc sourceFirst)
    (sourceFirstPlan.context targetContext)
    (ScopeView.bindPlan sourceScope.view sourceFirstPlan)
    sourceMember sourceMemberPlan
  sourceModel_eq : source.model =
    ⟨Pair.Proper.plan sourceFirstPlan sourceMemberPlan,
      .properPair (label := label) sourceFirstModel sourceMemberModel⟩
  targetFirstPlan : ValuePlan sig
  targetMemberPlan : ValuePlan targetFirstPlan.scope
  targetFirstModel : BidirectionalPlanModel sourceContext targetContext
    demandScope.view targetFirst targetFirstPlan
  targetMemberModel : BidirectionalPlanModel
    (sourceContext.snoc targetFirst)
    (targetFirstPlan.context targetContext)
    (ScopeView.bindPlan demandScope.view targetFirstPlan)
    targetMember targetMemberPlan
  demandModel_eq : demand.model =
    ⟨Pair.Proper.plan targetFirstPlan targetMemberPlan,
      .properPair (label := label) targetFirstModel targetMemberModel⟩

/-- The first-component seam is a recursive fused adaptation indexed by the
exact first premise.  Its two plan equalities tie it to the enclosing pair
models, so no unrelated adapter can enter the representation bridge. -/
structure FirstAdaptation
    {sourceScope demandScope : ScopeModel sourceContext targetContext}
    {sourceFirst targetFirst : LambdaPFC.Ty n}
    {sourceMember targetMember : LambdaPFC.Ty (n + 1)}
    {label : LambdaPFC.Name}
    {source : OrdinaryProducer sourceContext targetContext sourceScope
      (.Pair sourceFirst label (.ty sourceMember))}
    {demand : ProperDemand sourceContext targetContext demandScope
      (.Pair targetFirst label (.ty targetMember))}
    (endpoints : EndpointModels source demand)
    (subtyping : Tau.Sub sourceContext (.ty sourceFirst) (.ty targetFirst)) :
    Type where
  producerScope : ScopeModel sourceContext targetContext
  consumerScope : ScopeModel sourceContext targetContext
  alignment : ScopeAlignment producerScope.view consumerScope.view
  producer : ProperProducer sourceContext targetContext producerScope
    sourceFirst
  consumer : ProperDemand sourceContext targetContext consumerScope targetFirst
  adaptation : FusedAdaptation alignment subtyping producer consumer
  producerPlan_eq : producer.plan = endpoints.sourceFirstPlan
  consumerPlan_eq : consumer.plan = endpoints.targetFirstPlan

namespace FirstAdaptation

/-- Project the exact first adapter fixed by the two enclosing pair plans. -/
noncomputable def adapter
    {sourceScope demandScope : ScopeModel sourceContext targetContext}
    {sourceFirst targetFirst : LambdaPFC.Ty n}
    {sourceMember targetMember : LambdaPFC.Ty (n + 1)}
    {label : LambdaPFC.Name}
    {source : OrdinaryProducer sourceContext targetContext sourceScope
      (.Pair sourceFirst label (.ty sourceMember))}
    {demand : ProperDemand sourceContext targetContext demandScope
      (.Pair targetFirst label (.ty targetMember))}
    {endpoints : EndpointModels source demand}
    {subtyping : Tau.Sub sourceContext (.ty sourceFirst) (.ty targetFirst)}
    (first : FirstAdaptation endpoints subtyping) :
    StableIdentity.Adapter targetContext endpoints.sourceFirstPlan
      endpoints.targetFirstPlan := by
  rw [← first.producerPlan_eq, ← first.consumerPlan_eq]
  exact first.adaptation.adapter

end FirstAdaptation

/-- The exact target context obtained after opening the source
representation, adapting its first package, and opening the adapted target
first package. -/
abbrev CommonMemberContext
    {sourceScope demandScope : ScopeModel sourceContext targetContext}
    {sourceFirst targetFirst : LambdaPFC.Ty n}
    {sourceMember targetMember : LambdaPFC.Ty (n + 1)}
    {label : LambdaPFC.Name}
    {source : OrdinaryProducer sourceContext targetContext sourceScope
      (.Pair sourceFirst label (.ty sourceMember))}
    {demand : ProperDemand sourceContext targetContext demandScope
      (.Pair targetFirst label (.ty targetMember))}
    (endpoints : EndpointModels source demand) :=
  PairRepresentationBridgeConstruction.targetFirstOpenedContext targetContext
    endpoints.sourceFirstPlan endpoints.sourceMemberPlan
    endpoints.targetFirstPlan

/-- Reindexing canonical `Top.plan` into the representation bridge's common
member context remains canonical `Top.plan`. -/
theorem targetMemberAtSource_top
    (sourceFirst : ValuePlan sig)
    (sourceMember : ValuePlan sourceFirst.scope)
    (targetFirst : ValuePlan sig) :
    PairRepresentationBridgeConstruction.targetMemberAtSource sourceFirst
        sourceMember targetFirst (Top.plan targetFirst.scope) =
      Top.plan
        (PairRepresentationBridgeConstruction.targetFirstAtSource sourceFirst
          sourceMember targetFirst).scope := by
  rfl

/-- Exact recursive member evidence in the representation bridge's common
target context. The source producer remains modeled under `Γ,S`, while the
target demand remains modeled under `Γ,S′`; their source contexts are related
by precisely the first premise of the enclosing pair rule.

The only computational input is a sealed `HeterogeneousAdaptation`. Stable
adapters, callbacks returning adapters, path substitutions, and transported
source models are not fields of this record. -/
structure HeterogeneousMemberInput
    {sourceScope demandScope : ScopeModel sourceContext targetContext}
    {sourceFirst targetFirst : LambdaPFC.Ty n}
    {sourceMember targetMember : LambdaPFC.Ty (n + 1)}
    {label : LambdaPFC.Name}
    {source : OrdinaryProducer sourceContext targetContext sourceScope
      (.Pair sourceFirst label (.ty sourceMember))}
    {demand : ProperDemand sourceContext targetContext demandScope
      (.Pair targetFirst label (.ty targetMember))}
    (endpoints : EndpointModels source demand)
    (firstSubtyping : Tau.Sub sourceContext
      (.ty sourceFirst) (.ty targetFirst))
    (memberSubtyping : Tau.Sub (sourceContext.snoc sourceFirst)
      (.ty sourceMember) (.ty targetMember)) : Type where
  producerScope : ScopeModel (sourceContext.snoc sourceFirst)
    (CommonMemberContext endpoints)
  demandScope : ScopeModel (sourceContext.snoc targetFirst)
    (CommonMemberContext endpoints)
  alignment : ScopeAlignment producerScope.view demandScope.view
  producer : OrdinaryProducer (sourceContext.snoc sourceFirst)
    (CommonMemberContext endpoints) producerScope sourceMember
  demand : ProperDemand (sourceContext.snoc targetFirst)
    (CommonMemberContext endpoints) demandScope targetMember
  adaptation : HeterogeneousAdaptation (CommonMemberContext endpoints)
    (ContextSubtyping.underBinder firstSubtyping) alignment memberSubtyping
    producer demand
  producerPlan_eq : producer.plan =
    (PairRepresentationBridgeConstruction.sourceMemberAtTargetFirst
      targetContext endpoints.sourceFirstPlan endpoints.sourceMemberPlan
      endpoints.targetFirstPlan).plan
  demandPlan_eq : demand.plan =
    PairRepresentationBridgeConstruction.targetMemberAtSource
      endpoints.sourceFirstPlan endpoints.sourceMemberPlan
      endpoints.targetFirstPlan endpoints.targetMemberPlan

namespace HeterogeneousMemberInput

/-- Eliminate the sealed recursive evidence at exactly the two plans opened
by the proper-pair representation bridge. -/
noncomputable def adapter
    {sourceScope demandScope : ScopeModel sourceContext targetContext}
    {sourceFirst targetFirst : LambdaPFC.Ty n}
    {sourceMember targetMember : LambdaPFC.Ty (n + 1)}
    {label : LambdaPFC.Name}
    {source : OrdinaryProducer sourceContext targetContext sourceScope
      (.Pair sourceFirst label (.ty sourceMember))}
    {demand : ProperDemand sourceContext targetContext demandScope
      (.Pair targetFirst label (.ty targetMember))}
    {endpoints : EndpointModels source demand}
    {firstSubtyping : Tau.Sub sourceContext
      (.ty sourceFirst) (.ty targetFirst)}
    {memberSubtyping : Tau.Sub (sourceContext.snoc sourceFirst)
      (.ty sourceMember) (.ty targetMember)}
    (input : HeterogeneousMemberInput endpoints firstSubtyping
      memberSubtyping) :
    StableIdentity.Adapter (CommonMemberContext endpoints)
      (PairRepresentationBridgeConstruction.sourceMemberAtTargetFirst
        targetContext endpoints.sourceFirstPlan endpoints.sourceMemberPlan
        endpoints.targetFirstPlan).plan
      (PairRepresentationBridgeConstruction.targetMemberAtSource
        endpoints.sourceFirstPlan endpoints.sourceMemberPlan
        endpoints.targetFirstPlan endpoints.targetMemberPlan) := by
  rw [← input.producerPlan_eq, ← input.demandPlan_eq]
  exact input.adaptation.adapter

end HeterogeneousMemberInput

/-- Closed evidence for a contextual pair-member adapter.

The family is indexed by the original enclosing pair models and by both exact
premises of the pair rule. It deliberately does not invent a target
`DemandPlanModel` under `sourceContext.snoc sourceFirst`. -/
inductive ContextualMemberAdaptationEvidence
    {sourceScope demandScope : ScopeModel sourceContext targetContext}
    {sourceFirst targetFirst : LambdaPFC.Ty n}
    {sourceMember targetMember : LambdaPFC.Ty (n + 1)}
    {label : LambdaPFC.Name}
    {source : OrdinaryProducer sourceContext targetContext sourceScope
      (.Pair sourceFirst label (.ty sourceMember))}
    {demand : ProperDemand sourceContext targetContext demandScope
      (.Pair targetFirst label (.ty targetMember))}
    (endpoints : EndpointModels source demand)
    (firstSubtyping : Tau.Sub sourceContext
      (.ty sourceFirst) (.ty targetFirst))
    (subtyping : Tau.Sub (sourceContext.snoc sourceFirst)
      (.ty sourceMember) (.ty targetMember)) :
    StableIdentity.Adapter (CommonMemberContext endpoints)
      (PairRepresentationBridgeConstruction.sourceMemberAtTargetFirst
        targetContext endpoints.sourceFirstPlan endpoints.sourceMemberPlan
        endpoints.targetFirstPlan).plan
      (PairRepresentationBridgeConstruction.targetMemberAtSource
        endpoints.sourceFirstPlan endpoints.sourceMemberPlan
        endpoints.targetFirstPlan endpoints.targetMemberPlan) -> Type where
  | observationFree
      (targetPlan_eq : endpoints.targetMemberPlan =
        Top.plan endpoints.targetFirstPlan.scope) :
      ContextualMemberAdaptationEvidence endpoints firstSubtyping subtyping
        (by
          rw [targetPlan_eq, targetMemberAtSource_top]
          exact StableIdentity.Adapter.toTop (CommonMemberContext endpoints)
            (PairRepresentationBridgeConstruction.sourceMemberAtTargetFirst
              targetContext endpoints.sourceFirstPlan
              endpoints.sourceMemberPlan endpoints.targetFirstPlan).plan)
  | heterogeneous
      (input : HeterogeneousMemberInput endpoints firstSubtyping subtyping) :
      ContextualMemberAdaptationEvidence endpoints firstSubtyping subtyping
        input.adapter

/-- The minimal sealed output consumed by the proper-pair representation
bridge.  Its target is the exact outer member plan reindexed into the common
target context. -/
structure ContextualMemberAdaptation
    {sourceScope demandScope : ScopeModel sourceContext targetContext}
    {sourceFirst targetFirst : LambdaPFC.Ty n}
    {sourceMember targetMember : LambdaPFC.Ty (n + 1)}
    {label : LambdaPFC.Name}
    {source : OrdinaryProducer sourceContext targetContext sourceScope
      (.Pair sourceFirst label (.ty sourceMember))}
    {demand : ProperDemand sourceContext targetContext demandScope
      (.Pair targetFirst label (.ty targetMember))}
    (endpoints : EndpointModels source demand)
    (firstSubtyping : Tau.Sub sourceContext
      (.ty sourceFirst) (.ty targetFirst))
    (subtyping : Tau.Sub (sourceContext.snoc sourceFirst)
      (.ty sourceMember) (.ty targetMember)) : Type where
  adapter : StableIdentity.Adapter (CommonMemberContext endpoints)
    (PairRepresentationBridgeConstruction.sourceMemberAtTargetFirst
      targetContext endpoints.sourceFirstPlan endpoints.sourceMemberPlan
      endpoints.targetFirstPlan).plan
    (PairRepresentationBridgeConstruction.targetMemberAtSource
      endpoints.sourceFirstPlan endpoints.sourceMemberPlan
      endpoints.targetFirstPlan endpoints.targetMemberPlan)
  evidence : ContextualMemberAdaptationEvidence endpoints firstSubtyping
    subtyping adapter

namespace ContextualMemberAdaptation

/-- Consume an exact observation-free outer member plan.  The only adapter
choice is canonical observation erasure. -/
noncomputable def observationFree
    {sourceScope demandScope : ScopeModel sourceContext targetContext}
    {sourceFirst targetFirst : LambdaPFC.Ty n}
    {sourceMember targetMember : LambdaPFC.Ty (n + 1)}
    {label : LambdaPFC.Name}
    {source : OrdinaryProducer sourceContext targetContext sourceScope
      (.Pair sourceFirst label (.ty sourceMember))}
    {demand : ProperDemand sourceContext targetContext demandScope
      (.Pair targetFirst label (.ty targetMember))}
    {endpoints : EndpointModels source demand}
    (firstSubtyping : Tau.Sub sourceContext
      (.ty sourceFirst) (.ty targetFirst))
    (subtyping : Tau.Sub (sourceContext.snoc sourceFirst)
      (.ty sourceMember) (.ty targetMember))
    (targetPlan_eq : endpoints.targetMemberPlan =
      Top.plan endpoints.targetFirstPlan.scope) :
    ContextualMemberAdaptation endpoints firstSubtyping subtyping where
  adapter := by
    rw [targetPlan_eq, targetMemberAtSource_top]
    exact StableIdentity.Adapter.toTop (CommonMemberContext endpoints)
      (PairRepresentationBridgeConstruction.sourceMemberAtTargetFirst
        targetContext endpoints.sourceFirstPlan endpoints.sourceMemberPlan
        endpoints.targetFirstPlan).plan
  evidence := .observationFree targetPlan_eq

/-- Consume one exact recursive heterogeneous member adaptation. Its source
and demand keep their original, different source binder contexts; only their
stable target plans meet in the representation bridge's generated common
context. -/
noncomputable def ofHeterogeneous
    {sourceScope demandScope : ScopeModel sourceContext targetContext}
    {sourceFirst targetFirst : LambdaPFC.Ty n}
    {sourceMember targetMember : LambdaPFC.Ty (n + 1)}
    {label : LambdaPFC.Name}
    {source : OrdinaryProducer sourceContext targetContext sourceScope
      (.Pair sourceFirst label (.ty sourceMember))}
    {demand : ProperDemand sourceContext targetContext demandScope
      (.Pair targetFirst label (.ty targetMember))}
    {endpoints : EndpointModels source demand}
    {firstSubtyping : Tau.Sub sourceContext
      (.ty sourceFirst) (.ty targetFirst)}
    {subtyping : Tau.Sub (sourceContext.snoc sourceFirst)
      (.ty sourceMember) (.ty targetMember)}
    (input : HeterogeneousMemberInput endpoints firstSubtyping subtyping) :
    ContextualMemberAdaptation endpoints firstSubtyping subtyping where
  adapter := input.adapter
  evidence := .heterogeneous input

/-- Package the sealed contextual adapter as the exact dependent member input
required by `PairRepresentationBridgeConstruction`. -/
noncomputable def bridge
    {sourceScope demandScope : ScopeModel sourceContext targetContext}
    {sourceFirst targetFirst : LambdaPFC.Ty n}
    {sourceMember targetMember : LambdaPFC.Ty (n + 1)}
    {label : LambdaPFC.Name}
    {source : OrdinaryProducer sourceContext targetContext sourceScope
      (.Pair sourceFirst label (.ty sourceMember))}
    {demand : ProperDemand sourceContext targetContext demandScope
      (.Pair targetFirst label (.ty targetMember))}
    {endpoints : EndpointModels source demand}
    {firstSubtyping : Tau.Sub sourceContext
      (.ty sourceFirst) (.ty targetFirst)}
    {subtyping : Tau.Sub (sourceContext.snoc sourceFirst)
      (.ty sourceMember) (.ty targetMember)}
    (member : ContextualMemberAdaptation endpoints firstSubtyping subtyping) :
    PairRepresentationBridgeConstruction.DependentMemberAdapter targetContext
      endpoints.sourceFirstPlan endpoints.sourceMemberPlan
      endpoints.targetFirstPlan endpoints.targetMemberPlan where
  adapter := member.adapter

end ContextualMemberAdaptation

/-- Assemble the exact outer proper-pair stable adapter.  The corresponding
source derivation is `Tau.Sub.pair firstSubtyping memberSubtyping`; this leaf
does not claim a general `FusedAdaptation` result for it. -/
noncomputable def adapter
    {sourceScope demandScope : ScopeModel sourceContext targetContext}
    {sourceFirst targetFirst : LambdaPFC.Ty n}
    {sourceMember targetMember : LambdaPFC.Ty (n + 1)}
    {label : LambdaPFC.Name}
    {source : OrdinaryProducer sourceContext targetContext sourceScope
      (.Pair sourceFirst label (.ty sourceMember))}
    {demand : ProperDemand sourceContext targetContext demandScope
      (.Pair targetFirst label (.ty targetMember))}
    (firstSubtyping : Tau.Sub sourceContext
      (.ty sourceFirst) (.ty targetFirst))
    (memberSubtyping : Tau.Sub (sourceContext.snoc sourceFirst)
      (.ty sourceMember) (.ty targetMember))
    (endpoints : EndpointModels source demand)
    (first : FirstAdaptation endpoints firstSubtyping)
    (member : ContextualMemberAdaptation endpoints firstSubtyping
      memberSubtyping) :
    StableIdentity.Adapter targetContext source.plan demand.plan := by
  change StableIdentity.Adapter targetContext source.model.1 demand.model.1
  rw [endpoints.sourceModel_eq, endpoints.demandModel_eq]
  exact PairRepresentationBridgeConstruction.adapter first.adapter
    member.bridge

end LambdaPToFCo.Full.PairSubtypingRuleConstruction
