import LambdaPCCI.Runtime

/-!
Proof-relevant runtime equality and type conversion.

Runtime equality is generated by paths resolving to the same generalized
referent, then closed under equivalence and path congruence.  Its scoped lift
extends the relation below a source binder without giving the fresh variable
any equations beyond reflexivity.  Generalized-type conversion records
replacement of runtime-equal paths in an arbitrary type context.
-/

namespace LambdaPCCI

/-! ## Runtime path equality -/

/-- Finite evidence for store-indexed runtime path equality. -/
inductive Path.RuntimeEq (sigma : Store n) : Path n -> Path n -> Type where
| refl : Path.RuntimeEq sigma p p
| symm : Path.RuntimeEq sigma p q -> Path.RuntimeEq sigma q p
| trans :
    Path.RuntimeEq sigma p q ->
    Path.RuntimeEq sigma q r ->
    Path.RuntimeEq sigma p r
| coresolve {referent : Path.Referent n} :
    Path.Resolve p sigma referent ->
    Path.Resolve q sigma referent ->
    Path.RuntimeEq sigma p q
| fst : Path.RuntimeEq sigma p q -> Path.RuntimeEq sigma p.fst q.fst
| sel : Path.RuntimeEq sigma p q ->
    (a : Name) -> Path.RuntimeEq sigma (p.sel a) (q.sel a)

/-- Runtime equality preserves the complete generalized-resolution graph. -/
theorem Path.RuntimeEq.resolve_iff
    {n : Nat} {sigma : Store n} {p q : Path n}
    (evidence : Path.RuntimeEq sigma p q) (referent : Path.Referent n) :
    Path.Resolve p sigma referent <-> Path.Resolve q sigma referent := by
  induction evidence generalizing referent with
  | refl => exact Iff.rfl
  | symm _ ih => exact (ih referent).symm
  | trans _ _ ih1 ih2 => exact (ih1 referent).trans (ih2 referent)
  | coresolve commonLeft commonRight =>
      constructor
      · intro left
        have referents := commonLeft.deterministic left
        cases referents
        exact commonRight
      · intro right
        have referents := commonRight.deterministic right
        cases referents
        exact commonLeft
  | fst _ ih =>
      constructor
      · rintro (_ | ⟨hp, hb⟩)
        exact .fst ((ih _).mp hp) hb
      · rintro (_ | ⟨hp, hb⟩)
        exact .fst ((ih _).mpr hp) hb
  | sel _ _ ih =>
      constructor
      · intro h
        cases h with
        | sel hp hb => exact .sel ((ih _).mp hp) hb
        | sel_miss hp hb hne htail =>
            exact .sel_miss ((ih _).mp hp) hb hne htail
      · intro h
        cases h with
        | sel hp hb => exact .sel ((ih _).mpr hp) hb
        | sel_miss hp hb hne htail =>
            exact .sel_miss ((ih _).mpr hp) hb hne htail

noncomputable def Path.RuntimeEq.weaken
    {n : Nat} {sigma : Store n} {p q : Path n}
    (evidence : Path.RuntimeEq sigma p q)
    (v : Tm n) (vv : v.IsValue) :
    Path.RuntimeEq (Store.val sigma v vv) p.weaken q.weaken := by
  induction evidence with
  | refl => exact .refl
  | symm _ ih => exact .symm ih
  | trans _ _ ih1 ih2 => exact .trans ih1 ih2
  | coresolve left right =>
      exact .coresolve (left.weaken v vv) (right.weaken v vv)
  | fst _ ih => exact .fst ih
  | sel _ a ih => exact .sel ih a

/-! ## Generic equivalence and binder lifting -/

/-- Operations required of proof-relevant path equality. -/
structure Path.EqCongruence
    (R : Path n -> Path n -> Type) : Type where
  refl : forall p, R p p
  symm : forall {p q}, R p q -> R q p
  trans : forall {p q r}, R p q -> R q r -> R p r
  fst : forall {p q}, R p q -> R p.fst q.fst
  sel : forall {p q}, R p q -> forall a, R (p.sel a) (q.sel a)

def Path.RuntimeEq.eqCongruence (sigma : Store n) :
    Path.EqCongruence (Path.RuntimeEq sigma) where
  refl _ := .refl
  symm evidence := .symm evidence
  trans first second := .trans first second
  fst evidence := evidence.fst
  sel evidence a := evidence.sel a

/-- Least path congruence below a binder.  Ambient equations are weakened;
the fresh variable has only its reflexive seed. -/
inductive Path.ScopedLift
    (R : Path n -> Path n -> Type) :
    Path (n + 1) -> Path (n + 1) -> Type where
| bound : Path.ScopedLift R (.var 0) (.var 0)
| old : R p q -> Path.ScopedLift R p.weaken q.weaken
| symm : Path.ScopedLift R p q -> Path.ScopedLift R q p
| trans :
    Path.ScopedLift R p q ->
    Path.ScopedLift R q r ->
    Path.ScopedLift R p r
| fst : Path.ScopedLift R p q -> Path.ScopedLift R p.fst q.fst
| sel : Path.ScopedLift R p q -> Path.ScopedLift R (p.sel a) (q.sel a)

noncomputable def Path.ScopedLift.refl
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R) (p : Path (n + 1)) :
    Path.ScopedLift R p p := by
  induction p with
  | var x =>
      refine Fin.cases ?_ (fun y => ?_) x
      · exact .bound
      · simpa [Path.weaken, Path.rename] using
          Path.ScopedLift.old (operations.refl (Path.var y))
  | fst p ih => exact .fst ih
  | sel p a ih => exact .sel ih

noncomputable def Path.ScopedLift.eqCongruence
    (operations : Path.EqCongruence R) :
    Path.EqCongruence (Path.ScopedLift R) where
  refl := Path.ScopedLift.refl operations
  symm evidence := .symm evidence
  trans first second := .trans first second
  fst evidence := .fst evidence
  sel evidence _ := .sel evidence

/-- Scoped runtime equality is stable under allocation in the ambient store. -/
noncomputable def Path.ScopedLift.weakenRuntime
    {n : Nat} {sigma : Store n} {p q : Path (n + 1)}
    (evidence : Path.ScopedLift (Path.RuntimeEq sigma) p q)
    (v : Tm n) (vv : v.IsValue) :
    Path.ScopedLift (Path.RuntimeEq (Store.val sigma v vv))
      (p.rename FinFun.weaken.ext) (q.rename FinFun.weaken.ext) := by
  induction evidence with
  | bound => exact .bound
  | old evidence =>
      simpa only [Path.weaken, Path.rename_rename, FinFun.comp_weaken] using
        Path.ScopedLift.old (evidence.weaken v vv)
  | symm _ ih => exact .symm ih
  | trans _ _ ih1 ih2 => exact .trans ih1 ih2
  | fst _ ih => exact .fst ih
  | sel _ ih => exact .sel ih

/-- A relation morphism for simultaneous path substitution. -/
abbrev Path.SubstHom
    (R : Path n -> Path n -> Type)
    (E : Path m -> Path m -> Type)
    (rho : PathSubst n m) : Type :=
  forall {p q}, R p q -> E (p.subst rho) (q.subst rho)

/-- Substitution beneath a binder maps the scoped lift of a relation to the
scoped lift of its image. -/
noncomputable def Path.ScopedLift.subst
    {R : Path n -> Path n -> Type}
    {E : Path m -> Path m -> Type}
    {rho : PathSubst n m}
    (mapOld : Path.SubstHom R E rho)
    (evidence : Path.ScopedLift R p q) :
    Path.ScopedLift E (p.subst rho.lift) (q.subst rho.lift) := by
  induction evidence with
  | bound => exact .bound
  | old evidence =>
      simpa only [Path.weaken_subst_lift] using
        Path.ScopedLift.old (mapOld evidence)
  | symm _ ih => exact .symm ih
  | trans _ _ ih1 ih2 => exact .trans ih1 ih2
  | fst _ ih => exact .fst ih
  | sel _ ih => exact .sel ih

/-- Instantiating scoped equality with related paths yields ambient runtime
equality. -/
noncomputable def Path.ScopedLift.open
    {n : Nat} {R : Path n -> Path n -> Type}
    {p q : Path (n + 1)} {r s : Path n}
    (operations : Path.EqCongruence R)
    (evidence : Path.ScopedLift R p q)
    (arguments : R r s) :
    R (p.open r) (q.open s) := by
  induction evidence generalizing r s with
  | bound => exact arguments
  | old evidence =>
      simpa only [Path.weaken_open] using evidence
  | symm _ ih => exact operations.symm (ih (operations.symm arguments))
  | trans _ _ ih1 ih2 =>
      exact operations.trans (ih1 arguments) (ih2 (operations.refl s))
  | fst _ ih => exact operations.fst (ih arguments)
  | sel _ ih => exact operations.sel (ih arguments) _

/-! ## Proof-relevant conversion -/

mutual

/-- Conversion of capture sets generated by replacement of related paths. -/
inductive CaptureSet.RuntimeConv :
    {n : Nat} -> (Path n -> Path n -> Type) ->
      CaptureSet n -> CaptureSet n -> Type 1 where
| refl : CaptureSet.RuntimeConv R C C
| replace :
    (context : CaptureSet (n + 1)) -> R p q ->
    CaptureSet.RuntimeConv R (context.open p) (context.open q)
| empty : CaptureSet.RuntimeConv R .empty .empty
| union :
    CaptureSet.RuntimeConv R C C' ->
    CaptureSet.RuntimeConv R D D' ->
    CaptureSet.RuntimeConv R (.union C D) (.union C' D')
| singleton : R p q ->
    CaptureSet.RuntimeConv R (.singleton p) (.singleton q)
| select : R p q ->
    CaptureSet.RuntimeConv R (.select p a) (.select q a)

/-- Conversion of capturing types. -/
inductive Ty.RuntimeConv :
    {n : Nat} -> (Path n -> Path n -> Type) -> Ty n -> Ty n -> Type 1 where
| refl : Ty.RuntimeConv R T T
| replace :
    (context : Ty (n + 1)) -> R p q ->
    Ty.RuntimeConv R (context.open p) (context.open q)
| capt :
    CaptureSet.RuntimeConv R C D ->
    Shape.RuntimeConv R S T ->
    Ty.RuntimeConv R (.capt C S) (.capt D T)

/-- Conversion of shapes. -/
inductive Shape.RuntimeConv :
    {n : Nat} -> (Path n -> Path n -> Type) ->
      Shape n -> Shape n -> Type 1 where
| refl : Shape.RuntimeConv R S S
| replace :
    (context : Shape (n + 1)) -> R p q ->
    Shape.RuntimeConv R (context.open p) (context.open q)
| top : Shape.RuntimeConv R .Top .Top
| bot : Shape.RuntimeConv R .Bot .Bot
| inter :
    Shape.RuntimeConv R S S' ->
    Shape.RuntimeConv R T T' ->
    Shape.RuntimeConv R (.Inter S T) (.Inter S' T')
| union :
    Shape.RuntimeConv R S S' ->
    Shape.RuntimeConv R T T' ->
    Shape.RuntimeConv R (.Union S T) (.Union S' T')
| fun :
    Ty.RuntimeConv R S S' ->
    Ty.RuntimeConv (Path.ScopedLift R) T T' ->
    Shape.RuntimeConv R (.Fun S T) (.Fun S' T')
| pair :
    Ty.RuntimeConv R S S' ->
    Tau.RuntimeConv (Path.ScopedLift R) d d' ->
    Shape.RuntimeConv R (.Pair S a d) (.Pair S' a d')
| single : R p q -> Shape.RuntimeConv R (.Single p) (.Single q)
| selection : R p q -> Shape.RuntimeConv R (.TSel p A) (.TSel q A)

/-- Conversion of generalized member signatures. -/
inductive Tau.RuntimeConv :
    {n : Nat} -> (Path n -> Path n -> Type) ->
      {k : Kind} -> Tau n k -> Tau n k -> Type 1 where
| refl : Tau.RuntimeConv R d d
| replace :
    (context : Tau (n + 1) k) -> R p q ->
    Tau.RuntimeConv R (context.open p) (context.open q)
| term : Ty.RuntimeConv R T U ->
    Tau.RuntimeConv R (.term T) (.term U)
| «type» :
    Shape.RuntimeConv R L L' -> Shape.RuntimeConv R U U' ->
    Tau.RuntimeConv R (.type L U) (.type L' U')
| capture :
    CaptureSet.RuntimeConv R C C' -> CaptureSet.RuntimeConv R D D' ->
    Tau.RuntimeConv R (.capture C D) (.capture C' D')

end

/-- Project the capture-set conversion from a runtime conversion of
capturing types. -/
noncomputable def Ty.RuntimeConv.captureConversion
    {n : Nat} {R : Path n -> Path n -> Type}
    {T U : Ty n} (conversion : Ty.RuntimeConv R T U) :
    CaptureSet.RuntimeConv R T.captureSet U.captureSet :=
  match conversion with
  | .refl => .refl
  | .replace context paths =>
      match context with
      | .capt captures _ => .replace captures paths
  | .capt captures _ => captures

/-! ## Substitution, renaming, opening, and allocation -/

mutual

noncomputable def CaptureSet.RuntimeConv.subst
    {R : Path n -> Path n -> Type} {E : Path m -> Path m -> Type}
    {rho : PathSubst n m} (mapPaths : Path.SubstHom R E rho) :
    CaptureSet.RuntimeConv R C D ->
      CaptureSet.RuntimeConv E (C.subst rho) (D.subst rho)
| .refl => .refl
| .replace context evidence => by
    simpa only [CaptureSet.open_subst] using
      CaptureSet.RuntimeConv.replace (context.subst rho.lift) (mapPaths evidence)
| .empty => .empty
| .union left right => .union (left.subst mapPaths) (right.subst mapPaths)
| .singleton evidence => .singleton (mapPaths evidence)
| .select evidence => .select (mapPaths evidence)

noncomputable def Ty.RuntimeConv.subst
    {R : Path n -> Path n -> Type} {E : Path m -> Path m -> Type}
    {rho : PathSubst n m} (mapPaths : Path.SubstHom R E rho) :
    Ty.RuntimeConv R T U -> Ty.RuntimeConv E (T.subst rho) (U.subst rho)
| .refl => .refl
| .replace context evidence => by
    simpa only [Ty.open_subst] using
      Ty.RuntimeConv.replace (context.subst rho.lift) (mapPaths evidence)
| .capt captures shape => .capt (captures.subst mapPaths) (shape.subst mapPaths)

noncomputable def Shape.RuntimeConv.subst
    {R : Path n -> Path n -> Type} {E : Path m -> Path m -> Type}
    {rho : PathSubst n m} (mapPaths : Path.SubstHom R E rho) :
    Shape.RuntimeConv R S T -> Shape.RuntimeConv E (S.subst rho) (T.subst rho)
| .refl => .refl
| .replace context evidence => by
    simpa only [Shape.open_subst] using
      Shape.RuntimeConv.replace (context.subst rho.lift) (mapPaths evidence)
| .top => .top
| .bot => .bot
| .inter left right =>
    .inter (left.subst mapPaths) (right.subst mapPaths)
| .union left right =>
    .union (left.subst mapPaths) (right.subst mapPaths)
| .fun domain codomain =>
    .fun (domain.subst mapPaths)
      (codomain.subst (rho := rho.lift) fun evidence => evidence.subst mapPaths)
| .pair first member =>
    .pair (first.subst mapPaths)
      (member.subst (rho := rho.lift) fun evidence => evidence.subst mapPaths)
| .single evidence => .single (mapPaths evidence)
| .selection evidence => .selection (mapPaths evidence)

noncomputable def Tau.RuntimeConv.subst
    {R : Path n -> Path n -> Type} {E : Path m -> Path m -> Type}
    {rho : PathSubst n m} (mapPaths : Path.SubstHom R E rho) :
    Tau.RuntimeConv R d e -> Tau.RuntimeConv E (d.subst rho) (e.subst rho)
| .refl => .refl
| .replace context evidence => by
    simpa only [Tau.open_subst] using
      Tau.RuntimeConv.replace (context.subst rho.lift) (mapPaths evidence)
| .term types => .term (types.subst mapPaths)
| .type lower upper => .type (lower.subst mapPaths) (upper.subst mapPaths)
| .capture lower upper => .capture (lower.subst mapPaths) (upper.subst mapPaths)

end

mutual

noncomputable def CaptureSet.RuntimeConv.rename
    (f : FinFun n m)
    (mapPaths : forall {p q}, R p q -> E (p.rename f) (q.rename f))
    (conversion : CaptureSet.RuntimeConv R C D) :
    CaptureSet.RuntimeConv E (C.rename f) (D.rename f) := by
  simpa only [CaptureSet.subst_asSubst] using
    conversion.subst (rho := f.asSubst) (fun evidence => by
      simpa only [Path.subst_asSubst] using mapPaths evidence)

noncomputable def Ty.RuntimeConv.rename
    (f : FinFun n m)
    (mapPaths : forall {p q}, R p q -> E (p.rename f) (q.rename f))
    (conversion : Ty.RuntimeConv R T U) :
    Ty.RuntimeConv E (T.rename f) (U.rename f) := by
  simpa only [Ty.subst_asSubst] using
    conversion.subst (rho := f.asSubst) (fun evidence => by
      simpa only [Path.subst_asSubst] using mapPaths evidence)

noncomputable def Shape.RuntimeConv.rename
    (f : FinFun n m)
    (mapPaths : forall {p q}, R p q -> E (p.rename f) (q.rename f))
    (conversion : Shape.RuntimeConv R S T) :
    Shape.RuntimeConv E (S.rename f) (T.rename f) := by
  simpa only [Shape.subst_asSubst] using
    conversion.subst (rho := f.asSubst) (fun evidence => by
      simpa only [Path.subst_asSubst] using mapPaths evidence)

noncomputable def Tau.RuntimeConv.rename
    (f : FinFun n m)
    (mapPaths : forall {p q}, R p q -> E (p.rename f) (q.rename f))
    (conversion : Tau.RuntimeConv R d e) :
    Tau.RuntimeConv E (d.rename f) (e.rename f) := by
  simpa only [Tau.subst_asSubst] using
    conversion.subst (rho := f.asSubst) (fun evidence => by
      simpa only [Path.subst_asSubst] using mapPaths evidence)

end

/-- Scoped capturing-type conversion is stable under ambient allocation. -/
noncomputable def Ty.RuntimeConv.weakenScoped
    {n : Nat} {sigma : Store n} {T U : Ty (n + 1)}
    (conversion : Ty.RuntimeConv (Path.ScopedLift (Path.RuntimeEq sigma)) T U)
    (v : Tm n) (vv : v.IsValue) :
    Ty.RuntimeConv (Path.ScopedLift (Path.RuntimeEq (Store.val sigma v vv)))
      (T.rename FinFun.weaken.ext) (U.rename FinFun.weaken.ext) :=
  conversion.rename FinFun.weaken.ext
    (fun evidence => evidence.weakenRuntime v vv)


mutual

noncomputable def CaptureSet.RuntimeConv.openSame
    {n : Nat} {R : Path n -> Path n -> Type}
    {C D : CaptureSet (n + 1)}
    (operations : Path.EqCongruence R)
    (conversion : CaptureSet.RuntimeConv (Path.ScopedLift R) C D)
    (argument : Path n) :
    CaptureSet.RuntimeConv R (C.open argument) (D.open argument) :=
  conversion.subst (rho := PathSubst.openAt argument)
    (fun evidence => evidence.open operations (operations.refl argument))

noncomputable def Ty.RuntimeConv.openSame
    {n : Nat} {R : Path n -> Path n -> Type}
    {T U : Ty (n + 1)}
    (operations : Path.EqCongruence R)
    (conversion : Ty.RuntimeConv (Path.ScopedLift R) T U)
    (argument : Path n) : Ty.RuntimeConv R (T.open argument) (U.open argument) :=
  conversion.subst (rho := PathSubst.openAt argument)
    (fun evidence => evidence.open operations (operations.refl argument))

noncomputable def Shape.RuntimeConv.openSame
    {n : Nat} {R : Path n -> Path n -> Type}
    {S T : Shape (n + 1)}
    (operations : Path.EqCongruence R)
    (conversion : Shape.RuntimeConv (Path.ScopedLift R) S T)
    (argument : Path n) :
    Shape.RuntimeConv R (S.open argument) (T.open argument) :=
  conversion.subst (rho := PathSubst.openAt argument)
    (fun evidence => evidence.open operations (operations.refl argument))

noncomputable def Tau.RuntimeConv.openSame
    {n : Nat} {R : Path n -> Path n -> Type}
    {d e : Tau (n + 1) k}
    (operations : Path.EqCongruence R)
    (conversion : Tau.RuntimeConv (Path.ScopedLift R) d e)
    (argument : Path n) : Tau.RuntimeConv R (d.open argument) (e.open argument) :=
  conversion.subst (rho := PathSubst.openAt argument)
    (fun evidence => evidence.open operations (operations.refl argument))

end


mutual

noncomputable def CaptureSet.RuntimeConv.weaken
    {n : Nat} {sigma : Store n} {C D : CaptureSet n}
    (conversion : CaptureSet.RuntimeConv (Path.RuntimeEq sigma) C D)
    (v : Tm n) (vv : v.IsValue) :
    CaptureSet.RuntimeConv (Path.RuntimeEq (Store.val sigma v vv))
      C.weaken D.weaken := by
  simpa only [CaptureSet.weaken] using
    conversion.rename FinFun.weaken (fun evidence => evidence.weaken v vv)

noncomputable def Ty.RuntimeConv.weaken
    {n : Nat} {sigma : Store n} {T U : Ty n}
    (conversion : Ty.RuntimeConv (Path.RuntimeEq sigma) T U)
    (v : Tm n) (vv : v.IsValue) :
    Ty.RuntimeConv (Path.RuntimeEq (Store.val sigma v vv)) T.weaken U.weaken := by
  simpa only [Ty.weaken] using
    conversion.rename FinFun.weaken (fun evidence => evidence.weaken v vv)

noncomputable def Shape.RuntimeConv.weaken
    {n : Nat} {sigma : Store n} {S T : Shape n}
    (conversion : Shape.RuntimeConv (Path.RuntimeEq sigma) S T)
    (v : Tm n) (vv : v.IsValue) :
    Shape.RuntimeConv (Path.RuntimeEq (Store.val sigma v vv)) S.weaken T.weaken := by
  simpa only [Shape.weaken] using
    conversion.rename FinFun.weaken (fun evidence => evidence.weaken v vv)

noncomputable def Tau.RuntimeConv.weaken
    {n : Nat} {sigma : Store n} {d e : Tau n k}
    (conversion : Tau.RuntimeConv (Path.RuntimeEq sigma) d e)
    (v : Tm n) (vv : v.IsValue) :
    Tau.RuntimeConv (Path.RuntimeEq (Store.val sigma v vv)) d.weaken e.weaken := by
  simpa only [Tau.weaken] using
    conversion.rename FinFun.weaken (fun evidence => evidence.weaken v vv)

end


/-! ## Structural view -/

/-- Pointwise related substitutions remain related after lifting through one
binder. -/
def Path.ScopedLift.pointwise
    {R : Path n -> Path n -> Type} {rho1 rho2 : PathSubst l n}
    (related : forall x, R (rho1 x) (rho2 x)) :
    forall x, Path.ScopedLift R (rho1.lift x) (rho2.lift x) := by
  intro x
  refine Fin.cases ?_ (fun i => ?_) x
  · exact .bound
  · exact .old (related i)

mutual

inductive CaptureSet.RuntimeCongruent :
    {n : Nat} -> (Path n -> Path n -> Type) ->
      CaptureSet n -> CaptureSet n -> Type 1 where
| empty : CaptureSet.RuntimeCongruent R .empty .empty
| union :
    CaptureSet.RuntimeCongruent R C C' ->
    CaptureSet.RuntimeCongruent R D D' ->
    CaptureSet.RuntimeCongruent R (.union C D) (.union C' D')
| singleton : R p q ->
    CaptureSet.RuntimeCongruent R (.singleton p) (.singleton q)
| select : R p q ->
    CaptureSet.RuntimeCongruent R (.select p a) (.select q a)

inductive Ty.RuntimeCongruent :
    {n : Nat} -> (Path n -> Path n -> Type) -> Ty n -> Ty n -> Type 1 where
| capt :
    CaptureSet.RuntimeCongruent R C D ->
    Shape.RuntimeCongruent R S T ->
    Ty.RuntimeCongruent R (.capt C S) (.capt D T)

inductive Shape.RuntimeCongruent :
    {n : Nat} -> (Path n -> Path n -> Type) ->
      Shape n -> Shape n -> Type 1 where
| top : Shape.RuntimeCongruent R .Top .Top
| bot : Shape.RuntimeCongruent R .Bot .Bot
| inter :
    Shape.RuntimeCongruent R S S' ->
    Shape.RuntimeCongruent R T T' ->
    Shape.RuntimeCongruent R (.Inter S T) (.Inter S' T')
| union :
    Shape.RuntimeCongruent R S S' ->
    Shape.RuntimeCongruent R T T' ->
    Shape.RuntimeCongruent R (.Union S T) (.Union S' T')
| fun :
    Ty.RuntimeCongruent R S S' ->
    Ty.RuntimeCongruent (Path.ScopedLift R) T T' ->
    Shape.RuntimeCongruent R (.Fun S T) (.Fun S' T')
| pair :
    Ty.RuntimeCongruent R S S' ->
    Tau.RuntimeCongruent (Path.ScopedLift R) d d' ->
    Shape.RuntimeCongruent R (.Pair S a d) (.Pair S' a d')
| single : R p q -> Shape.RuntimeCongruent R (.Single p) (.Single q)
| selection : R p q -> Shape.RuntimeCongruent R (.TSel p A) (.TSel q A)

inductive Tau.RuntimeCongruent :
    {n : Nat} -> (Path n -> Path n -> Type) ->
      {k : Kind} -> Tau n k -> Tau n k -> Type 1 where
| term : Ty.RuntimeCongruent R T U ->
    Tau.RuntimeCongruent R (.term T) (.term U)
| «type» :
    Shape.RuntimeCongruent R L L' -> Shape.RuntimeCongruent R U U' ->
    Tau.RuntimeCongruent R (.type L U) (.type L' U')
| capture :
    CaptureSet.RuntimeCongruent R C C' ->
    CaptureSet.RuntimeCongruent R D D' ->
    Tau.RuntimeCongruent R (.capture C D) (.capture C' D')

end


/-! ### Equivalence operations -/

mutual

noncomputable def CaptureSet.RuntimeCongruent.refl
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R) :
    (C : CaptureSet n) -> CaptureSet.RuntimeCongruent R C C
| .empty => .empty
| .union C D => .union (CaptureSet.RuntimeCongruent.refl operations C)
    (CaptureSet.RuntimeCongruent.refl operations D)
| .singleton p => .singleton (operations.refl p)
| .select p _ => .select (operations.refl p)

noncomputable def Ty.RuntimeCongruent.refl
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R) :
    (T : Ty n) -> Ty.RuntimeCongruent R T T
| .capt C S => .capt (CaptureSet.RuntimeCongruent.refl operations C)
    (Shape.RuntimeCongruent.refl operations S)

noncomputable def Shape.RuntimeCongruent.refl
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R) :
    (S : Shape n) -> Shape.RuntimeCongruent R S S
| .Top => .top
| .Bot => .bot
| .Inter S T => .inter (Shape.RuntimeCongruent.refl operations S)
    (Shape.RuntimeCongruent.refl operations T)
| .Union S T => .union (Shape.RuntimeCongruent.refl operations S)
    (Shape.RuntimeCongruent.refl operations T)
| .Fun S T => .fun (Ty.RuntimeCongruent.refl operations S)
    (Ty.RuntimeCongruent.refl (Path.ScopedLift.eqCongruence operations) T)
| .Pair S _ d => .pair (Ty.RuntimeCongruent.refl operations S)
    (Tau.RuntimeCongruent.refl (Path.ScopedLift.eqCongruence operations) d)
| .Single p => .single (operations.refl p)
| .TSel p _ => .selection (operations.refl p)

noncomputable def Tau.RuntimeCongruent.refl
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R) :
    (d : Tau n k) -> Tau.RuntimeCongruent R d d
| .term T => .term (Ty.RuntimeCongruent.refl operations T)
| .type L U => .type (Shape.RuntimeCongruent.refl operations L)
    (Shape.RuntimeCongruent.refl operations U)
| .capture C D => .capture (CaptureSet.RuntimeCongruent.refl operations C)
    (CaptureSet.RuntimeCongruent.refl operations D)

end


mutual

noncomputable def CaptureSet.RuntimeCongruent.symm
    {n : Nat} {R : Path n -> Path n -> Type}
    {C D : CaptureSet n}
    (operations : Path.EqCongruence R) :
    CaptureSet.RuntimeCongruent R C D -> CaptureSet.RuntimeCongruent R D C
| .empty => .empty
| .union left right => .union (left.symm operations) (right.symm operations)
| .singleton path => .singleton (operations.symm path)
| .select path => .select (operations.symm path)

noncomputable def Ty.RuntimeCongruent.symm
    {n : Nat} {R : Path n -> Path n -> Type} {T U : Ty n}
    (operations : Path.EqCongruence R) :
    Ty.RuntimeCongruent R T U -> Ty.RuntimeCongruent R U T
| .capt captures shape =>
    .capt (captures.symm operations) (shape.symm operations)

noncomputable def Shape.RuntimeCongruent.symm
    {n : Nat} {R : Path n -> Path n -> Type} {S T : Shape n}
    (operations : Path.EqCongruence R) :
    Shape.RuntimeCongruent R S T -> Shape.RuntimeCongruent R T S
| .top => .top
| .bot => .bot
| .inter left right => .inter (left.symm operations) (right.symm operations)
| .union left right => .union (left.symm operations) (right.symm operations)
| .fun domain codomain => .fun (domain.symm operations)
    (codomain.symm (Path.ScopedLift.eqCongruence operations))
| .pair first member => .pair (first.symm operations)
    (member.symm (Path.ScopedLift.eqCongruence operations))
| .single path => .single (operations.symm path)
| .selection path => .selection (operations.symm path)

noncomputable def Tau.RuntimeCongruent.symm
    {n : Nat} {R : Path n -> Path n -> Type} {d e : Tau n k}
    (operations : Path.EqCongruence R) :
    Tau.RuntimeCongruent R d e -> Tau.RuntimeCongruent R e d
| .term types => .term (types.symm operations)
| .type lower upper => .type (lower.symm operations) (upper.symm operations)
| .capture lower upper =>
    .capture (lower.symm operations) (upper.symm operations)

end

/-! ### Structural conversion induced by substitution -/

/-- A path congruence maps pointwise-related substitutions to related paths. -/
noncomputable def Path.EqCongruence.ofSubst
    {l n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R)
    (rho1 rho2 : PathSubst l n)
    (related : forall x, R (rho1 x) (rho2 x)) :
    (p : Path l) -> R (p.subst rho1) (p.subst rho2)
| .var x => related x
| .fst p => operations.fst (operations.ofSubst rho1 rho2 related p)
| .sel p a => operations.sel (operations.ofSubst rho1 rho2 related p) a

mutual

noncomputable def CaptureSet.RuntimeCongruent.ofSubst
    {l n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R)
    (rho1 rho2 : PathSubst l n)
    (related : forall x, R (rho1 x) (rho2 x)) :
    (C : CaptureSet l) ->
      CaptureSet.RuntimeCongruent R (C.subst rho1) (C.subst rho2)
| .empty => .empty
| .union C D => .union
    (CaptureSet.RuntimeCongruent.ofSubst operations rho1 rho2 related C)
    (CaptureSet.RuntimeCongruent.ofSubst operations rho1 rho2 related D)
| .singleton p => .singleton (operations.ofSubst rho1 rho2 related p)
| .select p _ => .select (operations.ofSubst rho1 rho2 related p)

noncomputable def Ty.RuntimeCongruent.ofSubst
    {l n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R)
    (rho1 rho2 : PathSubst l n)
    (related : forall x, R (rho1 x) (rho2 x)) :
    (T : Ty l) -> Ty.RuntimeCongruent R (T.subst rho1) (T.subst rho2)
| .capt C S => .capt (CaptureSet.RuntimeCongruent.ofSubst
      operations rho1 rho2 related C)
    (Shape.RuntimeCongruent.ofSubst operations rho1 rho2 related S)

noncomputable def Shape.RuntimeCongruent.ofSubst
    {l n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R)
    (rho1 rho2 : PathSubst l n)
    (related : forall x, R (rho1 x) (rho2 x)) :
    (S : Shape l) -> Shape.RuntimeCongruent R (S.subst rho1) (S.subst rho2)
| .Top => .top
| .Bot => .bot
| .Inter S T => .inter
    (Shape.RuntimeCongruent.ofSubst operations rho1 rho2 related S)
    (Shape.RuntimeCongruent.ofSubst operations rho1 rho2 related T)
| .Union S T => .union
    (Shape.RuntimeCongruent.ofSubst operations rho1 rho2 related S)
    (Shape.RuntimeCongruent.ofSubst operations rho1 rho2 related T)
| .Fun S T => .fun (Ty.RuntimeCongruent.ofSubst operations rho1 rho2 related S)
    (Ty.RuntimeCongruent.ofSubst (Path.ScopedLift.eqCongruence operations)
      rho1.lift rho2.lift (Path.ScopedLift.pointwise related) T)
| .Pair S _ d => .pair (Ty.RuntimeCongruent.ofSubst operations rho1 rho2 related S)
    (Tau.RuntimeCongruent.ofSubst (Path.ScopedLift.eqCongruence operations)
      rho1.lift rho2.lift (Path.ScopedLift.pointwise related) d)
| .Single p => .single (operations.ofSubst rho1 rho2 related p)
| .TSel p _ => .selection (operations.ofSubst rho1 rho2 related p)

noncomputable def Tau.RuntimeCongruent.ofSubst
    {l n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R)
    (rho1 rho2 : PathSubst l n)
    (related : forall x, R (rho1 x) (rho2 x)) :
    (d : Tau l k) -> Tau.RuntimeCongruent R (d.subst rho1) (d.subst rho2)
| .term T => .term (Ty.RuntimeCongruent.ofSubst operations rho1 rho2 related T)
| .type L U => .type (Shape.RuntimeCongruent.ofSubst operations rho1 rho2 related L)
    (Shape.RuntimeCongruent.ofSubst operations rho1 rho2 related U)
| .capture C D => .capture
    (CaptureSet.RuntimeCongruent.ofSubst operations rho1 rho2 related C)
    (CaptureSet.RuntimeCongruent.ofSubst operations rho1 rho2 related D)

end


/-! ### Conversion between evidence representations -/

mutual

noncomputable def CaptureSet.RuntimeCongruent.toRuntimeConv :
    CaptureSet.RuntimeCongruent R C D -> CaptureSet.RuntimeConv R C D
| .empty => .empty
| .union left right => .union left.toRuntimeConv right.toRuntimeConv
| .singleton path => .singleton path
| .select path => .select path

noncomputable def Ty.RuntimeCongruent.toRuntimeConv :
    Ty.RuntimeCongruent R T U -> Ty.RuntimeConv R T U
| .capt captures shape => .capt captures.toRuntimeConv shape.toRuntimeConv

noncomputable def Shape.RuntimeCongruent.toRuntimeConv :
    Shape.RuntimeCongruent R S T -> Shape.RuntimeConv R S T
| .top => .top
| .bot => .bot
| .inter left right => .inter left.toRuntimeConv right.toRuntimeConv
| .union left right => .union left.toRuntimeConv right.toRuntimeConv
| .fun domain codomain => .fun domain.toRuntimeConv codomain.toRuntimeConv
| .pair first member => .pair first.toRuntimeConv member.toRuntimeConv
| .single path => .single path
| .selection path => .selection path

noncomputable def Tau.RuntimeCongruent.toRuntimeConv :
    Tau.RuntimeCongruent R d e -> Tau.RuntimeConv R d e
| .term types => .term types.toRuntimeConv
| .type lower upper => .type lower.toRuntimeConv upper.toRuntimeConv
| .capture lower upper => .capture lower.toRuntimeConv upper.toRuntimeConv

end


mutual

/-- Normalize capture-set conversion to componentwise path congruence. -/
noncomputable def CaptureSet.RuntimeConv.runtimeCongruent
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R) {C D : CaptureSet n}
    (conversion : CaptureSet.RuntimeConv R C D) :
    CaptureSet.RuntimeCongruent R C D :=
  match conversion with
  | .refl => CaptureSet.RuntimeCongruent.refl operations _
  | .replace (p := p) (q := q) context evidence =>
      CaptureSet.RuntimeCongruent.ofSubst operations
        (PathSubst.openAt p) (PathSubst.openAt q)
        (fun x => Fin.cases evidence (fun i => operations.refl (.var i)) x)
        context
  | .empty => .empty
  | .union left right =>
      .union (left.runtimeCongruent operations) (right.runtimeCongruent operations)
  | .singleton path => .singleton path
  | .select path => .select path

/-- Normalize capturing-type conversion to componentwise path congruence. -/
noncomputable def Ty.RuntimeConv.runtimeCongruent
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R) {T U : Ty n}
    (conversion : Ty.RuntimeConv R T U) : Ty.RuntimeCongruent R T U :=
  match conversion with
  | .refl => Ty.RuntimeCongruent.refl operations _
  | .replace (p := p) (q := q) context evidence =>
      Ty.RuntimeCongruent.ofSubst operations
        (PathSubst.openAt p) (PathSubst.openAt q)
        (fun x => Fin.cases evidence (fun i => operations.refl (.var i)) x)
        context
  | .capt captures shape =>
      .capt (captures.runtimeCongruent operations)
        (shape.runtimeCongruent operations)

/-- Normalize shape conversion to componentwise path congruence. -/
noncomputable def Shape.RuntimeConv.runtimeCongruent
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R) {S T : Shape n}
    (conversion : Shape.RuntimeConv R S T) : Shape.RuntimeCongruent R S T :=
  match conversion with
  | .refl => Shape.RuntimeCongruent.refl operations _
  | .replace (p := p) (q := q) context evidence =>
      Shape.RuntimeCongruent.ofSubst operations
        (PathSubst.openAt p) (PathSubst.openAt q)
        (fun x => Fin.cases evidence (fun i => operations.refl (.var i)) x)
        context
  | .top => .top
  | .bot => .bot
  | .inter left right =>
      .inter (left.runtimeCongruent operations)
        (right.runtimeCongruent operations)
  | .union left right =>
      .union (left.runtimeCongruent operations)
        (right.runtimeCongruent operations)
  | .fun domain codomain =>
      .fun (domain.runtimeCongruent operations)
        (codomain.runtimeCongruent (Path.ScopedLift.eqCongruence operations))
  | .pair first member =>
      .pair (first.runtimeCongruent operations)
        (member.runtimeCongruent (Path.ScopedLift.eqCongruence operations))
  | .single path => .single path
  | .selection path => .selection path

/-- Normalize generalized-signature conversion to componentwise path
congruence. -/
noncomputable def Tau.RuntimeConv.runtimeCongruent
    {n : Nat} {R : Path n -> Path n -> Type}
    (operations : Path.EqCongruence R) {d e : Tau n k}
    (conversion : Tau.RuntimeConv R d e) : Tau.RuntimeCongruent R d e :=
  match conversion with
  | .refl => Tau.RuntimeCongruent.refl operations _
  | .replace (p := p) (q := q) context evidence =>
      Tau.RuntimeCongruent.ofSubst operations
        (PathSubst.openAt p) (PathSubst.openAt q)
        (fun x => Fin.cases evidence (fun i => operations.refl (.var i)) x)
        context
  | .term types => .term (types.runtimeCongruent operations)
  | .type lower upper =>
      .type (lower.runtimeCongruent operations) (upper.runtimeCongruent operations)
  | .capture lower upper =>
      .capture (lower.runtimeCongruent operations) (upper.runtimeCongruent operations)

end

end LambdaPCCI
