import Coercions.FCdotR.Structural
import Coercions.FCdotR.Syntax

/-!
# Substitution on FCdotR evidence, atoms, terms and definitions

`Structural` ends by stating why its `Mono` cannot carry a substitution action:
`Le.subst` must send `selL p a v` to `selL (m.image p) a (v.subst …)` with the
inner substitution `m.at' p`, and `v` may contain `vcSub T₁ e w` whose `e` is
itself inclusion evidence.  Substituting `v` therefore needs a *prefix
respecting substitution at the restriction*, not merely the restriction.  A
recursive field `(x : BVar s₁ .var) → Mono (res x)` is not an inductive
definition and has no finite inhabitant, because at `.here` the restriction of
`lift` is `lift` again.

This module takes the second of the two routes the design round left open:
instead of adding a coherence equation to `Mono` and *defining* closure from
it, it introduces an inductive **syntax of prefix-respecting substitutions**
`MonoSyn`, generated by the substitutions the metatheory actually performs, and
**defines restriction by recursion on that syntax**.  Closure under restriction
is then a theorem-free matter of the recursion returning a `MonoSyn` in every
branch, and the star law is discharged once per generator rather than assumed.

Why this and not the coherence equation: the equation
`(θ↾x)↾y = θ↾((renameUpTo x).var y)` cannot be stated as a homogeneous equality.
Its two sides live in `Subst σ₁ (scopeUpTo y) σ₂ (scopeAt ((θ↾x).image y))` and
`Subst σ₁ (scopeUpTo ((renameUpTo x).var y)) σ₂ (scopeAt (θ.image …))`, whose
domain scopes agree only by `scopeUpTo_renameUpTo` and whose codomain scopes
agree only by a second instance of it.  Every use of the field would then be an
`HEq` elimination inside `Type`-valued data.  Recursion on a generator tree has
no such obligation: each branch produces its restriction as a *constructor
expression*, so every scope in sight computes.

What `MonoSyn` covers: `id`, local weakening, store renaming (hence store
weakening `ofStore Rename.succ`), the action on the empty local scope, `lift`,
composition, and `oneConc` — a single binder of `([],x)` replaced by a location,
which is the only substitution the machine performs (`ST_Obj` and `ST_AppAbs`
substitute a `Vr.conc` and a running term has an empty local scope).  There is
deliberately no generator for `Subst.one` at an abstract image; `Structural`
records why one cannot exist.

`MonoRAt` is `Structural`'s `MonoAt` moved from a `BVar` to a two-zone subject
and carrying two more fields: the `MonoSyn` witness for the restriction, which
is the closure, and `self`, which says the restriction sends the subject's own
self variable to the image's.  `self` is what the `vcUnfold` clause of the
typing theorem needs, and proving it per generator is what avoids an
injectivity lemma for `renameAt`.

This module is the substitution *action*; the preservation theorem for the
typing judgments is `SubstTyping`.
-/

namespace FCdotR

open FCdot (Kind Sig BVar Rename)
open Oopsla16 (Vr Ty Lb Subst scopeUpTo renameUpTo varUpTo renameNil)

/-! ## A syntax of prefix-respecting substitutions -/

/-- The substitutions built from the generators the metatheory performs.  Its
point is that restriction is a recursion on this tree, so the restriction of a
generator is again a generator expression and the scopes compute. -/
inductive MonoSyn : {σ1 σ2 s1 s2 : Sig} → Subst σ1 s1 σ2 s2 → Type where
  /-- The identity. -/
  | id {σ s : Sig} : MonoSyn (Subst.id (σ := σ) (s := s))
  /-- Weakening the local scope by one binder. -/
  | weaken {σ s : Sig} :
      MonoSyn (Subst.ofRename (σ := σ) (Rename.succ (s := s) (k := .var)))
  /-- Renaming the store scope; `Rename.succ` is allocation's weakening. -/
  | ofStore {σ1 σ2 s : Sig} (ρ : Rename σ1 σ2) :
      MonoSyn (Subst.ofStore (s := s) ρ)
  /-- The action on the empty local scope, where only the store part survives.
  This is the restriction at a location, so the syntax must be closed under it. -/
  | atNil {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} :
      MonoSyn θ → MonoSyn (Subst.atNil θ)
  /-- Pushing under a binder. -/
  | lift {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} : MonoSyn θ → MonoSyn θ.lift
  /-- Composition. -/
  | comp {σ1 σ2 σ3 s1 s2 s3 : Sig} {θ : Subst σ1 s1 σ2 s2} {φ : Subst σ2 s2 σ3 s3} :
      MonoSyn θ → MonoSyn φ → MonoSyn (θ.comp φ)
  /-- The single binder of `([],x)` replaced by a location: the machine's
  substitution, and the only instance of `Subst.one` that respects prefixes. -/
  | oneConc {σ : Sig} (l : BVar σ .var) :
      MonoSyn (Subst.one (σ := σ) (s := []) (.conc l))

/-- Store weakening, the instance allocation uses. -/
abbrev MonoSyn.weakenStore {σ s : Sig} :
    MonoSyn (Subst.ofStore (σ1 := σ) (s := s) (Rename.succ (k := .var))) :=
  .ofStore Rename.succ

/-! ## The restriction at a subject

`MonoRAt θ p` is the restriction of `θ` at a two-zone subject `p`, with the
image *named* by the constructor.  Naming it is what keeps `scopeAt image`
definitional in every branch; `Structural` explains the same choice for
`MonoAt`. -/

/-- The restriction of `θ` at `p`, its image named, its defining laws recorded,
and — this is the closure — a `MonoSyn` for the restriction itself. -/
inductive MonoRAt {σ1 σ2 s1 s2 : Sig} (θ : Subst σ1 s1 σ2 s2) (p : Vr σ1 s1) :
    Type where
  /-- The image is the abstract variable `z`. -/
  | toAbs (z : BVar s2 .var) (r : Subst σ1 (scopeAt p) σ2 (scopeUpTo z))
      (himg : p.subst θ = .abs z)
      (hstar : (Subst.ofRename (renameAt p)).comp θ
        = r.comp (Subst.ofRename (renameUpTo z)))
      (hself : (selfAt p).subst r = .abs (varUpTo z))
      (hsyn : MonoSyn r) : MonoRAt θ p
  /-- The image is the location `l`, whose prefix is the empty local scope. -/
  | toConc (l : BVar σ2 .var) (r : Subst σ1 (scopeAt p) σ2 [])
      (himg : p.subst θ = .conc l)
      (hstar : (Subst.ofRename (renameAt p)).comp θ
        = r.comp (Subst.ofRename renameNil))
      (hself : (selfAt p).subst r = .conc l)
      (hsyn : MonoSyn r) : MonoRAt θ p

namespace MonoRAt

/-- The image subject, read off the constructor. -/
def image {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} {p : Vr σ1 s1} :
    MonoRAt θ p → Vr σ2 s2
  | .toAbs z _ _ _ _ _ => .abs z
  | .toConc l _ _ _ _ _ => .conc l

/-- The restricted substitution, from the subject's prefix into the image's. -/
def restrict {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} {p : Vr σ1 s1} :
    (a : MonoRAt θ p) → Subst σ1 (scopeAt p) σ2 (scopeAt a.image)
  | .toAbs _ r _ _ _ _ => r
  | .toConc _ r _ _ _ _ => r

/-- The `MonoSyn` witness for the restriction: closure under restriction. -/
def syn {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} {p : Vr σ1 s1} :
    (a : MonoRAt θ p) → MonoSyn a.restrict
  | .toAbs _ _ _ _ _ h => h
  | .toConc _ _ _ _ _ h => h

/-- The image is the substitution's action, as it must be. -/
theorem image_eq {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} {p : Vr σ1 s1} :
    (a : MonoRAt θ p) → a.image = p.subst θ
  | .toAbs _ _ h _ _ _ => h.symm
  | .toConc _ _ h _ _ _ => h.symm

/-- The star law: weakening out of the prefix and then substituting is
substituting inside the prefix and then weakening out of the image's prefix. -/
theorem star {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} {p : Vr σ1 s1} :
    (a : MonoRAt θ p) →
    (Subst.ofRename (renameAt p)).comp θ
      = a.restrict.comp (Subst.ofRename (renameAt a.image))
  | .toAbs _ _ _ h _ _ => h
  | .toConc _ _ _ h _ _ => h

/-- The restriction sends the subject's own self variable to the image's.  This
is what the `vcUnfold` clause of the typing theorem needs, and proving it per
generator is cheaper than an injectivity lemma for `renameAt`. -/
theorem self {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} {p : Vr σ1 s1} :
    (a : MonoRAt θ p) → (selfAt p).subst a.restrict = selfAt a.image
  | .toAbs _ _ _ _ h _ => h
  | .toConc _ _ _ _ h _ => h

end MonoRAt

/-- The `lift` case's bookkeeping, factored out so that the restriction of a
lifted substitution at an older variable can be *rewritten* to the restriction
of the underlying one.  Without this the equation is a stuck `match` and
`MonoSyn.Ev.lift` cannot state its own field. -/
def MonoRAt.underLift {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2}
    {y : BVar s1 .var} : MonoRAt θ (.abs y) → MonoRAt θ.lift (.abs (.there y))
  | .toAbs z r himg hstar hself hsyn =>
      .toAbs (.there z) r
        (by
          have h : θ.abs y = Vr.abs z := himg
          show (θ.abs y).weaken = Vr.abs (.there z)
          rw [h]; rfl)
        (by
          have hs : (Subst.ofRename (renameUpTo y)).comp θ
              = r.comp (Subst.ofRename (renameUpTo z)) := hstar
          apply Subst.ext <;> intro w
          · have hc : θ.conc w = r.conc w := congrArg (fun t => Subst.conc t w) hs
            exact hc
          · have hw : θ.abs ((renameUpTo y).var w)
                = (r.abs w).subst (Subst.ofRename (renameUpTo z)) :=
              congrArg (fun t => Subst.abs t w) hs
            show (θ.abs ((renameUpTo y).var w)).weaken
                = (r.abs w).subst
                    (Subst.ofRename ((renameUpTo z).comp Rename.succ))
            rw [hw, Vr.weaken_subst_ofRename])
        hself hsyn
  | .toConc l r himg hstar hself hsyn =>
      .toConc l r
        (by
          have h : θ.abs y = Vr.conc l := himg
          show (θ.abs y).weaken = Vr.conc l
          rw [h]; rfl)
        (by
          have hs : (Subst.ofRename (renameUpTo y)).comp θ
              = r.comp (Subst.ofRename renameNil) := hstar
          apply Subst.ext <;> intro w
          · have hc : θ.conc w = r.conc w := congrArg (fun t => Subst.conc t w) hs
            exact hc
          · have hw : θ.abs ((renameUpTo y).var w)
                = (r.abs w).subst (Subst.ofRename renameNil) :=
              congrArg (fun t => Subst.abs t w) hs
            show (θ.abs ((renameUpTo y).var w)).weaken
                = (r.abs w).subst (Subst.ofRename renameNil)
            rw [hw]
            cases hv : r.abs w with
            | conc c => rfl
            | abs u => exact nomatch u)
        hself hsyn

/-- The restriction is unchanged by `underLift`. -/
@[simp] theorem MonoRAt.restrict_underLift {σ1 σ2 s1 s2 : Sig}
    {θ : Subst σ1 s1 σ2 s2} {y : BVar s1 .var} :
    (a : MonoRAt θ (.abs y)) → HEq a.underLift.restrict a.restrict
  | .toAbs .. => HEq.rfl
  | .toConc .. => HEq.rfl

/-- The image is weakened by `underLift`. -/
@[simp] theorem MonoRAt.image_underLift {σ1 σ2 s1 s2 : Sig}
    {θ : Subst σ1 s1 σ2 s2} {y : BVar s1 .var} :
    (a : MonoRAt θ (.abs y)) → a.underLift.image = a.image.weaken
  | .toAbs .. => rfl
  | .toConc .. => rfl

/-! ## Restriction, by recursion on the generator tree

One clause per generator, plus one clause that covers *every* generator at a
concrete subject: a location's prefix is the empty local scope, so the
restriction there is `Subst.atNil θ` and the star law is `Subst.nil_comp`.
That uniformity is why `atNil` has to be a generator. -/

/-- The restriction at an *abstract* subject, by recursion on the generator
tree.  Every branch hands back a constructor expression, so `scopeAt image`
computes and no transport occurs; and every branch hands back a `MonoSyn`,
which is the closure under restriction that the substitution action needs. -/
def MonoSyn.atAbs : {σ1 σ2 s1 s2 : Sig} → {θ : Subst σ1 s1 σ2 s2} →
    MonoSyn θ → (x : BVar s1 .var) → MonoRAt θ (.abs x)
  | _, _, _, _, _, .id, x =>
      .toAbs x Subst.id rfl (by apply Subst.ext <;> intro y <;> rfl) rfl .id
  | _, _, _, _, _, .weaken, x =>
      .toAbs (.there x) Subst.id rfl
        (by apply Subst.ext <;> intro y <;> rfl) rfl .id
  | _, _, _, _, _, .ofStore ρ, x =>
      .toAbs x (Subst.ofStore ρ) rfl
        (by apply Subst.ext <;> intro y <;> rfl) rfl (.ofStore ρ)
  | _, _, _, _, _, .atNil _, x => nomatch x
  | _, _, _, _, _, .lift (θ := θ0) m, .here =>
      .toAbs .here θ0.lift rfl
        (by
          apply Subst.ext <;> intro w
          · rfl
          · show θ0.lift.abs w = (θ0.lift.abs w).subst Subst.id
            exact (Oopsla16.Vr.subst_id _).symm)
        rfl (.lift m)
  | _, _, _, _, _, .lift m, (.there y) => (m.atAbs y).underLift
  | _, _, _, _, _, .comp (θ := θ0) (φ := φ0) m n, x =>
      match m.atAbs x with
      | .toAbs z r himg hstar hself hsyn =>
          match n.atAbs z with
          | .toAbs z' r' himg' hstar' hself' hsyn' =>
              .toAbs z' (r.comp r')
                (by
                  have h : θ0.abs x = Vr.abs z := himg
                  have h' : φ0.abs z = Vr.abs z' := himg'
                  show (θ0.abs x).subst φ0 = Vr.abs z'
                  rw [h]; exact h')
                (by
                  have hs : (Subst.ofRename (renameUpTo x)).comp θ0
                      = r.comp (Subst.ofRename (renameUpTo z)) := hstar
                  have hs' : (Subst.ofRename (renameUpTo z)).comp φ0
                      = r'.comp (Subst.ofRename (renameUpTo z')) := hstar'
                  show (Subst.ofRename (renameUpTo x)).comp (θ0.comp φ0)
                      = (r.comp r').comp (Subst.ofRename (renameUpTo z'))
                  rw [← Subst.comp_assoc, hs, Subst.comp_assoc, hs',
                    ← Subst.comp_assoc])
                (by
                  have h : r.abs .here = Vr.abs .here := hself
                  have h' : r'.abs .here = Vr.abs .here := hself'
                  show (r.abs .here).subst r' = Vr.abs .here
                  rw [h]; exact h')
                (.comp hsyn hsyn')
          | .toConc l' r' himg' hstar' hself' hsyn' =>
              .toConc l' (r.comp r')
                (by
                  have h : θ0.abs x = Vr.abs z := himg
                  have h' : φ0.abs z = Vr.conc l' := himg'
                  show (θ0.abs x).subst φ0 = Vr.conc l'
                  rw [h]; exact h')
                (by
                  have hs : (Subst.ofRename (renameUpTo x)).comp θ0
                      = r.comp (Subst.ofRename (renameUpTo z)) := hstar
                  have hs' : (Subst.ofRename (renameUpTo z)).comp φ0
                      = r'.comp (Subst.ofRename renameNil) := hstar'
                  show (Subst.ofRename (renameUpTo x)).comp (θ0.comp φ0)
                      = (r.comp r').comp (Subst.ofRename renameNil)
                  rw [← Subst.comp_assoc, hs, Subst.comp_assoc, hs',
                    ← Subst.comp_assoc])
                (by
                  have h : r.abs .here = Vr.abs .here := hself
                  have h' : r'.abs .here = Vr.conc l' := hself'
                  show (r.abs .here).subst r' = Vr.conc l'
                  rw [h]; exact h')
                (.comp hsyn hsyn')
      | .toConc l r himg hstar hself hsyn =>
          .toConc (φ0.conc l) (r.comp (Subst.atNil φ0))
            (by
              have h : θ0.abs x = Vr.conc l := himg
              show (θ0.abs x).subst φ0 = Vr.conc (φ0.conc l)
              rw [h]; rfl)
            (by
              have hs : (Subst.ofRename (renameUpTo x)).comp θ0
                  = r.comp (Subst.ofRename renameNil) := hstar
              show (Subst.ofRename (renameUpTo x)).comp (θ0.comp φ0)
                  = (r.comp (Subst.atNil φ0)).comp (Subst.ofRename renameNil)
              rw [← Subst.comp_assoc, hs, Subst.comp_assoc, Subst.nil_comp,
                ← Subst.comp_assoc])
            (by
              have h : r.abs .here = Vr.conc l := hself
              show (r.abs .here).subst (Subst.atNil φ0) = Vr.conc (φ0.conc l)
              rw [h]; rfl)
            (.comp hsyn (.atNil n))
  | _, _, _, _, _, .oneConc l, .here =>
      .toConc l (Subst.one (.conc l)) rfl
        (by
          apply Subst.ext <;> intro w
          · rfl
          · cases w with
            | here => rfl
            | there y => cases y)
        rfl (.oneConc l)
  | _, _, _, _, _, .oneConc _, (.there y) => nomatch y

/-- Weakening a variable and then instantiating the new binder is the
identity.  `Subst.weaken_subst_lift`'s companion, for the `substVr` direction. -/
@[simp] theorem Vr.weaken_subst_one {σ s : Sig} (v : Vr σ s) (u : Vr σ s) :
    v.weaken.subst (Subst.one u) = v := by cases v <;> rfl

/-- The restriction at a subject of either zone.  A location's prefix is the
empty local scope, so the restriction there is `Subst.atNil θ` whatever the
generator and the star law is `Subst.nil_comp`; that uniformity is why `atNil`
has to be a generator.  Splitting on the subject *first* makes both equations
hold by `rfl`, which is what the closure lemmas below rewrite with. -/
def MonoSyn.at' {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} (m : MonoSyn θ) :
    (p : Vr σ1 s1) → MonoRAt θ p
  | .conc l =>
      .toConc (θ.conc l) (Subst.atNil θ) rfl (Subst.nil_comp θ) rfl (.atNil m)
  | .abs x => m.atAbs x


namespace MonoSyn

/-- The image of a subject under a generated substitution. -/
abbrev image {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} (m : MonoSyn θ)
    (p : Vr σ1 s1) : Vr σ2 s2 := (m.at' p).image

/-- The restriction of a generated substitution at a subject. -/
abbrev restrict {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} (m : MonoSyn θ)
    (p : Vr σ1 s1) : Subst σ1 (scopeAt p) σ2 (scopeAt (m.image p)) :=
  (m.at' p).restrict

/-- **Closure under restriction**: the restriction is itself generated.  This is
the field `Structural` could not add to `Mono`, and the reason this module
exists. -/
abbrev resSyn {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} (m : MonoSyn θ)
    (p : Vr σ1 s1) : MonoSyn (m.restrict p) := (m.at' p).syn

/-! ### The equations the closure lemmas rewrite with -/

/-- At a location the restriction is the substitution's store part, whatever
the generator. -/
@[simp] theorem MonoSyn.at'_conc {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2}
    (m : MonoSyn θ) (l : BVar σ1 .var) :
    m.at' (.conc l)
      = .toConc (θ.conc l) (Subst.atNil θ) rfl (Subst.nil_comp θ) rfl (.atNil m) :=
  rfl

/-- A lifted substitution restricted at an older variable is the underlying
one's restriction, with its image weakened. -/
@[simp] theorem MonoSyn.at'_lift_there {σ1 σ2 s1 s2 : Sig}
    {θ : Subst σ1 s1 σ2 s2} (m : MonoSyn θ) (y : BVar s1 .var) :
    m.lift.at' (.abs (.there y)) = (m.at' (.abs y)).underLift := rfl

/-- The image of a lifted substitution at an older variable. -/
@[simp] theorem MonoSyn.image_lift_there {σ1 σ2 s1 s2 : Sig}
    {θ : Subst σ1 s1 σ2 s2} (m : MonoSyn θ) (y : BVar s1 .var) :
    m.lift.image (.abs (.there y)) = (m.image (.abs y)).weaken :=
  MonoRAt.image_underLift _

/-- The image of a lifted substitution at the new binder. -/
@[simp] theorem MonoSyn.image_lift_here {σ1 σ2 s1 s2 : Sig}
    {θ : Subst σ1 s1 σ2 s2} (m : MonoSyn θ) :
    m.lift.image (.abs .here) = Vr.abs .here := rfl

/-- The restriction of a lifted substitution at the new binder is the lifted
substitution itself. -/
@[simp] theorem MonoSyn.restrict_lift_here {σ1 σ2 s1 s2 : Sig}
    {θ : Subst σ1 s1 σ2 s2} (m : MonoSyn θ) :
    m.lift.restrict (.abs .here) = θ.lift := rfl

/-- The image is the substitution's action. -/
@[simp] theorem image_eq {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2}
    (m : MonoSyn θ) (p : Vr σ1 s1) : m.image p = p.subst θ :=
  (m.at' p).image_eq

/-- The star law, at a subject of either zone. -/
theorem star {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} (m : MonoSyn θ)
    (p : Vr σ1 s1) :
    (Subst.ofRename (renameAt p)).comp θ
      = (m.restrict p).comp (Subst.ofRename (renameAt (m.image p))) :=
  (m.at' p).star

/-- The restriction sends the subject's self variable to the image's. -/
theorem self {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} (m : MonoSyn θ)
    (p : Vr σ1 s1) : (selfAt p).subst (m.restrict p) = selfAt (m.image p) :=
  (m.at' p).self

/-- The star law as a law on *types*, which is the form the typing theorem
uses: weakening a type out of a prefix and substituting is substituting inside
the prefix and weakening out of the image's prefix. -/
theorem star_ty {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} (m : MonoSyn θ)
    (p : Vr σ1 s1) (T : Ty σ1 (scopeAt p)) :
    (T.rename (renameAt p)).subst θ
      = (T.subst (m.restrict p)).rename (renameAt (m.image p)) := by
  show (T.subst (Subst.ofRename (renameAt p))).subst θ
      = (T.subst (m.restrict p)).subst (Subst.ofRename (renameAt (m.image p)))
  rw [Ty.subst_comp, Ty.subst_comp, m.star p]

/-- Instantiating a subject's self and substituting commute.  The `vcUnfold`
clause of the typing theorem is this law. -/
theorem substVr_selfAt {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2}
    (m : MonoSyn θ) (p : Vr σ1 s1) (T : Ty σ1 (scopeAt p,x)) :
    (T.substVr (selfAt p)).subst (m.restrict p)
      = (T.subst (m.restrict p).lift).substVr (selfAt (m.image p)) := by
  show (T.subst (Subst.one (selfAt p))).subst (m.restrict p)
      = (T.subst (m.restrict p).lift).subst (Subst.one (selfAt (m.image p)))
  rw [Ty.subst_comp, Ty.subst_comp]
  refine congrArg (fun φ => T.subst φ) (Subst.ext (fun _ => rfl) ?_)
  intro y
  cases y with
  | here => exact m.self p
  | there w => exact (Vr.weaken_subst_one ((m.restrict p).abs w) _).symm

/-- Every generated substitution respects prefixes in the sense of
`Structural.Mono`: the notion of this module refines that one rather than
replacing it. -/
def toMono {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} (m : MonoSyn θ) :
    Mono θ := fun x =>
  match m.at' (.abs x) with
  | .toAbs z r himg hstar _ _ => .toAbs z r himg hstar
  | .toConc l r himg hstar _ _ => .toConc l r himg hstar

end MonoSyn

/-! ## The restriction is unique

A restriction is not merely *a* substitution satisfying the star law: it is the
only one.  Weakening out of a prefix is injective, and the star law determines
the restriction after post-composing with it.

This is the first step of the route to the coherence
`(θ↾x)↾y ≅ θ↾((renameUpTo x).var y)` that `SubstTyping` still assumes: with
uniqueness in hand that coherence does not need an induction over generators at
all, only the two composition laws
`renameUpTo ((renameUpTo x).var y) ≅ (renameUpTo y).comp (renameUpTo x)` and its
`renameAt` counterpart, after which both sides satisfy the same star law at the
composite subject. -/

/-- Weakening out of a prefix is injective on variables. -/
theorem renameUpTo_inj : {s : Sig} → (x : BVar s .var) →
    {y z : BVar (scopeUpTo x) .var} → (renameUpTo x).var y = (renameUpTo x).var z →
    y = z
  | _ :: _, .here, _, _, h => h
  | _ :: _, .there x', _, _, h => by
      refine renameUpTo_inj x' ?_
      exact (by injection h : _ = _)

/-- Weakening a variable out of a subject's prefix is injective. -/
theorem Vr.rename_renameAt_inj {σ s : Sig} : (p : Vr σ s) → {u w : Vr σ (scopeAt p)} →
    u.rename (renameAt p) = w.rename (renameAt p) → u = w
  | .abs x, .conc _, .conc _, h => by
      exact congrArg Vr.conc (by injection h)
  | .abs x, .abs _, .abs _, h => by
      refine congrArg Vr.abs (renameUpTo_inj x ?_)
      exact (by injection h : _ = _)
  | .abs _, .conc _, .abs _, h => by cases h
  | .abs _, .abs _, .conc _, h => by cases h
  | .conc _, .conc _, .conc _, h => by exact congrArg Vr.conc (by injection h)
  | .conc _, .abs u, _, _ => nomatch u
  | .conc _, _, .abs u, _ => nomatch u

/-- **The restriction is determined by the star law.**  Two substitutions from a
subject's prefix into an image's prefix that both satisfy it are equal. -/
theorem restrict_unique {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2}
    {p : Vr σ1 s1} {q : Vr σ2 s2} (r1 r2 : Subst σ1 (scopeAt p) σ2 (scopeAt q))
    (h1 : (Subst.ofRename (renameAt p)).comp θ
      = r1.comp (Subst.ofRename (renameAt q)))
    (h2 : (Subst.ofRename (renameAt p)).comp θ
      = r2.comp (Subst.ofRename (renameAt q))) : r1 = r2 := by
  have h : r1.comp (Subst.ofRename (renameAt q))
      = r2.comp (Subst.ofRename (renameAt q)) := h1.symm.trans h2
  refine Subst.ext (fun l => ?_) (fun w => ?_)
  · have hc : (r1.comp (Subst.ofRename (renameAt q))).conc l
        = (r2.comp (Subst.ofRename (renameAt q))).conc l :=
      congrArg (fun t => Subst.conc t l) h
    exact hc
  · have ha : (r1.comp (Subst.ofRename (renameAt q))).abs w
        = (r2.comp (Subst.ofRename (renameAt q))).abs w :=
      congrArg (fun t => Subst.abs t w) h
    exact Vr.rename_renameAt_inj q ha

/-! ## The substitution action

`Vc` is scope-uniform — every premise of every former lives in the same local
scope as its conclusion — so `Vc.subst` needs no subject: by the time it is
called, the scope index *is* the prefix scope and the substitution handed to it
*is* the restriction.  The subject is consumed one level up, in `Le.subst`'s
`selL`/`selR` clause, which is where `resSyn` supplies the restricted generated
substitution.  That is the whole content of the closure. -/

mutual

/-- Substitution on inclusion evidence.  `defL`/`defR` descend into the empty
local scope through `atNil`; `selL`/`selR` descend into the subject's prefix
through `resSyn`. -/
def Le.subst {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} :
    Le σ1 s1 → MonoSyn θ → Le σ2 s2
  | .refl T, _ => .refl (T.subst θ)
  | .trans M e f, m => .trans (M.subst θ) (e.subst m) (f.subst m)
  | .top T, _ => .top (T.subst θ)
  | .bot T, _ => .bot (T.subst θ)
  | .dtyp l e f, m => .dtyp l (e.subst m) (f.subst m)
  | .dfun l e f, m => .dfun l (e.subst m) (f.subst m.lift)
  | .andI T1 T2 e f, m => .andI (T1.subst θ) (T2.subst θ) (e.subst m) (f.subst m)
  | .andE1 T2 e, m => .andE1 (T2.subst θ) (e.subst m)
  | .andE2 T1 e, m => .andE2 (T1.subst θ) (e.subst m)
  | .orI1 T2 e, m => .orI1 (T2.subst θ) (e.subst m)
  | .orI2 T1 e, m => .orI2 (T1.subst θ) (e.subst m)
  | .orE S1 S2 e f, m => .orE (S1.subst θ) (S2.subst θ) (e.subst m) (f.subst m)
  | .defL l a e, m => .defL (θ.conc l) a (e.subst m.atNil)
  | .defR l a e, m => .defR (θ.conc l) a (e.subst m.atNil)
  | .selL p a v, m => .selL (m.image p) a (v.subst (m.resSyn p))
  | .selR p a v, m => .selR (m.image p) a (v.subst (m.resSyn p))
  | .bindx S T e, m => .bindx (S.subst θ.lift) (T.subst θ.lift) (e.subst m.lift)
  | .muDrop T, _ => .muDrop (T.subst θ)

/-- Substitution on observation evidence.  The substitution it takes is already
the restriction at the subject, so no former here has to restrict. -/
def Vc.subst {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} :
    Vc σ1 s1 → MonoSyn θ → Vc σ2 s2
  | .vcVar, _ => .vcVar
  | .vcLoc l, _ => .vcLoc (θ.conc l)
  | .vcPack T v, m => .vcPack (T.subst θ.lift) (v.subst m)
  | .vcUnfold T v, m => .vcUnfold (T.subst θ.lift) (v.subst m)
  | .vcSub T1 e v, m => .vcSub (T1.subst θ) (e.subst m) (v.subst m)

end

mutual

/-- Substitution on atoms.  A variable goes to its image, so an atom's root
moves the way the substitution moves it (`Atom.root_subst`). -/
def Atom.subst {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} :
    Atom σ1 s1 → MonoSyn θ → Atom σ2 s2
  | .var p, _ => .var (p.subst θ)
  | .cast a e, m => .cast (a.subst m) (e.subst m)
  | .pack T a, m => .pack (T.subst θ.lift) (a.subst m)
  | .unpack T a, m => .unpack (T.subst θ.lift) (a.subst m)

/-- Substitution on terms. -/
def Tm.subst {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} :
    Tm σ1 s1 → MonoSyn θ → Tm σ2 s2
  | .atom a, m => .atom (a.subst m)
  | .new T ds, m => .new (T.subst θ.lift) (ds.subst m.lift)
  | .app a l b, m => .app (a.subst m) l (b.subst m)
  | .«let» t u, m => .«let» (t.subst m) (u.subst m.lift)
  | .cast t e, m => .cast (t.subst m) (e.subst m)

/-- Substitution on definition lists.  Labels are positional and substitution
preserves the length, so no label moves. -/
def Defs.subst {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} :
    Defs σ1 s1 → MonoSyn θ → Defs σ2 s2
  | .dnil, _ => .dnil
  | .dty T ds, m => .dty (T.subst θ) (ds.subst m)
  | .dfun S U t ds, m =>
      .dfun (S.subst θ) (U.subst θ.lift) (t.subst m.lift) (ds.subst m)

end

/-- An atom's root moves exactly as the substitution moves it.  This is what
makes `app a l b`'s codomain instantiation `U{root b}` stable. -/
@[simp] theorem Atom.root_subst {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} :
    (a : Atom σ1 s1) → (m : MonoSyn θ) → (a.subst m).root = a.root.subst θ
  | .var _, _ => rfl
  | .cast a _, m => Atom.root_subst a m
  | .pack _ a, m => Atom.root_subst a m
  | .unpack _ a, m => Atom.root_subst a m

/-- Substitution preserves the number of members, hence every label. -/
@[simp] theorem Defs.length_subst {σ1 σ2 s1 s2 : Sig} {θ : Subst σ1 s1 σ2 s2} :
    (ds : Defs σ1 s1) → (m : MonoSyn θ) → (ds.subst m).length = ds.length
  | .dnil, _ => rfl
  | .dty _ ds, m => congrArg (· + 1) (Defs.length_subst ds m)
  | .dfun _ _ _ ds, m => congrArg (· + 1) (Defs.length_subst ds m)

end FCdotR
