import Coercions.Translation.ManySorted.BinderOnly.TermElaboration
import Coercions.Translation.ManySorted.BinderOnly.SourceErasure
import Coercions.ManySortedFC.Administrative

/-!
# Erased behavior of certified binder-only elaboration

Certified elaboration preserves the source runtime spine up to the precise
administrative equivalence generated by value eta and ANF identity lets.
Most elaboration constructs erase literally.  The only non-literal case is
source value adaptation: a structural function adapter may eta-expand its
argument, and `ManySortedFC.Adapter.erase_admin` accounts for exactly that
difference.
-/

namespace DOTCaptureToManySortedFC.BinderOnly

private abbrev ErasureMapsAgree
    {scope : DOTCapture.BinderOnly.Sig}
    (context : DOTCapture.BinderOnly.Ctx scope)
    {runtimeScope : Nat}
    (targetMap : ManySortedFC.Erasure.Renaming
      (sig context) runtimeScope)
    (sourceMap : SourceErasure.Renaming scope runtimeScope) : Prop :=
  forall name, targetMap (termVar context name) = sourceMap name

private theorem ErasureMapsAgree.liftTerm
    {scope : DOTCapture.BinderOnly.Sig}
    {context : DOTCapture.BinderOnly.Ctx scope}
    {runtimeScope : Nat}
    {targetMap : ManySortedFC.Erasure.Renaming
      (sig context) runtimeScope}
    {sourceMap : SourceErasure.Renaming scope runtimeScope}
    (agree : ErasureMapsAgree context targetMap sourceMap)
    (bound : DOTCapture.BinderOnly.Ty scope) :
    ErasureMapsAgree (context.extendTerm bound)
      targetMap.liftTerm sourceMap.liftTerm := by
  intro name
  cases name with
  | here => rfl
  | there older =>
      exact congrArg Fin.succ (agree older)

private theorem ErasureMapsAgree.liftStatic
    {scope : DOTCapture.BinderOnly.Sig}
    {context : DOTCapture.BinderOnly.Ctx scope}
    {runtimeScope : Nat}
    {targetMap : ManySortedFC.Erasure.Renaming
      (sig context) runtimeScope}
    {sourceMap : SourceErasure.Renaming scope runtimeScope}
    (agree : ErasureMapsAgree context targetMap sourceMap)
    {sort : DOTCapture.BinderOnly.StaticSort}
    (interval : DOTCapture.BinderOnly.Interval sort scope) :
    ErasureMapsAgree (context.extendStatic interval)
      (targetMap.liftStatic [translateSort sort]
        (intervalRelations interval))
      (sourceMap.liftStatic sort) := by
  intro name
  cases name with
  | there older =>
      cases interval with
      | bounds lower upper =>
          cases lower <;> cases upper <;> exact agree older

private theorem ErasureMapsAgree.liftPayload
    {scope : DOTCapture.BinderOnly.Sig}
    {context : DOTCapture.BinderOnly.Ctx scope}
    {runtimeScope : Nat}
    {targetMap : ManySortedFC.Erasure.Renaming
      (sig context) runtimeScope}
    {sourceMap : SourceErasure.Renaming scope runtimeScope}
    (agree : ErasureMapsAgree context targetMap sourceMap)
    {sort : DOTCapture.BinderOnly.StaticSort}
    (interval : DOTCapture.BinderOnly.Interval sort scope)
    (payloadType : DOTCapture.BinderOnly.Ty (scope ▹ .static sort)) :
    ErasureMapsAgree
      ((context.extendStatic interval).extendTerm payloadType)
      (targetMap.liftPayload [translateSort sort]
        (intervalRelations interval))
      (sourceMap.liftPayload sort) :=
  (agree.liftStatic interval).liftTerm payloadType

mutual

private def compileValue_eraseWith_admin
    {scope : DOTCapture.BinderOnly.Sig}
    {context : DOTCapture.BinderOnly.Ctx scope}
    {value : DOTCapture.BinderOnly.Value scope}
    {type : DOTCapture.BinderOnly.Ty scope}
    (typing : DOTCapture.BinderOnly.Value.HasType context value type) :
    {runtimeScope : Nat} ->
    (targetMap : ManySortedFC.Erasure.Renaming
      (sig context) runtimeScope) ->
    (sourceMap : SourceErasure.Renaming scope runtimeScope) ->
    ErasureMapsAgree context targetMap sourceMap ->
      ManySortedFC.Runtime.AdministrativeEq
        ((compileValue typing).term.eraseWith targetMap)
        (SourceErasure.eraseValueWith sourceMap value) :=
  match typing with
  | @DOTCapture.BinderOnly.Value.HasType.var _ _ name =>
      fun targetMap sourceMap agree => by
        change ManySortedFC.Runtime.AdministrativeEq
          (.var (targetMap (termVar context name)))
          (.var (sourceMap name))
        rw [agree name]
        exact .refl
  | @DOTCapture.BinderOnly.Value.HasType.unit _ _ =>
      fun _ _ _ => by
        exact .refl
  | @DOTCapture.BinderOnly.Value.HasType.lam _ context domain _ _ _ _
      bodyTyping _ =>
      fun targetMap sourceMap agree => by
        exact .lam
          (compileTerm_eraseWith_admin bodyTyping
            targetMap.liftTerm sourceMap.liftTerm
            (agree.liftTerm domain))
  | @DOTCapture.BinderOnly.Value.HasType.staticLam _ context _ interval
      _ _ _ bodyTyping _ =>
      fun targetMap sourceMap agree => by
        exact compileValue_eraseWith_admin bodyTyping
          (targetMap.liftStatic [_] (intervalRelations interval))
          (sourceMap.liftStatic _)
          (agree.liftStatic interval)
  | @DOTCapture.BinderOnly.Value.HasType.pack _ context sort interval
      payloadType witness payload closure satisfaction payloadTyping
      captures =>
      fun targetMap sourceMap agree => by
        exact compileValue_eraseWith_admin payloadTyping
          targetMap sourceMap agree
  | @DOTCapture.BinderOnly.Value.HasType.adapt _ _ _ _ _
      valueTyping adaptation =>
      fun targetMap sourceMap agree => by
        let compiledInner := compileValue valueTyping
        let compiledAdapter := compileAdapts adaptation
        exact
          (ManySortedFC.Adapter.erase_admin compiledAdapter.adapter
            (compiledInner.term.eraseWith targetMap)
            (compiledInner.isValue.eraseWith targetMap)).trans
          (compileValue_eraseWith_admin valueTyping targetMap sourceMap agree)

private def compileTerm_eraseWith_admin
    {scope : DOTCapture.BinderOnly.Sig}
    {context : DOTCapture.BinderOnly.Ctx scope}
    {term : DOTCapture.BinderOnly.Term scope}
    {use : DOTCapture.BinderOnly.Capture scope}
    {type : DOTCapture.BinderOnly.Ty scope}
    (typing : DOTCapture.BinderOnly.Term.HasType context term use type) :
    {runtimeScope : Nat} ->
    (targetMap : ManySortedFC.Erasure.Renaming
      (sig context) runtimeScope) ->
    (sourceMap : SourceErasure.Renaming scope runtimeScope) ->
    ErasureMapsAgree context targetMap sourceMap ->
      ManySortedFC.Runtime.AdministrativeEq
        ((compileTerm typing).term.eraseWith targetMap)
        (SourceErasure.eraseTermWith sourceMap term) :=
  match typing with
  | @DOTCapture.BinderOnly.Term.HasType.ret _ _ _ _ valueTyping =>
      fun targetMap sourceMap agree => by
        exact compileValue_eraseWith_admin valueTyping
          targetMap sourceMap agree
  | @DOTCapture.BinderOnly.Term.HasType.app _ _ _ _ _ _ _
      functionTyping _ argumentTyping =>
      fun targetMap sourceMap agree => by
        exact .app
          (compileValue_eraseWith_admin functionTyping
            targetMap sourceMap agree)
          (compileValue_eraseWith_admin argumentTyping
            targetMap sourceMap agree)
  | @DOTCapture.BinderOnly.Term.HasType.let' _ _ _ bound _ _ _ _ _
      rhsTyping bodyTyping _ =>
      fun targetMap sourceMap agree => by
        exact .let'
          (compileTerm_eraseWith_admin rhsTyping targetMap sourceMap agree)
          (compileTerm_eraseWith_admin bodyTyping
            targetMap.liftTerm sourceMap.liftTerm
            (agree.liftTerm bound))
  | @DOTCapture.BinderOnly.Term.HasType.staticApp _ _ _ _ _ _ _ _
      functionTyping _ _ =>
      fun targetMap sourceMap agree => by
        exact compileValue_eraseWith_admin functionTyping
          targetMap sourceMap agree
  | @DOTCapture.BinderOnly.Term.HasType.«open» _ context sort interval
      payloadType result package body packageType bodyUse bodyOuterUse
      packageTyping packageShape bodyTyping discharge =>
      fun targetMap sourceMap agree => by
        exact .let'
          (compileValue_eraseWith_admin packageTyping
            targetMap sourceMap agree)
          (compileTerm_eraseWith_admin bodyTyping
            (targetMap.liftPayload [translateSort sort]
              (intervalRelations interval))
            (sourceMap.liftPayload sort)
            (agree.liftPayload interval payloadType))
  | @DOTCapture.BinderOnly.Term.HasType.use _ _ _ _ _ _
      termTyping _ =>
      fun targetMap sourceMap agree => by
        exact compileTerm_eraseWith_admin termTyping
          targetMap sourceMap agree

end

private theorem canonicalErasureMapsAgree
    {scope : DOTCapture.BinderOnly.Sig}
    (context : DOTCapture.BinderOnly.Ctx scope) :
    ErasureMapsAgree context
      (ManySortedFC.Erasure.Renaming.identity (sig context))
      (SourceErasure.compiledRenaming context) := by
  intro name
  rfl

/-- Certified value elaboration preserves direct source erasure up to target
administrative equivalence.  Structural source adapters are the only reason
the conclusion is not stated as syntactic equality. -/
theorem compileValue_erase_admin
    {scope : DOTCapture.BinderOnly.Sig}
    {context : DOTCapture.BinderOnly.Ctx scope}
    {value : DOTCapture.BinderOnly.Value scope}
    {type : DOTCapture.BinderOnly.Ty scope}
    (typing : DOTCapture.BinderOnly.Value.HasType context value type) :
    ManySortedFC.Runtime.AdministrativeEq
      (compileValue typing).term.erase
      (SourceErasure.eraseValue context value) :=
  compileValue_eraseWith_admin typing
    (ManySortedFC.Erasure.Renaming.identity (sig context))
    (SourceErasure.compiledRenaming context)
    (canonicalErasureMapsAgree context)

/-- Certified computation elaboration preserves direct source erasure up to
target administrative equivalence. -/
theorem compileTerm_erase_admin
    {scope : DOTCapture.BinderOnly.Sig}
    {context : DOTCapture.BinderOnly.Ctx scope}
    {term : DOTCapture.BinderOnly.Term scope}
    {use : DOTCapture.BinderOnly.Capture scope}
    {type : DOTCapture.BinderOnly.Ty scope}
    (typing : DOTCapture.BinderOnly.Term.HasType context term use type) :
    ManySortedFC.Runtime.AdministrativeEq
      (compileTerm typing).term.erase
      (SourceErasure.eraseTerm context term) :=
  compileTerm_eraseWith_admin typing
    (ManySortedFC.Erasure.Renaming.identity (sig context))
    (SourceErasure.compiledRenaming context)
    (canonicalErasureMapsAgree context)

namespace TermElaborationErasureExamples

open DOTCapture.BinderOnly.TypingExamples

/-- Ordinary abstraction preserves the direct identity runtime. -/
theorem identity_erasure :
    ManySortedFC.Runtime.AdministrativeEq
      (compileValue identityTyping).term.erase
      (.lam (.var 0)) := by
  simpa using compileValue_erase_admin identityTyping

/-- Static abstraction and application both erase their static boundary. -/
theorem static_abstraction_erasure :
    ManySortedFC.Runtime.AdministrativeEq
      (compileValue staticAbstractOneTyping).term.erase
      .unit := by
  simpa using compileValue_erase_admin staticAbstractOneTyping

theorem static_application_erasure :
    ManySortedFC.Runtime.AdministrativeEq
      (compileTerm applyStaticAbstractOneTyping).term.erase
      .unit := by
  simpa using compileTerm_erase_admin applyStaticAbstractOneTyping

/-- Existential packages disappear and opening remains one runtime let. -/
theorem package_erasure :
    ManySortedFC.Runtime.AdministrativeEq
      (compileValue packedAbstractOneTyping).term.erase
      .unit := by
  simpa using compileValue_erase_admin packedAbstractOneTyping

theorem open_erasure :
    ManySortedFC.Runtime.AdministrativeEq
      (compileTerm openPackedAbstractOneTyping).term.erase
      (.let' .unit (.var 0)) := by
  simpa using compileTerm_erase_admin openPackedAbstractOneTyping

/-- A bare callable variable can request a genuinely structural, reflexive
function adapter.  Its target erasure is eta-expanded, so this regression
exercises administrative equivalence rather than definitional equality. -/
def structuralAdapterContext :
    DOTCapture.BinderOnly.Ctx ([] ▹ .term) :=
  DOTCapture.BinderOnly.Ctx.nil.extendTerm (.arr .one .one)

def structurallyAdaptedVariableTyping :
    DOTCapture.BinderOnly.Value.HasType structuralAdapterContext
      (.var .here) (.arr .one .one) :=
  .adapt .var (.function .identity .identity)

theorem structural_adapter_erasure :
    ManySortedFC.Runtime.AdministrativeEq
      (compileValue structurallyAdaptedVariableTyping).term.erase
      (.var (ManySortedFC.BVar.toTermIndex
        (termVar structuralAdapterContext .here))) := by
  simpa using compileValue_erase_admin structurallyAdaptedVariableTyping

end TermElaborationErasureExamples

end DOTCaptureToManySortedFC.BinderOnly
